package.json
=> Add fields to package.json

bin/package, packages/desktop-electron/package.json
This is quite a small PR but once #50 is merged it will allow us to remove some of the `cd`-ing around in the `package` script to simplify it.
=> Improved yarn scripts in desktop-electron package

.github/workflows/lint.yml, packages/loot-core/.eslintignore, packages/loot-core/package.json, packages/loot-core/src/server/budget/base.js
A copy of the linting task added in https://github.com/actualbudget/actual-server/pull/37
=> Add linting job to CI

README.md
=> Remove holiday text from README

packages/desktop-client/src/components/Settings.js, packages/desktop-client/src/components/manager/ManagementApp.js, packages/desktop-client/src/hooks/useServerVersion.js, packages/loot-core/src/server/main.js
This PR adds a version number display to the Settings component.
As suggested in discord. Didn't spot a corresponding issue.
=> display version on settings page

tsconfig.json
This configures TS to look at JS files as well, so that IDEs like VSCode can provide better edit-time checks.
Twin of https://github.com/actualbudget/actual-server/pull/13
=> add: tsconfig.json

.eslintrc.js, package.json, packages/desktop-client/package.json, packages/desktop-client/src/components/accounts/TransactionsTable.test.js, packages/desktop-client/src/components/budget/budget-sheets-old.js, yarn.lock
I've fixed some of the more obvious errors and silenced the rest for now (especially as it seems like that file can just be deleted due to it being old?).
=> Enforce linting in desktop-client

packages/desktop-electron/package.json, packages/import-ynab4/package.json, packages/import-ynab5/package.json, packages/loot-core/package.json
see https://yarnpkg.com/features/workspaces#workspace-ranges-workspace
=> Use workspace ranges for monorepo dependencies

packages/loot-core/src/server/aql/index.js, packages/loot-core/src/server/db/index.js
#68 was pre-linter changes and so breaks some new rules, this PR fixes those issues.
=> Fix linter issues

.github/actions/setup/action.yml
Let's avoid potential CI headaches by being very explicit here.
=> Fix CI to an exact node version

packages/api/utils.js, packages/desktop-electron/index.js, packages/loot-core/bin/profile-sql.js, packages/loot-core/src/client/queries.js, packages/loot-core/src/client/query-helpers.test.js, packages/loot-core/src/mocks/budget.js, packages/loot-core/src/mocks/index.js, packages/loot-core/src/server/aql/compiler.js, packages/loot-core/src/server/aql/schema-helpers.js, packages/loot-core/src/server/aql/schema/executors.test.js, packages/loot-core/src/server/budget/actions.js, packages/loot-core/src/server/budget/report.js, packages/loot-core/src/server/budget/rollover.js, packages/loot-core/src/server/budget/util.js, packages/loot-core/src/server/crdt/merkle.js, packages/loot-core/src/server/db/sort.js, packages/loot-core/src/server/sync/sync.property.test.js, packages/loot-core/src/shared/rules.js, packages/loot-core/src/shared/schedules.js, packages/loot-core/src/shared/util.js, packages/loot-design/src/parse-figma-theme.js, packages/loot-design/src/setupTests.js
Rebased version of https://github.com/actualbudget/actual/pull/138
=> Remove 32bit limit on amounts

packages/desktop-client/src/components/accounts/Account.js
Solves https://github.com/actualbudget/actual/issues/384 
Original RFC: https://github.com/actualbudget/actual/discussions/374
=> feat: ability to add notes to accounts

packages/loot-design/src/components/manager/BudgetList.js, packages/loot-design/src/util/environment.js, packages/loot-design/src/util/preview.js
Enabling the test budget creation button for netlify deployments. This will make running manual tests that much easier.
=> feat: allow creating test budget in netlify deployments

packages/loot-design/src/components/budget/rollover/rollover-components.js, packages/loot-design/src/components/common.js
Fixing two react warnings. See inlined comments for more details.
=> fix: some react warnings

packages/desktop-client/package.json
Release notes: https://github.com/actualbudget/docs/pull/75
=> :bookmark: (23.1.12) responsive mobile version and sidebar improvements

packages/desktop-client/src/components/settings/index.js
Otherwise we get this when you enable advanced settings and scroll down a bit
=> Center the settings UI when the sidebar is collapsed

packages/desktop-client/src/wtftags.js
=> :fire:  delete unused file: wtftags

packages/desktop-client/src/components/FinancesApp.js, packages/desktop-client/src/components/Titlebar.js, packages/desktop-client/src/components/accounts/Filters.js, packages/desktop-client/src/components/modals/EditRule.js, packages/desktop-client/src/components/reports/graphs/NetWorthGraph.js, packages/desktop-client/src/components/schedules/EditSchedule.js, packages/loot-core/src/client/data-hooks/payees.js, packages/loot-core/src/shared/util.js, packages/loot-design/src/components/DateSelect.js, packages/loot-design/src/components/sidebar.js
Most of the remaining errors are due to using deprecated APIs via lively, but those should be fixed by #438.
=> Fix a bunch of warnings/errors

packages/loot-core/src/server/accounts/transfer.js
Closes #487
Reproduction steps best explained in the linked issue ticket. But TLDR:
1. create a transfer transaction from account A to B
2. open "all accounts" view
3. select both transfer transactions
4. click delete
5. before: error appears; after: no error, both transactions deleted
=> :bug:  allow deleting both transfer transactions at the same time

packages/desktop-client/src/components/settings/Export.js
Added the date to the file name of the zip file.
**Current Behaviour**
**New Behaviour**
=> Added date to export file name

packages/desktop-client/src/components/accounts/Account.js
=> Update SelectedBalance to use useSheetValue

packages/desktop-client/src/components/accounts/Account.js
=> Don’t crash when loading an invalid account ID

packages/api/package.json
node-fetch upgrade PR: https://github.com/actualbudget/actual/pull/609
I will publish a new api release to npmjs after this is merged.
=> :bookmark: (api) 4.1.6: node-fetch upgrade

packages/desktop-client/src/components/FatalError.js
Removed reference to automatic reporting of errors to ActualBudget, also removed the email address as a endpoint for errors to be reported to and replaced it with GitHub issues.
This should resolve #623
=> Fatal error dialog update to reflect open source.

packages/loot-core/src/client/upgrade-notifications.js, packages/loot-design/src/components/modals/PlaidExternalMsg.js
Removing any links that no longer exist and can't move the content to docs. This resolves #634
=> Removing dead links

packages/desktop-client/src/components/accounts/AccountSyncCheck.js, packages/desktop-client/src/components/tutorial/Final.js, packages/loot-core/src/client/actions/budgets.js, packages/loot-core/src/platform/client/fetch/index.browser.js, packages/loot-core/src/server/main.js, packages/loot-core/src/shared/errors.js, packages/loot-core/src/shared/rules.js
Replaced help@actualbudget.com with link to GitHub issues, this should resolve #625
=> Remove all references to help@actualbudget.com

packages/desktop-client/src/components/settings/Encryption.js
Must not have updated this properly when resolving merge conflicts 🤦
=> Fix prop name for button to enable e2ee

packages/desktop-client/src/components/settings/Export.js
See https://github.com/actualbudget/actual-server/issues/136#issuecomment-1428759968
=> Better explain the process for importing an exported file

packages/loot-design/src/components/table.js
Before:
https://user-images.githubusercontent.com/25517624/218864177-06c53a06-f6ae-484b-bb63-50c8c9947a6c.mov
After:
https://user-images.githubusercontent.com/25517624/218864255-2de3da06-9c73-41f0-b7f4-8d8bf4ea0d4d.mov
=> Stop editing when clicking on blank areas of tables

packages/desktop-client/src/components/LoggedInUser.js
Flow:
1. log into an Actual server
1. change the server password in another browser (or delete the `server-files` DB)
1. Reload the budget page. Now the top right says “Not logged in”
1. Click on “Not logged in” to close the current file and open the bootstrap/login flow
Once you click the “Not logged in” button you can go to “Change” → “Stop using a server” to get back to your local files.
=> Make the “Not logged in” warning a button

packages/desktop-client/config/webpack.config.js, packages/desktop-client/src/components/modals/FixEncryptionKey.js
This should allow the Netlify deploy to happen even if the linter reports issues
=> Don’t run linting while building in CI

packages/loot-core/src/platform/client/fetch/index.browser.js
While reviewing the Nordigen PR locally, I noticed that the frontend would think it was not connected to a server. This seems to be because the `get-server-url` message is sent super early in the app lifecycle, after the worker has been created but before it is ready to receive a message. This PR uses the existing `messageQueue` logic but extends it from just the time before `init` is called all the way until the `connect` event is sent by the worker to indicate it is ready for messages.
=> Don’t post messages to the worker until it is ready

packages/desktop-client/e2e/page-models/navigation.js, packages/desktop-client/e2e/page-models/schedules-page.js, packages/desktop-client/e2e/schedules.test.js, packages/desktop-client/src/components/schedules/EditSchedule.js, packages/desktop-client/src/components/schedules/SchedulesTable.js, packages/desktop-client/src/components/util/AmountInput.js, packages/loot-design/src/components/common.js, packages/loot-design/src/components/forms.js
=> :white_check_mark: (e2e) adding e2e tests for schedules page

packages/desktop-client/e2e/accounts.test.js, packages/desktop-client/e2e/page-models/account-page.js, packages/desktop-client/e2e/page-models/close-account-modal.js, packages/desktop-client/e2e/page-models/navigation.js, packages/desktop-client/e2e/page-models/reports-page.js, packages/desktop-client/e2e/page-models/rules-page.js, packages/desktop-client/e2e/page-models/schedules-page.js, packages/desktop-client/e2e/page-models/settings-page.js, packages/desktop-client/e2e/reports.test.js, packages/desktop-client/e2e/rules.test.js, packages/desktop-client/e2e/settings.test.js, packages/desktop-client/src/components/ManageRules.js, packages/desktop-client/src/components/accounts/Account.js, packages/desktop-client/src/components/modals/EditRule.js, packages/desktop-client/src/components/reports/Overview.js, packages/desktop-client/src/components/reports/index.js, packages/loot-design/src/components/Stack.js
=> :white_check_mark: (e2e) adding e2e tests for accounts: creating & closing

packages/desktop-client/e2e/page-models/rules-page.js, packages/desktop-client/e2e/rules.test.js, packages/desktop-client/e2e/schedules.test.js, packages/desktop-client/src/components/ManageRules.js
Currently this crashes. Use case: the “link schedule” action in the rule list
=> Allow rendering a schedule in <Value />

packages/desktop-client/src/components/manager/subscribe/Bootstrap.js
Since (after #649) this will be the first page they see out of Actual, I’ve updated it to be more welcoming. Let me know if you have any suggested changes for the wording!
=> Update the Bootstrap page to be more welcoming

packages/api/package.json, packages/loot-core/package.json, packages/loot-core/src/server/accounts/transaction-rules.js, yarn.lock
I think this also unblocks updating to the latest Node version but I will investigate that in future PRs.
=> Upgrade better-sqlite3 to the latest version

packages/desktop-client/src/components/modals/EditRule.js, packages/loot-core/src/shared/rules.js
✨
https://user-images.githubusercontent.com/25517624/220503404-2ddb046c-fc2f-4c19-a825-1a6a7104e84a.mov
=> Intelligently adjust field for newly added action

.eslintrc.js, packages/desktop-client/src/components/accounts/AccountSyncCheck.js, packages/desktop-client/src/components/reports/CashFlow.js, packages/desktop-client/src/components/reports/NetWorth.js, packages/desktop-client/src/components/reports/Overview.js, packages/desktop-client/src/components/reports/util.js, packages/loot-design/src/components/RecurringSchedulePicker.js, packages/loot-design/src/components/sort.js
Re-enabling the `react-hooks/rules-of-hooks` eslint rule.
There should be no real change in functionality.
=> :rotating_light:  re-enable react-hooks/rules-of-hooks eslint rule

.github/workflows/build.yml
Part of fixing the horrendously slow Docker build for the server edge images.
=> Create an artifact with the built web UI for each commit

packages/desktop-client/package.json
23.3.0
Docs: https://github.com/actualbudget/docs/pull/119
=> :bookmark: (23.3.0) experimental bank-sync integration, maintenace, fixes

packages/loot-core/src/server/budget/goaltemplates.js, upcoming-release-notes/751.md
Thanks @kidglove57 for spotting this issue and helping me track down the cause!
=> Fix #template 0 causing an error

packages/loot-core/src/server/budget/goal-template.pegjs, upcoming-release-notes/756.md
Fixes https://github.com/actualbudget/actual/pull/751#issuecomment-1468627695
=> Make goal template keywords case insensitive

packages/desktop-client/src/components/accounts/TransactionsTable.js, packages/desktop-client/src/components/accounts/TransactionsTable.test.js, packages/desktop-client/src/hooks/usePrevious.js, packages/loot-core/src/mocks/index.js, packages/loot-design/src/components/table.js, packages/loot-design/src/setupTests.js, upcoming-release-notes/769.md
Ported `TransactionsTable` to react hook. This hopefully solves the test flakiness issue 🤞
=> :recycle: (TransactionsTable) port to react hooks

packages/desktop-client/src/components/accounts/TransactionsTable.js, upcoming-release-notes/777.md
Brining back `onHover`. This is a small regression.
=> :bug: (TransactionsTable) bring back missing onHover

packages/desktop-client/src/components/manager/ConfigServer.js, packages/desktop-client/src/components/modals/ManageRulesModal.js, packages/desktop-client/src/hooks/useFeatureFlag.js, packages/loot-core/src/server/main.js, packages/loot-design/src/components/manager/BudgetList.js, packages/loot-design/src/util/environment.js, upcoming-release-notes/790.md
Depends on server change: https://github.com/actualbudget/actual-server/pull/168
=> :sparkles: (bank-sync) expose demo-bank in the UI for DEV & preview builds

CONTRIBUTING.md, upcoming-release-notes/803.md
=> :pencil:  remove rich from core contributors

packages/loot-design/src/components/modals/NordigenExternalMsg.js, upcoming-release-notes/801.md
Adding an explicit bank-sync warning disclaimer.
#724
=> :sparkles: (bank-sync) add explicit nordigen bank-sync warning

packages/desktop-client/e2e/onboarding.test.js, packages/loot-core/src/platform/server/connection/index.api.js, packages/loot-core/src/platform/server/connection/index.web.js, upcoming-release-notes/819.md
=> Fix error when running importTransactions from the API

packages/desktop-client/e2e/onboarding.test.js, packages/desktop-client/e2e/page-models/configuration-page.js, packages/desktop-client/e2e/page-models/navigation.js, packages/desktop-client/src/components/manager/ManagementApp.js, packages/desktop-client/src/components/manager/subscribe/common.js, upcoming-release-notes/851.md
=> :bug:  navigation back to config-server page after clicking on "no server"

packages/desktop-client/src/components/App.js, packages/desktop-client/src/components/manager/ImportActual.js, packages/desktop-client/src/components/manager/ManagementApp.js, upcoming-release-notes/853.md
=> Fix display of loading indicator in management app

packages/desktop-client/src/components/autocomplete/NewAutocomplete.tsx, packages/desktop-client/src/components/autocomplete/NewPayeeAutocomplete.js, packages/desktop-client/src/components/autocomplete/autocomplete-styles.js, upcoming-release-notes/856.md
https://github.com/actualbudget/actual/issues/773
Before:
https://user-images.githubusercontent.com/886567/229928970-b243e7b9-0f28-41ed-8140-7cc4db26db8c.mov
After:
https://user-images.githubusercontent.com/886567/229929000-58fa8557-2c4d-48cd-87f4-21209e3aa5a4.mov
=> :bug: (autocomplete) allow editing selected payee name

packages/desktop-client/src/components/accounts/Filters.js, packages/desktop-client/src/components/autocomplete/autocomplete-styles.js, upcoming-release-notes/862.md
Fix for: https://github.com/actualbudget/actual/issues/773#issuecomment-1499235857
=> :bug: (autocomplete) height of the input box

packages/api/package.json
=> :bookmark: (5.1.1) api

packages/api/package.json
=> :bookmark: (api) 5.1.2

packages/desktop-client/src/browser-preload.browser.js, packages/desktop-client/src/components/GlobalKeys.js, packages/desktop-client/src/components/accounts/TransactionsTable.js, packages/desktop-client/src/components/autocomplete/Autocomplete.js, packages/desktop-client/src/components/autocomplete/NewAutocomplete.tsx, packages/desktop-client/src/components/budget/misc.js, packages/desktop-client/src/components/budget/rollover/rollover-components.js, packages/desktop-client/src/components/common.js, packages/desktop-client/src/components/select/DateSelect.js, packages/desktop-client/src/components/table.js, packages/desktop-client/src/components/tooltips.js, upcoming-release-notes/883.md
=> Recognize numpad enter key as enter key

packages/desktop-client/src/components/select/RecurringSchedulePicker.js, packages/loot-core/src/shared/schedules.ts, upcoming-release-notes/900.md
Add daily option to schedules. Satisfies #308.
=> Add daily option to schedules

packages/desktop-client/src/components/accounts/Account.js, upcoming-release-notes/886.md
Addresses https://github.com/actualbudget/actual/issues/866
=> Fill category field when selecting 'Create rule'

packages/desktop-client/package.json, upcoming-release-notes/860.md, upcoming-release-notes/864.md, upcoming-release-notes/865.md, upcoming-release-notes/869.md, upcoming-release-notes/870.md, upcoming-release-notes/877.md, upcoming-release-notes/881.md, upcoming-release-notes/882.md, upcoming-release-notes/883.md, upcoming-release-notes/884.md, upcoming-release-notes/886.md, upcoming-release-notes/887.md, upcoming-release-notes/889.md, upcoming-release-notes/890.md, upcoming-release-notes/891.md, upcoming-release-notes/893.md, upcoming-release-notes/895.md, upcoming-release-notes/900.md, upcoming-release-notes/902.md
=> :bookmark: (23.4.1) fix rule creation from transaction list

packages/desktop-client/src/components/accounts/Account.js, packages/loot-core/src/shared/util.ts, upcoming-release-notes/915.md
Fixes #913. (And probably a few other similar bugs)
=> Fix currencyToInteger returning null when amount is zero

packages/desktop-client/e2e/budget.test.js, packages/desktop-client/e2e/onboarding.test.js, upcoming-release-notes/932.md
Small changes to the e2e tests to improve the stability.
=> :white_check_mark: (e2e) improving stability - reducing flakiness

packages/desktop-client/src/components/autocomplete/Autocomplete.js, upcoming-release-notes/947.md
Before:
https://user-images.githubusercontent.com/886567/233850648-28a8ff3f-d332-436d-a9f9-cfeb9fdc648d.mov
After:
https://user-images.githubusercontent.com/886567/233850603-7e3ede17-bbbe-43a7-9138-cf17b43f0fdb.mov
=> :bug: (autocomplete) fix multi-select

packages/desktop-client/src/components/autocomplete/Autocomplete.js, upcoming-release-notes/949.md
=> :bug: (autocomplete) touch event support

packages/loot-core/src/server/accounts/parse-file.ts, upcoming-release-notes/951.md
=> Fixes issue #846 by eliminating empty lines during import.

packages/desktop-client/src/components/select/DateSelect.js, packages/desktop-client/src/components/settings/Format.js, upcoming-release-notes/910.md
=> Add setting to change first day of the week: Issue #844

packages/desktop-client/src/components/schedules/EditSchedule.js, upcoming-release-notes/953.md
=> :recycle:  re-arrange schedule operation options to be more logical

packages/desktop-client/src/components/accounts/TransactionsTable.js, upcoming-release-notes/966.md
=> :bug: (transaction-table) show checkbox on hover

packages/desktop-client/src/components/Notifications.js, upcoming-release-notes/972.md
=> :bug:  position notification banners always at bottom

packages/desktop-client/package.json, upcoming-release-notes/976.md, yarn.lock
Removing unused `prop-types` dependency.
=> :fire:  remove unused prop-types dependency

CONTRIBUTING.md, upcoming-release-notes/978.md
Updating active contributor list
=> :pencil:  add back rich, add alberto

.github/workflows/issues-close-feature-requests.yml, upcoming-release-notes/980.md
Run the feature request management action when adding "feature" label.
This will allow us to..
1. remove "feature" label
2. add back "feature" label
Thus execute the workflow on the existing issues.
=> :construction_worker:  run feature-request action on labeled action

packages/loot-core/src/shared/util.test.ts, packages/loot-core/src/shared/util.ts, upcoming-release-notes/995.md
Country found using https://gist.github.com/ncreated/9934896 Possible alternatives: mfe, ses, twq, khq, dje
=> Add a new number format (space-dot)

packages/desktop-client/src/components/reports/Header.js, upcoming-release-notes/1000.md
=> :bug: (reports) 1y date range should be 12 months not 13 months

packages/loot-core/src/server/accounts/parse-file.ts, upcoming-release-notes/1005.md
@j-f1 This should make the error messages better, just capture more lines in a try-block :joy:
=> Detect more errors in JS OFX importer.

README.md, upcoming-release-notes/1012.md
README now links to the right way to see open feature requests.
=> Add feature request link to README

packages/desktop-client/src/components/accounts/TransactionsTable.js, upcoming-release-notes/999.md
=> :bug: (TransactionTable) fix split-transaction focus field

packages/desktop-client/package.json, packages/desktop-client/src/components/Modals.js, packages/desktop-client/src/components/budget/rollover/BudgetSummary.js, packages/desktop-client/src/components/manager/Modals.js, packages/desktop-client/src/components/modals/LoadBackup.js, packages/desktop-client/src/components/payees/index.js, upcoming-release-notes/1036.md, yarn.lock
=> Remove `@reactions/component` dependency

.github/workflows/build.yml, packages/api/package.json, packages/api/tsconfig.dist.json, upcoming-release-notes/1002.md
- Use more modern ES features to improve debuggability
- Fix how data is copied into dist/ during the build
- Upload the built package as an artifact with every commit
=> Fix the API (again)

packages/desktop-client/src/components/schedules/DiscoverSchedules.js, upcoming-release-notes/1033.md
=> Remove messaging around where to find schedules in the future

packages/desktop-client/package.json, packages/desktop-client/src/components/BankSyncStatus.js, packages/desktop-client/src/components/budget/BudgetSummaries.js, upcoming-release-notes/1043.md, yarn.lock
Now we just have one spring animation library
=> Upgrade react-spring, remove wobble

packages/api/package.json
=> :bookmark: (6.0.1) api

README.md, upcoming-release-notes/1079.md
=> chore: remove `loot-design` reference from readme.md

packages/desktop-client/src/hooks/useLatestVersion.ts, packages/desktop-client/src/hooks/useResizeObserver.ts, packages/desktop-client/src/hooks/useSyncServerStatus.ts, packages/desktop-client/src/index.tsx, packages/desktop-client/src/polyfills.ts, packages/desktop-client/src/util.ts, packages/desktop-client/src/util/versions.ts, upcoming-release-notes/1078.md
I'm just replacing some JS files with TS, nothing huge.
=> chore: migrate some JS to TS

packages/desktop-client/src/components/settings/Reset.js, packages/desktop-client/src/components/settings/index.js, upcoming-release-notes/1104.md
=> Disable “Reset sync” button when sync is disabled

README.md, packages/api/README.md, packages/desktop-client/src/components/FatalError.js, packages/desktop-client/src/components/ManageRules.js, packages/desktop-client/src/components/SidebarWithData.js, packages/desktop-client/src/components/UpdateNotification.js, packages/desktop-client/src/components/accounts/AccountSyncCheck.js, packages/desktop-client/src/components/manager/ImportYNAB5.js, packages/desktop-client/src/components/manager/ManagementApp.js, packages/desktop-client/src/components/manager/WelcomeScreen.js, packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx, packages/desktop-client/src/components/modals/CreateAccount.js, packages/desktop-client/src/components/modals/CreateEncryptionKey.js, packages/desktop-client/src/components/modals/CreateLocalAccount.js, packages/desktop-client/src/components/modals/FixEncryptionKey.js, packages/desktop-client/src/components/schedules/EditSchedule.js, packages/desktop-client/src/components/settings/Encryption.js, packages/desktop-client/src/components/settings/index.js, packages/desktop-client/src/components/tutorial/Final.js, packages/desktop-client/src/components/tutorial/Intro.js, packages/desktop-electron/menu.js, packages/loot-core/src/client/shared-listeners.ts, packages/loot-core/src/client/update-notification.ts, packages/loot-core/src/platform/client/fetch/index.browser.ts, packages/loot-core/src/server/main.ts, packages/loot-core/src/shared/errors.ts, packages/loot-core/src/shared/rules.ts, upcoming-release-notes/1129.md
Depends on https://github.com/actualbudget/docs/pull/202.
=> Update links to point to new domain

packages/desktop-client/src/components/FixedSizeList.js, packages/desktop-client/src/components/KeyHandlers.tsx, packages/desktop-client/src/components/ManageRules.js, packages/desktop-client/src/components/NotesButton.tsx, packages/desktop-client/src/components/Titlebar.js, packages/desktop-client/src/components/accounts/MobileAccounts.js, packages/desktop-client/src/components/accounts/MobileTransaction.js, packages/desktop-client/src/components/accounts/TransactionsTable.js, packages/desktop-client/src/components/alerts.tsx, packages/desktop-client/src/components/autocomplete/AccountAutocomplete.js, packages/desktop-client/src/components/autocomplete/Autocomplete.tsx, packages/desktop-client/src/components/autocomplete/CategorySelect.tsx, packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js, packages/desktop-client/src/components/budget/BudgetMonthCountContext.js, packages/desktop-client/src/components/budget/MobileBudgetTable.js, packages/desktop-client/src/components/budget/misc.js, packages/desktop-client/src/components/common.tsx, packages/desktop-client/src/components/common/Text.tsx, packages/desktop-client/src/components/modals/EditRule.js, packages/desktop-client/src/components/modals/ImportTransactions.js, packages/desktop-client/src/components/select/DateSelect.js, packages/desktop-client/src/components/sort.js, packages/desktop-client/src/components/table.tsx, packages/desktop-client/src/hooks/useProperFocus.js, packages/desktop-client/src/util/versions.ts, upcoming-release-notes/1139.md
As discussed in #1126 creating separate PRs.
The linter rule isn't actually part of this first PR and will likely be in the final PR as otherwise it will just fail because all the issues aren't resolved. 
The code is 'ready' though so as soon as this is merged I will open next one(s)
=> Remove 'export' keyword where not needed.

packages/loot-core/src/server/migrate/migrations.ts, upcoming-release-notes/1161.md
Will help debug #1160 and similar issues in the future.
=> Log more details when migrations are out of sync

packages/loot-core/src/server/main.ts, upcoming-release-notes/1174.md
Looks like this got missed in the last PR!
=> Remove remaining tutorial code

packages/desktop-client/src/components/accounts/Account.js, packages/desktop-client/src/components/accounts/TransactionList.js, packages/desktop-client/src/components/accounts/TransactionsTable.js, upcoming-release-notes/1176.md
=> Automatic category selection for new category transactions

packages/desktop-client/src/components/FinancesApp.js, packages/desktop-client/src/components/accounts/Account.js, packages/desktop-client/src/components/accounts/MobileAccount.js, packages/desktop-client/src/components/budget/index.js, upcoming-release-notes/1171.md
Also remove the need to unmount & remount when switching between accounts. Fixes #1169
=> Fix transaction list page being blank on mobile

packages/desktop-electron/build.sh, packages/desktop-electron/electron-builder-fork.sh, packages/desktop-electron/package.json, upcoming-release-notes/1221.md
Bumping package version to match actual/web, and deleting two scripts i'm pretty sure are legacy/unused.
=> Tidy up electron

packages/desktop-client/src/components/FinancesApp.js, packages/desktop-client/src/global-events.js, packages/loot-core/typings/window.d.ts, upcoming-release-notes/1234.md
=> Restore undo-url-saving behavior

.github/ISSUE_TEMPLATE/bug-report.yml, upcoming-release-notes/1239.md
=> Add electron options to bug-report.yml

.github/actions/handle-feature-requests.js, .github/workflows/issues-feature-implemented.yml, upcoming-release-notes/1243.md
This should hopefully fix the workflow, which is currently failing quietly when feature request PRs are merged.
=> Run “Handle completed feature requests” in pull_request_target

packages/desktop-client/src/components/accounts/Account.js, upcoming-release-notes/1252.md
Closes #1249
Also removing some unused code
=> :bug:  fix toggling of balances in all-accounts view

packages/desktop-client/src/components/common.tsx, packages/desktop-client/src/components/common/Block.tsx, packages/desktop-client/src/components/common/Card.tsx, packages/desktop-client/src/components/common/HoverTarget.tsx, packages/desktop-client/src/components/common/InlineField.tsx, packages/desktop-client/src/components/common/Label.tsx, packages/desktop-client/src/components/common/Select.tsx, packages/desktop-client/src/components/common/TextOneLine.tsx, upcoming-release-notes/1248.md
This is direct copy & paste with no changes. Just moving things a bit to reduce the size of the massive common.tsx file
=> :recycle:  moving some components from common.tsx to separate files

packages/desktop-client/src/components/accounts/Account.js, packages/desktop-client/src/global-events.js, packages/desktop-client/src/util/router-tools.tsx, packages/desktop-electron/menu.js, packages/loot-core/typings/window.d.ts, upcoming-release-notes/1256.md
=> Remove remaining locationPtr usage

packages/desktop-client/src/components/common.tsx, packages/desktop-client/src/components/common/AlignedText.tsx, packages/desktop-client/src/components/common/CustomSelect.tsx, packages/desktop-client/src/components/common/FormError.tsx, packages/desktop-client/src/components/common/InitialFocus.tsx, packages/desktop-client/src/components/common/InputWithContent.tsx, packages/desktop-client/src/components/common/Menu.tsx, packages/desktop-client/src/components/common/Search.tsx, upcoming-release-notes/1257.md
Moving some more components out of `common.tsx` into their own files.
There are no functional changes. This is a direct copy&paste into new files.
=> :recycle:  moving more components out of common.tsx

packages/desktop-client/src/components/common/CustomSelect.tsx, packages/desktop-client/src/components/reports/Header.js, upcoming-release-notes/1294.md
Closes #1286, closes #1283
Scrollbar fix by @aleetsaiya
=> :bug:  custom select width and scrollbars

packages/desktop-client/package.json, packages/desktop-electron/package.json, upcoming-release-notes/1289.md, upcoming-release-notes/1291.md, upcoming-release-notes/1294.md
=> :bookmark: (23.7.1) critical sync fixes

packages/desktop-client/src/components/spreadsheet/format.js, upcoming-release-notes/1308.md
=> :bug:  fix zero budget values

.github/actions/check-migrations.js, .github/workflows/check.yml, upcoming-release-notes/1307.md
Now, it checks that all newly added migrations are dated after the newest migration on `master`.
=> Fix migration check script

packages/loot-core/src/server/budget/goaltemplates.ts, upcoming-release-notes/1288.md
This PR changes slightly how the remainder is calculated when multiple templates are used in the same category.  The remainder should be added to the already budgeted amount.
=> Goals: Improve remainder calculation when combined with other keywords

packages/desktop-electron/package.json, upcoming-release-notes/1281.md
I _think_ this no longer applies?
=> Remove author from electron package.json

packages/desktop-client/src/components/transactions/TransactionsTable.js, upcoming-release-notes/1362.md
Error in master when clicking on a schedule transaction cell.
=> Fix onExpose is not a function error

.github/workflows/issues-close-feature-requests.yml, upcoming-release-notes/1374.md
The change isn’t so new anymore so I’ve updated the comment to recognize that.
=> Update the text of the comment posted when closing feature requests

packages/desktop-client/src/components/budget/index.js, upcoming-release-notes/1237.md
Remembering the state of start month (selected month in budget)
Closes #1039
=> Storing start month in user prefs

packages/desktop-client/src/components/Notifications.tsx, packages/desktop-client/src/components/accounts/Header.js, packages/desktop-client/src/components/common/Button.tsx, packages/desktop-client/src/components/common/Modal.tsx, packages/desktop-client/src/icons/Loading.js, upcoming-release-notes/1390.md
This should help make it easier to implement dark mode 🤞
=> Consistency improvements for <AnimatedLoading>

packages/loot-core/src/server/api.ts, packages/loot-core/src/shared/errors.ts, upcoming-release-notes/1396.md
=> Improve messaging when the API fails to download a file

.github/actions/handle-feature-requests.js, upcoming-release-notes/1411.md
=> Fix typo in handle-feature-requests.js

packages/loot-core/src/shared/util.test.ts, packages/loot-core/src/shared/util.ts, upcoming-release-notes/0000.md, upcoming-release-notes/1412.md
Formats numbers as: 1,00,000 (100,000 == 1 lakh) and 1,00,00,000 (10M == 1 crore)
https://en.wikipedia.org/wiki/Indian_numbering_system
=> Add Indian numbering format

packages/desktop-client/src/components/sidebar.js, upcoming-release-notes/1421.md
=> :bug:  fix side-nav collapse/pin icon color

packages/desktop-client/src/components/LoggedInUser.js, upcoming-release-notes/1433.md
=> :bug:  fix incorrect state slice usage

.github/workflows/size-compare.yml, upcoming-release-notes/1435.md
Includes a few typographical improvements I PR’d.
(since the workflow is a `pull_request_target` one, the changes won’t show up in the comments till this PR is merged)
=> Update to the latest version of the size compare action

packages/desktop-client/src/components/accounts/Header.js, packages/desktop-client/src/components/budget/report/BudgetSummary.tsx, packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx, upcoming-release-notes/1446.md
Updating other menus to sentence case so that it is consistent with the other menus throughout the app
=> Sentence case in menus

packages/desktop-client/src/components/PrivacyFilter.tsx, packages/desktop-client/src/components/reports/CashFlow.js, packages/desktop-client/src/components/reports/NetWorth.js, packages/desktop-client/src/components/reports/Overview.js, upcoming-release-notes/1447.md
Addresses https://github.com/actualbudget/actual/issues/1360#issuecomment-1646600087
=> Reports privacy filter

packages/crdt/src/crdt/merkle.test.ts, packages/crdt/src/crdt/merkle.ts, packages/crdt/src/crdt/timestamp.test.ts, packages/crdt/src/crdt/timestamp.ts, packages/crdt/tsconfig.dist.json, upcoming-release-notes/1437.md
This PR has no functional changes. Only types are changing and getting improved (more stricter).
A follow-up PR will come next that does a few functional changes to make this package fully strict.
=> :recycle: (crdt) adding more strict typings

packages/desktop-client/src/components/ServerContext.tsx, packages/desktop-client/src/components/common/Input.tsx, packages/desktop-client/src/components/manager/ConfigServer.js, packages/desktop-client/src/components/manager/ConfigServer.tsx, packages/desktop-client/src/components/manager/ServerURL.tsx, packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.tsx, packages/desktop-client/src/components/manager/subscribe/Login.tsx, packages/desktop-client/src/components/manager/subscribe/common.tsx, packages/loot-core/src/types/server-handlers.d.ts, upcoming-release-notes/1431.md
=> Move big input component into Input.js, port some of the manager app to TS

packages/loot-core/migrations/1691233396000_add_schedule_next_date_tombstone.sql, packages/loot-core/src/server/schedules/app.ts, upcoming-release-notes/1463.md
=> :bug: (schedules) fix creating schedules with the same name

packages/desktop-client/src/components/FinancesApp.tsx, packages/desktop-client/src/style/themes/dark.ts, packages/desktop-client/src/style/themes/light.ts, upcoming-release-notes/1456.md
=> Fix the mobile footer color

packages/api/package.json, packages/desktop-client/package.json, packages/desktop-electron/package.json, upcoming-release-notes/1431.md, upcoming-release-notes/1437.md, upcoming-release-notes/1438.md, upcoming-release-notes/1446.md, upcoming-release-notes/1447.md, upcoming-release-notes/1448.md, upcoming-release-notes/1449.md, upcoming-release-notes/1450.md, upcoming-release-notes/1451.md, upcoming-release-notes/1452.md, upcoming-release-notes/1456.md, upcoming-release-notes/1458.md, upcoming-release-notes/1460.md, upcoming-release-notes/1461.md, upcoming-release-notes/1462.md, upcoming-release-notes/1463.md, upcoming-release-notes/1464.md, upcoming-release-notes/1473.md, upcoming-release-notes/1478.md
- web: https://github.com/actualbudget/actual/pull/1475
- server: https://github.com/actualbudget/actual-server/pull/240
- docs: https://github.com/actualbudget/docs/pull/260
=> :bookmark: (23.8.1) fix nYNAB import, mobile colors and other smaller fixes

packages/desktop-client/src/components/accounts/MobileAccount.js, upcoming-release-notes/1486.md
Closes https://github.com/actualbudget/actual/issues/1485.
See the issue for details.
=> Fix mobile account view

packages/loot-core/src/server/budget/goaltemplates.ts, upcoming-release-notes/1481.md
Resolves: https://github.com/actualbudget/actual/issues/1441
=> Goals: Ignore hidden categories when running goal templates

packages/desktop-client/src/components/accounts/Account.js, packages/desktop-client/src/components/transactions/TransactionsTable.js, upcoming-release-notes/1508.md
Display both - transfer & schedule icon if they are available.
=> :bug:  show all available transaction icons

packages/loot-core/src/server/importers/ynab4-types.d.ts, packages/loot-core/src/server/importers/ynab4.ts, upcoming-release-notes/1515.md
=> Import category notes from YNAB4 exports

packages/loot-core/src/server/importers/ynab5.ts, upcoming-release-notes/1529.md
=> :bug: (importer) fix nYNAB importer when decimal budgets used

.eslintrc.js, packages/desktop-client/src/components/accounts/Balance.js, packages/desktop-client/src/components/accounts/Header.js, packages/desktop-client/src/components/schedules/StatusBadge.js, packages/desktop-client/src/components/transactions/TransactionsTable.js, packages/desktop-client/src/style/themes/light.ts, upcoming-release-notes/1530.md
Fixing lightmode regressions after some of the darkmode PRs were merged.
=> :bug: (darkmode) fixing lightmode regressions in transaction table

packages/desktop-client/src/components/budget/MobileBudgetTable.js, upcoming-release-notes/1539.md
Addresses https://github.com/actualbudget/actual/issues/1196
=> Mobile: Don't show hidden categories

packages/desktop-client/src/components/modals/BudgetSummary.js, upcoming-release-notes/1540.md
Addresses https://github.com/actualbudget/actual/issues/1538
Just had to rearrange a few things.
=> Mobile: To Budget inconsistency 

packages/desktop-client/src/components/FatalError.tsx, upcoming-release-notes/1552.md
Resolves #1537 
- Unified UI Error and renderSimple design
- Turned renderSimple into React component
- Refactored Fatal Error Component to not repeat code
=> [Bug]: darkmode regression - fatal error message is ugly

packages/desktop-client/src/components/schedules/SchedulesTable.js, upcoming-release-notes/1580.md
Addresses https://github.com/actualbudget/actual/issues/1360#issuecomment-1666891359
=> Schedule privacy

packages/desktop-client/src/components/Modals.tsx, upcoming-release-notes/1613.md
https://github.com/actualbudget/actual/issues/1608
=> Close modals on route change

packages/desktop-client/src/components/accounts/Balance.js, packages/desktop-client/src/components/accounts/Reconcile.js, packages/desktop-client/src/components/budget/MobileBudgetTable.js, packages/desktop-client/src/components/budget/report/BudgetSummary.tsx, packages/desktop-client/src/components/budget/report/components.tsx, packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx, packages/desktop-client/src/components/budget/rollover/rollover-components.tsx, packages/desktop-client/src/components/modals/BudgetSummary.js, packages/desktop-client/src/components/spreadsheet/CellValue.tsx, packages/desktop-client/src/components/spreadsheet/useFormat.ts, packages/desktop-client/src/components/table.tsx, upcoming-release-notes/1630.md
Replace usage of format to useFormat + converted `BudgetTable` in `MobileBudgetTable.js` to functional component to be able to use the hook.
=> Replace format with useFormat

packages/desktop-client/src/components/transactions/TransactionsTable.js, upcoming-release-notes/1645.md
=> Fix onNavigateToSchedule prop

packages/desktop-client/src/components/AppBackground.tsx, packages/desktop-client/src/components/NotesButton.tsx, packages/desktop-client/src/components/autocomplete/Autocomplete.tsx, packages/desktop-client/src/components/budget/BudgetSummaries.js, packages/desktop-client/src/components/budget/report/BudgetSummary.tsx, packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx, packages/desktop-client/src/components/common/AnchorLink.tsx, packages/desktop-client/src/components/common/Block.tsx, packages/desktop-client/src/components/common/InlineField.tsx, packages/desktop-client/src/components/common/Input.tsx, packages/desktop-client/src/components/common/LinkButton.tsx, packages/desktop-client/src/components/common/Paragraph.tsx, packages/desktop-client/src/components/common/Select.tsx, packages/desktop-client/src/components/common/Text.tsx, packages/desktop-client/src/components/common/View.tsx, packages/desktop-client/src/components/forms.tsx, packages/desktop-client/src/components/mobile/MobileForms.js, packages/desktop-client/src/components/modals/CreateEncryptionKey.js, packages/desktop-client/src/components/reports/Tooltip.js, packages/desktop-client/src/components/settings/UI.tsx, packages/desktop-client/src/components/sidebar/Account.tsx, packages/desktop-client/src/components/tooltips.js, packages/desktop-client/src/components/transactions/MobileTransaction.js, packages/desktop-client/src/icons/AnimatedLoading.js, upcoming-release-notes/1637.md
Changes are on top top of #1542. That needs to be merged first before this PR.
=> Remove glamor css

packages/desktop-client/src/components/accounts/MobileAccountDetails.js, packages/desktop-client/src/components/transactions/MobileTransaction.js, upcoming-release-notes/1648.md
Update mobile page "back" navigations to go back to previous page instead of fixed routes.
=> Fix mobile page "back" behaviors

packages/desktop-client/src/components/PrivacyFilter.tsx, upcoming-release-notes/1646.md
=> Fix blur performance issue in Safari

packages/desktop-client/src/components/modals/ImportTransactions.js, upcoming-release-notes/1649.md
Fix QFX import errors reported in version 23.9.0.
=> Fix ofx/qfx import options

packages/desktop-client/.swcrc, packages/loot-core/.swcrc, upcoming-release-notes/1659.md
=> Enable swc sourcemap

package.json, packages/loot-core/src/client/platform.electron.ts, upcoming-release-notes/1658.md
Improving OS detection for electron apps.
=> :wrench: (electron) improved OS detection

packages/desktop-electron/package.json, upcoming-release-notes/1674.md, yarn.lock
Nothing very interesting here.. just upgrading all electron dependencies in preperation of experimental release of the desktop app.
=> :arrow_up: (electron) upgrading electron-based dependencies

packages/desktop-client/src/components/gocardless/GoCardlessLink.js
=> Fix typo in GoCardlessLink.js

packages/desktop-client/src/components/sidebar/Account.tsx, packages/desktop-client/src/style/themes/dark.ts, packages/desktop-client/src/style/themes/light.ts, upcoming-release-notes/1703.md
=> Sidebar Account Fix

packages/loot-core/src/server/accounts/rules.ts, packages/loot-core/src/server/accounts/transaction-rules.test.ts, packages/loot-core/src/server/accounts/transaction-rules.ts, packages/loot-core/src/shared/rules.ts, upcoming-release-notes/1708.md
=> fix: filter empty note

packages/loot-core/src/server/schedules/app.ts, upcoming-release-notes/1728.md
Fixes #1726 
Not sure if this implementation is the best way to approach this problem, looking forward to feedback on this
=> keep name after schedule completion or recreation

packages/desktop-client/src/components/sort.tsx, packages/desktop-client/src/hooks/useMergedRefs.ts, upcoming-release-notes/1733.md
Consolidate useMergedRefs hook and convert it to TypeScript.
=> Maintenance: Consolidate useMergedRef and convert to typescript

packages/desktop-client/src/components/budget/MobileBudgetTable.js, packages/desktop-client/src/components/common/InputWithContent.tsx, packages/desktop-client/src/components/schedules/EditSchedule.js, packages/desktop-client/src/components/spreadsheet/CellValue.tsx, packages/desktop-client/src/components/util/AmountInput.js, upcoming-release-notes/1662.md
=> Editable mobile budget

packages/loot-core/src/server/accounts/transfer.ts, upcoming-release-notes/1751.md
Related to https://github.com/actualbudget/actual/issues/1746
=> Prevent parent transaction from being added to transfer account

.github/FUNDING.yml
=> Update FUNDING.yml - add github sponsors

packages/desktop-client/src/components/schedules/EditSchedule.js, upcoming-release-notes/1759.md
Closes https://github.com/actualbudget/actual/issues/1719
=> Allow linked child transactions

packages/desktop-client/src/components/Titlebar.tsx, packages/desktop-client/src/components/budget/BudgetPageHeader.tsx, packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx, packages/desktop-client/src/components/budget/index.tsx, packages/desktop-client/src/components/budget/rollover/HoldTooltip.tsx, packages/desktop-client/src/components/budget/rollover/TransferTooltip.tsx, packages/desktop-client/src/components/table.tsx, packages/loot-core/src/client/SpreadsheetProvider.tsx, packages/loot-core/src/client/actions/queries.ts, packages/loot-core/src/server/spreadsheet/spreadsheet.ts, packages/loot-core/src/types/prefs.d.ts, packages/loot-core/src/types/server-handlers.d.ts, upcoming-release-notes/1834.md
Convert Titlebar, BudgetPageHeader, DynamicBudgetTable, Tooltips components to Typescript
#1483
=> Maintenance: Moving some components to Typescript

packages/desktop-client/src/components/budget/MobileBudget.js, packages/desktop-client/src/components/budget/MobileBudgetTable.js, upcoming-release-notes/1858.md
We could decide in the future to remove the sync button in the budget page header which does the same thing.
=> Mobile budget pull down to sync

.eslintrc.js, packages/desktop-client/src/components/filters/SavedFilters.js, packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx, packages/desktop-client/src/components/transactions/MobileTransaction.js, packages/desktop-client/src/components/transactions/TransactionsTable.js, upcoming-release-notes/1893.md
Enabled `react/no-unstable-nested-components` rule. This should help us build more maintainable code going forward. Also fixed some of the existing issues.
=> :wrench: (eslint) enabling 'react/no-unstable-nested-components' rule

packages/desktop-client/src/components/modals/ImportTransactions.js, packages/loot-core/src/server/accounts/ofx2json.ts, upcoming-release-notes/1876.md
Resolves #1863. A sample file can be found in the ticket for testing.
=> Support ofx INVSTMTMSGSRSV1

.eslintrc.js, packages/desktop-client/src/browser-preload.browser.js, packages/desktop-electron/afterSignHook.js, packages/desktop-electron/security.js, packages/node-libofx/index.js, upcoming-release-notes/1949.md
https://eslint.org/docs/latest/rules/no-var
=> :wrench: (eslint) disallow using 'var': no-var rule

.eslintrc.js, packages/api/app/query.js, packages/crdt/src/crdt/merkle.test.ts, packages/crdt/src/crdt/merkle.ts, packages/crdt/src/crdt/timestamp.test.ts, packages/crdt/src/crdt/timestamp.ts, packages/desktop-client/src/browser-preload.browser.js, packages/desktop-client/src/browser-server.js, packages/desktop-client/src/global-events.js, packages/desktop-client/src/gocardless.js, packages/desktop-client/src/hooks/useLatestVersion.ts, packages/desktop-client/src/hooks/useNavigate.ts, packages/desktop-client/src/hooks/useProperFocus.tsx, packages/desktop-client/src/hooks/useResizeObserver.ts, packages/desktop-client/src/hooks/useSelected.tsx, packages/desktop-client/src/icons/Loading.tsx, packages/desktop-client/src/plaid.js, packages/desktop-client/src/style/styles.ts, packages/desktop-client/src/style/theme.tsx, packages/desktop-client/src/util/router-tools.tsx, packages/desktop-client/src/util/versions.ts, packages/desktop-electron/afterSignHook.js, packages/desktop-electron/index.js, packages/desktop-electron/menu.js, packages/desktop-electron/preload.js, packages/desktop-electron/security.js, packages/desktop-electron/server.js, packages/desktop-electron/updater.js, packages/desktop-electron/window-state.js, upcoming-release-notes/1956.md
This is the first PR to apply ESLint's `prefer-const` rule. The strategy is to add more on and more folders to `.eslintrc.js` until the whole codebase warnings are address and then we can remove the override in `.eslintrc.js` to apply the rule globally.
For this PR, I applied the rule to less frequently changed files so it shouldn't conflict with the other ongoing PRs.
=> [Maintenance] ESLint - prefer-const

packages/loot-core/src/server/accounts/rules.ts, packages/loot-core/src/types/models/rule.d.ts, upcoming-release-notes/1987.md
Looks like a really simple fix. Just missing some values in the rule ranker.
fixes #1825 
fixes #1985
=> Update rules API

packages/loot-core/src/mocks/budget.ts, packages/loot-core/src/server/accounts/transaction-rules.ts, packages/loot-core/src/shared/transactions.ts, packages/loot-core/src/shared/util.ts, packages/loot-core/src/types/models/transaction.d.ts, upcoming-release-notes/2023.md
Adding more strict typings to `utils.ts` and some of its dependencies (where necessary).
=> :recycle: (typescript) adding strict typings to utils.ts

packages/desktop-client/src/components/FinancesApp.tsx, upcoming-release-notes/2092.md
Hi,
this should fix issue #2089 
In the light theme the white bg color is also wrong but not that visible
Thank you!
=> Added BG Color to view to fix Issue 2089

.eslintrc.js, packages/desktop-client/src/components/filters/FiltersButton.tsx, packages/desktop-client/src/components/reports/ReportTableHeader.tsx, packages/desktop-client/src/components/reports/ReportTableTotals.tsx, packages/desktop-client/src/components/reports/SaveReport.tsx, packages/desktop-client/src/components/reports/graphs/BarGraph.tsx, packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx, upcoming-release-notes/2111.md
Disallow using unnecessary curly braces.
Should make our codebase slightly more consistent.
=> :recycle: (eslint) disallow unnecessary curly braces

packages/desktop-client/src/components/manager/DeleteFile.tsx, packages/loot-core/src/types/server-handlers.d.ts, upcoming-release-notes/2112.md
=> :recycle: (typescript) moving DeleteFile modal to TS

packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx, upcoming-release-notes/2098.md
=> Custom Reports Donut Graph refactor

packages/desktop-client/src/components/common/Menu.tsx, packages/desktop-client/src/components/payees/PayeeTable.tsx, packages/desktop-client/src/components/schedules/SchedulesTable.tsx, packages/desktop-client/src/components/table.tsx, packages/desktop-client/src/components/transactions/TransactionsTable.jsx, packages/loot-core/src/server/sync/sync.property.test.ts, upcoming-release-notes/2071.md
Reverting https://github.com/actualbudget/actual/pull/2071
This is causing some issues in payee table. I will investigate and re-revert with the patch.
=> revert: ♻️ (TypeScript) fix strictFunctionTypes violations (pt 4)

packages/desktop-client/src/components/mobile/MobileAmountInput.jsx, packages/desktop-client/src/components/transactions/MobileTransaction.jsx, packages/desktop-client/src/hooks/useSingleActiveEditForm.tsx, upcoming-release-notes/2166.md
https://github.com/actualbudget/actual/issues/2149
=> Fix mobile transaction page amount input

packages/desktop-client/src/components/common/Menu.tsx, packages/desktop-client/src/components/payees/PayeeTable.tsx, packages/desktop-client/src/components/schedules/SchedulesTable.tsx, packages/desktop-client/src/components/table.tsx, packages/loot-core/src/server/sync/sync.property.test.ts, upcoming-release-notes/2142.md
re-revert of https://github.com/actualbudget/actual/pull/2128
=> ♻️ (TypeScript) fix strictFunctionTypes violations (pt 4)

packages/desktop-client/src/components/accounts/MobileAccount.jsx, upcoming-release-notes/2114.md, upcoming-release-notes/2186.md
Reverts actualbudget/actual#2114
The change was not compatible with the latest no default exports changes
=> Revert "Add "error" Page for special accounts in Mobile"

packages/desktop-client/src/components/ManageRules.tsx, upcoming-release-notes/2199.md
=> :bug: (rules) add 'no rules' message & always show rule table

packages/desktop-client/public/site.webmanifest, upcoming-release-notes/2202.md
=> Fix webmanifest to enable Actual to be installed as Chromium PWA

packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx, upcoming-release-notes/2181.md
Related PR in `actual-server`: https://github.com/actualbudget/actual-server/pull/293
=> :recycle: (gocardless) rename nordigen_* secrets to gocardless_*

packages/loot-core/src/server/budget/actions.ts
=> chore: Update actions.ts

packages/loot-core/src/server/accounts/sync.ts, upcoming-release-notes/2238.md
=> :bug: (gocardless) fix sync when additionalInformation field is null

packages/desktop-client/src/components/manager/DeleteFile.tsx, upcoming-release-notes/2251.md
=> :bug: fix 'delete budget' button always deleting cloud file

packages/desktop-client/src/components/select/RecurringSchedulePicker.jsx, upcoming-release-notes/2261.md
=> fix color of schedule before/after weekend box

packages/desktop-client/src/components/accounts/MobileAccountDetails.jsx, packages/desktop-client/src/components/transactions/MobileTransaction.jsx, upcoming-release-notes/2284.md
=> Mobile Off Budget category label

packages/desktop-client/README.md, upcoming-release-notes/2287.md
Ive updated this to clear up some of what may have cause me some confusion originally.
=> update vrt instructions

packages/loot-core/src/server/main.ts, upcoming-release-notes/2328.md
=> :fire: removing unused/dead code

packages/desktop-client/src/components/reports/ChooseGraph.tsx, packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx, packages/desktop-client/src/components/reports/graphs/BarGraph.tsx, packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx, upcoming-release-notes/2346.md
Dynamically changing graph margins for large budgets with YAxis max > 1,000,000.
=> Dynamic graph margins

packages/desktop-client/src/components/sidebar/Sidebar.tsx, upcoming-release-notes/2383.md
Fixes https://github.com/actualbudget/actual/issues/2382
=> Fix ability to rename budget in the UI

packages/desktop-client/src/components/payees/PayeeTableRow.tsx, packages/desktop-client/src/style/themes/midnight.ts, upcoming-release-notes/2394.md
Addresses https://github.com/actualbudget/actual/issues/2393
=> [Theme] Midnight updates

packages/desktop-client/src/components/schedules/ScheduleDetails.jsx, upcoming-release-notes/2401.md
Attempt to fix #2363 bug causing the create schedule from transaction feature to not work.  I dont understand why this broke when the pr build works fine.
=> fix #2363 broken create schedule from transaction

packages/desktop-client/src/components/reports/graphs/BarGraph.tsx, packages/desktop-client/src/components/reports/graphs/renderCustomLabel.tsx, upcoming-release-notes/2411.md
Found a crash in BarGraph that's been missed.
=> BarGraph crash

packages/desktop-client/src/components/FatalError.tsx, packages/desktop-client/src/components/GlobalKeys.ts, packages/desktop-client/src/components/accounts/Account.jsx, packages/desktop-client/src/components/manager/ImportActual.tsx, packages/desktop-client/src/components/manager/ImportYNAB4.tsx, packages/desktop-client/src/components/manager/ImportYNAB5.tsx, packages/desktop-client/src/components/manager/ManagementApp.jsx, packages/desktop-client/src/components/modals/ImportTransactions.jsx, packages/desktop-client/src/components/settings/Export.tsx, packages/desktop-client/src/components/settings/FixSplits.tsx, packages/desktop-client/src/components/settings/Global.tsx, packages/desktop-client/src/components/settings/Reset.tsx, packages/desktop-client/src/components/settings/index.tsx, packages/desktop-client/src/gocardless.ts, packages/desktop-client/src/hooks/useFeatureFlag.ts, packages/desktop-client/src/plaid.js, packages/desktop-client/src/tokens.ts, packages/desktop-client/src/util/versions.ts, upcoming-release-notes/2403.md
=> :recycle: (typescript) move some files to strict mode

packages/desktop-client/src/components/accounts/MobileAccountDetails.jsx, packages/desktop-client/src/components/common/Input.tsx, packages/desktop-client/src/components/common/Search.tsx, packages/desktop-client/src/components/filters/NameFilter.tsx, packages/desktop-client/src/components/manager/ConfigServer.tsx, packages/desktop-client/src/components/mobile/MobileAmountInput.jsx, packages/desktop-client/src/components/mobile/MobileForms.jsx, packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx, packages/desktop-client/src/components/modals/ImportTransactions.jsx, packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx, packages/desktop-client/src/components/modals/SingleInput.tsx, packages/desktop-client/src/components/reports/SaveReportName.tsx, packages/desktop-client/src/components/table.tsx, packages/desktop-client/src/components/util/AmountInput.tsx, upcoming-release-notes/2381.md
The goal is to have consistent naming convention in the codebase.
- onUpdate
- Fires on blur
- onChangeValue
- Fires whenever input value is changed
=> [Maintenance] Input onChangeValue and onUpdate prop naming

packages/desktop-client/src/style/themes/midnight.ts, upcoming-release-notes/2460.md
=> [Theme] Bugfix: Bulk edit background color for Midnight theme

packages/desktop-client/src/components/budget/BudgetTable.jsx, packages/desktop-client/src/components/budget/DynamicBudgetTable.tsx, packages/desktop-client/src/components/budget/index.tsx, upcoming-release-notes/2459.md
=> Convert BudgetTable to a functional component

packages/desktop-client/src/components/mobile/PullToRefresh.tsx, upcoming-release-notes/2487.md
Closes https://github.com/actualbudget/actual/issues/2486
=> Force async onRefresh on PullToRefresh component

packages/desktop-client/src/components/ScrollProvider.tsx, packages/desktop-client/src/components/mobile/transactions/ListBox.jsx, upcoming-release-notes/2504.md
Fixes https://github.com/actualbudget/actual/issues/2427
=> Fix mobile transactions load more

packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx, packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx, packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx, upcoming-release-notes/2530.md
Fixes https://github.com/actualbudget/actual/issues/2517
=> Fix mobile autocomplete colors

packages/api/tsconfig.dist.json, packages/loot-core/src/server/importers/ynab5.ts, packages/loot-core/src/types/api-handlers.d.ts, upcoming-release-notes/2567.md
- Fixes some missing models
- Fixes some output path aliasing
=> Improve api output types

packages/desktop-client/src/components/common/Modal.tsx, upcoming-release-notes/2586.md
=> [Maintenance] Remove left behind editableTitle prop

packages/desktop-client/src/components/reports/ChooseGraph.tsx, packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx, upcoming-release-notes/2583.md
Enables the ability to show transactions when donut graph is clicked.
=> Custom Reports: Show Activity for donutGraph

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx, packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx, packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx, upcoming-release-notes/2598.md
Update balance menu modal title and add balance amount in the modal.
=> Balance menu modal enhancement

packages/desktop-client/src/components/LoggedInUser.tsx, packages/desktop-client/src/components/NotesButton.tsx, packages/desktop-client/src/components/ThemeSelector.tsx, packages/desktop-client/src/components/Titlebar.tsx, packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx, packages/desktop-client/src/components/common/Popover.tsx, packages/desktop-client/src/components/sidebar/Sidebar.tsx, upcoming-release-notes/2593.md
Follow up to https://github.com/actualbudget/actual/pull/2493
=> :recycle: (tooltip) migration to react-aria (vol 2)

packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx, upcoming-release-notes/2608.md
=> [Mobile] Scheduled transaction menu modal

packages/desktop-client/src/components/NotesButton.tsx, packages/desktop-client/src/components/modals/AccountMenuModal.tsx, packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx, packages/desktop-client/src/components/modals/CategoryMenuModal.tsx, packages/desktop-client/src/components/modals/Notes.tsx, packages/desktop-client/src/hooks/useNotes.ts, upcoming-release-notes/2599.md
=> [Mobile] Fix account notes not retrieving correctly in mobile

packages/desktop-client/src/components/modals/HoldBufferModal.tsx, packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx, packages/desktop-client/src/components/modals/TransferModal.tsx, upcoming-release-notes/2607.md
=> [Mobile] Use decimal input mode for mobile modal amount fields

.gitignore, upcoming-release-notes/2623.md
Organize .gitignore and remove duplicated lines
=> [Maintenance] Organize .gitignore

packages/desktop-client/src/style/styles.ts, upcoming-release-notes/2650.md
Fixes #2621 
For now just doing the recommended 'auto' fix.  Doesn't do anything about styles
=> fix superfluous tooltip scrollbars fixes #2621

packages/desktop-client/src/components/reports/getLiveRange.ts, packages/desktop-client/src/components/reports/reportRanges.ts, packages/desktop-client/src/components/reports/reports/CustomReport.jsx, packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx, packages/desktop-client/src/components/reports/reports/GetCardData.tsx, packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts, packages/loot-core/src/shared/months.ts, upcoming-release-notes/2637.md
Fixing typescript issues with firstDayOfWeek. Also fixes bug with TableGraph report card.
=> Custom Reports update TS issues

packages/desktop-client/src/components/Modals.tsx, packages/desktop-client/src/components/modals/CoverModal.tsx, packages/desktop-client/src/components/modals/TransferModal.tsx, upcoming-release-notes/2635.md
Add To Be Budgeted category to cover and transfer modal
=> [Mobile] Add To Be Budgeted category to cover and transfer modal

packages/desktop-client/src/components/App.tsx, packages/desktop-client/src/components/AppBackground.tsx, packages/desktop-client/src/components/manager/BudgetList.jsx, packages/loot-core/src/types/file.d.ts, upcoming-release-notes/2663.md
=> Fix loading screen not showing when opening a budget file

packages/desktop-client/src/components/Modals.tsx, packages/desktop-client/src/components/Notes.tsx, packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx, packages/desktop-client/src/components/mobile/budget/index.tsx, packages/desktop-client/src/components/modals/AccountMenuModal.tsx, packages/desktop-client/src/components/modals/NotesModal.tsx, packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx, packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx, packages/loot-core/src/client/state-types/modals.d.ts, upcoming-release-notes/2690.md
Fix mobile notes modal not retrieving correct notes
=> [Mobile] Fix mobile account notes modal not retrieving correct notes

packages/desktop-client/src/components/App.tsx, upcoming-release-notes/2692.md
Closes https://github.com/actualbudget/actual/issues/2682
=> Fix management app flashing on page init

packages/loot-core/src/client/actions/budgets.ts, upcoming-release-notes/2730.md
=> Update load budget loading texts

packages/api/package.json, upcoming-release-notes/2853.md
Related: https://github.com/actualbudget/actual/pull/2852
=>  :bookmark: (api) 6.8.1: fix #2829

packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx, upcoming-release-notes/2875.md
Resolves https://github.com/actualbudget/actual/issues/2868
=> Fix mobile budget and spent column auto sizing

packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx, packages/desktop-client/src/components/reports/reports/ListCardsMenu.tsx, packages/desktop-client/src/components/reports/reports/ListCardsPopover.tsx, upcoming-release-notes/2878.md
A regression was introduced in #2778 that broke the menus for the individual custom report cards. Here is the fix.
=> Custom Reports: fix card menus regression

packages/loot-core/src/shared/schedules.ts, upcoming-release-notes/2890.md
Fixes https://github.com/actualbudget/actual/issues/2851
=> Revert scheduled transaction date filter causing weekly scheduled transactions as Paid

.github/workflows/trafico.yml, upcoming-release-notes/2895.md
Embed the trafico action as a workflow to get it working again.
(We can further improve or replace it going forward)
Here is an example showing it working for basic use case between two of my actual forks:  (showing that forked workflow still works here) https://github.com/twk3/actual-actions-target/pull/14
=> Trafico embedded action

packages/desktop-client/src/components/transactions/TransactionsTable.jsx, upcoming-release-notes/2941.md
=> Fix: Transaction table constantly resizing

packages/desktop-client/src/hooks/useNavigate.ts, upcoming-release-notes/2772.md
Reverts actualbudget/actual#2772
Fixes https://github.com/actualbudget/actual/issues/2962
=> Revert "[WIP] :bug: fix the app randomly navigating back (closing)"

packages/desktop-electron/index.ts, packages/desktop-electron/menu.ts, upcoming-release-notes/2978.md
Electron: Updating menu.js to menu.ts
Tested on:
- Windows
- Linux
=> :electron: Electron menu.js ➡️  menu.ts

packages/desktop-client/src/components/accounts/Account.jsx, packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx, packages/desktop-client/src/components/transactions/TransactionsTable.jsx, packages/loot-core/migrations/1720310586000_link_transfer_schedules.sql, packages/loot-core/src/client/data-hooks/schedules.tsx, packages/loot-core/src/server/accounts/transfer.ts, upcoming-release-notes/2990.md
=> Assign schedule to both transactions if schedule is a transfer

packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx, upcoming-release-notes/3008.md
=> Fix cover modal title

packages/loot-core/src/server/budget/goaltemplates.ts, upcoming-release-notes/3011.md
=> [Goals]: don't reset goals when using "apply template"

packages/desktop-client/src/browser-preload.browser.js, packages/desktop-client/src/components/Modals.tsx, packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx, packages/desktop-client/src/components/modals/KeyboardShortcuts.tsx, packages/loot-core/src/client/reducers/modals.ts, upcoming-release-notes/3033.md
Adds a modal for showing the keyboard shortcuts.
=> Add help modal for keyboard shortcuts.

packages/desktop-client/src/components/manager/Modals.jsx, upcoming-release-notes/3084.md
=> Fix "?" crashing on budget selection page.

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx, upcoming-release-notes/3073.md
Resolves https://github.com/actualbudget/actual/issues/3071
=> Fix rules not being applied in mobile transaction entry

packages/desktop-client/src/components/modals/AccountMenuModal.tsx, packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx, packages/desktop-client/src/components/modals/CategoryMenuModal.tsx, packages/desktop-client/src/components/modals/CloseAccountModal.tsx, packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx, packages/desktop-client/src/components/modals/ConfirmTransactionDelete.tsx, packages/desktop-client/src/components/modals/ConfirmTransactionEdit.tsx, packages/desktop-client/src/components/modals/ConfirmUnlinkAccount.tsx, packages/desktop-client/src/components/modals/CoverModal.tsx, packages/desktop-client/src/components/modals/CreateAccountModal.tsx, packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx, packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx, packages/desktop-client/src/components/modals/EditField.jsx, packages/desktop-client/src/components/modals/EditRule.jsx, packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx, packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx, packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx, packages/desktop-client/src/components/modals/HoldBufferModal.tsx, packages/desktop-client/src/components/modals/ImportTransactions.jsx, packages/desktop-client/src/components/modals/LoadBackup.jsx, packages/desktop-client/src/components/modals/MergeUnusedPayees.jsx, packages/desktop-client/src/components/modals/NotesModal.tsx, packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx, packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx, packages/desktop-client/src/components/modals/SelectLinkedAccounts.jsx, packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx, packages/desktop-client/src/components/modals/SingleInputModal.tsx, packages/desktop-client/src/components/modals/TransferModal.tsx, upcoming-release-notes/2918.md
=> React Aria Button on Modals

packages/desktop-electron/menu.ts, upcoming-release-notes/3100.md
**Added keyboard shortcuts reference to help menu so that people know it exists:**
=> :electron: Added keyboard shortcuts reference to Help menu

README.md, upcoming-release-notes/3101.md
=> Add callouts to starting fresh and migration documentations in README

README.md, upcoming-release-notes/3106.md
=> :pencil: update some information in the README

packages/desktop-client/src/components/reports/ReportSidebar.tsx, upcoming-release-notes/3117.md
Adding a "+1" to indicate that the current month toggle is on.
=> Custom Reports: PlusOne

packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx, packages/desktop-client/src/components/reports/reports/Spending.tsx, packages/desktop-client/src/components/reports/reports/SpendingCard.tsx, packages/loot-core/src/types/models/reports.d.ts, packages/loot-core/src/types/prefs.d.ts, upcoming-release-notes/3135.md
Card doesn't show the correct difference.
Fixes #3134
=> Spending Report: card fix

packages/desktop-client/src/components/common/Menu.tsx, packages/desktop-client/src/components/mobile/accounts/Accounts.jsx, packages/desktop-client/src/components/mobile/transactions/Transaction.jsx, upcoming-release-notes/3131.md
https://discord.com/channels/937901803608096828/1027831756545609789/1265864766631706625
=> Fix menus autoclosed when clicked element on top of the menu item

packages/desktop-client/src/components/common/Button2.tsx, upcoming-release-notes/3142.md
=> :bug: add missing hover cursor to new button component

packages/desktop-client/src/components/common/Button2.tsx, upcoming-release-notes/3146.md
=> Fix Button2 isDisabled prop

packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx, packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx, upcoming-release-notes/3151.md
=> :bug: fix plain-text link in simplefin error

packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx, packages/desktop-client/src/components/modals/EditRule.jsx, packages/desktop-client/src/components/modals/FixEncryptionKeyModal.tsx, packages/desktop-client/src/components/modals/GoCardlessInitialise.tsx, packages/desktop-client/src/components/modals/ImportTransactions.jsx, packages/desktop-client/src/components/modals/SimpleFinInitialise.tsx, packages/desktop-client/src/components/schedules/ScheduleDetails.jsx, packages/loot-core/src/server/accounts/rules.test.ts, packages/loot-core/src/server/accounts/rules.ts, packages/loot-core/src/server/rules/app.ts, upcoming-release-notes/3149.md
Closes #3139
Also patching some other modals. They would always close. Even if there were errors.
=> :bug: (rules) fix error handling

packages/desktop-client/playwright.config.js, upcoming-release-notes/3158.md
=> Fix local playwright reporter config

packages/desktop-client/src/components/common/Modal2.tsx, upcoming-release-notes/3160.md
=> :bug: (modals) remove focus outline

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx, upcoming-release-notes/3168.md
=> Set minWidth on <input /> to allow it to shrink.

packages/desktop-client/src/components/common/InputWithContent.tsx, packages/desktop-client/src/components/common/Modal2.tsx, upcoming-release-notes/3161.md
=> :bug: (modals) allow content to be vertically scrollable

packages/desktop-client/src/components/reports/ModeButton.tsx, packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx, packages/desktop-client/src/components/reports/reports/CashFlow.tsx, packages/desktop-client/src/components/reports/reports/Spending.tsx, upcoming-release-notes/3166.md
Tweaking the UI to make it more consistent with other reports.
=> Spending Report: UI Adjustments

packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx, packages/desktop-client/src/components/mobile/accounts/Accounts.jsx, upcoming-release-notes/3206.md
=> Fix mobile status indicators cutting off.

packages/desktop-client/src/components/reports/Header.jsx, packages/desktop-client/src/components/reports/reports/Spending.tsx, upcoming-release-notes/3209.md
Adjusting UI so that spending report works on mobile
=> Spending Report: Mobile UI

packages/desktop-client/src/components/autocomplete/ReportAutocomplete.tsx, packages/desktop-client/src/components/reports/Overview.tsx, packages/desktop-client/src/components/reports/SaveReport.tsx, packages/desktop-client/src/components/util/GenericInput.jsx, packages/loot-core/src/client/data-hooks/reports.ts, upcoming-release-notes/3198.md
Split off from https://github.com/actualbudget/actual/pull/3108
=> :recycle: (reports) improve useReports data fetching hook to return loading state

packages/desktop-electron/index.ts, packages/loot-core/src/platform/exceptions/index.electron.ts, upcoming-release-notes/3219.md
**Adding some error logs:**
Mac issue:
=>  :electron:  Making Electron server logs visible in devtools

packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx, packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetAmount.tsx, tsconfig.json, upcoming-release-notes/3237.md
Fix comment in https://github.com/actualbudget/actual/pull/3097#issuecomment-2276968422
=> Correct type for `to-budget` field

packages/desktop-client/src/components/mobile/transactions/Transaction.jsx, upcoming-release-notes/3258.md
=> fix(mobile): show category for on-to-off-budget transfers

packages/desktop-client/src/components/filters/FilterExpression.tsx, packages/desktop-client/src/components/filters/FilterMenu.tsx, packages/desktop-client/src/components/filters/FiltersButton.tsx, packages/desktop-client/src/components/filters/FiltersMenu.jsx, packages/desktop-client/src/components/filters/NameFilter.tsx, packages/desktop-client/src/components/filters/SavedFilterMenuButton.tsx, upcoming-release-notes/3270.md
Translation support for `packages/desktop-client/components/filters`.
=> Translation: desktop-client/components/filters

packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx, packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx, packages/desktop-client/src/components/autocomplete/FilterList.tsx, packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx, packages/desktop-client/src/components/autocomplete/ReportList.tsx, upcoming-release-notes/3275.md
Translation support for `packages/desktop-client/components/autocomplete`.
=> Translation: desktop-client/components/autocomplete

packages/desktop-client/src/components/budget/report/BalanceMenu.tsx, packages/desktop-client/src/components/budget/report/BudgetMenu.tsx, packages/desktop-client/src/components/budget/report/ReportComponents.tsx, packages/desktop-client/src/components/budget/report/budgetsummary/BudgetMonthMenu.tsx, packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx, packages/desktop-client/src/components/budget/report/budgetsummary/BudgetTotal.tsx, packages/desktop-client/src/components/budget/report/budgetsummary/ExpenseTotal.tsx, packages/desktop-client/src/components/budget/report/budgetsummary/IncomeTotal.tsx, packages/desktop-client/src/components/budget/report/budgetsummary/Saved.tsx, upcoming-release-notes/3280.md
Translation support for `packages/desktop-client/components/budget/report`.
=> Translation: desktop-client/components/budget/report

.github/workflows/electron-master.yml, .github/workflows/electron-pr.yml, packages/desktop-electron/package.json, upcoming-release-notes/3300.md, yarn.lock
Should close these: 
https://github.com/actualbudget/actual/issues/3259
https://github.com/actualbudget/actual/issues/3088
Tested with this artifact: https://github.com/MikesGlitch/actual/actions/runs/10496563766
=> :electron: Notarize the mac desktop app

packages/desktop-client/src/components/reports/Overview.tsx, upcoming-release-notes/3323.md
=> :bug: (dashboards) add back spending report if dashboards feature is not enabled

packages/desktop-client/src/components/table.tsx, upcoming-release-notes/3337.md
=> :bug: fix schedules modal closing when selecting link transactions

packages/desktop-client/src/components/transactions/TransactionsTable.jsx, upcoming-release-notes/3340.md
=> :bug: fix long payee name overflow

packages/desktop-client/src/components/accounts/Reconcile.jsx, upcoming-release-notes/3338.md
=> :bug: fix reconciliation closing on enter click

packages/desktop-client/src/components/accounts/Account.jsx, packages/desktop-client/src/components/accounts/AccountSyncCheck.jsx, packages/desktop-client/src/components/accounts/Balance.jsx, packages/desktop-client/src/components/accounts/Header.jsx, packages/desktop-client/src/components/accounts/Reconcile.jsx, upcoming-release-notes/3277.md
Translation support for `packages/desktop-client/src/components/accounts`
=> 🌍 add translations for `desktop-client/components/accounts`

packages/desktop-client/src/index.tsx, packages/desktop-electron/menu.ts, upcoming-release-notes/3389.md
=> :electron: Prevent keyboard shortcuts modal when entering shortcut into editable field

packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx, upcoming-release-notes/3394.md
Noticed this when debugging - it's polluting the logs
=> 🔧  Remove unneeded console log

packages/desktop-client/src/components/FatalError.tsx, packages/desktop-client/src/components/LoggedInUser.tsx, packages/desktop-client/src/components/gocardless/GoCardlessLink.tsx, packages/desktop-client/src/components/manager/BudgetList.tsx, packages/desktop-client/src/components/modals/GoCardlessExternalMsgModal.tsx, upcoming-release-notes/3430.md
Marked following files for translations:
- `/components/FatalError.tsx`
- `/components/gocardless/GoCardlessLink.tsx`
- `/components/LoggedInUser.tsx`
- `/components/modals/GoCardlessExternalMsgModal.tsx`
- `/components/manager/BudgetList.tsx`
=> Marked files for translation

packages/desktop-client/src/components/mobile/budget/index.tsx, upcoming-release-notes/3448.md
=> [Maintenance] Reduce budget table re-renders

packages/loot-core/src/server/accounts/sync.ts, upcoming-release-notes/3452.md
Re-implements db balance update if present (SimpleFin)
https://github.com/actualbudget/actual/issues/3279#issuecomment-2335154942
=> update synced account balance in db if available

packages/desktop-client/src/components/modals/CreateAccountModal.tsx, packages/desktop-client/src/components/settings/Experimental.tsx, packages/desktop-client/src/hooks/useFeatureFlag.ts, packages/loot-core/src/types/prefs.d.ts, upcoming-release-notes/3459.md
=> :sparkles: release simplefin as a first-party feature

packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx, packages/desktop-client/src/components/modals/CategoryMenuModal.tsx, upcoming-release-notes/3463.md
Fixes https://github.com/actualbudget/actual/issues/3418
=> Do not allow renaming to an empty category or group name

packages/desktop-client/src/global-events.ts, upcoming-release-notes/3468.md
Removing some old code that was missed.
=> :electron: Remove some old updater code

bin/run-vrt, upcoming-release-notes/3497.md
https://stackoverflow.com/questions/40213524/using-absolute-path-with-docker-run-command-not-working
=> fix: vrt:docker with git-bash

packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx, upcoming-release-notes/3509.md
=> add disable option for ToBudgetAmount popover when displaying modal

packages/desktop-client/src/components/accounts/Account.tsx, upcoming-release-notes/3539.md
=> fix creating rule from transaction

packages/desktop-client/src/components/modals/ImportTransactionsModal.jsx, upcoming-release-notes/3541.md
=>  :bug: (import) fix qfx import crash if input is malformed file

.github/workflows/size-compare.yml, upcoming-release-notes/3577.md
=> :arrow_up: upgrade some github actions

packages/desktop-client/src/hooks/useLocalPref.ts, upcoming-release-notes/3718.md
=> :recycle: (synced-prefs) remove no longer necessary migration

.github/workflows/update-vrt.yml, upcoming-release-notes/3764.md
Unfortunately this can't be tested on this PR. And only with it on the main branch.
=> ci: /update-vrt

.github/workflows/update-vrt.yml
=> fix: /update-vrt on forks

.github/workflows/update-vrt.yml
fatal: detected dubious ownership in repository at 
https://github.com/actions/runner-images/issues/6775
=> fix: /update-vrt

.github/workflows/update-vrt.yml
=> [WIP] Update update-vrt.yml

packages/desktop-client/src/components/settings/Experimental.tsx
Missed this, we shouldn't use the old feature request issue for new feedback.
I've skipped the release note, I don't think it's really required
=> change feedback issue for openid

packages/desktop-client/src/components/modals/HoldBufferModal.tsx, upcoming-release-notes/4068.md
=> fix mobile hold buffer initial sign

eslint.config.mjs, packages/api/index.ts, packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx, packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx, upcoming-release-notes/4123.md
The rule was unintentionally removed in the eslint PR
=> Add back eslint useDispatch and useSelector rules

packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
just fixing the capital / lowercase letter thing for authentik :)
=> Correct name for authentik IDP

packages/desktop-client/src/components/reports/SaveReportDelete.tsx, upcoming-release-notes/4167.md
Change from using ':' and no question mark to a full sentence and a question mark
=> Improve string to be clearer in other languages

packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
My PR on authentik was merged, so now we can link a complete guide on how to get Actual working with authentik.
=> Update Link to official authentik documentation

packages/desktop-client/src/components/schedules/UpcomingLength.tsx, packages/loot-core/src/client/data-hooks/schedules.tsx, packages/loot-core/src/client/data-hooks/transactions.ts, packages/loot-core/src/shared/schedules.test.ts, packages/loot-core/src/shared/schedules.ts, upcoming-release-notes/4168.md
https://github.com/actualbudget/actual/issues/3660
- makes the one month option dynamic
- adds current month option
=> make one month schedule upcoming length dynamic and add current month option

packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx, packages/loot-core/src/types/models/transaction.d.ts
This probably doesn't need a release note, there's been enough noise about schedules today
=> fix mobile schedule status

eslint.config.mjs, packages/api/index.ts, packages/desktop-client/src/components/App.tsx, upcoming-release-notes/4184.md
=> :bug: patch lint issues in master branch

.github/ISSUE_TEMPLATE/bug-report.yml, packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx, packages/desktop-client/src/components/modals/manager/ImportActualModal.tsx, packages/desktop-client/src/components/modals/manager/ImportModal.tsx, packages/desktop-client/src/components/modals/manager/ImportYNAB4Modal.tsx, packages/desktop-client/src/components/modals/manager/ImportYNAB5Modal.tsx, packages/desktop-client/src/components/settings/Export.tsx, packages/desktop-client/src/util/versions.ts, packages/loot-core/src/client/actions/notifications.ts, packages/loot-core/src/client/shared-listeners.ts, upcoming-release-notes/4187.md
It follows the [official trademark style](https://docs.github.com/en/site-policy/content-removal-policies/github-trademark-policy).
=> Ensure GitHub name is used correctly across the project

packages/desktop-client/src/browser-preload.browser.js, packages/desktop-client/src/util/versions.ts, upcoming-release-notes/4183.md
=> :recycle: do not check outdated version for preview builds

packages/loot-core/src/client/data-hooks/schedules.tsx, packages/loot-core/src/server/schedules/app.ts, packages/loot-core/src/shared/schedules.test.ts, packages/loot-core/src/shared/schedules.ts, upcoming-release-notes/4199.md
This fix addresses https://github.com/actualbudget/actual/issues/3709
=> Fix type mismatch in getStatus

packages/loot-core/src/client/actions/budgets.ts, upcoming-release-notes/4208.md
=> [Typescript] Update validateBudgetName and uniqueBudgetName return types

packages/desktop-client/src/components/ManageRules.tsx, packages/desktop-client/src/components/Modals.tsx, packages/desktop-client/src/components/accounts/Account.tsx, packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx, packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx, packages/desktop-client/src/components/transactions/SelectedTransactionsButton.tsx, packages/desktop-client/src/components/transactions/TransactionMenu.tsx, packages/loot-core/src/client/state-types/modals.d.ts, upcoming-release-notes/4180.md
Fixes https://github.com/actualbudget/actual/issues/923, fixes #3383
There was a discussion in the issue as to whether to delete the schedule instead of complete it, what do you think?
=> add option to complete non-recurring schedules from transaction menu

packages/desktop-client/e2e/budget.mobile.test.ts
=> fix mobile e2e test

packages/desktop-client/src/components/settings/LanguageSettings.tsx, upcoming-release-notes/4312.md
=> fix Weblate URL if language has never been changed

eslint.config.mjs, packages/desktop-client/src/hooks/useAccounts.ts, upcoming-release-notes/4262.md
Fix some suppressed react-hooks/exhaustive-deps ESLint errors
=> Fix react-hooks/exhaustive-deps error on useAccounts.ts

packages/desktop-client/src/i18n.test.ts, packages/desktop-client/src/i18n.ts, upcoming-release-notes/4453.md
These seem to cause a bit of confusion, this should clear it up.
=> change i18n errors to info

packages/desktop-client/src/components/reports/CategorySelector.tsx, packages/desktop-client/src/components/reports/ReportSidebar.tsx, upcoming-release-notes/4522.md
=> :bug: make custom report side nav bar responsive

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx, upcoming-release-notes/4560.md
=> Replace usage of deprecated Button in TransactionEdit with new Button component

packages/desktop-client/src/components/mobile/accounts/Accounts.tsx, packages/desktop-client/src/components/mobile/budget/BudgetCell.tsx, packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx, packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx, packages/desktop-client/src/components/mobile/budget/IncomeGroup.tsx, packages/loot-core/src/client/queries/queriesSlice.ts, packages/loot-core/src/server/db/index.ts, packages/loot-core/src/server/sync/sync.test.ts, upcoming-release-notes/4482.md
Drag and drop doesn't seem to work with the Chrome mobile simulator but it works when the demo link is opened in an actual mobile phone.
At the moment, this only supports Chromium based browsers due to some quirks on how drag and drop works on other browsers. The plan is to push through with this limited support for now and check future releases of react aria and/or browsers once they add proper support/functionality.
=> [Mobile] Drag and drop income categories to re-order

packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx, packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx, upcoming-release-notes/4621.md
=> [Mobile] Click on income category balance to show transactions

packages/sync-server/src/app-pluggyai/app-pluggyai.js, upcoming-release-notes/4628.md
This fixes credit card transactions to pluggyai
=> 🐛 Pluggy.ai credit card transactions were inverted

packages/loot-core/src/shared/schedules.ts, upcoming-release-notes/4627.md
=> 🐛 added null/undefined check for scheduleIsRecurring

packages/desktop-client/src/components/filters/FiltersButton.tsx, packages/desktop-client/src/components/filters/FiltersMenu.jsx, packages/desktop-client/src/components/modals/EditRuleModal.jsx, packages/desktop-client/src/components/rules/Value.tsx, packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx, packages/desktop-client/src/components/util/GenericInput.jsx, packages/loot-core/src/client/data-hooks/schedules.tsx, packages/loot-core/src/shared/schedules.ts, upcoming-release-notes/4635.md
One more batch of translations
=> 📚 More translations for rules and fields

packages/api/tsconfig.dist.json, upcoming-release-notes/4640.md
Split off from https://github.com/actualbudget/actual/pull/4592
=> :recycle: (api) do not bundle test files in package output

packages/desktop-client/src/components/Modals.tsx, upcoming-release-notes/4647.md
Simplify Modals component by destructuring `modal.options` instead of one by one. This would remove the need to modify Modals component to pass in new option whenever a new one is added.
=> Simplify Modals component by destructuring modal.options instead of passing options one by one

packages/sync-server/src/app-gocardless/bank-factory.js, upcoming-release-notes/4595.md
=> Added CZ AirBank to banks with only 90 days of history

packages/desktop-client/src/components/reports/reports/CustomReport.tsx, upcoming-release-notes/4652.md
=> :bug: (reports) fix conditionsOp not applying for saved reports

packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx, packages/loot-core/src/client/SpreadsheetProvider.tsx, packages/loot-core/src/platform/client/fetch/index.d.ts, packages/loot-core/src/server/budget/app.ts, packages/loot-core/src/server/main.ts, packages/loot-core/src/server/spreadsheet/app.ts, packages/loot-core/src/server/spreadsheet/spreadsheet.ts, packages/loot-core/src/shared/async.ts, packages/loot-core/src/types/handlers.d.ts, packages/loot-core/src/types/server-handlers.d.ts, upcoming-release-notes/4649.md
Related to https://github.com/actualbudget/actual/issues/1113
=> Extract spreadsheet related server handlers from main.ts to server/spreadsheet/app.ts

packages/desktop-client/src/components/Modals.tsx, packages/desktop-client/src/components/manager/BudgetFileSelection.tsx, packages/desktop-client/src/components/manager/ManagementApp.tsx, packages/desktop-client/src/components/modals/BudgetListModal.tsx, upcoming-release-notes/4625.md
Fix this error in budget selection page:
I converted the budget list to be a GridList instead of buttons.
=> Fix nested button error in budget file selection page

packages/desktop-client/src/components/Modals.tsx, packages/desktop-client/src/components/manager/BudgetFileSelection.tsx, packages/desktop-client/src/components/mobile/budget/index.tsx, packages/desktop-client/src/components/modals/BudgetFileSelectionModal.tsx, packages/loot-core/src/client/modals/modalsSlice.ts, upcoming-release-notes/4670.md
=> Fix error on budget file selection page when using server

packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx, upcoming-release-notes/4667.md
I don't have a GoCardless account, so I would ask that someone verifies this, but I think this resolves #4666
=> 🐛 Fixed GoCardless SelectLinkedAccounts institution bug

packages/loot-core/src/server/main.ts, packages/loot-core/src/server/sync/app.ts, packages/loot-core/src/types/handlers.d.ts, packages/loot-core/src/types/server-handlers.d.ts, upcoming-release-notes/4661.md
Related to https://github.com/actualbudget/actual/issues/1113
=> Extract sync related server handlers from main.ts to server/sync/app.ts

packages/desktop-client/src/components/budget/envelope/BalanceMenu.tsx, packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx, upcoming-release-notes/4729.md
=> fix balance menu alignment

packages/desktop-client/src/components/modals/CloseAccountModal.tsx, upcoming-release-notes/4769.md
=> 🐛 [Bug]: Fixed bug where closing account did not properly validate transfer or category

packages/desktop-client/src/components/plugins/ManagePlugins.tsx, packages/desktop-client/src/plugin/core/pluginLoader.ts, packages/desktop-client/src/plugin/core/pluginStore.ts, packages/loot-core/src/client/notifications/notificationsSlice.ts, packages/plugins-core/src/types/actualPluginManifest.d.ts
Can now click pause/play on plugin.
=> ✨ [Feature] Plugin enable/disable button

packages/desktop-client/src/browser-preload.browser.js, packages/desktop-client/src/components/ServerContext.tsx, packages/desktop-client/src/components/manager/subscribe/Login.tsx, packages/loot-core/src/client/app/appSlice.ts, packages/loot-core/src/server/auth/app.ts, packages/loot-core/src/server/main.ts, packages/loot-core/src/types/handlers.d.ts, packages/loot-core/src/types/server-handlers.d.ts, packages/loot-core/typings/window.d.ts, upcoming-release-notes/4660.md
Related to https://github.com/actualbudget/actual/issues/1113
=> Extract auth related server handlers from main.ts to server/auth/app.ts

packages/desktop-client/src/components/accounts/Account.tsx, packages/desktop-client/src/components/accounts/AccountEmptyMessage.tsx, packages/desktop-client/src/components/accounts/Header.tsx, upcoming-release-notes/4824.md
`Account.tsx` is frustratingly large and hard to grok. It would be really good to split it out into smaller components with clearer boundaries for state, and eventually move to functional components. For now, this PR addresses two low-hanging fruit within the file—I hope to open more PRs like this in the future, but no promises.
Suggest reviewing by commit as the changes are isolated.
=> Slow improvements to `Account.tsx` (1/many)

packages/loot-core/src/server/transactions/import/__snapshots__/parse-file.test.ts.snap, packages/loot-core/src/server/transactions/import/ofx2json.test.ts, packages/loot-core/src/server/transactions/import/ofx2json.ts, upcoming-release-notes/4838.md
Fixes a bug in the ofx2json logic where some HTML entities could get incorrectly translated.
=> Fix bug in ofx2json logic

packages/loot-core/src/server/schedules/app.ts, upcoming-release-notes/4719.md
**WIP: Feature/Bug Fix Description**  
This PR is a work in progress. The final release note will be added once it's ready for review. 
I've opened this pull request early, before starting implementation, to ensure that no duplicate work is being done, following the project's contribution guidelines. If I'm overstepping any rules, please let me know—I'm happy to learn and improve.
I'm new to open-source contributions. I've been using this application to track my budget for some time and would love to be part of this community.
fixes #4705
=> Fixes Bug #4705 scheduled transaction date when posting early.

packages/crdt/jest.config.js, packages/crdt/package.json, packages/crdt/src/crdt/__snapshots__/merkle.test.ts.snap, packages/loot-core/src/server/encryption/encryption-internals.ts, packages/loot-core/src/server/encryption/encryption-internals.web.ts, upcoming-release-notes/4851.md, yarn.lock
Follow-up PR to https://github.com/actualbudget/actual/pull/4840
=> Move crdt to vitest

packages/desktop-electron/menu.ts, upcoming-release-notes/4860.md
**Fixed** 
- Keyboard shortcuts modal
- Find schedules
- Documentation link
=> :electron:  Fix some menu links

packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx, packages/desktop-client/src/components/mobile/budget/ExpenseCategoryList.tsx, packages/desktop-client/src/components/mobile/budget/ExpenseCategoryListItem.tsx, packages/desktop-client/src/components/mobile/budget/ExpenseGroupList.tsx, packages/desktop-client/src/components/mobile/budget/ExpenseGroupListItem.tsx, packages/desktop-client/src/components/mobile/budget/IncomeGroup.tsx, packages/desktop-client/src/components/mobile/budget/index.tsx, upcoming-release-notes/4880.md
=> [Mobile] Fix hidden category groups not being hidden

packages/desktop-client/src/components/settings/AuthSettings.tsx, upcoming-release-notes/4942.md
=> Fix lint error accidentally pushed to master

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx, packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx, packages/desktop-client/src/components/mobile/budget/BalanceCell.tsx, packages/desktop-client/src/components/mobile/budget/BudgetCell.tsx, packages/desktop-client/src/components/mobile/budget/ExpenseCategoryListItem.tsx, packages/desktop-client/src/components/mobile/budget/IncomeCategoryListItem.tsx, packages/desktop-client/src/components/mobile/budget/SpentCell.tsx, packages/desktop-client/src/components/settings/AuthSettings.tsx, upcoming-release-notes/4940.md
Closes https://github.com/actualbudget/actual/issues/4938
=> [Mobile] Show transactions upon clicking income categories

packages/desktop-client/src/components/reports/reports/Spending.tsx, upcoming-release-notes/4917.md
=> Fixed graphical bug in monthly spending report

packages/loot-core/src/server/transactions/import/ofx2json.ts, upcoming-release-notes/4911.md
=> Ofx parsing dates incorrectly

packages/loot-core/src/shared/util.test.ts, packages/loot-core/src/shared/util.ts, upcoming-release-notes/4908.md
Fixed a undefined reference issue
closes #4906
=> Fix title first null undefined

bin/release-note-generator.ts, packages/desktop-client/src/style/styles.ts, upcoming-release-notes/4923.md
=> 🐛 fixed scrollbar being impossible to grab

packages/loot-core/src/server/budget/categoryTemplate.test.ts, packages/loot-core/src/server/budget/categoryTemplate.ts, packages/loot-core/src/server/budget/types/templates.d.ts, upcoming-release-notes/4882.md
Tests for the template processing functions and a full chain for single categories.
Adds tests for:
each template type individually
variations of limits
misc stacked templates (throughout, not a specific section)
full chain tests
full chain with goals
Utilized Cursor IDE
resolves #1686
=> Tests for goal templates

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx, upcoming-release-notes/4910.md
=> Inconsistent date update mobile new transaction

packages/desktop-client/package.json, packages/desktop-client/src/components/AppBackground.tsx, packages/desktop-client/src/components/BankSyncStatus.tsx, packages/desktop-client/src/components/Notifications.tsx, packages/desktop-client/src/components/budget/BudgetSummaries.tsx, packages/desktop-client/src/components/mobile/MobileNavTabs.tsx, packages/desktop-client/src/components/reports/reports/Calendar.tsx, upcoming-release-notes/4992.md, yarn.lock
Update react-spring to latest version 10.0.0 to get rid of the `@ts-expect-error` lines.
=> Update react-spring to v10.0.0

packages/desktop-client/src/components/manager/ConfigServer.tsx
=> Fix pipeline build

packages/desktop-client/src/components/manager/ConfigServer.tsx, upcoming-release-notes/4995.md
=> Fix prefsSlice import

packages/desktop-client/src/components/manager/ConfigServer.tsx
=> Remove duplicate import

packages/loot-core/src/server/transactions/import/qif2json.ts, upcoming-release-notes/5002.md
=> [WIP] Qif empty lines

packages/component-library/src/InitialFocus.ts, packages/desktop-client/src/components/budget/envelope/CoverMenu.tsx, upcoming-release-notes/5008.md
=> Make InitialFocus component generic

packages/desktop-client/package.json, packages/desktop-client/src/components/banksync/AccountRow.tsx, packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx, packages/desktop-client/src/components/reports/spreadsheets/net-worth-spreadsheet.ts, packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts, packages/desktop-client/src/components/select/DateSelect.tsx, packages/desktop-client/src/hooks/useCategoryScheduleGoalTemplateIndicator.ts, packages/loot-core/package.json, packages/loot-core/src/shared/months.ts, packages/loot-core/src/shared/schedules.ts, packages/loot-core/src/shared/util.ts, packages/sync-server/package.json, packages/sync-server/src/app-gocardless/banks/easybank_bawaatww.js, packages/sync-server/src/app-gocardless/banks/lhv-lhvbee22.js, packages/sync-server/src/app-gocardless/banks/swedbank_habalv22.js, upcoming-release-notes/5041.md, yarn.lock
We now need to import the Locale type explicitly
Nice new timezone support if we ever need it!
https://github.com/date-fns/date-fns/releases
=> ⬆️ upgrade date-fns from v2.30.0 -> v4.1.0

packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx, upcoming-release-notes/5045.md
=> fix "delete x users" translation string

packages/desktop-client/src/components/select/DateSelect.tsx, upcoming-release-notes/5095.md
=> fix crash when datepicker deselected with no date set

packages/sync-server/src/app.ts, upcoming-release-notes/5093.md
Docker image here: https://hub.docker.com/r/mclarkgb/test/tags
docker pull mclarkgb/test:sha-067d968
Tested the:
- Ubuntu Docker image 
- CLI tool
- local build
=> :bug: Fix server version on docker

packages/loot-core/src/server/budget/goal-template.ts, upcoming-release-notes/5112.md
fix #5103 Applying templates to a group was broken because the aql query was bad
=> :bug: group template apply

.github/actions/get-next-package-version.js, .github/scripts/count-points.mjs, .github/workflows/count-points.yml, .github/workflows/docker-edge.yml, .github/workflows/i18n-string-extract-master.yml, .github/workflows/netlify-release.yml, .github/workflows/stale.yml, .prettierignore, package.json, upcoming-release-notes/5147.md, yarn.lock
Running locally:
```
GITHUB_TOKEN=xxxxxxxx node ./.github/scripts/count-points.mjs
```
Sample output (for current month):
``` 
PR Review Statistics (docs):
============================
youngcw: 5 (PRs: #709 (2pts), #719 (2pts), #721 (2pts), #717 (2pts), #716 (2pts))
matt-fidd: 4 (PRs: #709 (2pts), #709 (2pts), #720 (2pts), #713 (2pts))
MikesGlitch: 3 (PRs: #709 (2pts), #721 (2pts), #715 (4pts))
RubenOlsen: 3 (PRs: #709 (2pts), #712 (2pts), #710 (2pts))
jfdoming: 2 (PRs: #717 (2pts), #716 (2pts))
MatissJanis: 2 (PRs: #722 (2pts), #715 (4pts))
"Needs Triage" Label Removal Statistics (docs):
===============================================
No "needs triage" label removal statistics (docs) found in the last month.
Issue Closing Statistics (docs):
================================
youngcw: 3 …
```
=> Add GitHub workflow and script for counting monthly contributor points

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/actions/setup/action.yml, .prettierignore, upcoming-release-notes/5181.md
Just a bit of cleanup.. nothing much to see here
=> Clean up configuration files

.github/actions/ai-generated-release-notes/check-first-comment.js, .github/actions/ai-generated-release-notes/check-release-notes-exists.js, .github/actions/ai-generated-release-notes/comment-on-pr.js, .github/actions/ai-generated-release-notes/create-release-notes-file.js, .github/actions/ai-generated-release-notes/determine-category.js, .github/actions/ai-generated-release-notes/generate-summary.js, .github/actions/ai-generated-release-notes/pr-details.js, .github/workflows/ai-generated-release-notes.yml, upcoming-release-notes/5182.md
Uses OpenAI to generate release note based on code rabbit summary
=> Auto generate Release Notes

packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx, packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx, upcoming-release-notes/5246.md
Update links pointing to docs/budgeting/users to docs/config/multi-user.
=> Update links pointing to /budgeting/users/.

packages/desktop-client/src/components/mobile/budget/BalanceCell.tsx, packages/desktop-client/src/components/mobile/budget/IncomeCategoryListItem.tsx, upcoming-release-notes/5251.md
=> fix: Tracking budget income budget fields missing in mobile view 

packages/desktop-client/src/components/util/AmountInput.tsx, upcoming-release-notes/5270.md
=> :bug: fix amount input

packages/desktop-client/src/components/schedules/ScheduleDetails.tsx, upcoming-release-notes/5290.md
Add notes to the scheduled transactions table
=> add notes to scheduled transactions table

packages/desktop-client/src/components/settings/Format.tsx, upcoming-release-notes/5353.md
---
category: Enhancements
authors: [martijnhielema]
---
Adding DD-MM-YYYY as a date format option for displaying.
=> Add extra date format

packages/desktop-client/src/components/modals/EditFieldModal.tsx, upcoming-release-notes/5360.md
Fixes https://github.com/actualbudget/actual/issues/5329
=> fix crash when using bulk amount update

packages/desktop-client/src/components/tags/TagCreationRow.tsx, packages/desktop-client/src/components/tags/TagEditor.tsx, packages/desktop-client/src/style/tags.ts
@youngcw : Fix typecheck & tag validation
=> tags fixes

.github/scripts/count-points.mjs, upcoming-release-notes/5393.md
Follow-up to https://github.com/actualbudget/actual/pull/5392
Fixing another points calculation issue.
=> Fix potential undefined points issue in contributor points calculation

packages/loot-core/src/server/rules/index.ts, packages/loot-core/src/server/transactions/transaction-rules.ts, upcoming-release-notes/5386.md
Fix tag matching of filter and make hasTags op case-sensitive
=> Fix tag matching of filter and make hasTags op case-sensitive

packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx, packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx, packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx, packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx, packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx, packages/desktop-client/src/components/modals/AccountMenuModal.tsx, packages/desktop-client/src/components/reports/reports/Calendar.tsx, packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts, packages/desktop-client/src/hooks/useCategoryPreviewTransactions.ts, packages/desktop-client/src/hooks/usePreviewTransactions.ts, packages/desktop-client/src/modals/modalsSlice.ts, upcoming-release-notes/5219.md, upcoming-release-notes/5405.md
=> Revert "Mobile running balance" because its causing extreme slowness in large accounts.

packages/desktop-client/e2e/data/ynab5-demo-budget.json, packages/loot-core/src/server/importers/ynab5-types.ts, packages/loot-core/src/server/importers/ynab5.ts, upcoming-release-notes/5461.md
Closes https://github.com/actualbudget/actual/issues/5453
=> import category notes from nYNAB

packages/desktop-client/src/components/settings/Currency.tsx, packages/loot-core/src/shared/currencies.ts, upcoming-release-notes/5477.md
Adding SEK and TRY as currencies
=> Add currencies SEK and TRY

packages/desktop-client/src/components/settings/Currency.tsx, packages/loot-core/src/shared/currencies.ts, upcoming-release-notes/5507.md
=> Add Philippine Peso (PHP) currency

packages/desktop-client/src/components/App.tsx, packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx, packages/desktop-client/src/components/modals/ImportTransactionsModal/InOutOption.tsx, packages/desktop-client/src/components/modals/ImportTransactionsModal/Transaction.tsx, upcoming-release-notes/5565.md
1 Translate the modal "import transactions"
2 Standardize the login text
=> translate import transactions

packages/desktop-client/src/components/mobile/budget/UncategorizedTransactions.tsx, packages/desktop-client/src/queries/index.ts, packages/desktop-client/src/spreadsheet/bindings.ts, upcoming-release-notes/5589.md
Closes https://github.com/actualbudget/actual/issues/5588
=> [Mobile] Do not show transfer transactions on uncategorized transactions view/page

packages/desktop-client/src/accounts/accountsSlice.ts, packages/desktop-client/src/components/FinancesApp.tsx, packages/desktop-client/src/components/accounts/Account.tsx, packages/desktop-client/src/components/mobile/accounts/AccountPage.tsx, packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx, packages/desktop-client/src/components/mobile/accounts/AccountsPage.tsx, packages/desktop-client/src/components/modals/CloseAccountModal.tsx, packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx, packages/desktop-client/src/components/sidebar/Account.tsx, packages/desktop-client/src/components/transactions/TransactionsTable.tsx, packages/desktop-client/src/global-events.ts, packages/desktop-client/src/hooks/useAccounts.ts, packages/desktop-client/src/hooks/useUpdatedAccounts.ts, packages/desktop-client/src/modals/modalsSlice.ts, packages/desktop-client/src/queries/queriesSlice.ts, packages/desktop-client/src/sync-events.ts, upcoming-release-notes/5581.md
https://github.com/actualbudget/actual/pull/5579 needs to be merged first
=> [Redux] Move account states from queriesSlice to accountsSlice

packages/desktop-client/src/accounts/accountsSlice.ts, packages/desktop-client/src/components/ManageRules.tsx, packages/desktop-client/src/components/accounts/Account.tsx, packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx, packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx, packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx, packages/desktop-client/src/components/rules/RuleEditor.tsx, packages/desktop-client/src/components/rules/ScheduleValue.tsx, packages/desktop-client/src/components/schedules/ScheduleDetails.tsx, packages/desktop-client/src/components/transactions/TransactionsTable.tsx, packages/desktop-client/src/global-events.ts, packages/desktop-client/src/hooks/usePayees.ts, packages/desktop-client/src/payees/payeesSlice.ts, packages/desktop-client/src/queries/queriesSlice.ts, packages/desktop-client/src/redux/mock.tsx, packages/desktop-client/src/redux/store.ts, packages/desktop-client/src/sync-events.ts, upcoming-release-notes/5592.md
~~#5581 needs to be merged first~~
=> [Redux] Move payee states from queriesSlice to payeesSlice

packages/loot-core/src/shared/transfer.ts, upcoming-release-notes/5604.md
Closes https://github.com/actualbudget/actual/issues/3802
=> Enable Make Transfer menu for child transactions

packages/desktop-client/src/accounts/accountsSlice.ts, packages/desktop-client/src/components/tags/ManageTags.tsx, packages/desktop-client/src/components/tags/TagCreationRow.tsx, packages/desktop-client/src/components/tags/TagEditor.tsx, packages/desktop-client/src/components/tags/TagRow.tsx, packages/desktop-client/src/components/tags/TagsList.tsx, packages/desktop-client/src/hooks/useTags.ts, packages/desktop-client/src/queries/queriesSlice.ts, packages/desktop-client/src/redux/mock.tsx, packages/desktop-client/src/redux/store.ts, packages/desktop-client/src/tags/tagsSlice.ts, packages/loot-core/src/server/tags/app.ts, packages/loot-core/src/types/models/tags.ts, upcoming-release-notes/5597.md
https://github.com/actualbudget/actual/pull/5593 needs to be merged first
=> [Redux] Move tags states from queriesSlice to tagsSlice

packages/desktop-client/src/components/select/DateSelect.tsx, upcoming-release-notes/5607.md
Needs to be tested on a mobile device to work effectively
=> Implement responsive DateSelect component for mobile view

packages/desktop-client/src/components/modals/CreateAccountModal.tsx, packages/desktop-client/src/components/settings/Experimental.tsx, packages/desktop-client/src/hooks/useFeatureFlag.ts, packages/loot-core/src/types/prefs.ts, upcoming-release-notes/5628.md
Only removing the feature flag. No other changes here.
IMO safe to merge during code-freeze. LMK if you disagree.
=> Release Pluggy bank-sync integration

packages/desktop-client/src/components/ScrollProvider.tsx, packages/desktop-client/src/components/mobile/MobileNavTabs.tsx, packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx, packages/desktop-client/src/hooks/useTransactionsSearch.ts, upcoming-release-notes/5690.md
Fix unnecessary re-renders on useScrollListener and useTransactionsSearch hooks
=> Optimize usage of useScrollListener and useTransactionsSearch

packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx, packages/desktop-client/src/hooks/useDisplayPayee.ts, packages/desktop-client/src/hooks/usePayees.ts, upcoming-release-notes/5761.md
=> Avoid  repeated calls to payee.find in useDisplayPayee.ts

packages/sync-server/package.json, packages/sync-server/src/app-cors-proxy.js, packages/sync-server/src/app-cors-proxy.test.js, packages/sync-server/src/app.ts, packages/sync-server/src/load-config.js, upcoming-release-notes/5780.md, yarn.lock
For now, a CORS proxy is needed. Actual will ship a very simple CORS proxy with an allowlist that prevents other applications from using it. This can be changed later to third-party CORS proxies if needed.
This is necessary to make the plugin store functional
=> Frontend plugins Support [1/10]: CORS proxy

packages/sync-server/src/load-config.js, packages/sync-server/src/load-config.test.js, upcoming-release-notes/5782.md
Fixes https://github.com/actualbudget/actual/issues/5773
=> Fix token expiration parsing

packages/desktop-client/src/components/mobile/payees/PayeesList.tsx, upcoming-release-notes/5803.md
=> Mobile Payees - add back padding around searchbar

packages/loot-core/src/shared/rules.ts, upcoming-release-notes/5831.md
Fixes https://github.com/actualbudget/actual/issues/5701
Small fix so we can merge during freeze, I know there's a rewrite in the currency change we can sort out after the cut.
=> fix decimal input in amount input boxes

packages/desktop-client/src/components/reports/reports/Summary.tsx, packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts, packages/loot-core/src/types/models/dashboard.ts, upcoming-release-notes/5838.md
what it says on the box, useful for "what do I expect to spend this year on my car maintenance" etc...
=> add average per year calculation to the summary report
