packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/2754.md

[Mobile] Do not remember last entered category in mobile transaction entry

---

packages/api/methods.test.ts
packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/2648.md

Following work done in #1559 and update in #2534 (discussion https://github.com/actualbudget/actual/pull/2534#discussion_r1545649961), I think manual import should not override the transaction date as is done with bank account sync.

Don't update transaction date when importing manually

---

packages/loot-core/src/shared/arithmetic.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/2672.md

Implements #2318
It's only allowed for formats not using period or comma as a thousand separator. I don't think somebody using a format with comma and dot as decimal and thousand separator would have the issue in the first place.
I reworked the arithmetic parser to let `currencyToAmount()` handle number formatting with active format. I noticed it also made an exception for a leading currency symbol but not for a tailing one. I fixed it to allow that case. (actually in my implementation you could also put a currency symbol in the middle of a value but it would be ignored anyway, I don't think it's an issue)

[Feature] Make comma's and period interchangeable when entering figures

---

packages/api/package.json
packages/desktop-client/package.json
packages/desktop-electron/package.json
packages/loot-core/package.json
upcoming-release-notes/2763.md
yarn.lock

Updated Electron to the latest stable version. We were previously on version 27 which was EOL April 2024. We're now on 31 which is EOL Jan 2025.
Electron release info: https://www.electronjs.org/docs/latest/tutorial/electron-timelines
- Tested on Linux Mint Debian Edition and Windows 10
:heavy_check_mark: Tested the flatpak
:heavy_check_mark: Tested the appimage
:heavy_check_mark: Tested the windows app
All working as usual

:electron: Update Electron to latest stable version 

---

bin/run-vrt
package.json
packages/desktop-client/README.md
upcoming-release-notes/2762.md

Run vrt tests in the standardized docker container by simply running:
```sh
yarn vrt:docker
yarn vrt:docker --update-snapshots
```

Add run-vrt script to run vrt inside docker

---

packages/desktop-client/src/components/reports/reports/CashFlowCard.jsx
upcoming-release-notes/2775.md

ref: https://github.com/actualbudget/actual/issues/2710

fix: put income on left and expense on right always, hide when 0

---

.github/workflows/netlify-release.yml
.gitignore
upcoming-release-notes/2750.md

This is working in my fork.  Still a few things to do to tie it all together.
The goal here is to have two deployments.
1.  edge.actualbudget.org  --  This will be what demo.actualbudget.org is today.  A live preview of the master branch that is updated with each new merge.
2. demo.actualbudget.org -- This will only be updated when a release is made.  This will provide a more stable preview of what to expect after installation.

Github action to automatically deploy a release image to Netlify

---

packages/desktop-client/src/components/reports/ChooseGraph.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/RenderTableRow.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
packages/desktop-client/src/components/reports/spreadsheets/custom-spreadsheet.ts
packages/desktop-client/src/components/reports/spreadsheets/recalculate.ts
packages/loot-core/src/types/models/reports.d.ts
upcoming-release-notes/2768.md

Creating a callback for the table totals to fix a bug that created duplicate columns while rendering.

Custom Reports: Table Totals Callback

---

packages/desktop-client/src/components/budget/SidebarCategory.tsx
packages/desktop-client/src/components/budget/SidebarGroup.tsx
upcoming-release-notes/2773.md

Fixes #2736 by telling the browser this icon should not be shrunk in these rows (default is 1, which means the other icons which have `flexShrink: 0` get more space).
Before/after:
|Before (demo.actualbudget.org)|After (this branch)|
|----|----|
|![image](https://github.com/actualbudget/actual/assets/8148535/04783556-facf-4117-aa0b-ce81839c9c57)|![image](https://github.com/actualbudget/actual/assets/8148535/bcf7236a-7e60-473e-b92e-75612ab5b538)|
|![image](https://github.com/actualbudget/actual/assets/8148535/fdee8ac7-f8de-4903-9bdb-84f22b98215a)|![image](https://github.com/actualbudget/actual/assets/8148535/014ac0f7-1453-497f-908f-80f26814b340)|
(first contribution, so please let me know if I missed anything)

Fix notes icon changing size/position with long category or group names

---

packages/desktop-client/src/components/common/MenuButton.tsx
packages/desktop-client/src/components/common/Popover.tsx
packages/desktop-client/src/components/reports/GraphButton.tsx
packages/desktop-client/src/components/reports/ReportSidebar.tsx
packages/desktop-client/src/components/reports/SaveReport.tsx
packages/desktop-client/src/components/reports/SaveReportChoose.tsx
packages/desktop-client/src/components/reports/SaveReportDelete.tsx
packages/desktop-client/src/components/reports/SaveReportMenu.tsx
packages/desktop-client/src/components/reports/SaveReportName.tsx
packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
upcoming-release-notes/2778.md

Refactoring custom reports usages of the old `Tooltip` component to `react-aria`.

♻️ (tooltip) refactoring to react-aria (vol.7)

---

packages/desktop-client/src/components/modals/CreateAccountModal.tsx
upcoming-release-notes/2765.md

Avoid using underlines for emphasis

---

packages/desktop-client/src/components/budget/MonthPicker.tsx
upcoming-release-notes/2797.md

I often second-guess myself when trying to select the set of months I want displayed in the budget when viewing it by more than one month at a time.  After some thought, I decided it was because I could not quickly mentally compute the full set of months I was about to select.
Here, I tweak the way the months render during a hover event so it is more obvious which set of months you will get if you click:

Make picking budget months easier to see

---

packages/loot-core/src/server/accounts/transaction-rules.test.ts
packages/loot-core/src/server/accounts/transaction-rules.ts
upcoming-release-notes/2643.md
upcoming-release-notes/2803.md

#2643 is a nice change, but there are multiple things that use the amount filter, like schedules, that would need changed to match the update.  We could return to this after the release if desired and have time to fix the internal amount filter uses.
Also, maybe instead of changing how the filter works we would instead use the amountInput component when creating the filter to be more clear what the amount is.  That way the filter uses don't have to be changed to match then new filter.

Revert #2643

---

packages/desktop-client/src/components/reports/graphs/SpendingGraph.tsx
packages/desktop-client/src/components/reports/reports/Spending.tsx
packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
upcoming-release-notes/2809.md

Fixes a crashing bug that happens when the current day of the month is greater than 28.

Spending report error fix with some visual changes

---

packages/desktop-client/src/components/sidebar/Account.tsx
upcoming-release-notes/2796.md

Shows the account's notes when hovering the account in the sidebar:
If the account has no notes, just the full name shows (which can be very useful when long names are cut off):

Show account notes in tooltip on sidebar

---

packages/desktop-client/e2e/rules.test.js
packages/desktop-client/src/components/modals/EditRule.jsx
packages/desktop-client/src/components/settings/Experimental.tsx
packages/desktop-client/src/hooks/useFeatureFlag.ts
packages/loot-core/src/server/accounts/rules.ts
packages/loot-core/src/types/prefs.d.ts
upcoming-release-notes/2789.md

As it says on the tin. There are further UX improvements that could still be made (e.g., recomputing percent-based splits during manual transaction entry) but by and large this is feature complete and stable.

Release 'Splits in rules' feature

---

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
packages/loot-core/src/shared/transactions.ts
upcoming-release-notes/2821.md

Two child transactions created instead of one:

[Mobile] Auto create 2 child transactions on split

---

packages/desktop-client/src/components/sidebar/Account.tsx
upcoming-release-notes/2838.md

Fixes the flakey VRT issues caused by the merge of #2796, by not showing account tooltips during VRT.

[WIP] Don't show account tooltips during VRT

---

packages/desktop-client/src/components/modals/EditRule.jsx
packages/desktop-client/src/components/spreadsheet/useFormat.ts
packages/desktop-client/src/components/util/GenericInput.jsx
packages/desktop-client/src/components/util/PercentInput.tsx
upcoming-release-notes/2566.md

There was feedback on the original rules-with-splits PR that amount inputs could use the featureful amount input instead of a plain text field. This PR updates that page to use the `AmountInput` component.

Use amount input on rules page instead of plain text field

---

packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
packages/desktop-client/src/components/mobile/budget/CategoryTransactions.jsx
packages/desktop-client/src/components/mobile/transactions/TransactionList.jsx
packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
upcoming-release-notes/2831.md

A loading indication will show up instead of displaying "No transactions" initially and then rendering the fetched transactions.
Also changed the number of transactions page count to 50 from 10 to load more transactions at a time.

[Mobile] Add loading indicator on mobile transactions list

---

packages/loot-core/webpack/webpack.browser.config.js
upcoming-release-notes/2825.md

Fixes #1766 
The worker script `kcab.worker.$HASH.js` which minified by swcMinify includes functions like `function e(e,t=0){}`. Run this function in safari 16 will throw SyntaxError
Enable compress for swcMinify will remove useless function name `e` in `function e(e,t=0){}`. You can try compress flags in [this swc playground](https://play.swc.rs/?version=1.5.24&code=H4sIAAAAAAAAAytKTc8sLkkt0kgrzUsuyczPU0gpLcjJTE4sSY0HCWkguAWJRYm5Ogr5aWnFqSUKtgoGmgrVtZpcACgasG1CAAAA&config=H4sIAAAAAAAAA1WPSwrDMAxE9zmF0bqLttAueocewrhKcPAPS4GGkLvH33521sw8j7QNQsBMCh5iS880BBkJ42dOCq2O5TspgMpKUlEHhlN3Z8rWKA1hkfbqAMs4IReKrufLrRFgvCfsRNOsdnpcfzuVtyEi0X8wR6WbTOY5Lq1waKVg%2FWspXjuF14B1gTt8Q70rf1AUTc8O1jP2A%2BC7qlwWAQAA).

Enable compress to avoid minified scripts from throwing SyntaxError in safari16

---

packages/desktop-client/src/components/Modals.tsx
packages/desktop-client/src/components/budget/rollover/BalanceMenu.tsx
packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudget.tsx
packages/desktop-client/src/components/budget/rollover/budgetsummary/ToBudgetMenu.tsx
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
packages/desktop-client/src/components/modals/CoverModal.tsx
packages/desktop-client/src/components/modals/RolloverBudgetSummaryModal.tsx
packages/desktop-client/src/components/modals/RolloverToBudgetMenuModal.tsx
packages/loot-core/src/client/actions/queries.ts
packages/loot-core/src/client/state-types/modals.d.ts
packages/loot-core/src/server/budget/actions.ts
packages/loot-core/src/server/budget/app.ts
packages/loot-core/src/server/budget/types/handlers.d.ts
upcoming-release-notes/2850.md

Cover overbudgeted action + make balance movement menus only appear on relevant conditions e.g. transfer to another category menu only when there is a leftover balance.
New action can be found when clicking on an Overbudgeted amount. You can cover the Overbudgeted amount from any category same as how an overspent category can be covered from another category.

Cover overbudgeted action + make balance movement menus only appear on relevant conditions

---

packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
upcoming-release-notes/2842.md

category: Enhancements
authors: [lelemm]
This enhances the capability to use autocomplete for languages that use accents like Portuguese.
For example, you may have a category that has accents, but currently it will match only when you type the accent in the search string. That seems minimal, but it gets frustrating at some point.
This PR address this quality of life. When searching, it will match if you do not type the accent, and vice-versa. Check the vid bellow:
https://github.com/actualbudget/actual/assets/15043428/e478a7fa-ebc5-48c2-830c-5812786ef697

Changing the autocomplete search to accept text without accents to match options with accents

---

packages/desktop-client/src/components/common/Tooltip.tsx
upcoming-release-notes/2866.md

fix: Account names in side nav squashed

---

packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/2864.md

- Removes a redundant style declaration overriding scheduled transaction's background colour
- https://github.com/actualbudget/actual/issues/2856 
Background colour is already set here:
- https://github.com/actualbudget/actual/pull/2864/files#diff-3087d39fd07c36984e71c4d00f499b77d68a797730f84f042b0cf659cc6e7cf4R807-R811

fix: schedules are missing highlight color

---

packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
packages/loot-core/src/client/actions/account.ts
packages/loot-core/src/server/db/index.ts
upcoming-release-notes/2896.md

This PR enables the user-defined account sort order in all account lists displayed in the autocomplete dropdowns (account and payee autocomplete).
Currently, the category autocomplete does respect the user-defined sort order while it's not the case for accounts. This little improvement makes the app behavior consistent.

Consider account sort order in autocomplete

---

packages/desktop-client/src/components/accounts/Header.jsx
upcoming-release-notes/2899.md

We are getting a few confused folks on Discord that confuse the "sync" button at the top of the page with the "sync" button in account view.
Updating the label of this button to clear the confusion a bit.

:speech_balloon: (bank-sync) update sync button label to improve discoverability

---

packages/loot-core/src/platform/server/sqlite/index.electron.ts
upcoming-release-notes/2929.md

Fixes: #2917
This PR adds in the Regex function to the DB in the same way the web client does. 
It must have been forgotten when regex functionality was added.
- Tested on WIndows

:electron: Fix regex filters on electron app

---

packages/desktop-electron/index.js
upcoming-release-notes/2925.md

partial for: https://github.com/actualbudget/actual/issues/2907
The issue is due to this bug https://github.com/electron/electron/issues/42621
We're working around it by using the async version of the same function (which works)
Tested: 
- Windows
- Linux AppImage
- Linux Flatpak

:electron: Fix "Export" function on desktop app

---

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
upcoming-release-notes/2940.md

fix: #2938
The makes it so the mobile category balance acts the same on mobile as it does on desktop.  Templates will cause colors for balance, otherwise only white, gray, or red.
This also fixes a small bug where the carryover arrow would always show the template color even with templates disabled.

change the mobile budget balance colors to be the same as desktop

---

packages/desktop-client/src/hooks/useNavigate.ts
upcoming-release-notes/2772.md

Closes #2596
Reproduction:
1. open demo link and create an empty budget
2. close the tab
3. open demo link /accounts
4. close the tab
5. open demo link /accounts
6. 💣

[WIP] :bug: fix the app randomly navigating back (closing)

---

packages/loot-core/src/server/backups.ts
upcoming-release-notes/2960.md

Previously we were showing 12 hour format for both AM and PM without showing the fact it was AM or PM. 
I've changed it to 24h format so the time is always shown correctly.
**Old (incorrectly appears like "4:41" - people would assume AM)** 
**New (shows 24H format)**

:electron: Fix backup time format in electron

---

packages/desktop-client/e2e/page-models/schedules-page.js
packages/desktop-client/package.json
packages/desktop-client/src/components/common/Button2.tsx
packages/desktop-client/src/components/schedules/DiscoverSchedules.tsx
packages/desktop-client/src/components/schedules/PostsOfflineNotification.jsx
packages/desktop-client/src/components/schedules/ScheduleDetails.jsx
packages/desktop-client/src/components/schedules/ScheduleLink.tsx
packages/desktop-client/src/components/schedules/SchedulesTable.tsx
packages/desktop-client/src/components/schedules/index.tsx
packages/desktop-client/src/components/util/AmountInput.tsx
upcoming-release-notes/2904.md
yarn.lock

This will be the first part of a multi-PR effort to migrate all the buttons in the code to use react-aria-components' Button component under the hood. The plan is to do one PR per page to make it easier to review the changes. 
This first one migrates the buttons on the schedules page.

React Aria Button as base of Button component

---

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
packages/desktop-client/src/components/budget/report/ReportComponents.tsx
packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
packages/desktop-client/src/components/modals/ReportBalanceMenuModal.tsx
packages/desktop-client/src/components/modals/RolloverBalanceMenuModal.tsx
upcoming-release-notes/2943.md

Fixes: #2879 
This PR implements a new look for the mobile carryover indicator (arrow) in the budget view. The arrow looks similar to notification badges on mobile apps.
This PR also fixes the issues when showing this arrow display in the desktop view (narrow window widths).
Additionally, the arrow display is also improved in the balance modals.

Fix rollover arrow display for mobile and desktop

---

packages/loot-core/src/platform/server/sqlite/index.electron.ts
packages/loot-core/src/platform/server/sqlite/index.web.ts
packages/loot-core/src/platform/server/sqlite/unicodeLike.test.ts
packages/loot-core/src/platform/server/sqlite/unicodeLike.ts
packages/loot-core/src/server/aql/compiler.test.ts
packages/loot-core/src/server/aql/compiler.ts
upcoming-release-notes/2903.md

Fixes: #2755, #2347
This PR changes the behavior of the `LIKE` SQLite queries. Instead of using the built-in implementation that can run in case-insensitive mode only for ASCII characters (and thus performs case-sensitive comparison for all other, like Cyrillic, diacritic, accents etc), the new implementation is based on JS regex that handles all characters in Unicode.

fix: use Unicode-aware SQLite LIKE filtering

---

packages/desktop-electron/package.json
upcoming-release-notes/3000.md

This will make it so the desktop app filename is always the same in the release and we can point the download page to the release page without having to update the page every month
Do I get a prize for being PR 3000?

remove version from electron build names

---

packages/loot-core/src/shared/arithmetic.test.ts
packages/loot-core/src/shared/arithmetic.ts
packages/loot-core/src/shared/util.test.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/2982.md

Adds a Swiss style number format option.
The Intl.NumberFormat API formats de `de-CH` locale using a fancy apostrophe (U+2019):
```
> Intl.NumberFormat('de-CH').format(1200.33)
< "1’200.33" 
```
This PR is based on #2981

Add apostrophe dot format

---

packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
upcoming-release-notes/3019.md

The button to create a new payee when entering a transaction on mobile does not currently expand when text wraps. This PR allows the button to expand in the same way it does on desktop.

Fix mobile payee creation display for long payee names

---

packages/loot-core/src/server/aql/schema/index.ts
upcoming-release-notes/3022.md

These fields exist in the table, but were not exposed via AQL. So people using the API could not get this data.  This is needed for properly matching accounts to SimpleFIN (either by the ID or by the 'official' name).

Expose bank sync account data in AQL.

---

packages/loot-core/src/client/actions/account.ts
packages/loot-core/src/server/main.ts
upcoming-release-notes/3029.md

Right now bank sync syncs one bank at a time, based on the default sort order returned by the SQL query.  This makes them sync in the same order they show in the left sidebar.

Perform bank sync in same order as accounts shown in sidebar.

---

packages/desktop-client/src/components/budget/IncomeCategory.tsx
upcoming-release-notes/3032.md

If you hide an income category, only the name of the category was dimming. This dims the entire row, similar to the expense categories being hidden.

Dim hidden income category rows

---

packages/desktop-client/src/components/modals/EditRule.jsx
upcoming-release-notes/3037.md

Noticed the separator line was in the wrong position when I was editing a rule. This should fix it.
Before:
After:

Fix the position of the separator in the operator menu when editing a rule

---

packages/desktop-client/src/components/Notifications.tsx
upcoming-release-notes/3046.md

Issue: N/A
Description: Fixes alignment of notifications on mobile to be centered on the viewport.
Old | New
:---:|:---:

fixes alignment of notifications on mobile to be centered

---

packages/desktop-client/src/components/manager/BudgetList.tsx
packages/loot-core/src/client/reducers/budgets.ts
packages/loot-core/src/types/file.d.ts
upcoming-release-notes/3026.md

Relates to https://github.com/actualbudget/actual/issues/1483

migrate BudgetList to typescript

---

packages/desktop-electron/package.json
upcoming-release-notes/3015.md

Improve Electron Mac build to target "Universal" for better performance on Apple Silicon.
**NOTE:** this will increase the size of the Mac app from 111MB to 182MB
Tested by: [michaelhofer](https://github.com/michaelhofer) - on https://github.com/actualbudget/actual/issues/3004#issuecomment-2227006927

:electron: Build electron for Mac Universal arch 

---

packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
upcoming-release-notes/3056.md

Having your words be automatically capitalized while typing in payee names is a nice QoL feature that we can add for very little effort on our part. Existing search functionality is maintained because the search is case-insensitive. Only mobile browsers are affected.
Before:
[Screen_Recording_20240714_203146_Firefox.webm](https://github.com/user-attachments/assets/a696c864-bc3e-473d-bf62-5ffde724c307)
After:
[Screen_Recording_20240714_203019_Firefox.webm](https://github.com/user-attachments/assets/46fd422e-83d1-4dcc-84cd-bc6894f0bdf1)
Reference:
[autocapitalize="words"](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize#words)

Add autocapitalize to payee autocomplete

---

packages/desktop-client/src/components/manager/BudgetList.tsx
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/components/manager/DeleteFile.tsx
packages/desktop-client/src/components/manager/Import.tsx
packages/desktop-client/src/components/manager/ImportActual.tsx
packages/desktop-client/src/components/manager/ImportYNAB4.tsx
packages/desktop-client/src/components/manager/ImportYNAB5.tsx
packages/desktop-client/src/components/manager/WelcomeScreen.tsx
packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
packages/desktop-client/src/components/manager/subscribe/ChangePassword.tsx
packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.tsx
packages/desktop-client/src/components/manager/subscribe/Error.tsx
packages/desktop-client/src/components/manager/subscribe/Login.tsx
upcoming-release-notes/2916.md

React Aria Button on Management App

---

packages/loot-core/src/mocks/files/camt/camt.053.xml
packages/loot-core/src/server/accounts/xmlcamt2json.ts
upcoming-release-notes/3086.md

In the XML export from [LHV](https://lhv.ee) entries only have date information in `BookgDt` but there is no `ValDt`.
For reference, this is the schema declared in the export I get:
```
<Document
xmlns="urn:iso:std:iso:20022:tech:xsd:camt.053.001.02"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:camt.053.001.02 camt.053.001.02.xsd"
>
```
---
The error I got was in `getDtOrDtTm`:
> TypeError: right-hand side of 'in' should be an object, got undefined
This handles that by explicitly checking for falsy input. The code seems to have already been expecting
this situation as it already falls back to `BookgDt` in:
```javascript
const date = getDtOrDtTm(entry.ValDt) || getDtOrDtTm(entry.BookgDt);
```
Glancing over the xsd spec this seems …

CAMT.053: Handle missing ValDt on entries with Sts Book

---

packages/desktop-electron/index.ts
packages/desktop-electron/preload.ts
packages/desktop-electron/security.ts
upcoming-release-notes/3066.md

Updated security.js and preload.js to Typescript and fixed Theme not setting correctly when set via dev console
#1483

:electron: security.js and preload.js ➡️ .ts 

---

.github/workflows/stale.yml
upcoming-release-notes/3107.md

We have quite a few PRs in the backlog that are marked as "WIP". I'm not sure if they are actually WIP or if the authors simply didn't know they should remove the "WIP" prefix for the PR to be reviewed.
Either way - adding a small automation that will ping WIP PRs that have been inactive for a week. Hopefully that will help unblock some of these PRs.

:wrench: ping WIP PRs that have been inactive for a week

---

README.md
upcoming-release-notes/3113.md

- README: noticed fly.io points to docker, updated the url

[WIP] modify fly.io url to point to correct documentation

---

packages/loot-core/src/mocks/setup.ts
upcoming-release-notes/3144.md

We use uuid package throughout the codebase to generate unique ids. In unit tests - we have mocked it (here https://github.com/actualbudget/actual/blob/master/packages/loot-core/src/mocks/setup.ts#L55-L60). For tests it generates a sequential ID. This works fine for the most part.
Until we add a new migration that also wants to use uuid. Migrations run before all other code. So a new migration using uuid messes up all test snapshots. Suddenly id5 becomes id6.
This solves the problem. No matter how many new migrations will be added - they will not mess up the snapshots that rely on `uuid`.

:wrench: improve unit test stability while using uuid

---

packages/desktop-client/src/components/settings/Global.tsx
packages/desktop-client/src/components/settings/index.tsx
upcoming-release-notes/3133.md

- Fix the electron "Data" directory picker - it wasn't showing 
- Should partly resolve: https://github.com/actualbudget/actual/issues/2951 
- We're still storing our files in "Documents" by default on WIndows - so the issue should remain open
Tested on:
- Windows
- Linux AppImage and Flatpak
In future it would be worth moving this to the "Manage Files" area of the app - so it can be selected before creating the first budget. 
For now, I've enabled the existing functionality.

:electron: Fix electron "Data Dir" picker on Settings page

---

packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
upcoming-release-notes/3153.md

[Fix] "Enter" key should save on "Cover Overspending" popup 

---

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
upcoming-release-notes/3123.md

I saw a suggestion along these lines in the discord some time ago (can't pinpoint exactly but somewhere around the 2 month mark probably)
What do people think? I've gone through a good few designs so if anyone has any suggestions I'm more than open to them!
To test you'll need to enable goal templates, apply them, and hover over the balance in the final column of the budget table. I'm not sure if this would want a dashed underline to make it more obvious or if it's best left discovered organically to keep the table clearer.

add goal tooltip to balance in budget table

---

packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
packages/desktop-client/src/components/budget/index.tsx
packages/desktop-client/src/components/mobile/budget/index.tsx
packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
packages/desktop-client/src/components/settings/Experimental.tsx
upcoming-release-notes/3169.md

**Issue**: When switching from "rollover" budget to "report" budget for the first time, the toggle doesn't actually work. This is because the localPref `budgetType` does not have a value initially, and the logic did not handle that so it attempts to toggle to a "rollover" budget (when it is already by default a "rollover")
`const newBudgetType = budgetType === 'rollover' ? 'report' : 'rollover';`
This PR fixes that issue by defaulting the localPref to "rollover" (also fixed it in other files where we use that localPref.

Fix budget type toggle not working the first time

---

packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
packages/desktop-client/src/components/budget/rollover/TransferMenu.tsx
packages/desktop-client/src/components/filters/AppliedFilters.tsx
packages/desktop-client/src/components/filters/ConditionsOpMenu.tsx
packages/desktop-client/src/components/filters/FilterExpression.tsx
packages/desktop-client/src/components/filters/subfieldFromFilter.ts
packages/desktop-client/src/components/filters/updateFilterReducer.ts
packages/desktop-client/src/components/modals/CoverModal.tsx
packages/desktop-client/src/components/modals/TransferModal.tsx
packages/desktop-client/src/components/reports/ReportOptions.ts
packages/desktop-client/src/hooks/useFilters.ts
packages/loot-core/src/mocks/budget.ts
packages/loot-core/src/types/models/category-group.d.ts
packages/loot-core/src/types/models/category.d.ts
packages/loot-core/src/types/models/reports.d.ts
packages/loot-core/src/types/models/rule.d.ts
upcoming-release-notes/3180.md

Making `Category` and `Rule` types stricter and fixing the issues that arise.
Split off from: https://github.com/actualbudget/actual/pull/3108 and https://github.com/actualbudget/actual/pull/3178

:recycle: (typescript) make category and rule types stricter

---

.eslintrc.js
packages/loot-core/src/server/aql/views.test.ts
upcoming-release-notes/3114.md

In https://github.com/actualbudget/actual/pull/3044 the `typography` linter rule is applying to test files. Strings in test files aren't user-facing, so it doesn't make sense to apply this rule there.

Disable typography linter in tests

---

packages/desktop-client/src/components/modals/ImportTransactions.jsx
upcoming-release-notes/3203.md

Use CSV fields with name "payee" or "notes" as defaults for Payee/Notes in getInitialMappings. Falls back to the first unused field if none exists with matching name (which is the current behavior).
Fixes #3154

Identify Payee and Notes fields by name if they exist in CSV import

---

packages/loot-core/src/server/main.ts
upcoming-release-notes/3232.md

This PR fixes the issue described in issue #3227. This bug was caused by an oversight when merging the `strictIdChecking` feature with the `isPreview` feature that was implemented into the same `reconcileTransactions` function.
I've deliberately not hoisted the `strictIdChecking` parameter through to the API layer because I figured that having it set to true as default is sensible. If not, we can hoist it up.

Fix reconcileTransactions Invokation To Use strictIdChecking

---

packages/desktop-client/src/components/budget/BudgetTable.jsx
packages/desktop-client/src/components/budget/util.ts
upcoming-release-notes/3241.md

There was a typo in `findSortDown` which led to categories being dropped in the last place when it should be in the second-to-last place. However, fixing the typo broke the sorting of groups, because `findSortDown` was passed _every_ group, including the non-sortable income group, so before the typo fix, there were two off-by-one errors that cancelled each other out. This was fixed by pulling out the Income group before passing it to `findSortDown`.

Fix off-by-one error when placing category into 2nd-to-last place

---

packages/desktop-client/src/i18n.ts
upcoming-release-notes/3242.md

Using 'cimode' as default language code will return the translation keys verbatim without doing interpolation. This is unwanted unless working directly on localization.
Fixes #3240

fix: i18n: Use 'en' as default language

---

packages/loot-core/src/platform/server/sqlite/index.electron.ts
upcoming-release-notes/3250.md

Fixes: https://github.com/actualbudget/actual/issues/2907

:electron:  Fix export on mac

---

packages/desktop-client/src/components/Modals.tsx
packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
packages/desktop-client/src/components/modals/CoverModal.tsx
upcoming-release-notes/3115.md

When using the cover overspending menu, it allows you to select the target category as the cover source. This doesn't cause a problem but doesn't make much sense or do anything.

hide target category from cover overspending list

---

README.md
upcoming-release-notes/3271.md

From the ongoing localization project, to get access to the Libre plan, the Weblate project which hosts the translated strings should be mentioned in the readme.
Following example from a few other projects, I put together a little blurb. Crediting Julian b/c they set up the project and this is just a single sentence.

feat: [localization] Update README to mention weblate

---

packages/desktop-client/src/components/settings/Experimental.tsx
upcoming-release-notes/3283.md

Also added translation lines for the feature flag component.

:sparkles: adding feedback links besides the feature flags

---

packages/desktop-client/src/components/transactions/TransactionsTable.jsx
packages/loot-core/src/server/db/index.ts
upcoming-release-notes/3318.md

Fix issue #3317 by adding tombstone filter to common payee query.

Fix suggested payee issues #3317 #3316

---

packages/desktop-client/src/components/common/Tooltip.tsx
upcoming-release-notes/3342.md

Fixes: https://github.com/actualbudget/actual-server/issues/443#issue-2499664333
https://github.com/user-attachments/assets/76ef9845-5072-425a-bd62-26ed227a32da
Touch devices like MS Surface Pro7 use touchscreens (no hover states). When touching the notes field the pointer is "entered" into the area, the timeout triggered and 300ms later the hover state showed (even though there was no hover). 
The fix was to trigger the tooltip only on mouse hover - not pointer entering.

🐛  Fix tooltip when using touch devices

---

packages/desktop-client/src/components/sidebar/Sidebar.tsx
upcoming-release-notes/3393.md

The sidebar is saving to metadata.json every time the window is resized and on every movement while being dragged.
This fix makes it save when the drag has ended.
I looked into this due to this bug: https://github.com/actualbudget/actual/issues/3390 . I'm doubtful that it will fix it, but it's the only thing I can see that's saving to metadata.json a lot.

🔧 Prevent sidebar from saving to metadata until resize is complete

---

packages/desktop-client/src/components/common/Menu.tsx
packages/desktop-client/src/components/common/Select.tsx
packages/desktop-client/src/components/reports/ReportSidebar.tsx
packages/desktop-client/src/components/reports/SaveReportMenu.tsx
upcoming-release-notes/3391.md

This is useful in general but in particular for migrating some components such as `RecurringSchedulePicker` to TypeScript—these components use non-string types for values (e.g. `number`).
The non-`Select` non-`Menu` component changes are to switch those components to use the correct types instead of inferring from the props of `Select`/`Menu`. Using props doesn't play well with generics.

Refine `Menu`/`Select` types to allow broader types for the `value`/`name` attribute

---

packages/desktop-client/src/components/common/Select.tsx
packages/desktop-client/src/components/forms.tsx
packages/desktop-client/src/components/select/DateSelect.tsx
packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
packages/loot-core/src/types/models/schedule.d.ts
upcoming-release-notes/3396.md

Convert `RecurringSchedulePicker.jsx` -> `RecurringSchedulePicker.tsx`

---

packages/loot-core/src/server/sync/index.ts
upcoming-release-notes/3398.md

The sync gets fired when the user changes focus to the Actual app - this can cause unnecessary updates to metadata.json. 
This change checks the current sync time and skips updating the metadata.json if the value is the same.
Evidence: 
This may help with #3390

🔧 Prevent metadata.json update if the sync time value is the same 

---

packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/mobile/accounts/Account.jsx
packages/desktop-client/src/components/mobile/accounts/AccountTransactions.jsx
packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
packages/desktop-client/src/components/mobile/budget/Category.tsx
packages/desktop-client/src/components/mobile/budget/CategoryTransactions.jsx
packages/desktop-client/src/components/mobile/budget/index.tsx
packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
packages/desktop-client/src/components/modals/ImportTransactions.jsx
packages/desktop-client/src/components/settings/Experimental.tsx
packages/desktop-client/src/components/settings/Format.tsx
packages/desktop-client/src/components/util/AmountInput.tsx
packages/desktop-client/src/hooks/useFeatureFlag.ts
packages/desktop-client/src/hooks/usePrivacyMode.ts
packages/loot-core/src/client/reducers/prefs.ts
packages/loot-core/src/client/selectors.ts
packages/loot-core/src/shared/util.ts
packages/loot-core/src/types/prefs.d.ts
tsconfig.json
upcoming-release-notes/3395.md

We discussed this in private among the maintainers, but here's the TLDR:
SyncedPrefs are getting moved to the database. The database for synced prefs no notion of data types of the values (i.e. number, boolean, enum). All the values there are treated as `string`.
Which means we need to decide between:
1. using `string` for all the values in the UI code as well or
2. implement conversion/type-guard logic inside the `useSyncedPrefs`
We decided to go with (1) because that's generally the more simple solution. (2) would require implementation of lots of logic which would make the seemingly simple hook very verbose.
This PR converts the SyncedPrefs to `string` type.

:recycle: (synced-prefs) refactor some SyncedPrefs to string type

---

packages/desktop-client/public/site.webmanifest
upcoming-release-notes/3400.md

I noticed that (at least on Android) the PWA looks weird when launching: the background is fully white, which makes it look like we didn't bother to theme the app. This PR updates the background color to match the theme, which I think is reasonable (e.g., my bank's app has a splash-screen background color that matches the icon). I think we could still do better (e.g., having a higher-resolution image—the current icon looks a little blurry in the screenshot below) but IMO this is an improvement.
Thoughts? If this is something we want to add, having someone test on iOS would be great (I don't have a device handy).
Recommend reviewing with whitespace diff off (my editor auto-formatted 😞).
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/8f864d9b-944 …

Update splash background to match theming

---

packages/desktop-client/src/components/modals/ImportTransactions.jsx
packages/desktop-client/src/hooks/useSyncedPrefs.ts
upcoming-release-notes/3408.md

Refactoring SyncedPref usage in `ImportedTransaction`. This will make the migration to database-driven prefs more seamless.

:recycle: (synced-prefs) refactor ImportedTransactions usage of prefs

---

packages/loot-core/src/platform/server/fs/index.electron.ts
upcoming-release-notes/3406.md

Should fix: #3390
Adds retries into file system write calls. This should mitigate errors caused by virus scanners locking the files shortly after they've been written to.
File system reads aren't affected by the lock, so I haven't touched them.

:electron: Adding retries in to the file system writes

---

packages/desktop-client/src/components/accounts/Account.tsx
upcoming-release-notes/3441.md

:bug: fix account filters being overridden

---

packages/desktop-electron/beforePackHook.ts
packages/desktop-electron/package.json
upcoming-release-notes/3443.md

**Tested on:** 
- Windows
- Linux AppImage
- Didn't test mac - my VM broke - it should work exactly the same
**Before:** 
**After:**

:electron: Reduce package size 

---

packages/desktop-client/src/browser-preload.browser.js
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/hooks/useGlobalPref.ts
packages/desktop-electron/index.ts
packages/desktop-electron/preload.ts
packages/loot-core/src/client/actions/prefs.ts
packages/loot-core/src/platform/server/fetch/index.electron.ts
packages/loot-core/typings/window.d.ts
upcoming-release-notes/3431.md

Selecting a self signed certificate no longer restarts the app. Instead we restart the server process silently. The user shouldn't notice.
I've also added some logging for errors given by nodeFetch. That should help people diagnose cert/network related erros.

:electron: Restart server silently when adding self signed cert and add some logs

---

packages/desktop-client/src/hooks/useSyncedPrefs.ts
packages/loot-core/src/client/query-hooks.tsx
upcoming-release-notes/3460.md

Reproduction:
1. attempt to import [this csv file](https://github.com/user-attachments/files/17034819/Vanguard-401k.csv)
2. edge will crash; the current PR should work

:bug: (synced-prefs) fix bulk-reading not working in import modal

---

packages/desktop-client/src/components/reports/SaveReportChoose.tsx
packages/desktop-client/src/components/reports/SaveReportName.tsx
upcoming-release-notes/3462.md

Fixes https://github.com/actualbudget/actual/issues/3439

Fix reports form submit handlers

---

packages/desktop-client/src/components/Notifications.tsx
packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/common/Button2.tsx
packages/desktop-client/src/components/common/Link.tsx
packages/desktop-client/src/components/common/Select.tsx
packages/desktop-client/src/components/mobile/MobileBackButton.tsx
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
packages/desktop-client/src/components/modals/EditRuleModal.jsx
packages/desktop-client/src/components/modals/ImportTransactionsModal.jsx
packages/desktop-client/src/components/modals/ReportBudgetMonthMenuModal.tsx
packages/desktop-client/src/components/modals/RolloverBudgetMonthMenuModal.tsx
packages/desktop-client/src/components/reports/Header.tsx
packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
packages/desktop-client/src/components/settings/Format.tsx
packages/desktop-client/src/components/settings/Themes.tsx
packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/3453.md

Resolves #3447 
Preferring to use className instead of the inline style syntax to allow for easier CSS library migration in the future

Fix React Aria Button hover styles 

---

packages/desktop-client/src/components/Modals.tsx
packages/desktop-client/src/components/budget/rollover/BalanceMovementMenu.tsx
packages/desktop-client/src/components/budget/rollover/CoverMenu.tsx
packages/desktop-client/src/components/budget/rollover/TransferMenu.tsx
packages/desktop-client/src/components/budget/util.ts
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
packages/desktop-client/src/components/modals/CoverModal.tsx
packages/desktop-client/src/components/modals/TransferModal.tsx
packages/loot-core/src/client/state-types/modals.d.ts
packages/loot-core/src/server/budget/actions.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/notes/app.ts
upcoming-release-notes/3411.md

Resolves https://github.com/actualbudget/actual/issues/3404

Undoable auto transfer notes + auto notes for cover

---

packages/desktop-electron/index.ts
upcoming-release-notes/3475.md

Replaced the registerFileProtocol with the new version. This should make upgrading Electron easier.
https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-250

:electron: Replace deprecated file protocol registration

---

packages/desktop-client/src/components/modals/ImportTransactionsModal.jsx
upcoming-release-notes/3478.md

Fixes https://github.com/actualbudget/actual/issues/3464

:bug: (import) fix csv import checkboxes not working

---

packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
upcoming-release-notes/3487.md

fix modals on mobile BudgetTable

---

packages/desktop-client/src/components/ManageRules.tsx
upcoming-release-notes/3498.md

https://github.com/actualbudget/actual/issues/3482
I have not been able to reproduce this locally. But judging from the failing e2e test trace: the issue is that payee/category/account (one of the variables) is `undefined`. So I'm hoping this change will improve the e2e stability.
Sample failure: https://github.com/actualbudget/actual/actions/runs/11020812113/job/30606649587?pr=3491

:test_tube: improving rules e2e test stability

---

packages/desktop-client/src/components/FinancesApp.tsx
upcoming-release-notes/3503.md

Improving onboarding e2e test stability.
Root cause: race condition when loading account list. If account list loads quickly - we redirect to `/account` and then back to `/budget`. If they load slower - we redirect to `/budget` and then to `/account`.
More info (failure example & trace): https://github.com/actualbudget/actual/issues/3482#issuecomment-2375104467

:test_tube: improve onboarding e2e test stability

---

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
packages/desktop-client/src/components/modals/TrackingBalanceMenuModal.tsx
upcoming-release-notes/3492.md

Fixes https://github.com/actualbudget/actual/issues/3489

Fix mobile balance modal colors

---

packages/desktop-client/package.json
packages/desktop-client/src/components/PrivacyFilter.tsx
packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudgetAmount.tsx
packages/desktop-client/src/components/budget/tracking/TrackingBudgetComponents.tsx
packages/desktop-client/src/components/budget/tracking/budgetsummary/Saved.tsx
packages/desktop-client/src/components/reports/ReportSummary.tsx
packages/desktop-client/src/components/reports/reports/CustomReport.tsx
packages/desktop-client/src/components/reports/reports/NetWorth.jsx
packages/desktop-client/src/components/reports/reports/Spending.tsx
packages/desktop-client/src/components/table.tsx
packages/desktop-client/src/fonts.scss
upcoming-release-notes/3377.md
yarn.lock

- For #3376
Instead of blurring, uses the font Redacted Script https://github.com/christiannaths/redacted-font#redacted-script.
The good: much more private
Edit: the following limitation no longer applies (see https://github.com/actualbudget/actual/pull/3377#pullrequestreview-2287013488)
~The touchy: this font's sizing isn't identical to the non-private font. In some cases there's a minor layout shift on hover, and/or when toggling between modes.~
~The implementation support per-element `line-height` customization, and could easily be extended to support per-element `letter-spacing`. I haven't gone deep down that rabbit hole, only customizing line height on the two large font size numbers, where the difference is more significant.~
<details><summary>screenshot</summary><img width="1145" …

Privacy mode: instead of blurring, use an illegible font (#3376)

---

packages/loot-core/src/server/main.ts
upcoming-release-notes/3514.md

I think this will speed up the loading of the goal indicators on the budget page.  I added the two cache entries to the list of values to prewarm for each month.  This doesn't totally fix the issue, but I think it helps. 
For a bit I've been seeing the category balances progressively color when opening the app(except for negative balances that are always colored correct).  Sometimes it's really slow. It is more pronounced on mobile but still noticeable on desktop.

Add goal info to the prewarm list

---

.github/workflows/electron-master.yml
.github/workflows/electron-pr.yml
upcoming-release-notes/3526.md

Fixes build errors like below that seem to be failing every PR since last night.
https://github.com/actualbudget/actual/actions/runs/11084107270/job/30799089795#step:5:1

Fix electron build workflows for ubuntu-latest

---

packages/desktop-client/src/gocardless.ts
upcoming-release-notes/3515.md

Multiple reports in Discord shows that the current master branch has issues with gocardless linking: [mine](https://discord.com/channels/937901803608096828/1288271251810422857), [valerio's](https://discord.com/channels/937901803608096828/1288418544739942452), [aaarzan's](https://discord.com/channels/937901803608096828/1285223872022712353), [ROuGGy's](https://discord.com/channels/937901803608096828/1286541192191938570) among others. The symptom seems to be that, after a successful callback from GoCardless, Actual refuses to pop up the next step in the linking process, which is to select accounts to sync from. Server logs and browser console logs shows no anomaly.
I tracked down the issue, and found that in [gocardless.ts](https://github.com/actualbudget/actual/blob/686ce5b504e40646a0d7b9211 …

fix: pushModal not dispatched in GoCardless linking

---

packages/desktop-client/src/components/util/LoadComponent.tsx
packages/loot-core/src/shared/errors.ts
upcoming-release-notes/3525.md

When developing, especially deep in a component, the original error will get swallowed on the error screen. You can often get a generic error like this:
the root cause though, doesn't get passed on the exception chain, so the console will just report the generic error:
this captures the original exception to show as the cause:

pass causes along in failed-to-load exceptions

---

packages/desktop-client/src/components/FinancesApp.tsx
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/components/manager/ManagementApp.jsx
packages/desktop-client/src/components/mobile/accounts/Account.tsx
packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
packages/desktop-client/src/components/mobile/budget/Category.tsx
packages/desktop-client/src/components/mobile/budget/index.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
packages/desktop-client/src/components/settings/index.tsx
packages/desktop-client/src/hooks/useMetaThemeColor.ts
upcoming-release-notes/3521.md

Set theme-color at App level instead of per page

---

packages/desktop-client/e2e/onboarding.test.js
packages/desktop-client/e2e/page-models/configuration-page.js
upcoming-release-notes/3530.md

Fix the flaky `navigates back to start page by clicking on “no server” in an empty budget file` test from onboarding.test.js

[e2e] Account page tests - wait for transaction table to be visible

---

packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx
packages/loot-core/src/client/actions/account.ts
upcoming-release-notes/3540.md

Two fixes here for the initial bank sync:
1. close all the modal windows after successfully linking
2. show a loading indicator besides accounts after linking

:bug: (bank-sync) fix initial sync - close modal stack, show loading indicators

---

packages/loot-core/src/server/budget/goals/goalsSchedule.test.ts
packages/loot-core/src/server/budget/goals/goalsSchedule.ts
upcoming-release-notes/3511.md

Current behavior of template goals set to a schedule with frequency `yearly` are broken once the category is fully funded. This means budgeting into future months does not work as expected, in this case the full yearly amount is budgeted in the month following the transaction (instead of 1/12 the amount). The function that handles calculating the base savings amount has been updated to take yearly schedules into account.
Example of **previous broken** behavior:
The same budget file with the fix applied and templates re-ran:

Fix yearly schedule templates

---

packages/desktop-electron/bin/update-client
packages/desktop-electron/index.ts
packages/desktop-electron/modules.d.ts
packages/desktop-electron/package.json
packages/desktop-electron/server.ts
packages/desktop-electron/window-state.ts
upcoming-release-notes/3553.md
yarn.lock

We currently include all of loot-core's dependencies in the electron app. This may have been the root cause of the better-sqlite x64/arm64 issues we had a while ago. We don't need to include these modules because we bundle loot-core into bundle.desktop.js. 
This change makes it much easier to see what the Electron app _really_ depends on.
**Difference in size:** 
**Old :** 
**New:** 
**Tested on:**

:electron: Reduce electron package size

---

packages/desktop-client/src/components/manager/BudgetList.tsx
upcoming-release-notes/3574.md

Resolves https://github.com/actualbudget/actual/issues/3564 https://github.com/actualbudget/actual/issues/3563
Fix is to use Button instead of a View on the budget list

[Mobile] Fix budget list on mobile auto selecting a budget file under the Switch budget file menu

---

packages/desktop-electron/index.ts
packages/desktop-electron/package.json
upcoming-release-notes/3580.md
yarn.lock

```electron-is-dev``` is no longer required now that Electron has a an ```isPackaged``` property. 
The ```isPackaged``` property is the recommended way to know if we're in dev mode or not.

:electron: Removing electron-is-dev dependency

---

packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
packages/desktop-client/src/components/reports/reports/NetWorth.tsx
upcoming-release-notes/3576.md

:recycle: (typescript) migrated NetWorth component to TS

---

packages/desktop-client/src/components/reports/Overview.tsx
upcoming-release-notes/3566.md

Fixes #3559
Not exactly a _perfect_ patch, but a workable short-term solution until I get the dashboards feature finished off.

:bug: (reports) fix reports page having empty blocks

---

.github/workflows/size-compare.yml
upcoming-release-notes/3594.md

This fixes the errors we're seeing with the size comparison workflow
eg.
https://github.com/actualbudget/actual/actions/runs/11219565964/job/31185802750?pr=3581
new default value for `allow_forks` is `false` as of dawidd6/action-download-artifact v4
https://github.com/dawidd6/action-download-artifact/releases/tag/v4

fix size comparison workflow

---

packages/desktop-client/src/components/EditablePageHeaderTitle.tsx
packages/desktop-client/src/components/reports/Header.tsx
packages/desktop-client/src/components/reports/reports/CashFlow.tsx
packages/desktop-client/src/components/reports/reports/NetWorth.tsx
packages/desktop-client/src/components/reports/reports/Spending.tsx
packages/loot-core/src/server/reports/app.ts
packages/loot-core/src/server/reports/types/handlers.ts
upcoming-release-notes/3587.md

https://github.com/actualbudget/actual/issues/3282

:sparkles: (dashboards) ability to quick-edit widget names from inner report pages

---

packages/desktop-client/src/components/reports/Overview.tsx
upcoming-release-notes/3588.md

Feedback item here: https://github.com/actualbudget/actual/issues/3282#issuecomment-2357762546
---
Before: "add widget" button was visible only in edit mode; "create custom report" button was visible only in non-edit mode
After: "add widget" button is always visible (both edit and non-edit mode); "create custom report" has been removed
---
These changes are under feature flag. Experience WITHOUT the feature flag has no changes (there is still a "create custom report" button)

 :sparkles: (dashboards) making "all widget" button always visible

---

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/3549.md

[Mobile]  Allow updating existing transaction's account

---

packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/transactions/TransactionList.jsx
packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/3603.md

Fixes #2703 to show an account's running balance accurately when hiding its reconciled transactions. This addresses the use case of wanting to hide reconciled transactions (to keep them off of mind) and still showing the account's running balance.
* This fix changes `updateQuery` to _not_ filter out reconciled transactions, but defers the filtering downstream to `TransactionsTable` instead (which now takes the `showReconciled` prop accordingly).
* This allows us to call `calculateBalances` on the full set of account transactions. Previously, `calculateBalances` would be executed on only the rendered transactions, which meant the calculation would not reflect the account's actual balance.
* This does not break the existing behaviour that hides running balances when searching, filtering, or …

Fixes #2703 - Fixes inaccurate running balance when hiding reconciled transactions

---

packages/desktop-electron/menu.ts
packages/desktop-electron/package.json
packages/loot-core/src/platform/server/log/index.api.ts
packages/loot-core/src/platform/server/log/index.d.ts
packages/loot-core/src/platform/server/log/index.electron.ts
packages/loot-core/src/platform/server/log/index.web.ts
packages/loot-core/webpack/webpack.desktop.config.js
upcoming-release-notes/3599.md
yarn.lock

We don't use electron-logger for anything. The logs are buried in a hidden directory and we only log the server sync status. Instead of logging there, I've put the log messages into the console (which is what the web version does). It will be easier for users to see them there.
Someone asked for the ability to reload the app inside of electron - I've enabled it in the menu.

:electron: Remove unneeded logger and add reload functionality

---

packages/api/package.json
packages/desktop-client/package.json
packages/desktop-electron/package.json
upcoming-release-notes/3544.md
upcoming-release-notes/3566.md
upcoming-release-notes/3573.md
upcoming-release-notes/3574.md

What commits will be included in the release?
https://github.com/actualbudget/actual/compare/v24.10.1?expand=1
---
- web: https://github.com/actualbudget/actual/pull/3596
- server: https://github.com/actualbudget/actual-server/pull/475
- docs: https://github.com/actualbudget/docs/pull/465

:bookmark: (24.10.1) fix synced prefs

---

packages/desktop-client/src/components/modals/ImportTransactionsModal/FieldMappings.jsx
packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
packages/desktop-client/src/components/modals/ImportTransactionsModal/utils.js
packages/loot-core/src/server/accounts/rules.ts
upcoming-release-notes/3605.md

broken csv before: 
[CSV import actual issue.csv](https://github.com/user-attachments/files/17295454/CSV.import.actual.issue.csv)

fix: csv import with less than 5 columns

---

packages/desktop-client/src/components/accounts/Header.jsx
upcoming-release-notes/3615.md

Tiny quality of life improvement.

:sparkles: show the 'import transactions' button even if accounts have banksync

---

packages/loot-core/src/server/dashboard/app.ts
upcoming-release-notes/3626.md

When importing the exported file of the report dashboard. Names and timeframe data is lost.
Related feature: #3282 
Testing:
The following json should fail on edge to be imported (the metadata of text is required)
[dashboard (3).json](https://github.com/user-attachments/files/17330845/dashboard.3.json)
The following should be import but without custom names for networth
[dashboard (4).json](https://github.com/user-attachments/files/17330996/dashboard.4.json)
Hope it is clear!

fix: import meta of non custom report widgets

---

packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
packages/loot-core/src/types/prefs.d.ts
upcoming-release-notes/3543.md

save csv inOutMode settings

---

packages/desktop-client/src/components/accounts/Account.tsx
upcoming-release-notes/3625.md

Run rules on reconciliated transactions

fix: run rules on reconciliation transaction

---

packages/loot-core/package.json
upcoming-release-notes/3645.md
yarn.lock

Should close a number of dependabot alerts. These are not real alerts (`yargs` is only used in a single development-only script) but they're distracting from other potentially more useful alerts.

Bump `yargs` to newer version

---

packages/desktop-client/src/components/common/Search.tsx
upcoming-release-notes/3659.md

Translation support for packages/desktop-client/components/common/search

Translation: desktop-client/src/components/common/search.tsx

---

packages/desktop-client/src/components/modals/EditRuleModal.jsx
packages/desktop-client/src/components/rules/Value.tsx
packages/loot-core/src/server/accounts/rules.ts
packages/loot-core/src/server/accounts/sync.ts
packages/loot-core/src/server/accounts/transaction-rules.test.ts
packages/loot-core/src/server/accounts/transaction-rules.ts
packages/loot-core/src/shared/rules.ts
packages/loot-core/src/types/models/rule.d.ts
upcoming-release-notes/3619.md

Adds the field `payee_name` as possiblity for templating.
Makes it possible to change `payee_name` to whatever template you want.
Currently there is another field in the selector for setting the name but maybe this should not be visible and be auto selected when enabling templating on `payee` 
#3606

feat: templating on payee_name

---

packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
upcoming-release-notes/3674.md

When an account includes "Credit Card", 1Password really wants to suggest credit cards when you try to set the category or payee. This PR explicitly disables 1Password's autocomplete feature on table inputs to prevent these unwanted suggestions [using the `data-1p-ignore` property](https://developer.1password.com/docs/web/compatible-website-design/).
I took a bit of a large-hammer/simpler approach and assumed there shouldn't be 1Password suggestions anywhere within Actual, so I added it to all `input` elements added by `Autocomplete`, but I can refactor it to push this into the properties if you'd prefer.

Explicitly disable 1Password on table inputs

---

packages/loot-core/src/server/accounts/rules.ts
upcoming-release-notes/3624.md

Call recalculateSplit one last time to clear any erroneous errors
Fixes #3353

recalculateSplit one last time to clear any erroneous errors

---

packages/loot-core/src/server/budget/goal-template.pegjs
packages/loot-core/src/server/budget/goals/goalsAverage.ts
packages/loot-core/src/server/budget/goals/goalsCopy.ts
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/3617.md

Add a template to copy budgeted amount from X months prior
Test using `#template copy from <months back> months ago` or `#template copy from <back> months ago up to <some limit>`
fixes #3612
docs PR actualbudget/docs#467

[Goals] Add copy template

---

packages/loot-core/src/shared/util.test.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/3676.md

fixes #3638 
Still ignores 3 decimal places since that would break things for lots of people.
I should have allowed this before, but I didn't know if any banks actually exported 4 places.  I guess we know now.

allow 4 decimal places in file imports

---

packages/loot-core/src/server/accounts/rules.test.ts
packages/loot-core/src/server/accounts/rules.ts
upcoming-release-notes/3641.md

Closes #3353 and fixes another bug I found in the process (if you add amounts that _don't_ add up to the total, previously there _was no error_). Process I used to test this:
1. Add unit tests for #3353 and validate the specific test fails.
2. Add tests for the other bug and validate they fail.
3. Refactor and simplify the split generation logic. All tests now pass, and some basic testing in the UI looks good.
The straightforward fix for this issue is in https://github.com/actualbudget/actual/pull/3624. However, from revisiting this logic, it was pretty messy and hard to reason about before. Hopefully the refactor I'm landing here along with the tests will give increased confidence.

Clarify logic to generate splits from rules

---

packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
upcoming-release-notes/3679.md

Hey, this is my first pull request and I'm not very familiar with contributing to projects in general, so let me know if this is the correct process or if I should do anything in a different way.
This change fixes incorrect cumulative totals on days 28+ in the Spending Report that can occur when there are deposit transactions.
Brief summary of code's purpose:
Loops through an array with objects for days 28 to 30/31. Objects have a "cumulative total" already calculated. We want to use the latest "real" value (ie: if it's the 29th of the current month, the 30th's value doesn't exist, so use the 29th's cumulative total).
Explanation of issue:
The old code seemed to assume each "real" day's cumulative total would always decrease (larger negative value). It checked each day's value against the …

Fix incorrect cumulative totals for Days 28+ on the Spending Report

---

packages/loot-core/src/server/accounts/transactions.ts
packages/loot-core/src/server/accounts/transfer.ts
upcoming-release-notes/3705.md

feat: fix categories being set on offbudget transactions

---

packages/loot-core/src/server/post.ts
upcoming-release-notes/3697.md

If the sync server is behind an active tunnel but the server is offline we get a error message like: 
```
We had problems syncing your changes. Please report this as a bug by [opening a Github issue]
```
We get the error because the tunnel service says it can't connect to the server and we're not handling it.
This could be a common situation when the user wants to run the sync server on a computer in their house, but expose it to the internet for mobile use. Tunneling services like ngrok stay online forever, but If they turn their computer off the sync server goes offline. 
This fix detects known tunnels (ngrok for now) and if the tunnel is telling us the server is offline we handle it as normal - we tell the user it's offline.
This was found while working on the desktop app server sync: …

Handling tunnel errors as network failure

---

packages/desktop-client/src/components/HelpMenu.tsx

There was a race between a PR I merged and another PR (wasn't detected in the PR before merge because it wasn't up-to-date with master). This fixes the issue introduced in `HelpMenu.tsx`

Fix merge race

---

packages/loot-core/src/server/accounts/rules.ts
packages/loot-core/src/server/accounts/transaction-rules.ts
upcoming-release-notes/3704.md

fix: change payee rule not working #3702

---

packages/loot-core/src/client/actions/account.ts
upcoming-release-notes/3720.md

In https://github.com/actualbudget/actual/pull/3540 I was attempting to fix the status indicator for initial bank-sync operation. Unfortunately, this change has made things slightly worse. Sometimes the "loading" state for the initial bank-sync comes up, but then never goes away. I have not been able to figure out WHY. But arguably having no loading state is better than a forever-loading state, so reverting my original patch until I figure out a better solution.

:bug: (bank-sync) revert bank-sync status indicator change

---

packages/desktop-client/src/components/transactions/TransactionList.jsx
upcoming-release-notes/3728.md

Fix Issue #3662 - Distribute button calculates splits one at a time

---

packages/loot-core/src/client/actions/queries.ts
upcoming-release-notes/3721.md

[Goals]: fix no messages #1507

---

packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
upcoming-release-notes/3723.md

I noticed the Monthly Spending report wasn't properly averaging the previous three months when "Average" was selected. In my tests only the previous two months were averaged.
Issue was that not all date variables were in the same format. 
`month.month` was `YYYY-MM`
`startDate` was `YYYY-MM-DD`
This caused issues when doing the string compare of `month.month >= startDate`
Changed it to call the month helper function to format startDate correctly for the comparison

Fix issue with Monthly Spending report not properly averaging previous three months

---

packages/desktop-client/src/components/reports/DateRange.tsx
upcoming-release-notes/3735.md

Fix parse date in DateRange element which is causing the cards to display the wrong dates.

Fix Parse for Date Range

---

packages/loot-core/src/server/accounts/transaction-rules.ts
upcoming-release-notes/3725.md

Actual would crash if user attempted to filter by a Tag that has regex special characters in it - see discord support thread https://discord.com/channels/937901803608096828/1297943156146311208
Fixed by escaping regex special characters in tag before doing regex tag search - used regex found here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions#escaping

fix Tag filtering crashing app when tag has regex special character

---

packages/desktop-client/src/components/schedules/SchedulesTable.tsx
upcoming-release-notes/3739.md

Fixed "None" not being in the disabled colour.
<details>
<summary>Original behaviour</summary>
</details>

Fix "Name" field being in wrong colour in Schedules page

---

packages/loot-core/src/server/accounts/rules.test.ts
packages/loot-core/src/server/accounts/rules.ts
upcoming-release-notes/3749.md

Fixxes an issue that `{{day today}}` wasn't working. As reported in #3606 by @IsThisThingStillOn

fix: date handlebar functions

---

packages/desktop-client/src/components/payees/PayeeTable.tsx
packages/desktop-client/src/components/payees/PayeeTableRow.tsx
upcoming-release-notes/3768.md

Two bugs:
1. #3767 
2. In edge, you can select transfer payees even though the checkbox is invisible.
Ideally we'd have tests for these features. Not feeling super well right now so if someone wants to take a stab at it in the future, I'll make an issue.

Fix bugs in payee table

---

packages/desktop-client/src/components/accounts/AccountSyncCheck.tsx
packages/desktop-client/src/components/budget/util.ts
upcoming-release-notes/3757.md

[Typescript migration] Migrate AccountSyncCheck to ts

---

packages/desktop-client/src/components/reports/reports/CashFlow.tsx
packages/loot-core/src/types/models/dashboard.d.ts
upcoming-release-notes/3745.md

Closes #3671
It doesn't actually affect the widget in the dashboard page though... but now the state of it will be saved in the "inner" pages.

:bug: (dashboards) save cash flow balance setting

---

packages/desktop-electron/index.ts
packages/desktop-electron/package.json
packages/desktop-electron/server.ts
packages/loot-core/package.json
packages/loot-core/src/platform/server/fetch/index.electron.ts
packages/loot-core/src/server/main.ts
packages/loot-core/webpack/webpack.desktop.config.js
upcoming-release-notes/3782.md
yarn.lock

- The less Electron specific dependencies the better
- Electron supports Fetch out of the box nowadays so there's no reason to have node-fetch in Electron. Fetch supports the env variable but not the https.agent implementation - that's why that's updated.
- I'd like us to start moving Electron specific functionality out of loot-core and into Electrons main process to make the system more rebust. This should prevent any issues in the event that loot-core bundle crashes (this has caused issues in the past)
- It will reduce our electron bundle size a little bit
Found while working on this: #3631 
**Tested on:** 
Didn't test Mac but should be fine.

:electron: Removing node-fetch and updating root ca impl for more support

---

packages/desktop-client/src/components/common/Modal.tsx
upcoming-release-notes/3794.md

It looks like one file was missed in updating ```useResponsive```.  This corrects the reference in ```packages/desktop-client/src/components/common/Modal.tsx```

Fixes #3729: Typescript and Runtime error after previous merge

---

packages/loot-core/migrations/1730744182000_fix_dashboard_table.sql
upcoming-release-notes/3785.md

Created a migration that removes faulty widgets. I suspect a SyncedPrefs issue (which has been patched) might have been the root cause of these being created in the first place.
But we should still clean them up even if the root cause might be patched.

:bug: (dashboards) remove faulty dashboard widgets

---

packages/desktop-client/src/components/modals/GoCardlessExternalMsgModal.tsx
upcoming-release-notes/3793.md

Hey, thanks for the great work on actual. I had a smaller issue and could fix it myself, so I'm raising this PR.
I had the issue that I deleted my token in GoCardless and then GoCardless would give back an error object instead of an array in the `useAvailableBanks` hook. This would cause errors down the line, for example when giving this as  `sugggestions` to the `Autocomplete` component.
Checking if the response is an array prevents the app from crashing and also displays the correct "Failed loading available banks: GoCardless access credentials might be misconfigured. Please set them up again." error message.

Check gocardless bank data type before setting state

---

packages/loot-core/src/server/budget/categoryTemplate.ts
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/3817.md

I had messed up how the template goal values were calculated in the recent rewrite.
I had to change the following:
1. add a variable to track what the full template amount is compared to the amount that will be budgeted.
2. Remove the breaks on negative available.  That stopped the templates running early and calculating the full goal as was requested by the templates.  I was trying to be efficient, but all the processing is needed and I should have realized that.

[Goals] fix how goal values are calculated

---

packages/loot-core/src/server/budget/categoryTemplate.ts

Fix the case that there is only a remainder template and no other templates.  Remainders shouldn't set or affect goals.  Edge currently will show 0 as the goal for remainder only templates, but categories with other template lines work fine.
To test:
1. Add a remainder template to a category
2. Add a template and a remainder template to a category
3. Run templates
4. See that the remainder only category has no goal set (no tooltip will show on hover of balance), and that the category with two templates will show the expected goal excluding the remainder additions
Ill skip the release note since I just merged in a PR that talked about fixing goals.

[Goals] fix remainder goal

---

packages/loot-core/src/server/server-config.ts
upcoming-release-notes/3815.md

The provided server URL may already include a pathname, so all further segments need to be appended. This also more closely matches the name `joinURL`. Currently if `https://example.com/actual` is passed in to `getServer`, it will return URLs derived from `https://example.com` only.
While this doesn't implement #672, it would allow for any existing Actual client to access a server that's proxied behind a pathname.

fix: don't clobber server pathname

---

packages/loot-core/src/server/accounts/transaction-rules.ts
upcoming-release-notes/3823.md

Support post: https://discord.com/channels/937901803608096828/1304951796715884644
Iphone 13 cannot use Regex lookbehinds.  https://caniuse.com/?search=Lookbehind
This was stopping users from opening the app on Iphone 13.

🐛 Fix iphone 13 unable to use regex lookbehinds

---

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/3825.md

#3549 introduced a regression by removing `{ replace: true }` on the call to `navigate()` when navigating to the account page after adding a new transaction. This PR fixes the behavior so the back button works as expected again.
[Link to breaking change](https://github.com/actualbudget/actual/pull/3549/files#diff-2160422ad72c178aebbd20787701c79186591fd731cdadbd2671467c78e0470aL539)
Closes #3712

Fix back button behavior after adding tx on mobile

---

packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
packages/desktop-client/src/components/modals/EnvelopeBudgetMenuModal.tsx
packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
packages/desktop-client/src/components/modals/LoadBackupModal.tsx
packages/desktop-client/src/components/modals/TrackingBalanceMenuModal.tsx
packages/desktop-client/src/components/modals/TrackingBudgetMenuModal.tsx
packages/desktop-client/src/components/modals/TrackingBudgetMonthMenuModal.tsx
packages/desktop-client/src/components/modals/TrackingBudgetSummaryModal.tsx
packages/desktop-client/src/components/reports/Header.tsx
packages/desktop-client/src/components/reports/reports/NetWorth.tsx
packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
upcoming-release-notes/3832.md

Marked files for translation:
- packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
- packages/desktop-client/src/components/modals/EnvelopeBudgetMenuModal.tsx
- packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
- packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
- packages/desktop-client/src/components/modals/LoadBackupModal.tsx
- packages/desktop-client/src/components/modals/TrackingBalanceMenuModal.tsx
- packages/desktop-client/src/components/modals/TrackingBudgetMenuModal.tsx
- packages/desktop-client/src/components/modals/TrackingBudgetMonthMenuModal.tsx
- packages/desktop-client/src/components/modals/TrackingBudgetSummaryModal.tsx
- packages/desktop-client/src/components/reports/Header.tsx
- …

Marked files for translation

---

packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/loot-core/src/server/main.ts
packages/loot-core/src/server/server-config.ts
upcoming-release-notes/3837.md

Fixes #3784.
**Issue**
Passing an invalid URL such as "wrong.server.here" does not throw a validation error, but it redirects to the login page without any password input box. See #3784 for details.
**Cause**
In a recent change, the validation logic returns the global server config if the URL cannot be parsed. This fails if there is no existing server config.
**Changes**
1. Append "https://" (if absent) to server URL in `ConfigServer.tsx` before validating the URL.
2. Before validating in "subscribe-needs-bootstrap" handler, check if the passed base URL can be used to construct `URL()`.

🐛 Fix validation issue for invalid server URLs in /config-server page

---

packages/loot-core/src/client/actions/account.ts
packages/loot-core/src/server/api.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/3821.md

As reported in Discord, the API was not updated to use the single call SimpleFin batch update handler

add simplefin batch sync to api

---

packages/loot-core/src/server/budget/actions.ts
packages/loot-core/src/server/budget/categoryTemplate.ts
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/3829.md

since limits were being applied at the end of the processing chain, the funds pulled from categories because of the limit never had a chance to be used in other underfunded categories.
Ive reworked the limits to apply at the beginning, to return any excess from the previous month; and every priority pass, to not pull in unneeded funds.  Goals for the categories with limits should also set correctly now.  This also now handles rollover funds properly.
To test:
1. make a category with a limit template
2. Make a category with template that wont get fully funded with a priority level higher than the limit
3. have there be extra funds in that first category being carried from the previous month to cause the limit to already be met
4. Run templates and see that the funds removed by the limit …

[Goals] fix limits

---

packages/desktop-client/src/components/budget/BudgetSummaries.tsx
packages/desktop-client/src/components/sidebar/Sidebar.tsx
packages/desktop-client/src/hooks/useResizeObserver.ts
upcoming-release-notes/3859.md

Strict TS typing for useResizeObserver

---

packages/desktop-client/src/components/manager/ManagementApp.tsx
upcoming-release-notes/3860.md

Convert ManagementApp.jsx to tsx

---

packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
upcoming-release-notes/3873.md

Fix preview transactions not showing on all accounts page and aggregated accounts page (budgeted/offbudget)

---

packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
upcoming-release-notes/3872.md

I'll need someone with more experience here to tell me if/why this is a bad idea, but it fixes my problem of the first column being far too small for account names etc.
Before:
After:

Allow the report table columns to grow to fill available space

---

packages/desktop-client/src/components/schedules/PostsOfflineNotification.tsx
upcoming-release-notes/3868.md

Convert PostsOfflineNotification.jsx to tsx

---

packages/desktop-client/src/components/transactions/SimpleTransactionsTable.tsx
upcoming-release-notes/3870.md

Convert SimpleTransactionsTable.jsx to tsx

---

packages/desktop-client/src/components/modals/EditFieldModal.tsx
upcoming-release-notes/3865.md

Convert EditFieldModal.jsx to tsx

---

packages/desktop-client/src/components/modals/MergeUnusedPayeesModal.tsx
upcoming-release-notes/3866.md

Convert MergeUnusedPayeesModal.jsx to tsx

---

packages/desktop-client/src/components/payees/ManagePayees.tsx
packages/desktop-client/src/components/payees/ManagePayeesPage.tsx
packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/3867.md

Convert ManagePayees components to Typescript

---

packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
packages/loot-core/src/client/reducers/queries.ts
packages/loot-core/src/client/state-types/queries.d.ts
upcoming-release-notes/3862.md

Convert mobile Accounts.jsx to tsx

---

packages/desktop-client/src/components/reports/SummaryNumber.tsx
packages/loot-core/src/server/dashboard/app.ts
upcoming-release-notes/3871.md

I've simplified the font sizing - it should have quicker performance and it's easier to understand. There's a slight spacing adjustment too - It should look less tight but still fill out the space. 
Will need a thorough check to ensure It has the same output depending on the value.
**This also fixes the Import dashboard** when a summary card is being imported. _summary-card_ has been added into the importable report types.

🔧 Summary Card: Change the font size implementation to be simpler & fix import dashboard

---

packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
upcoming-release-notes/3882.md

https://github.com/actualbudget/actual/issues/3881
This is a bit heavy handed but it works - open to other ideas. We must be passing in a new object ref with the same contents for query, so even if it's the same data it thought it was different. 
This is the only solution I can think of that doesn't involve lots of refactoring

🐛  Fix performance when navigating between budget/accounts

---

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/3905.md

Fixes https://github.com/actualbudget/actual/issues/3896

Fix mobile transaction edit page's back button behavior

---

packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
upcoming-release-notes/3920.md

:bug: Fix flicker when saving transaction on account page when transactions are scheduled

---

packages/desktop-client/src/components/LoggedInUser.tsx
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/components/modals/manager/ImportActualModal.tsx
packages/desktop-client/src/components/modals/manager/ImportYNAB4Modal.tsx
packages/desktop-client/src/components/modals/manager/ImportYNAB5Modal.tsx
packages/loot-core/src/client/actions/budgets.ts
upcoming-release-notes/3904.md

Use useNavigate instead of accessing window.__navigate

---

packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/3906.md

Fixes #3849 
Category Labels should now scale alongside the background on smaller screens. See fix below:

Category Labels Not Scaling Correctly On Small Screen

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/3895.md

Adds a little more information to the error printed in the console when the GoCardless rate limit is reached. I'd love to work this into the UI at some point but this is an improvement.
Complimentary server PR: https://github.com/actualbudget/actual-server/pull/509
Fixes https://github.com/actualbudget/actual-server/issues/488

Add more logging for GoCardless rate limit information

---

packages/desktop-client/src/components/modals/CreateAccountModal.tsx
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/3942.md

Closes #3854
Additionally..
- made the file strict TS compliant
- removed the need to use `ref`s and `isOpen` state handling - since we are now using React-aria buttons - we can leverage the power of `DialogTrigger` - which removes the need for `ref`

:bug: fix misaligned gocardless credential popover

---

packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
packages/loot-core/src/client/SpreadsheetProvider.tsx
packages/loot-core/src/mocks/spreadsheet.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/shared/query.ts
upcoming-release-notes/3879.md

Build on top of https://github.com/actualbudget/actual/pull/3882. This update checks if the component was already unmounted and prevents a set state call + only call JSON.stringify when there is a query.

Optimize useSheetValue

---

packages/desktop-client/src/components/LoggedInUser.tsx
packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/UpdateNotification.tsx
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/components/manager/WelcomeScreen.tsx
packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
packages/desktop-client/src/components/settings/Reset.tsx
packages/desktop-client/src/components/settings/index.tsx
upcoming-release-notes/3911.md

Remove use of useActions

---

packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
upcoming-release-notes/3962.md

The mobile navigation tabs are hidden whenever you scroll down, they reappear when scrolling up. This is intended behavior.
On a bounce at the top however they disappear erroneously. I guess due to the bounce which scrolls slightly back down.
The same appears at the bottom where a bounce back up makes the tabs reappear.
This only seems to be an issue on iOS. Could not test it on Android due to not owning a device. But I could not detect this behavior in Firefox with small viewport.
This solution prevents the hiding / opening of the nav tabs by checking if it's at the top / bottom.
Issue at the top:
Issue at the bottom:
Fixed:

Fix mobile navigation tabs disappearing on top bounce

---

packages/desktop-client/src/components/modals/CreateAccountModal.tsx
upcoming-release-notes/3985.md

---
category: BugFix
authors: talkintomato
---
- Add space to copy
Previously ->

[BugFix] Space missing on create local account copy

---

.github/ISSUE_TEMPLATE/bug-report.yml

People seem to be reporting bugs without giving us the reproduction steps.. Hopefully this will improve the situation.

Move reproduction block as a separate text block

---

packages/loot-core/src/server/main.ts
upcoming-release-notes/4009.md

Fix incorrect boldening of synced accounts in the sidebar

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/4010.md

my logic was wrong and made templates not apply to the tracking budget.  Fixes #4006 
To test:
Add any template to a tracking budget and try to apply it.  It won't do anything in current edge.

[Goals]: Fix applying templates in tracking budget

---

.github/actions/setup/action.yml
.github/workflows/i18n-string-extract-master.yml
packages/desktop-client/.gitignore
packages/desktop-client/i18next-parser.config.js
packages/desktop-client/src/i18n.ts
upcoming-release-notes/4002.md

As it says on the tin. I also fixed some other issues with loading translations.

Upload translations on builds of `master`

---

packages/desktop-client/src/components/spreadsheet/useFormat.ts
packages/loot-core/src/client/actions/prefs.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/4038.md

Fixes https://github.com/actualbudget/actual/issues/4037. The bug occurs because the React component renders without using `useFormat` at all. An easy fix would be to just call that hook inside the component, but then we risk this bug cropping up on other pages. Instead I changed the logic at preference load time so it's valid for all components
Requesting Matiss since this relates to https://github.com/actualbudget/actual/pull/3397 but feel free to request someone else instead

Fix loading of number format on initial app startup

---

packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/4056.md

Fix payee cell overflowing when it contains an icon

---

packages/loot-core/src/server/budget/categoryTemplate.ts
upcoming-release-notes/4066.md

The logic to update the dates on repeated spend templates got missed.  Fixes #4065

[Goals]: fix repeating spend templates

---

packages/desktop-client/src/style/themes/development.ts
upcoming-release-notes/4073.md

Fix calendar report day background colour in development theme

---

packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
upcoming-release-notes/4099.md

Fixes #4026 
I don't think there is anything else necessary and it seems like creating a new payee with the 'one of'-operator works just fine now. I will look into it again to make sure and learn a bit more about the project. 
Should I extend/create a test for this?

fix: creating new payee with 'one of'-condition broken

---

.github/workflows/electron-master.yml
upcoming-release-notes/4105.md

Feedback from latest release: mark GitHub release as draft initially
Also see Action docs https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing and our docs https://github.com/actualbudget/docs/pull/605

Mark release as draft initially

---

packages/desktop-client/src/components/budget/envelope/budgetsummary/BudgetMonthMenu.tsx
packages/desktop-client/src/components/budget/envelope/budgetsummary/BudgetSummary.tsx
packages/desktop-client/src/components/budget/tracking/budgetsummary/BudgetMonthMenu.tsx
packages/desktop-client/src/components/budget/tracking/budgetsummary/BudgetSummary.tsx
packages/loot-core/src/client/actions/queries.ts
packages/loot-core/src/server/budget/actions.ts
packages/loot-core/src/server/budget/app.ts
packages/loot-core/src/server/budget/types/handlers.d.ts
upcoming-release-notes/4096.md

Currently, the individual categories have option to copy last 3, 6, or 12 months.  But the overall budget only has last 3.  This makes them similar.

Add Copy last 6/12 months to budget menu

---

packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/budget/index.tsx
packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
packages/desktop-client/src/components/mobile/budget/index.tsx
packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
packages/desktop-client/src/global-events.ts
packages/loot-core/src/client/query-helpers.ts
packages/loot-core/src/client/shared-listeners.ts
packages/loot-core/src/platform/server/connection/index.d.ts
packages/loot-core/src/server/accounts/transactions.ts
packages/loot-core/src/server/app.ts
packages/loot-core/src/server/main-app.ts
packages/loot-core/src/server/schedules/app.ts
packages/loot-core/src/types/server-events.d.ts
upcoming-release-notes/4110.md

[Typescript] Server event types

---

packages/loot-core/src/server/budget/categoryTemplate.ts
upcoming-release-notes/4120.md

Bug discussed here https://discord.com/channels/937901803608096828/1326945284722524170
Multiple templates in a category/priority level would double/triple/etc count the amounts requested by the early templates causing the amount check to think it had overbudgeted and remove funds.

[Goals]: fix stacked templates

---

.github/workflows/i18n-string-extract-master.yml
upcoming-release-notes/4149.md

The previous iteration of this GitHub action had a small error in that `wlc pull` is for pulling translations _from_ Git _to_ Weblate, rather than from Weblate to Git. This PR updates the action to use the correct verb, and also adds logic to pull new strings back into Weblate right away.
Should fix [this](https://github.com/actualbudget/actual/actions/runs/12760920680/job/35567137047) failed run

Fix string upload if new changes are present

---

.github/actions/setup/action.yml
bin/package-browser
packages/desktop-client/bin/remove-untranslated-languages
upcoming-release-notes/4148.md

As we start allowing folks to add new languages for translation, we probably don't want to show every language in the UI. Instead of hand-maintaining an allowlist of "good" languages, my idea was to use translation % as a proxy instead.

Exclude untranslated languages from builds

---

packages/desktop-client/src/components/ServerContext.tsx
packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx
packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
packages/desktop-client/src/components/filters/SavedFilterMenuButton.tsx
packages/desktop-client/src/components/modals/CreateAccountModal.tsx
packages/desktop-client/src/components/modals/EditUser.tsx
packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
packages/desktop-client/src/components/reports/spreadsheets/calendar-spreadsheet.ts
packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
packages/desktop-client/src/components/reports/spreadsheets/summary-spreadsheet.ts
upcoming-release-notes/4146.md

In https://github.com/actualbudget/actual/pull/4145 I'm attempting to remove `any` types from the `send` function. In doing so I uncovered a bunch of places where types were set incorrectly. This PR cleans up those types (split into 2 for readability).

Fix `send` types in a number of places (1/2)

---

.yarnrc.yml
eslint.config.mjs
packages/loot-core/package.json
upcoming-release-notes/4160.md
yarn.lock

Laying some groundwork to make merging the repo's a bit easier. These actions came out of this POC: https://github.com/actualbudget/actual/pull/4139
- Ignore sync-server folder during lint - sync-server doesn't currently follow the linting rules
- Turning off enableTransparentWorkspaces to allow us to use the npm packages instead of the workspace package. 
- This allows us to use the npm packages for crdt instead of being forced to build it directly in the workspace
- If we wish to use the workspace package we have to explicitly set ```workspace:*``` in package.json

👷  Prep work for merging actual-server into actual repo

---

packages/api/tsconfig.dist.json
packages/crdt/tsconfig.dist.json
packages/desktop-client/src/components/Notes.tsx
packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/common/Block.tsx
packages/desktop-client/src/components/common/Button.tsx
packages/desktop-client/src/components/common/InlineField.tsx
packages/desktop-client/src/components/common/Input.tsx
packages/desktop-client/src/components/common/InputWithContent.tsx
packages/desktop-client/src/components/common/Link.tsx
packages/desktop-client/src/components/common/Paragraph.tsx
packages/desktop-client/src/components/common/Text.tsx
packages/desktop-client/src/components/common/View.tsx
packages/desktop-client/src/components/forms.tsx
packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
packages/desktop-client/src/components/modals/TrackingBudgetMonthMenuModal.tsx
packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
packages/desktop-client/src/components/select/DateSelect.tsx
packages/desktop-client/src/components/settings/UI.tsx
packages/desktop-client/src/components/sidebar/ItemContent.tsx
packages/desktop-client/src/components/table.tsx
packages/desktop-client/src/style/styles.ts
packages/desktop-electron/tsconfig.dist.json
tsconfig.json
upcoming-release-notes/4163.md

Changed `moduleResolution` to `bundler`. This will allow us to extract the common components into a separate component library that can then be re-used in plugins.
The change of `moduleResolution` exposed some issues with our current usage of `React.CSSProperties`. Namely: we are using properties that do not exist in this type, but there were no warnings about this.
There are a couple of potential solutions. Some described here: https://mattrossman.com/2024/01/19/css-variables-with-react-and-typescript
However, I think in the end we will need to bite the bullet and move away from `@emotion/css` which will also require many type changes. So it will be much easier to do this if we fully control the `CSSProperties` type. Hence why I extracted it into our codebase. It's definitely not perfect …

:wrench: (typescript) change moduleResolution to bundler

---

eslint.config.mjs
packages/desktop-client/src/components/App.tsx
upcoming-release-notes/4124.md

[Address suppressed ESLint errors] Fix exhaustive deps errors in App.tsx

---

packages/loot-core/src/shared/transactions.ts
upcoming-release-notes/4186.md

Fixes a number of errors occurring on edge when updating split transactions. Sample repro: with an existing split, select the amount in one of the splits and hit backspace to see an error notification.
Our query engine doesn't support `undefined` for null values, only `null`; i.e., to omit a value, you either have to make it `null` or explicitly not pass it. To keep our types the same I opted for the latter.
To reviewer: this issue would have tripped the type checker if we enabled [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes) in strict mode. I tried doing that though and we currently have 174 violations. How do you feel about this flag? Is it worth trying to fix the violations?

Fix various split transaction edits not working

---

packages/desktop-client/src/i18n.test.ts
packages/desktop-client/src/i18n.ts
upcoming-release-notes/4185.md

Two bugs here:
- All language codes were being converted to lowercase, which breaks languages with region codes as those are capitalized. Instead, we only fallback to lowercase.
- A missing language would crash the application due to explicitly throwing an error in that case. Instead, we'll fall back to English if all other attempted languages are missing.

Fix i18n language fallback for regional languages

---

packages/desktop-client/package.json
packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/4182.md
yarn.lock

Fixed #2392
The focus trigger for Safari on iOS does not work as expected. This is a known issue for PWAs on iOS. So the workaround is to remote the auto-focus explicitly for these devices.

:bug: (mobile) fix amount input requiring two clicks on safari mobile

---

packages/loot-core/src/client/data-hooks/transactions.ts
packages/loot-core/src/shared/schedules.ts
upcoming-release-notes/4188.md

I found an issue where if a schedule posts early the upcoming one will still show even if the schedule is "paid".
This adds the same helper function as https://github.com/actualbudget/actual/pull/4180 whichever is merged first will probably cause a conflict with the other, I'll fix it.

fix paid schedules showing as upcoming in the account

---

packages/loot-core/src/server/accounts/rules.test.ts
packages/loot-core/src/server/accounts/rules.ts
upcoming-release-notes/4190.md

The rounding adjustment was being applied the wrong way 😅 This PR fixes it and adds tests
Closes https://github.com/actualbudget/actual/issues/3934

Fix rounding of split rules

---

packages/loot-core/src/client/data-hooks/transactions.ts
upcoming-release-notes/4196.md

Keeps the loop moving if it gets "stuck" with the same nextDate twice in a row

Fix app hanging when schedule moved before weekend

---

packages/loot-core/src/server/schedules/app.ts
upcoming-release-notes/4195.md

I missed a place when I updated the values for the pref

fix api crash - schedule upcoming length used raw

---

packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/4200.md

In edge, there is an issue in mobile where if you open the category budget modal and close it the "{Category} budget has been updated..." notification pops up even if the amount was not changed.
This PR is to fix FocusableAmountInput's onUpdate to only fire when amount was updated
Steps to reproduce:
1. Open mobile budget page
2. Click on a category's budget amount
3. Close the budget modal
4. (The notification shows up)

[Mobile] Fix "Category budget has been updated to ..." notification even when the budget was not updated

---

packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/modals/EditUser.tsx
packages/desktop-client/src/components/reports/Overview.tsx
packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx
packages/loot-core/src/client/actions/budgets.ts
packages/loot-core/src/client/actions/prefs.ts
packages/loot-core/src/client/data-hooks/transactions.ts
packages/loot-core/src/client/query-helpers.ts
packages/loot-core/src/platform/client/fetch/index.d.ts
packages/loot-core/src/server/admin/types/handlers.ts
packages/loot-core/src/server/aql/compiler.ts
packages/loot-core/src/server/dashboard/types/handlers.d.ts
packages/loot-core/src/server/rules/types/handlers.ts
packages/loot-core/src/server/schedules/app.ts
packages/loot-core/src/server/schedules/types/handlers.ts
packages/loot-core/src/types/models/simplefin.d.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/4147.md

In https://github.com/actualbudget/actual/pull/4145 I'm attempting to remove `any` types from the `send` function. In doing so I uncovered a bunch of places where types were set incorrectly. This PR cleans up those types (split into 2 for readability).

Fix `send` types in a number of places (2/2)

---

packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
packages/desktop-client/src/hooks/useTransactionBatchActions.ts
packages/loot-core/src/client/state-types/modals.d.ts
upcoming-release-notes/4189.md

From https://github.com/actualbudget/actual/pull/4186, I discovered it would be useful to enable `exactOptionalPropertyTypes` to prevent similar issues in the future. However, doing so requires updates in quite a few places, and interacts weirdly with the following pattern in React:
```tsx
type ComponentProps = {
...
prop?: string;
}
...
<Component
...
prop={cond ? "abc" : undefined}
/>
```
The easiest fix for conditional props is to change the prop type to:
```tsx
type ComponentProps = {
...
prop?: string | undefined;
}
```
Opening this PR to get feedback on whether we can accept this slight degradation in dev experience in exchange for better type safety.

Make `Account.tsx` compatible with `exactOptionalPropertyTypes`

---

packages/desktop-client/src/components/modals/ImportTransactionsModal/Transaction.tsx
packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
packages/loot-core/src/shared/util.ts
upcoming-release-notes/4207.md

Add type to the the amount utils to clarify what's the difference between amount, integer amount, and currency.
The components that accept amounts need to be updated to use these types to make it clear which types of amounts they need, but that's for another PR.

[TypeScript] Add types to amount utils

---

eslint.config.mjs
packages/desktop-client/src/components/App.tsx
packages/desktop-client/src/components/budget/index.tsx
packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
packages/desktop-client/src/components/mobile/budget/index.tsx
packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
packages/desktop-client/src/global-events.ts
packages/desktop-client/src/index.tsx
packages/desktop-client/src/redux/index.ts
packages/loot-core/src/client/shared-listeners.ts
upcoming-release-notes/4161.md

Fixes https://github.com/actualbudget/actual/issues/4082
The `global-listeners` file listens to a bunch of events from the backend (i.e. service worker). One of these events is the `sync-event` this event is emitted whenever new messages are received from the sync server (`type: 'success'`) or whenever a DB update is made (`type: 'applied'`). This change updates the `sync-event` handler so that it handles both `success` and `applied` sync event types - what this means is that whenever Actual received sync messages from the sync server or whenever a DB update is made, the payees, categories, and accounts in the redux state are automatically updated.
This will also help with performance by removing some of the duplicate `sync-event` listeners resulting in less DB calls

Update global event listeners to handle sync server and DB update sync events

---

packages/loot-core/src/client/queries/queriesSlice.ts
upcoming-release-notes/4179.md

Follow up to https://github.com/actualbudget/actual/pull/4161
This will save us 1 DB call on each of the create/update/delete actions

Remove unnecessary dispatch calls that are already being handled by shared-listeners.ts

---

packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
packages/loot-core/src/shared/transactions.ts
packages/loot-core/src/types/models/transaction.d.ts
upcoming-release-notes/4225.md

Fixes https://github.com/actualbudget/actual/issues/4220
I'm not entirely sure this is the right fix, but it does work. The problem came because not passing an error object at all leaves the error field unchanged when the db is updated.

Fix persistent split error popover

---

packages/desktop-client/src/components/budget/envelope/budgetsummary/ToBudget.tsx
upcoming-release-notes/4246.md

fix: hide to budget tooltip when menu is open

---

packages/loot-core/src/server/accounts/rules.test.ts
packages/loot-core/src/server/accounts/rules.ts
upcoming-release-notes/4243.md

Part of #3606 
Adds the following helpers:
- `replace value pattern replacement` mimics js replace. When pattern is not as `/regex/flags` it just uses raw value as opposed to `{{regex ...`
- `replaceAll value pattern replacement` mimics js replaceAll
- `addDays date days` add x days to the day
- `subDays date days`
- `addWeeks date weeks`
- `subWeeks date weeks`
- `addMonths date months`
- `subMonths date months`
- `addYears date years`
- `subYears date years`
- `setDay date day` Overflows are handled, 0 will set to last day of month before
- `concat args..` joins all arguments together

enhance: add more action rule templating helpers

---

packages/loot-core/src/server/accounts/__snapshots__/transfer.test.ts.snap
packages/loot-core/src/server/accounts/rules.test.ts
packages/loot-core/src/server/accounts/transfer.test.ts
packages/loot-core/src/server/accounts/transfer.ts
upcoming-release-notes/4255.md

Fix for an issue reported on Discord. The original issue involved rules with splits, but I found a much simpler repro:
1. Create a transaction with a transfer payee but don't hit "Add."
2. Set the category to "Split" and add a single child.
3. Change the child payee to a different transfer account.
4. Click "Add."
5. Observe that the payee on the child in the added transaction is not set.
Looking for input from others with more context on the direction we're taking with payees on parent transactions, but I think this matches the approach we've taken in other places (child transactions are the source of truth, parents are generated based on the children).

fix: allow child transactions to have different transfer payees

---

packages/desktop-client/bin/remove-untranslated-languages
upcoming-release-notes/4232.md

English localisations (en-GB for example) only need a few strings changing, the rest we can allow to fall back as they're common between the US original and GB localisation.
This prevents every string having to be copied over to any en translations and allowing only the differences to be added.

keep all English translations regardless of translated %

---

packages/loot-core/src/server/budget/categoryTemplate.ts
packages/loot-core/src/server/budget/template-notes.test.ts
packages/loot-core/src/server/budget/template-notes.ts
upcoming-release-notes/4265.md

The schedule templates would sometimes have inconsistent budgeted amounts. This fixes that so they should budget the same amount not matter what, in a given month.
[test.zip](https://github.com/user-attachments/files/18608378/test.zip)
To test use this file and apply the templates multiple times and see that the amount budgeted changes back and forth between two different values in edge.

:bug: [Goals]: Fix inconsistent schedule amounts

---

packages/desktop-client/src/components/reports/ReportOptions.ts
packages/desktop-client/src/components/reports/ReportSidebar.tsx
packages/desktop-client/src/components/reports/disabledList.ts
packages/desktop-client/src/components/reports/reports/CustomReport.tsx
packages/desktop-client/src/components/reports/reports/GetCardData.tsx
packages/loot-core/migrations/1736640000000__custom_report_sorting.sql
packages/loot-core/migrations/1738491452000__sorting_rename.sql
packages/loot-core/src/types/models/reports.d.ts
upcoming-release-notes/4276.md

The sorting of reports on the dashboard

report sorting on dashboard

---

packages/loot-core/src/client/data-hooks/transactions.ts
upcoming-release-notes/4256.md

Testing:
If you upload this to edge you'll see the schedule preview doesn't show in the account, but it does in the preview build.
[schedules_test.zip](https://github.com/user-attachments/files/18609280/schedules_test.zip)

fix first occurrence of some schedules moved after the weekend not showing in preview

---

packages/desktop-client/src/components/manager/subscribe/Login.tsx
upcoming-release-notes/4266.md

Fixes #4242
Would be nice to get into 25.2 but feel free to remove from the milestone if you disagree.
Edge:
This PR:

Make password login page more mobile responsive

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/4241.md

Some bank accounts have no `transactionId` in GoCardless, meaning that any changes (e.g setting to 0 for duplicated transactions) to any such imported transaction will cause Actual to re-import the transaction instead of updating or ignoring it.
GoCardless has an `internalTransactionId` for cases like these as described here: https://bankaccountdata.zendesk.com/hc/en-gb/articles/11529646897820-internalTransactionId-a-unique-transaction-ID-now-generated-by-GoCardless
There are some caveats though:
- It does NOT exist in pending transactions
- It is ONLY guaranteed to be unique inside the same bank account
As such, this PR falls back to `{acctId}-{internalTransactionId}` in case `transactionId` does not exist AND the transaction has been cleared.
Fixes #2495

fix(#2495): fix GoCardless transaction ID to fallback to it's own generated ID on sync

---

packages/desktop-client/src/components/ManageRules.tsx
upcoming-release-notes/4224.md

fix deleting rules considering the applied filters

---

packages/loot-core/src/server/budget/categoryTemplate.ts
upcoming-release-notes/4300.md

[Goals]: Handle tracking budget income categories

---

packages/desktop-client/src/components/reports/ReportOptions.ts
packages/desktop-client/src/components/reports/ReportSidebar.tsx
packages/desktop-client/src/components/reports/disabledList.ts
packages/desktop-client/src/components/reports/reports/CustomReport.tsx
upcoming-release-notes/4303.md

As it says on the tin.
Steps to repro (in the latest release):
1. Pick a language other than English.
2. Reload the page.
3. Navigate to the Reports page.
4. Add a custom report.
5. Observe crashes.
Testing this PR involves all of the above, but fixing the original crash uncovered many other crashes of the same shape. It's worth just clicking around the custom reports UI to verify the issue is eliminated (I did as much as I could, but it's possible I missed something).
Note to reviewers: Most of the options I added a "key" to have another value we could have already used as a "key"; for example, `intervalOptions` has `.name`. However, there are a _ton_ of places in the reports code that hard-code string checks, and in most of these places, the `interval` (or other attribute) is passed as …

Fix crashes on reports page with translations enabled

---

packages/loot-core/src/server/importers/ynab5.ts
upcoming-release-notes/4293.md

Handles the condition where nYNAB imports have duplicate categories or groups.
fixes #3069

Handle duplicate categories/groups in nYNAB importer.

---

bin/package-electron
package.json
packages/desktop-client/src/i18n.ts
upcoming-release-notes/4317.md

Translations were in an infinite loop, constantly being set, which was causing unintended ui behaviour.

Fix electron translations

---

packages/api/package.json
packages/desktop-client/package.json
packages/desktop-electron/package.json
upcoming-release-notes/4303.md
upcoming-release-notes/4312.md
upcoming-release-notes/4317.md

What commits will be included in the release?
https://github.com/actualbudget/actual/compare/v25.2.1?expand=1
---
- web: https://github.com/actualbudget/actual/pull/4319
- server: https://github.com/actualbudget/actual-server/pull/565
- docs: https://github.com/actualbudget/docs/pull/628

🔖 (25.2.1) fix desktop apps and reports page

---

packages/desktop-client/src/components/App.tsx
upcoming-release-notes/4322.md

The hard crash was introduced here:  https://github.com/actualbudget/actual/pull/4124
**Cause:** 
When you close a cloud budget the useEffect that calls ```init``` is triggered because of the cloudFileId. The init triggers a load budget call - so we're loading the budget while we're closing it, causing the app to crash. It was crashing trying to get the global spreadsheet when it was unloaded.

Fix hard crash when closing budget thats synced to cloud file

---

eslint.config.mjs
packages/loot-core/src/client/actions/prefs.ts
packages/loot-core/src/client/data-hooks/schedules.tsx
packages/loot-core/src/client/data-hooks/transactions.ts
upcoming-release-notes/4347.md

:recycle: (eslint) disallow importing actual-app/web in loot-core

---

packages/api/index.ts
upcoming-release-notes/4350.md

The export should have been removed a long time ago.. 😅

:recycle: (api) removing deprecated 'methods' export

---

packages/loot-core/src/server/accounts/rules.test.ts
packages/loot-core/src/server/accounts/rules.ts
upcoming-release-notes/4356.md

To check if the template is correct we do an compile with empty context so all helpers should work with empty fields

fix: helpers with empty or undefined values

---

packages/desktop-client/src/components/settings/LanguageSettings.tsx
upcoming-release-notes/4353.md

Link to https://github.com/actualbudget/docs/pull/630

Correct link to translation setup for local install

---

packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts
packages/loot-core/src/server/accounts/transaction-rules.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/4360.md

Closes #4351
Repro:
1. open spending analysis report
2. apply "category is (nothing)" filter
3. the page should NOT show any errors

 :bug: fix category is nothing rule crashing spending report widget

---

packages/loot-core/src/client/accounts/accountsSlice.ts
packages/loot-core/src/client/actions/budgets.ts
packages/loot-core/src/client/data-hooks/reports.ts
packages/loot-core/src/client/data-hooks/transactions.ts
packages/loot-core/src/client/query-hooks.ts
packages/loot-core/src/client/state-types/modals.d.ts
packages/loot-core/src/client/state-types/notifications.d.ts
packages/loot-core/src/mocks/index.ts
packages/loot-core/src/server/api-models.ts
packages/loot-core/src/server/errors.ts
packages/loot-core/src/shared/test-helpers.ts
packages/loot-core/src/shared/transactions.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/4214.md

Part 2 from https://github.com/actualbudget/actual/pull/4189

Make `loot-core` compatible with `exactOptionalPropertyTypes`

---

packages/loot-core/src/platform/client/fetch/index.browser.ts
packages/loot-core/src/platform/server/connection/index.web.ts
upcoming-release-notes/4375.md

It was a race condition. The backend was loading in faster than the frontend. It was sending the **_connect_**  message to the frontend and the frontend wasn't ready to receive it. 
We can't guarantee the order that the frontend or backend will load in, so we have to add retries to deal with it. 
**Fixes this:** 
Fixes: https://github.com/actualbudget/actual/issues/2893

🐛  Fix Initializing the connection to the local database hang

---

package.json
packages/sync-server/docker/edge-alpine.Dockerfile
packages/sync-server/docker/edge-ubuntu.Dockerfile
packages/sync-server/docker/stable-alpine.Dockerfile
packages/sync-server/docker/stable-ubuntu.Dockerfile
packages/sync-server/package.json
sync-server.Dockerfile
upcoming-release-notes/4370.md
yarn.lock

Aligning the sync server package name with the rest of the workspace.

Updating sync server package name to @actual-app/sync-server

---

packages/sync-server/src/app.js
upcoming-release-notes/4400.md

The new proxy middleware was added as a dev dependency but imported in production as well. 
The fix is to only import the dev dependency when in dev mode.

🐛 Fix new proxy middleware dependency missing on prod build

---

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx

Looks like adding in a context flag modifies the base key, which we cant do since the key is what gets used for English text.
To test, add a `#goal` to a category and look at the tooltip after running templates.  On edge it will say "Long_noun" on the PR it will just say "Long".  You will need to be on English and not "British English" language.

Fix goals tooltip translation

---

packages/loot-core/src/server/budget/base.ts
packages/loot-core/src/server/budget/statements.ts
packages/loot-core/src/server/budget/template-notes.test.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/db/mappings.ts
packages/loot-core/src/server/db/types.d.ts
packages/loot-core/src/server/db/types/index.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/server/sync/index.ts
packages/loot-core/src/server/sync/migrate.test.ts
packages/loot-core/src/server/tools/app.ts
upcoming-release-notes/4247.md

This PR is to make the `runQuery` function generic to make it easy to type DB query results and propagate the proper types from the bottom up. Right now the `runQuery` returns `any` which means we lose type safety on the callers of this function unless we cast the result to the proper type.
Note: We have 2 `runQuery`s in the codebase. One is for AQL (server/aql folder) and the other is for direct DB access (server/db folder). This PR is for the DB.
The next phase for this is to make the higher level functions e.g. `first`, `all`, `firstSync`, etc, generic and all of their callers.

[TypeScript] Make `db.runQuery` generic to make it easy to type DB query results

---

packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
packages/desktop-client/src/components/banksync/FieldMapping.tsx
packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/4403.md

From feedback in #4253 
> @matt-fidd Some edge cases Ive found testing in my instance.
> 
> Old transactions don't pick up the raw data from the sync so only new data is available to use for the mapper. (this is a cause of below)
> If there is only data for Payments and not Deposits, you can open the account mapper settings and change to Deposits, but cant change back to Payments. This is because there are no Deposits that have raw data so you get the message about needing data. (The selection box for switching between Payment and Deposit should either always show, or show if either of them have data)

update mapping data for existing synced transactions and always show direction dropdown

---

packages/component-library/src/styles.ts
packages/desktop-client/src/components/budget/SidebarCategory.tsx
packages/desktop-client/src/components/budget/goals/CategoryAutomationButton.tsx
packages/desktop-client/src/components/modals/EditRuleModal.jsx
packages/desktop-client/src/components/settings/Experimental.tsx
packages/desktop-client/src/hooks/useFeatureFlag.ts
packages/loot-core/src/client/data-hooks/schedules.tsx
packages/loot-core/src/client/state-types/modals.d.ts
packages/loot-core/src/server/budget/types/templates.d.ts
packages/loot-core/src/types/prefs.d.ts
upcoming-release-notes/4308.md

Round 2 of prototyping a goal template UI (the [previous PR](https://github.com/actualbudget/actual/pull/3918) can't be reopened sadly). Addressed a bit of feedback from that PR.

Foundations for the budget automations UI

---

eslint.config.mjs
packages/desktop-client/src/hooks/usePayees.ts
upcoming-release-notes/4260.md

Fix some suppressed react-hooks/exhaustive-deps ESLint errors

Fix react-hooks/exhaustive-deps error on usePayees.ts

---

packages/loot-core/src/platform/server/asyncStorage/index.d.ts
packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
packages/loot-core/src/platform/server/asyncStorage/index.testing.ts
packages/loot-core/src/platform/server/asyncStorage/index.web.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/types/prefs.d.ts
upcoming-release-notes/4369.md

Every setting from global-store.json was being treated like a string and then parsed. There are values in the global-store.json that aren't strings. E.g. ```did-bootstrap```
I've added a new type to represent the global-store.json file as it currently stands. The existing GlobalStore represents the values after they have been parsed. 
This makes it a lot easier to add more complex types/types that aren't just strings. It also gives us intellisense/type safety on the prefs functions (e.g. multiGet). 
This should help me out in https://github.com/actualbudget/actual/pull/4357 where I want to add a global-store setting like:
``` 
syncServerSettings: {
port: 5007,
autoStart: true,
ngrok: {
token: 'thetoken',
domain: 'thengrokdomain.com'
}
}
```
#1483

👷 Typescript: Improving typing of asyncStorage (global-store.json)

---

packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/budget/SidebarCategory.tsx
packages/desktop-client/src/components/budget/envelope/budgetsummary/TotalsList.tsx
packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
packages/desktop-client/src/components/modals/manager/ImportModal.tsx
packages/desktop-client/src/components/reports/ReportSidebar.tsx
packages/desktop-client/src/components/reports/reports/CustomReport.tsx
packages/desktop-client/src/components/reports/reports/Spending.tsx
packages/desktop-client/src/components/settings/Export.tsx
packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/4408.md

More translations.
I'm dedicating some time to zero out all "old" strings that are not translated yet.
As far as I saw, I will do this in three batches.
This PR
The next one will focus on rules and schedules
The last will focus on dates (the one I started already)

📚 Translation batch #1

---

packages/desktop-client/src/components/sidebar/Account.tsx
packages/desktop-client/src/components/sidebar/Accounts.tsx
upcoming-release-notes/4417.md

The current implementation checks for the account text to show or not the underline. For translated account names, it does not work.
Added new variable to control when show or not the underline

🐛 Fix `On budget` / `Off budget` underline with translated languages

---

packages/desktop-client/src/components/budget/envelope/HoldMenu.tsx
packages/desktop-client/src/components/spreadsheet/useSheetValue.ts
packages/loot-core/package.json
packages/loot-core/src/client/SpreadsheetProvider.tsx
packages/loot-core/src/platform/server/sqlite/unicodeLike.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/types/server-handlers.d.ts
packages/loot-core/webpack/webpack.browser.config.js
upcoming-release-notes/4409.md
yarn.lock

[TypeScript] Add types to SpreadsheetProvider

---

packages/loot-core/src/server/transactions/transfer.ts
upcoming-release-notes/4413.md

This issue has been reported a few times on Discord, most recently https://discord.com/channels/937901803608096828/1335338862125256704
There seems to be an edge case where the payee is not found when processing the transfers, this stops it from crashing the sync. The transaction still goes through, but is not considered as a transfer.
```
main.ts:1121 Bank Sync operation for account: xxxx
sync.ts:194 Pulling transactions from SimpleFin
sync.ts:244 Response: {transactions: Array(xx), accountBalance: Array(xx), startingBalance: xxxx}
sync.ts:398 Performing transaction reconciliation
sync.ts:516 Performing transaction reconciliation matching
index.web.ts:4 [Exception] TypeError: Failed syncing account “xxxx”
at gg (https://localhost:5006/kcab/kcab.worker.1e21d5133f60a8255cff.js:199:137027) …
```

prevent bank sync from crashing when payee not found

---

packages/sync-server/src/account-db.js
packages/sync-server/src/config-types.ts
packages/sync-server/src/load-config.js
upcoming-release-notes/4423.md

Added environment variable `ACTUAL_OPENID_ENFORCE=true` to enforce OPENID only.
If the user wants to disable fallback login mechanics, they set this variable.

✨Enforce OPENID login

---

packages/desktop-electron/index.ts
packages/loot-core/src/platform/server/connection/index.web.ts
upcoming-release-notes/4407.md

Queueing log messages sent before the client window is available. 
This will help debug issues to do with background processes that launch before the window has loaded (e.g. the sync server).

:electron: Improving electron logs

---

packages/desktop-client/src/components/App.tsx
upcoming-release-notes/4415.md

When starting the application (for the first time mainly), the strings are not loaded because the loadPrefs is called way later.
With this change, we force the initial labels to use the default browser language

📚 Start the application with the browser default language

---

packages/desktop-client/src/components/App.tsx
upcoming-release-notes/4439.md

Electron build keeps changing the language and never stops

🐛 Fix the default language init for electron

---

packages/loot-core/src/client/data-hooks/transactions.ts
upcoming-release-notes/4452.md

This makes the running balance a little bit more sensible. Neither approach is actually "correct" here, as the order of the preview transactions in Actual is completely unrelated to the order the transactions might actually happen, but this is the more logical order for the transactions to happen in.

sort schedule previews by date, then amount

---

packages/loot-core/src/client/data-hooks/transactions.ts
upcoming-release-notes/4461.md

Resolves #4436 
---
category: Bugfix
authors: [alecbakholdin]
---
Fixed bug where partially erasing search string would not reset search and result in incorrect search results.

resets transaction search even if search text is not empty

---

packages/desktop-client/src/components/banksync/AccountsList.tsx
packages/desktop-client/src/components/banksync/index.tsx
upcoming-release-notes/4458.md

Fixes https://github.com/actualbudget/actual/issues/4457
To test, open the bank sync page on edge and decrease the window height, the rows will collapse into each other. They won't on this deploy.
Before:
After:

fix row spacing on bank sync page

---

packages/desktop-client/src/components/modals/CreateAccountModal.tsx
upcoming-release-notes/4463.md

On edge, there is a missing space in the bank sync translations:
It's fixed in this PR:
Unfortunately this change will require re-translation. We'll probably want to disable string pruning at some point (or at least move it later in the build process). Will take a look at some point.

Fix missing space in bank sync strings

---

packages/loot-core/src/server/accounts/app.ts
upcoming-release-notes/4472.md

Looks like this was accidentally removed in https://github.com/actualbudget/actual/pull/4227

add last bank sync tracking back in

---

.github/actions/bump-package-versions

Skipping release notes as this is a CI script and only added this month.
Tested by running locally on Linux via Docker—note that there is no error on MacOS which is why this wasn't previously caught :/

Update bump-package-versions script to handle no input version

---

.github/workflows/docker-edge.yml
.github/workflows/docker-release.yml
upcoming-release-notes/4483.md

The docker images are currently published to the actual-server repo: https://github.com/actualbudget/actual-server/pkgs/container/actual-server
It has a message saying the repo is readonly so it's not ideal. This PR should publish to this repo as well. We can phase out the old actual-server images in future.

🐳 Docker images to be published under the actual repo

---

packages/desktop-client/src/components/settings/RepairTransactions.tsx
packages/loot-core/src/server/tools/app.ts
packages/loot-core/src/server/tools/types/handlers.d.ts
upcoming-release-notes/4464.md

Opening this now so I don't forget to merge it, but let's not merge before the release just in case. Will open a separate PR to fix the related bug.
To test:
1. Add a split transaction with two children.
2. Delete both children but not the parent.
3. Hit "expand splits" and observe the crash (occurs as of 26/02).
4. Manually navigate to `/settings`, hit "Repair transactions", and observe the message.
5. Navigate back to the account you were previously in and observe the lack of crashes.

Update transaction repair tool to remove erroneous transaction errors

---

bin/package-browser
bin/package-electron
upcoming-release-notes/4485.md

This stops subsequent builds failing when pulling the transactions repo in.
```
$ yarn build:browser
Updating translations...
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
```
```
$ pwd
/Users/matt/actual/packages/desktop-client/locale
$ git status --short --branch .
D ar.json
D ca.json
D cs.json
D da.json
D el.json
D fi.json
D hu.json
D id.json
D it.json
D lt.json
D nb-NO.json
D pl.json
D pt.json
D ru.json
D sv.json
D ta.json
D tr.json
D zh-Hans.json
D zh-Hant.json
```

prevent subsequent builds from failing when fetching translations

---

packages/loot-core/src/shared/util.ts
upcoming-release-notes/4489.md

Fixes a regression caused by https://github.com/actualbudget/actual/pull/4383
Fixes https://github.com/actualbudget/actual/issues/4487

fix negative amount parsing

---

packages/loot-core/src/mocks/budget.ts
packages/loot-core/src/server/accounts/app.ts
packages/loot-core/src/server/accounts/link.ts
packages/loot-core/src/server/accounts/payees.ts
packages/loot-core/src/server/accounts/sync.ts
packages/loot-core/src/server/api.ts
packages/loot-core/src/server/budget/actions.ts
packages/loot-core/src/server/budget/base.ts
packages/loot-core/src/server/budget/cleanup-template.ts
packages/loot-core/src/server/budget/goalsSchedule.ts
packages/loot-core/src/server/dashboard/app.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/filters/app.ts
packages/loot-core/src/server/main.test.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/server/migrate/migrations.test.ts
packages/loot-core/src/server/reports/app.ts
packages/loot-core/src/server/schedules/app.ts
packages/loot-core/src/server/schedules/find-schedules.ts
packages/loot-core/src/server/sheet.ts
packages/loot-core/src/server/transactions/transaction-rules.test.ts
packages/loot-core/src/server/transactions/transaction-rules.ts
packages/loot-core/src/server/transactions/transfer.test.ts
packages/loot-core/src/server/transactions/transfer.ts
packages/loot-core/src/server/update.ts
packages/loot-core/src/types/models/index.d.ts
upcoming-release-notes/4248.md

Follow up to https://github.com/actualbudget/actual/pull/4247

[TypeScript] Make `db.first` generic to make it easy to type DB query results

---

packages/loot-core/src/shared/util.test.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/4503.md

Looking for help testing this for edge cases in the UI. The unit tests provide coverage based on how I think the function is used, and I've tested most format/fraction-hidden combinations in various places where that matters (reconciliation pop-up and mobile transaction input) but it would be good to get a second pair of eyes.
Fixes https://github.com/actualbudget/actual/issues/4494
Closes #4490

Fix number input on mobile with hidden decimals

---

.gitignore
upcoming-release-notes/4508.md

This file was ignored on the actual-server repo but not here.
Will make it easier for people with fly.io deployments to keep track with changes without having to stash/unstash.

Ignore user's fly.toml

---

packages/desktop-client/src/components/accounts/AccountSyncCheck.tsx
packages/loot-core/src/server/accounts/app.ts
packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/4515.md

This is a shot at fixing https://github.com/actualbudget/actual/issues/4480. Regardless of a new solution from SimpleFIN, the 60s timeout is probably not enough for them to respond to batch requests for 40+ accounts in some cases.
This change increases the timeout to 5 minutes for batch sync operations, shows a more elegant error, and adds some debug logging if it was to fail.
Tested this by making the server to hang indefinitely on request to '/transactions'.

increase timeout for SimpleFIN batch sync and add debug logging

---

packages/desktop-electron/index.ts
packages/desktop-electron/package.json
upcoming-release-notes/4507.md
yarn.lock

When the user tries to move their budget directory there's a chance the directory will fail if the permissions aren't right or the files are locked. 
The current issue is that if it fails it leaves the users budget files in one place, but the app still references the old file location. So their budget files appear to be gone. 
The fix is to allow the budget directory to succeed if the budget files moved, which allows the app to set the new budget directory. To mitigate file locking I've added retries.

:electron:  Copy budget files to succeed even if cleanup fails & adding retries

---

packages/loot-core/src/client/queries.ts
upcoming-release-notes/4519.md

This PR fixes https://github.com/actualbudget/actual/issues/3042.
It fixes an issue where transactions for transfers between accounts (i.e., transactions where the payee is another account) were not properly filtered during searches.
---
- Before
<kbd><img width="1565" alt="image" src="https://github.com/user-attachments/assets/7d14a2b9-be27-46df-8bc0-6e5833a5a904" /></kbd>
- After
<kbd><img width="1567" alt="image" src="https://github.com/user-attachments/assets/6d333eab-10b7-4838-b420-4f6a77f2f9db" /></kbd>
---

fix: filtering of transfer transactions

---

packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/accounts/Balance.tsx
packages/desktop-client/src/components/accounts/Header.tsx
packages/desktop-client/src/components/spreadsheet/index.ts
packages/loot-core/migrations/1740506588539_add_last_reconciled_at.sql
packages/loot-core/src/mocks/index.ts
packages/loot-core/src/server/accounts/app.ts
packages/loot-core/src/server/aql/schema/index.ts
packages/loot-core/src/shared/util.ts
packages/loot-core/src/types/models/account.d.ts
upcoming-release-notes/4459.md

**⚠️ This PR contains a migration ⚠️**
---
This PR resolves #2967. 
It adds a `last_reconciled` column to the `accounts` table, which stores a UNIX timestamp indicating when each account was last reconciled. Upon initial release, all accounts will display "Not yet reconciled"; however, after completing reconciliation and pressing the "Done reconciling" button, the timestamp will be updated accordingly.
---
<kbd><img width="793" alt="imagem" src="https://github.com/user-attachments/assets/0ac295fd-8c23-41d0-8d41-6363191475b1" /></kbd>
<kbd><img width="855" alt="imagem" src="https://github.com/user-attachments/assets/a0159795-f924-4c1a-a11a-60c67a933cb5" /></kbd>
<kbd><img width="852" alt="imagem" src="https://github.com/user-attachments/assets/9b511a17-a2bd-4952-b41c-abb7babb24b5" /></kbd> …

feat: add "last reconciled" timestamp to accounts

---

packages/desktop-client/src/components/banksync/AccountRow.tsx
packages/loot-core/src/shared/util.ts
upcoming-release-notes/4523.md

Thanks to the helper @tostasmistas introduced in https://github.com/actualbudget/actual/pull/4459, this looks much better!
Before:
After:
Those screenshots are taken on different instances so the dates don't match.

Show the last bank sync in plain language instead of timestamp

---

packages/desktop-client/src/components/manager/subscribe/OpenIdForm.tsx
packages/loot-core/src/server/main.ts
packages/loot-core/src/types/models/openid.d.ts
packages/sync-server/src/accounts/openid.js
upcoming-release-notes/4530.md

I had to introduce a new env var to make this work, its not working properly. this fixes the new variable usage

🐛 Fixes for OpenID with the new config

---

packages/sync-server/src/load-config.js
upcoming-release-notes/4535.md

When transitioning from old to new load-config we lost some default values for user data. This fix it

🐛 Fix config for default data dir

---

packages/desktop-client/vite.config.mts
packages/loot-core/webpack/webpack.browser.config.js
upcoming-release-notes/4532.md

We expect a bump in bundle size here, but the benefits to debugging outweigh the expected impact.

disable mangling when building

---

packages/sync-server/src/load-config.js
upcoming-release-notes/4537.md

Port variables are being ignored at the moment with the config refactory

🐛 Fix for ACTUAL_PORT and PORT vars

---

packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.test.tsx
packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
packages/desktop-client/src/components/payees/ManagePayees.tsx
packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
packages/desktop-client/src/components/payees/PayeeTableRow.tsx
packages/desktop-client/src/components/transactions/TransactionsTable.test.tsx
packages/loot-core/src/server/aql/schema/index.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/server/models.ts
packages/loot-core/src/server/payees/app.ts
packages/loot-core/src/server/undo.ts
packages/loot-core/src/shared/util.ts
packages/loot-core/src/types/handlers.d.ts
packages/loot-core/src/types/models/payee.d.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/4443.md

Related to https://github.com/actualbudget/actual/issues/1113

Extract payees related server handlers from main.ts to server/payees/app.ts

---

packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.jsx
upcoming-release-notes/4540.md

External accounts are sorted when showing the modal, but the way its coded, its resorting the list every frame.
This PR memoizes the sorted list to resort it only when changing the list

✨ Memoize external accounts for bank sync

---

packages/desktop-client/src/components/accounts/Reconcile.tsx
packages/desktop-client/src/components/common/Input.tsx
packages/desktop-client/src/components/common/InputWithContent.tsx
packages/desktop-client/src/components/common/Modal.tsx
packages/desktop-client/src/components/modals/EditFieldModal.tsx
packages/desktop-client/src/components/select/DateSelect.tsx
packages/desktop-client/src/components/util/AmountInput.tsx
packages/desktop-client/src/components/util/PercentInput.tsx
upcoming-release-notes/4557.md

As far as I'm aware - this prop does not actually do anything. It might have done something earlier..
For example: the component is used when reconciling. Even with the removal of this `focused` prop - the auto-focus logic still works (via other logic we have in the codebase).
Removing this prop also makes it possible to move `Input` to the component library as it no longer relies on a higher-level context.
**Looking for 2+ approvals prior to merging.**

:recycle: removing 'focused' prop from generic Input component

---

packages/desktop-client/src/components/manager/subscribe/Login.tsx
packages/sync-server/src/app-account.js
upcoming-release-notes/4533.md

Sometimes the variable `ACTUAL_OPENID_ENFORCE` was not being enforced.
Fixes #4509

🐛 Fix for var `ACTUAL_OPENID_ENFORCE`

---

packages/desktop-client/src/components/ManageRules.tsx
packages/desktop-client/src/components/admin/UserAccess/UserAccess.tsx
packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
packages/desktop-client/src/components/common/InfiniteScrollWrapper.tsx
upcoming-release-notes/4578.md

1. renamed `SimpleTable` to `InfiniteScrollWrapper` to better reflect what it actually does
2. removed some unused functionality from the component

:recycle: (components) rename SimpleTable to InfiniteScrollWrapper and cleanup

---

packages/desktop-client/src/components/common/InfiniteScrollWrapper.tsx
upcoming-release-notes/4586.md

Turns out the wrapping `div` element was necessary after all.. who knew?
Bug introduced in: https://github.com/actualbudget/actual/pull/4578
Reported in: https://discord.com/channels/937901803608096828/1348454815394431071/1348454815394431071

 :bug: fix rules page table incorrect row heights

---

packages/desktop-client/src/components/modals/ConfirmTransactionEditModal.tsx
upcoming-release-notes/4604.md

This PR fixes https://github.com/actualbudget/actual/issues/4597.
It aligns the "Cancel" and "Confirm" buttons in the modal for confirming a transaction edit to the right-hand side for consistency.
---
- Before
Desktop     |  Mobile
:----------:|:----------:
<kbd><img width="904" alt="image" src="https://github.com/user-attachments/assets/80bd30d3-a2ed-4133-b4ba-391241b6d627" /></kbd> |<kbd><img width="458" alt="image" src="https://github.com/user-attachments/assets/a1b09e3f-5fb6-4e13-8257-5da4e3e33003" /></kbd>
- After
Desktop     |  Mobile
:----------:|:----------:
<kbd><img width="904" alt="image" src="https://github.com/user-attachments/assets/dcf3ddf2-e788-44d0-b9c7-3b19797214f7" /></kbd> |<kbd><img width="458" alt="image" src="https://github.com/user-attachments/assets/379532cf-421a- …

fix: align action buttons in modal for confirming transaction edit

---

README.md

This is provided by Weblate, there are a few different options if this one's not popular, but it felt the least intrusive whilst also being informative.

add weblate widget to readme

---

packages/desktop-client/vite.config.mts
upcoming-release-notes/4665.md

Fixes offline mode when the server is offline. Also fixes it when the new version of the app is out and the service worker is still hanging onto the old version (the issue on edge).
We should look into reducing the size of the index.x.js file after. It's currently over 2MB.

🐛 Allowing service worker to cache files up to 5mb - fixes edge & offline mode 

---

packages/desktop-electron/package.json
packages/loot-core/package.json
tsconfig.json
upcoming-release-notes/4668.md

This is a temporary fix for an Electron issue that was brought in by: https://github.com/actualbudget/actual/pull/4592/files
Basically the app wont start because it's resolving the wrong files in loot-core. I think the API will be broken too, I haven't tested it though.
I think there's more than one issue with that exports list so I couldn't fix it without spending a lot of time. This will make edge builds work again until we sort it out.
Example of the issue: 
```
"./client/platform": {
"node": "./src/client/platform.electron.ts",
"default": "./src/client/platform.web.ts"
},
```
Node doesn't get resolved by electron.
Another issue: 
```
"./platform/server/fetch": "./src/platform/server/fetch/index.web.ts",
```
Server fetch is always resolving the web. If we're in Electron it should …

:electron:  Fix electron loot core resolutions

---

packages/loot-core/src/server/aql/schema/index.ts
upcoming-release-notes/4675.md

After some recent change can no longer rename categories. Identified that it was because the database schema was missing goal_def for categories.
Resolves #4679

🐛 fixed can't rename notes

---

packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
upcoming-release-notes/4680.md

Fix issue where Cover overspending modal shows no categories when the overspent categories are hidden.

[Mobile] Show hidden overspent categories on Cover overspending modal

---

packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
upcoming-release-notes/4683.md

This PR fixes https://github.com/actualbudget/actual/issues/4663 and fixes https://github.com/actualbudget/actual/issues/3915.
It fixes an issue where filters set in the widget editor for the cash flow widget were not applied in the Reports dashboard.
---
<kbd><img width="1351" alt="image" src="https://github.com/user-attachments/assets/8aa30027-600f-4cfd-a720-48ee01734fbb" /></kbd>
---
- Before
<kbd><img width="446" alt="image" src="https://github.com/user-attachments/assets/5f5cfed5-33fe-4e8b-b9e0-c2d6b0b2c9c6" /></kbd>
- After
<kbd><img width="446" alt="image" src="https://github.com/user-attachments/assets/85f31bce-2f21-464e-a243-c8adde0960ae" /></kbd>
---

fix: apply filters in Reports dashboard for cash flow widget

---

packages/component-library/src/Input.tsx
packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
upcoming-release-notes/4697.md

Fix `Make Transfer` closing the Popover when clicked

🐛 Fix `Make Transfer` closing the Popover when clicked

---

packages/sync-server/src/app-pluggyai/app-pluggyai.js
upcoming-release-notes/4712.md

Deleting `Amount` before spreading prevents this error. `Amount` is not needed

🐛 Fix pluggy.ai foreigner currency transaction

---

packages/component-library/src/Menu.tsx
packages/desktop-client/e2e/page-models/mobile-budget-page.ts
packages/desktop-client/e2e/page-models/mobile-category-menu-modal.ts
packages/desktop-client/src/components/accounts/Header.tsx
packages/desktop-client/src/components/modals/CreateAccountModal.tsx
packages/desktop-client/src/components/reports/Overview.tsx
upcoming-release-notes/4716.md

Related: https://github.com/actualbudget/actual/pull/4619/files#r2000984899
Reproduction:
1. open an account
2. open the account menu (three dots)
3. select one of the options - i.e. "export"
4. the menu should close
This is especially annoying for multi-step scenarios (i.e. "link account" opens a modal, but the menu remains open)

:bug: fix menu not closing when menu item is clicked

---

packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
upcoming-release-notes/4735.md

Resolves #4734
See here: https://www.w3schools.com/tags/tag_input.asp 
There is no `focused` HTML input attribute.

🐛 [Bug]: Focused console warning

---

packages/loot-core/src/platform/server/asyncStorage/__mocks__/index.ts
packages/loot-core/src/platform/server/asyncStorage/index.d.ts
packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
packages/loot-core/src/platform/server/asyncStorage/index.ts
packages/loot-core/src/server/preferences/app.ts
upcoming-release-notes/4733.md

Closes #4732
Updated saveGlobalPrefs:
1. Updated setItem declaration to be async (it's an async function)
2. floatingSidebar is now compared against `undefined` because it is a boolean value and false was being ignored
Caused by #4127

🐛  [Bug] Pinning sidebar doesnt persist on reload

---

packages/loot-core/package.json
upcoming-release-notes/4767.md

Looks like I missed this in this fix: https://github.com/actualbudget/actual/pull/4668
It allows us to reference the loot-core desktop bundle in dev mode. We need it so that we can run the backend in a worker process.

:electron:  Fix loot-core resolution

---

packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
packages/desktop-client/src/components/budget/BudgetCategories.jsx
packages/desktop-client/src/components/budget/ExpenseCategory.tsx
packages/desktop-client/src/components/budget/index.tsx
packages/desktop-client/src/components/budget/util.ts
packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
packages/desktop-client/src/components/reports/ReportOptions.ts
packages/loot-core/src/mocks/budget.ts
packages/loot-core/src/mocks/index.ts
packages/loot-core/src/server/api-models.ts
packages/loot-core/src/server/api.ts
packages/loot-core/src/server/aql/schema/executors.ts
packages/loot-core/src/server/aql/schema/index.ts
packages/loot-core/src/server/budget/app.ts
packages/loot-core/src/server/budget/base.ts
packages/loot-core/src/server/budget/goalsSchedule.test.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/importers/ynab5.ts
packages/loot-core/src/server/models.ts
packages/loot-core/src/types/models/category-group.d.ts
packages/loot-core/src/types/models/category.d.ts
upcoming-release-notes/4544.md

Right now there is a mismatch between the AQL schema and the `CategoryEntity` model. The schema defines a `group` property but the `CategoryEntity` defined a `cat_group` property. This PR is to align the two and modify the entity model to match the schema.
I have also updated the server handlers to use AQL to query categories so that we avoid directly returning the DB models to the client side.
A new AQL executor is also added for category_groups to quickly filter out categories if needed via the `categories` query option (similar to how transactions query have the `splits` option).
Example:
```typescript
// Returns groups with categories included. This is default behavior.
aqlQuery(q('category_groups').options({ categories: 'all' }).select('*'))
// Returns groups without categories. …
```

Replace category DB queries in server handlers with AQL queries + implement category_groups AQL executor

---

packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
upcoming-release-notes/4774.md

Fixes #4723 and applying to #4484 as well

[Mobile] Fix income categories not changing colors based on active month

---

packages/desktop-client/src/components/modals/GoCardlessExternalMsgModal.tsx
packages/loot-core/src/client/modals/modalsSlice.ts
packages/loot-core/src/server/accounts/app.ts
upcoming-release-notes/4756.md

Currently if the initial account linking fails - there is no friendly error message. I am patching this + surfacing the API error in the UI for the user to see.
Also: improving some type definitions.
Related: https://github.com/actualbudget/actual/issues/4695

:bug: (bank-sync) improved error handling for initial gocardless account linking

---

.github/actions/bump-package-versions
upcoming-release-notes/4740.md

Two issues that came up this release:
- `packages/sync-server/package.json` was not added as part of the server migration; this has been fixed.
- Versions were not being correctly generated if the month had rolled over. This PR fixes the logic such that a minor version increment will still occur past the 1st of the month.

Fix bump versions script

---

packages/desktop-client/src/components/mobile/accounts/Account.tsx
packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/components/mobile/accounts/Accounts.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
packages/desktop-client/src/components/spreadsheet/index.ts
packages/loot-core/src/client/queries.ts
upcoming-release-notes/4584.md

This PR adds an additional 'Closed Accounts' group to the accounts page, below the Budget and Off Budget groups.
This allows filtering / searching for transactions in closed accounts.

Show closed accounts on mobile UI (#4581)

---

package.json
upcoming-release-notes/4757.md

This might be controversial so I am looking for 2+ maintainer approvals and NO disapprovals.
After the change in https://github.com/actualbudget/actual/pull/4710 - eslint has become much quicker. So quick in fact that I would propose to run it in the `lint-staged` step.
**What does this entail?**
`lint-staged` runs the lint jobs on the staged (read: changed) files. It does **not** run it on ALL the files. Since the amount of files it runs on is small - the operation is super quick (for me the whole lint-staged operation takes ~2s).
Running both eslint & prettier as part of this step allows us to surface issues quicker. Instead of having to wait for CI jobs to finish - we can identify new issues quickly on your local machine prior to pushing.
This might not matter much for active …

:wrench: added eslint auto-fix to the lint-staged step

---

packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/4812.md

Closes #4811
Steps to repro on edge (web, not mobile):
1. Navigate to an account.
1. Turn on running balance.
1. Click "Add New" but don't edit the transaction.
1. Click "Reconcile" and change the value to anything else.
1. Click "Create reconciliation transaction".
1. Observe the crash.
Performing the same steps on this PR's preview will not crash.

Fix crash on transactions table with new transaction popup open

---

packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/accounts/Header.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
packages/desktop-client/src/components/transactions/SelectedTransactionsButton.tsx
packages/desktop-client/src/hooks/useTransactionBatchActions.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/transactions/app.ts
packages/loot-core/src/server/transactions/merge.test.ts
packages/loot-core/src/server/transactions/merge.ts
upcoming-release-notes/4739.md

Attempts to implement the manual transaction merge option described first in #669 and seen again in #4676
Merge is only selectable only when two transactions with matching amounts are selected:
Does not show up with one selected on desktop
Greyed out on mobile when conditions are not met
For the two transactions, one is kept and one is dropped using the following logic:
1. If only one of the two is bank synced (only one of them has imported_id set), that one is kept
2. If only one of the transactions is imported by file (only one of them has imported_payee set), that one is kept
3. The earlier transaction is kept
The following fields can be affected by merge:
1. payee
2. notes
3. category
4. cleared
5. reconciled
If any of these fields is empty in the kept transaction (for cleared and …

✨ [Feature] Manually merge transactions

---

packages/loot-core/src/platform/server/fetch/index.ts
upcoming-release-notes/4706.md

Reverts actualbudget/actual#4706
#4706 may be incompatible with [this line](https://github.com/actualbudget/actual/blob/master/packages/sync-server/src/app-openid.js#L105). Reverting to investigate.

Revert "Reload on all redirects to handle Cloudflare Access auth expiration"

---

packages/desktop-client/src/components/reports/reports/CustomReport.tsx
upcoming-release-notes/4724.md

This PR fixes https://github.com/actualbudget/actual/issues/4444.
It ensures that modified filters are reapplied to the Custom Report when changing its interval or date range, rather than reverting to the last saved state, which could overwrite unsaved changes to the filters or their conditional operand.
---
- Before
- After
---

fix: persist filters in Custom Report on interval or date range change

---

packages/sync-server/bin/actual-server.js
upcoming-release-notes/4825.md

**Two issues fixed - both to do with the data directory:**
1. When ACTAUL_DATA_DIR is set and --config isn't set, the environment variable specified was not being respected.
2. When  no --config is set, look for a default config.json (this is the current server behavior). 
- If it exists and has a dataDir value, use it. Otherwise default it to the directory where the command was run 
- If it doesn't exist, also default the data dir to where the command was run
Defaulting the `data` directory and `config.json` in this script ensures that it works the same way as is described here: https://actualbudget.org/docs/config/. 
If we don't set them here manually, the server will search for the files in the project root, which is the node_modules folder because this is installed as node module.

🐛 CLI: Fix ACTUAL_DATA_DIR env variable not respected in some cases

---

packages/desktop-client/src/browser-preload.browser.js
packages/desktop-electron/index.ts
packages/desktop-electron/preload.ts
packages/loot-core/src/platform/server/asyncStorage/__mocks__/index.ts
packages/loot-core/src/platform/server/asyncStorage/index.d.ts
packages/loot-core/src/platform/server/asyncStorage/index.electron.ts
packages/loot-core/src/platform/server/asyncStorage/index.ts
packages/loot-core/src/server/accounts/app.ts
packages/loot-core/src/server/preferences/app.ts
packages/loot-core/typings/window.d.ts
upcoming-release-notes/4847.md

Exposing some functions to allow the Electron UI to perform the following actions: 
- Start sync server
- Stop sync server
- Get sync server running status
I've also updated the multiGet to be type safe - it was typing everything as string values.

:electron: Prep for configure server page

---

packages/desktop-electron/menu.ts
upcoming-release-notes/4853.md

Fixes load backup modal not triggered correctly, resulting in a blank screen.
Reported on Discord: https://discord.com/channels/937901803608096828/1361876081405071421/1361876081405071421
Related to: https://github.com/actualbudget/actual/issues/4703

:electron: Fix Load Backup backup modal

---

packages/sync-server/src/app-gocardless/banks/commerzbank_cobadeff.js
packages/sync-server/src/app-gocardless/banks/tests/commerzbank_cobadeff.spec.js
packages/sync-server/src/app-gocardless/banks/util/escape-regexp.js
upcoming-release-notes/4845.md

This should fix the Issue #4788. Now the Payee is escaped, so that the regular expression can work

fix: commerzbank escape payee

---

packages/desktop-client/src/util/versions.ts
upcoming-release-notes/4933.md

Motivation: Currently, releasing is a multi-step process. First, a PR is merged and tagged on master, which triggers release builds to _start_. Second, completed _desktop app_ release builds create a draft GitHub release. Finally, a maintainer manually marks the release as non-draft. This results in a poor user experience with updates, because the first step (tagging) would trigger a notification in all apps before the builds are even completed.
This PR updates the notification checking logic to use the latest (non-draft) release, rather than the latest tag. This means that update notifications will not be sent out until a maintainer manually un-drafts a GitHub release as the final step of the process (we do this anyway as noted above).
There's still a bit of a confusing situation for …

Use the latest release tag instead of the latest tag for version checks

---

packages/sync-server/src/migrations.js
upcoming-release-notes/4953.md

Referencing the migrations relatively so the app doesn't need to know what folder it has been built to. 
This is an alternative approach to: https://github.com/actualbudget/actual/pull/4952 . I think they'll both do the job, but removing references to the build folder is ideal.

🐛 Fixing docker edge

---

package.json
packages/desktop-client/package.json
upcoming-release-notes/4943.md
yarn.lock

Removes 4 MB from my local install, and ensures we only have to worry about security fixes for a single version of `vite` rather than two of them.
(Incidentally, I also ran `yarn dedupe` so there should be additional deduped packages.)

Deduplicate vite versions

---

packages/sync-server/bin/actual-server.js
packages/sync-server/src/account-db.js
packages/sync-server/src/util/paths.js
upcoming-release-notes/4954.md

Reported on Discord: https://discord.com/channels/937901803608096828/1369372745036595260
The issue here is that the user files and server files aren't always being resolved to an **absolute directory**. 
This is not just happening on the sync server CLI, but it's also happening when specifying the values for userFiles and serverFiles via config.json. 
Example of failing config: 
```
{
"serverFiles": "./serverFiles",
"userFiles": "./userFiles",
"port": 5007
}
```
To make it fail:
- setup a server with the config above
- open the server url & upload a budget 
- expose it with a reverse proxy
- logon to the proxy & download the budget
`Rejection: TypeError: path must be absolute or specify root to res.sendFile`
If the user doesn't try to override it it doesn't normally fail because it picks …

🐛 Sync server - resolving the user-files and server-files to an absolute dir

---

packages/sync-server/package.json
packages/sync-server/src/load-config.js
upcoming-release-notes/4968.md

The new sync-server build process wasn't copying over non js/ts files. This casues new budgets to be created without the `messages_merkles` and `messages_binary` table. The budget will still load on the client, but the server will give errors.
From my digging I believe this is the only directory that is missed during the build process.
- Tested locally

🐛 Fix sync server build not copying sql files over

---

packages/desktop-electron/index.ts
packages/desktop-electron/package.json
packages/desktop-electron/tsconfig.dist.json
upcoming-release-notes/4864.md

I noticed as part of https://github.com/actualbudget/actual/pull/4862 that pulling in any `.ts` file to `desktop-electron` causes the directory structure in `packages/desktop-electron/build/` to change (to having one subdirectory per package), resulting in broken Electron artifacts. This PR aims to fix that issue.

Stabilize electron build directory paths

---

packages/sync-server/src/app-gocardless/bank-factory.js
upcoming-release-notes/4970.md

ABANCA recently has implemented a new feature that ask for an sms code if the user requests more than 90 days of history, breaking the synchronization throgh gocardless. Adding it to the list of banks with limited history solves the issue.

Add Abanca to the list of banks with limited history

---

packages/desktop-client/src/components/settings/RepairTransactions.tsx
packages/loot-core/src/server/tools/app.ts
packages/loot-core/src/server/transactions/index.ts
upcoming-release-notes/4889.md

This fixes an issue where an existing parent transaction is still set to a category and you cannot delete the category due to it being used by a parent transaction - **this is not obvious and you cannot see this in UI because we don't show category for parent transactions**. This tool removes those categories from parent transactions so users can delete.
Without this tool, the way to fix the issue it to:
1. Find which parent transaction is using the category you want to delete (by exporting the DB and querying)
2. Recreate the split transaction and make sure parent transaction is not set to any category (best to not set category before splitting)
3. Delete the original split transaction
4. Delete the category
This PR will also prevent future split transactions from setting the category on …

Split transactions repair tool to remove categories from parent transactions + prevent adding/updating parent transactions with categories

---

packages/desktop-client/src/budgets/budgetsSlice.ts
packages/desktop-client/src/components/App.tsx
packages/desktop-client/src/components/LoggedInUser.tsx
packages/desktop-client/src/components/manager/BudgetFileSelection.tsx
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/components/manager/WelcomeScreen.tsx
packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
packages/desktop-client/src/components/modals/LoadBackupModal.tsx
packages/desktop-client/src/components/modals/OpenIDEnableModal.tsx
packages/desktop-client/src/components/modals/OutOfSyncMigrationsModal.tsx
packages/desktop-client/src/components/modals/PasswordEnableModal.tsx
packages/desktop-client/src/components/modals/TransferOwnership.tsx
packages/desktop-client/src/components/modals/manager/DeleteFileModal.tsx
packages/desktop-client/src/components/modals/manager/DuplicateFileModal.tsx
packages/desktop-client/src/components/modals/manager/FilesSettingsModal.tsx
packages/desktop-client/src/components/modals/manager/ImportActualModal.tsx
packages/desktop-client/src/components/modals/manager/ImportYNAB4Modal.tsx
packages/desktop-client/src/components/modals/manager/ImportYNAB5Modal.tsx
packages/desktop-client/src/components/settings/index.tsx
packages/desktop-client/src/components/sidebar/BudgetName.tsx
packages/desktop-client/src/global-events.ts
packages/desktop-client/src/index.tsx
packages/loot-core/src/client/shared-listeners.ts
packages/loot-core/src/client/store/index.ts
packages/loot-core/src/client/store/mock.ts
packages/loot-core/src/client/users/usersSlice.ts
upcoming-release-notes/4818.md

The original reason this was designed this way it to share the code with a mobile app. But since we no longer have a mobile app, these codes can now be merged to `desktop-client` package.
There will be some suppressed import warning due to loot-core importing some desktop-client files but this is only temporary until we migrate all the files 
1. Move folder from loot-core to desktop-client (vscode does the import updates)
2. Run yarn lint:fix
3. Suppress some @actual-app/web imports in loot-core (temporary until all loot-core/client is moved over to desktop-client)

Move loot-core/client/budgets code over to desktop-client package

---

packages/sync-server/package.json
packages/sync-server/src/app.ts
upcoming-release-notes/4897.md
yarn.lock

There are issues with the way Actuator reads the package.json. It works for most Node applications, but when embedded in a CLI tool or Electron, the package.json cannot be resolved, resulting in no version being displayed in the UI. 
This implementation should work both for CLI and when embedded in Electron.
**Actuator package:** https://github.com/rcruzper/express-actuator/tree/master
**Before:** 
**After:** 
_NOTE: I incremented the version of the cli tool locally_

Replacing Actuator with our own implementation

---

packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
upcoming-release-notes/4935.md

Fixes pie/donut charts viewing on mobile. This change allows users to click on the individual slice of the pie chart on mobile for it to "focus" on that slice. The change only affects touch screen devices, functionality remains in the same for desktop.
Prior to this fix focusing on a slice of the pie chart did not work properly on IOS devices. I am unsure if this was also the case on other mobile devices as I did have some success focusing on a slice by clicking and holding when testing via chrome dev tools but still did not work on my IOS device. 
Unlike in desktop view hovering over the slice doesn't work, clicking a slice of the pie chart results in user being navigated to the "accounts" section instead of focusing on the slice, and click and holding also does not work on my IOS …

[Mobile] 🐛 Fix viewing pie/donut charts on mobile

---

packages/sync-server/src/accounts/openid.js
upcoming-release-notes/4980.md

Found in the docs here: https://github.com/panva/openid-client/tree/v5.7.0/docs#customizing-http-requests
Fixes an issue reported on Discord where self hosted Authentik can reply quite slowly. https://discord.com/channels/937901803608096828/1371254299392479292

increase OpenID timeout

---

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/4914.md

When launching quick action for PWA, there is no history entry for the New Transaction page to go back to. The UX of that is 
1. the back button at the top left doesn't work
2. the accounts and notes fields get stuck
Adding a history entry for this page solves that.
Closes #4794

Fix new transactions account notes not clearing

---

packages/loot-core/src/client/data-hooks/transactions.ts
packages/loot-core/src/types/models/transaction.ts
upcoming-release-notes/4987.md

How to use:
```js
const { transactions, runningBalances } = useTransactions({
query,
options: {
calculateRunningBalances: true,
}
})
```
or
```js
// The default calculation works well when transactions are order by date in descending order, when a custom order
// is needed, it's best to provide a custom calculation function to calculate the running balances.
const customCalculateRunningBalances = (transactions: TransactionEntity[], queryState: QueryState) => {
// Calculate running balances for each transaction.
return new Map<TransactionEntity['id'], IntegerAmount>(...);
}
const { transactions, runningBalances } = useTransactions({
queryWithCustomOrder,
options: {
calculateRunningBalances: customCalculateRunningBalances,
}
})
```

Add option to calculate running balances in useTransactions hook

---

packages/desktop-client/src/app/appSlice.ts
packages/desktop-client/src/budgets/budgetsSlice.ts
packages/desktop-client/src/components/App.tsx
packages/desktop-client/src/components/modals/CreateEncryptionKeyModal.tsx
packages/desktop-client/src/components/settings/index.tsx
packages/desktop-client/src/global-events.ts
packages/desktop-client/src/hooks/useGlobalPref.ts
packages/desktop-client/src/hooks/useMetadataPref.ts
packages/desktop-client/src/hooks/useSyncedPref.ts
packages/desktop-client/src/hooks/useSyncedPrefs.ts
packages/desktop-client/src/index.tsx
packages/desktop-client/src/prefs/prefsSlice.ts
packages/loot-core/src/client/shared-listeners.ts
packages/loot-core/src/client/store/index.ts
packages/loot-core/src/client/store/mock.ts
packages/loot-core/src/client/users/usersSlice.ts
upcoming-release-notes/4821.md

The original reason this was designed this way it to share the code with a mobile app. But since we no longer have a mobile app, these codes can now be merged to `desktop-client` package.
There will be some suppressed import warning due to loot-core importing some desktop-client files but this is only temporary until we migrate all the files 
1. Move folder from loot-core to desktop-client (vscode does the import updates)
2. Run yarn lint:fix
3. Suppress some @actual-app/web imports in loot-core (temporary until all loot-core/client is moved over to desktop-client)

Move loot-core/client/prefs code over to desktop-client package

---

packages/desktop-client/src/accounts/accountsSlice.ts
packages/desktop-client/src/components/ManageRules.tsx
packages/desktop-client/src/components/accounts/Account.tsx
packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
packages/desktop-client/src/components/budget/index.tsx
packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/components/mobile/budget/ExpenseCategoryList.tsx
packages/desktop-client/src/components/mobile/budget/ExpenseGroupList.tsx
packages/desktop-client/src/components/mobile/budget/IncomeCategoryList.tsx
packages/desktop-client/src/components/mobile/budget/index.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
packages/desktop-client/src/components/modals/CloseAccountModal.tsx
packages/desktop-client/src/components/modals/CreateLocalAccountModal.tsx
packages/desktop-client/src/components/modals/EditRuleModal.jsx
packages/desktop-client/src/components/modals/ImportTransactionsModal/ImportTransactionsModal.jsx
packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
packages/desktop-client/src/components/rules/ScheduleValue.tsx
packages/desktop-client/src/components/schedules/ScheduleDetails.tsx
packages/desktop-client/src/components/sidebar/Account.tsx
packages/desktop-client/src/components/transactions/TransactionsTable.jsx
packages/desktop-client/src/global-events.ts
packages/desktop-client/src/hooks/useAccounts.ts
packages/desktop-client/src/hooks/useCategories.ts
packages/desktop-client/src/hooks/usePayees.ts
packages/desktop-client/src/index.tsx
packages/desktop-client/src/queries/queriesSlice.ts
packages/loot-core/src/client/shared-listeners.ts
packages/loot-core/src/client/store/index.ts
packages/loot-core/src/client/store/mock.ts
upcoming-release-notes/4822.md

The original reason this was designed this way it to share the code with a mobile app. But since we no longer have a mobile app, these codes can now be merged to `desktop-client` package.
There will be some suppressed import warning due to loot-core importing some desktop-client files but this is only temporary until we migrate all the files 
1. Move folder from loot-core to desktop-client (vscode does the import updates)
2. Run yarn lint:fix
3. Suppress some @actual-app/web imports in loot-core (temporary until all loot-core/client is moved over to desktop-client)

Move loot-core/client/queries code over to desktop-client package

---

packages/desktop-client/src/budgets/budgetsSlice.ts
packages/desktop-client/src/components/App.tsx
packages/desktop-client/src/components/LoggedInUser.tsx
packages/desktop-client/src/components/admin/UserAccess/UserAccessRow.tsx
packages/desktop-client/src/components/admin/UserDirectory/UserDirectory.tsx
packages/desktop-client/src/components/manager/BudgetFileSelection.tsx
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/components/manager/ManagementApp.tsx
packages/desktop-client/src/components/manager/subscribe/Login.tsx
packages/desktop-client/src/components/manager/subscribe/OpenIdCallback.ts
packages/desktop-client/src/components/modals/EditAccess.tsx
packages/desktop-client/src/components/modals/EditUser.tsx
packages/desktop-client/src/index.tsx
packages/desktop-client/src/modals/modalsSlice.ts
packages/desktop-client/src/users/usersSlice.ts
packages/loot-core/src/client/shared-listeners.ts
packages/loot-core/src/client/store/index.ts
packages/loot-core/src/client/store/mock.ts
upcoming-release-notes/4823.md

The original reason this was designed this way it to share the code with a mobile app. But since we no longer have a mobile app, these codes can now be merged to `desktop-client` package.
There will be some suppressed import warning due to loot-core importing some desktop-client files but this is only temporary until we migrate all the files 
1. Move folder from loot-core to desktop-client (vscode does the import updates)
2. Run yarn lint:fix
3. Suppress some @actual-app/web imports in loot-core (temporary until all loot-core/client is moved over to desktop-client)

Move loot-core/client/users code over to desktop-client package

---

package.json
upcoming-release-notes/5011.md

Sets an engine version for yarn so that users with the wrong yarn version get early feedback and a clear error message.

Set yarn engine version

---

package.json
upcoming-release-notes/5017.md
yarn.lock

Fixes https://github.com/actualbudget/actual/security/dependabot/111
Fixes https://github.com/actualbudget/actual/security/dependabot/105
`socks` no longer uses IP, so resolving this manually to a higher version removes any potential exposure
Seen recommended https://github.com/indutny/node-ip/issues/150#issuecomment-2623196328

remove dependency on ip

---

package.json
upcoming-release-notes/5018.md
yarn.lock

Fixes https://github.com/actualbudget/actual/security/dependabot/52
Or at least, should do. It stops the version of `got` being pinned back.

⬆️ bump jq

---

packages/desktop-electron/package.json
upcoming-release-notes/5029.md
yarn.lock

tested on MacOSx ARM and x64 (emulated). tests on other platforms are welcomed but I don't foresee any issues.

⬆️ upgrade electron dependencies to their newest minor version

---

.github/workflows/electron-master.yml
upcoming-release-notes/5034.md

As it says on the tin. Automation!
Tested by running in my fork with temporary secrets (cloned these to actualbudget/actual). [Sample run](https://github.com/jfdoming/actual/actions/runs/15127700386)
To future maintainers: the store UI is buggy, in the sense that you need to give it ~30 mins or so before it will reflect that the app actually submitted. It did, don't worry!

Automatically upload to the MS store on release

---

packages/loot-core/src/server/accounts/app.ts
upcoming-release-notes/5038.md

---
category: Enhancements
authors: [SteinTokvam]
---
Added information that sync error are caued by a rate limit if that's the case.

if BankSyncError is caused by rate limit. display that in toast

---

.github/ISSUE_TEMPLATE/bug-report.yml
upcoming-release-notes/5070.md

I plan on retroactively adding this label to all the existing issues that have only the "bug" label too. Via some sort of one-off usage script I'll cook up later.

 :wrench: added needs-triage label to all new bug issues

---

packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/hooks/usePreviewTransactions.ts
upcoming-release-notes/5080.md

Sometimes loading schedules takes a bit of time. Having schedules fully loaded is a pre-requisite for bank-sync to work. So if a user is quick to perform the pull-to-refresh operation - it is just ignored.
Updated the logic to show a loading indicator if schedules are not yet fully loaded.
Should fix #5005

:bug: (mobile) fix - show loading indicator if schedules not yet loaded

---

packages/sync-server/src/app-gocardless/banks/danskebank_privat.js
upcoming-release-notes/5101.md

For the Norwegian Branch of Danske Bank, a `EndToEndID: NOTPROVIDED` suffix is appended to all SEPA transactions. The Danish branch of Danske Bank seems to use the same system as the Norwegian branch, and so `EndToEndID: NOTPROVIDED` is also appended to notes from this bank. This PR adds the Danish branch to `institutionIds`.
I've looked at the code responsible for loading bank overrides, and it seems like this fix should work, but I am not familiar with the code-base of Actual Budget, so please keep that in mind when reviewing.

Trim EndToEndID from the Danish Danske Bank branch

---

eslint.config.mjs
packages/desktop-client/src/hooks/useNavigate.ts
packages/desktop-client/src/redux/index.ts
packages/desktop-client/src/style/index.ts
packages/desktop-client/src/style/palette.ts
packages/desktop-client/src/style/themes/dark.ts
packages/desktop-client/src/style/themes/development.ts
packages/desktop-client/src/style/themes/light.ts
packages/desktop-client/src/style/themes/midnight.ts
packages/desktop-electron/e2e/onboarding.test.ts
upcoming-release-notes/5081.md

This issue has been annoying me for a while now. Let me explain what I'm doing here.
Eslint has a flat configuration object. It does not support partial rule config overrides.
For example: we can globally restrict importing from dependency A. If some file needs to have another different import restriction - there is no way to merge "restrict importing A" + "local restriction". The last applied config always takes priority.
Fortunately we don't have any violations because of the rule conflicts. But better fix this issue now and forget about it..
---
Alternative solution would be to bring back package-specific eslint runners & config files (& maybe also a shared config package so we could inherit the global config). But that would be a significantly heavier lift with more long-term …

:wrench: (eslint) patch no-restricted-imports rule

---

.github/workflows/stale.yml
upcoming-release-notes/5110.md

I made a small mistake..
1. the "needs info" label should not be automatically removed
2. the PRs should never be touched; only issues

 :wrench: improving the needs-info stale issue management

---

packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
upcoming-release-notes/5129.md

Fixes #3965
Ensures that the net worth graph's gradient ID is unique to prevent conflicts when multiple graphs are rendered on the same page.
To verify, I added a Net Worth Chart to the reports page of the test budget, where I simply added a filter `amount < 1000` to make the net worth negative.
**Before**
**After**

Fix net worth graph gradient conflict

---

packages/desktop-client/src/components/settings/Reset.tsx
upcoming-release-notes/5133.md

I was looking at contributing to some Dutch translations in Weblate and I noticed a strange key ([link](https://hosted.weblate.org/translate/actualbudget/actual/nl/?checksum=a96993dec4a7e11a)) that didn't make sense to me. Looking in the source code it appears this sentence dropped the `enabled.` in [this commit](https://github.com/actualbudget/actual/commit/0c94214a8ff5bdb802004cdeb323adcdffaa24f4#diff-506178988b30d52a1676964800c6206d8f4c2dbfc46c99fb77a755b9bfa690f6L75) by accident.
Are there certain steps I should follow due to updating a translation key or will it just be picked up as a new key to be translated in Weblate?

fix: add missing 'enabled' in sentence.

---

bin/release-note-generator.ts
upcoming-release-notes/5134.md

I usually create a draft PR before I generate the release notes and I found that the prompt value for PR number is not used for determining the file path, as it only uses the initial value. For me this didn't work because I'm not authenticated through the Github CLI so it will always use the value from `getNextPrNumber`, which is my draft PR number + 1. This change fixes it by using the inferred number as initial value for the command line prompt, and reading the actual value to be used for the file path.

fix: ensure correct PR number is used for release notes file

---

packages/desktop-client/src/components/Notifications.tsx
packages/desktop-client/src/components/common/Modal.tsx
upcoming-release-notes/5165.md

This gets really annoying if you are doing multiple quick operations and the screen has 3+ notifications. Suddenly they start overlaying also the modal content window - which obviously isn't great UX.
Before:
After:

Fix: display notifications below modal windows

---

packages/desktop-client/src/components/mobile/PullToRefresh.tsx
upcoming-release-notes/5179.md

Reproduction (on mobile):
1. create a new account
2. add a single transaction
3. pull down to refresh
1. before: only a small section of the page is "pullable" down (hard to describe what I mean, but you'll get it when you see the issue..)
2. after: transaction list expands to 100% height of the page

Enhance PullToRefresh component to ensure full height usage on mobile devices

---

packages/loot-core/src/server/budget/goal-template.pegjs
upcoming-release-notes/5189.md

Fixes issue #4607 which was introduced by feature #4257 
The changes fix parsing of schedule names containing square brackets by modifying the grammar rules:
- **Before:** Schedule names couldn't contain `[` characters at all, causing failures when brackets appeared
in schedule names
- **After:** Schedule names can now contain brackets, but the parser stops parsing the name when it
encounters `[increase` or `[decrease` modifiers (using negative lookahead)
- Also trims whitespace from the parsed schedule name
This allows schedule names like "My Schedule [2024]" to work properly while still recognizing increase/decrease modifiers.
https://github.com/user-attachments/assets/6221058c-954e-4b3a-9b6a-b5a1c18ffa93

Update parsing of schedule names (issue #4607)

---

packages/sync-server/src/app-gocardless/banks/kbc_kredbebb.js
upcoming-release-notes/5193.md

It is the same fix as done for KBC Bank in https://github.com/actualbudget/actual-server/pull/442 
In between there was a refactor done for CBC https://github.com/actualbudget/actual-server/pull/451 
KBC and KBC Brussels are the same banks in Belgium, the latter being the Brussels branch.
To be honest, I don't know the exact differences between the two, I think it is only for administrative reasons. I can log in both KBC and KBC Brussels without differences. The same applies to sync with GoCardLess. 
However, if I select sync with KBC Brussels, the fix for payeeName for KBC is not applied.
Please check if the fix I've done is the correct way to do it. I didn't want to create duplicate code which serves the same purpose. 
I tested the fix successfully on my build with KBC Brussels

fix: wrong payeeName for KBC Brussels

---

packages/sync-server/package.json
packages/sync-server/src/app.ts
upcoming-release-notes/5197.md
yarn.lock

body-parser is built into express 5, we can drop this dep now.
https://expressjs.com/en/5x/api.html

♻️ remove body-parser dependency

---

packages/sync-server/src/app-gocardless/banks/boursobank_bousfrppxxx.js
packages/sync-server/src/app-gocardless/banks/tests/boursobank_bousfrppxxx.spec.js
upcoming-release-notes/5202.md

This is a followup of https://github.com/actualbudget/actual/pull/4958, where the Boursobank Gocardless was introduced.
This PR addresses two comments made on the original PR:
- The payee name for transfers wasn't read properly (caused by a non-deterministic order of the transaction details array)
- Adding the date for card transactions in the notes
This PR also introduces enhanced transaction parsing:
- Removing unwanted parts of the transaction name
- Identifying a credit note / refund on the account

Improve Boursobank Gocardless transaction parsing

---

packages/loot-core/src/server/transactions/import/ofx2json.ts
upcoming-release-notes/5203.md

Reported on Discord, the bank provides a QFX with `<OFX >` instead of `<OFX>` as the opening tag, breaking our parsing.
It's not technically compliant with the standard, but it doesn't hurt to support it

improve compatibility with OFX/QFX files

---

packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
packages/desktop-client/src/components/modals/AccountMenuModal.tsx
packages/desktop-client/src/components/reports/reports/Calendar.tsx
packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
packages/desktop-client/src/modals/modalsSlice.ts
upcoming-release-notes/4809.md

Reverts actualbudget/actual#4809
The mobile running balance change has some issues that weren't caught originally:
1. accounts with many transactions load really slow now.  Maybe moving the calculation out of TS and into sql would speed this up.
2. Accounts with many transactions don't get summed up correctly.  This is because the transactions are loaded in pages, so each set of pages is summed within each batch, not all account transactions.
3. Some transactions don't get a balance and I don't know why.  Something to do with transfers it seems

Revert "Mobile running balance"

---

packages/sync-server/src/app-gocardless/banks/raiffeisen_at_rzbaatww.js
packages/sync-server/src/app-gocardless/banks/tests/raiffeisen_at_rzbaatww.spec.js
upcoming-release-notes/5244.md

Added a gocardless bank parser for Raiffeisen Bank Austria.
This is an update to PR #4776 which was closed due to inactivity.

Added a gocardless bank parser for Raiffeisen AT bank

---

packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
packages/desktop-client/src/components/util/AmountInput.tsx
packages/loot-core/src/shared/util.ts
upcoming-release-notes/5220.md

Fixes #5218
This ensures that the input going into `appendDecimals` is not malformed when the  `hideFraction` option is On, otherwise when hitting delete on the text `"1,234,567"`, it will result in the text `"1,234,56"` which the formatter will parse as `1234.56`. This doesn't happen when `hideFraction` is off since hitting delete on the text `"12,345.67"` results in `"12,345.6"`, which `appendDecimals` will happily handle in a separate case to provide `"12345.6"` as the input into `currencyToAmount`.

fix: reapply thousand separators before passing input to appendDecimals

---

packages/desktop-client/src/components/settings/BudgetTypeSettings.tsx
upcoming-release-notes/5253.md

Fix switching budget type requiring hard reload to take effect

---

packages/desktop-client/src/components/filters/FiltersMenu.jsx
packages/desktop-client/src/components/util/GenericInput.jsx
upcoming-release-notes/5263.md

When quickly typing into the filter input and pressing Enter, the entered value was not always correctly applied. Sometimes it resulted in an empty filter being created. In my test it ocurred for other types of filters as well, not only for "has tag(s)".
Updated the GenericInput component to add onChangeValue={onChange}, as suggested by @mauschil. Changed the defaultValue to value.
Now, however quickly you type a filter name and press Enter, your inputted value is correctly applied.

Fixes #5228 - has tag(s) filter now takes values when pressing Enter

---

packages/loot-core/src/server/rules/index.ts
upcoming-release-notes/5259.md

Fixes #5258 
Long story short, the "set" rule set a Date object to the transaction instead of a "yyyy-MM-dd" string.  
Causing a crash when calling `parseISO(date)` in the `serializeTransaction` function.

Fix rule templating on date causing crash

---

packages/desktop-client/src/components/transactions/TransactionsTable.tsx
upcoming-release-notes/5207.md

Fixes https://github.com/actualbudget/actual/issues/5170
It's easier to use the right balance than it is to completely hide it. I can probably work round it if we prefer that, but this is better than the current version.

use correct running balance when adding a new transaction

---

packages/desktop-client/src/components/budget/envelope/EnvelopeBudgetComponents.tsx
packages/desktop-client/src/components/settings/Currency.tsx
packages/desktop-client/src/components/settings/Experimental.tsx
packages/desktop-client/src/components/settings/Format.tsx
packages/desktop-client/src/components/settings/Themes.tsx
packages/desktop-client/src/components/settings/UI.tsx
packages/desktop-client/src/components/settings/index.tsx
packages/desktop-client/src/components/spreadsheet/CellValue.tsx
packages/desktop-client/src/components/util/PercentInput.tsx
packages/desktop-client/src/hooks/useFeatureFlag.ts
packages/desktop-client/src/hooks/useFormat.ts
packages/loot-core/src/shared/arithmetic.ts
packages/loot-core/src/shared/currencies.ts
packages/loot-core/src/shared/util.ts
packages/loot-core/src/types/prefs.ts
upcoming-release-notes/5167.md

This PR introduces the currency setting and the display in the useFormat hook.
I put the currency select into an experimental feature. For now I disabled YEN as currency, as this will not work at the current state (later PRs will fix this).
This is a part of multiple PRs to start intoducing a currency to the budget-file and display it. 
The full implementation can be seen here: https://github.com/actualbudget/actual/pull/4890

feat(currency): add currency setting and format

---

packages/desktop-client/src/components/HelpMenu.tsx
packages/desktop-electron/menu.ts
upcoming-release-notes/5286.md

Adding discord link into help menu so users can more easily find it. 
Some users will be coming from the app store/main website and wont realise we have community support via discord. This should make them more aware of it.

💬 Added Discord link to the help menu for discoverability

---

packages/loot-core/src/server/transactions/transfer.ts
upcoming-release-notes/5279.md

Implements #5154: running rules on transactions created by a transfer, until now when you manually or automatically create a transfer transaction the rules are only applied to the original transaction, not the transaction created by the transfer on the other account.
I implemented this, but only for the fields `notes` and `cleared` because if other fields were changed then the transactions from the transfer would not have the same/complementary information anymore (e.g. changing the payee/amount/...). 
What I didn't add is tests in the `transfer.test.ts` file because the rules are already tested in `transaction-rules.test.ts` but if that's needed there as well, I can add it.
I hope I did everything right in the code / in the pr because this is my first time with Typescript and with …

Run rules on transactions created by a transfer.

---

packages/component-library/src/ColorPicker.tsx
upcoming-release-notes/5335.md

I the original PR I replace `'""'` by `'‘’'` to fis eslint issue but it broke emotion/css, my bad
See: https://discord.com/channels/937901803608096828/1027831756545609789/1393967029689778336
And https://github.com/emotion-js/emotion/issues/1435#issue-469332317

fix pseudo-element quotes in ColorPicker

---

packages/sync-server/src/app-gocardless/banks/boursobank_bousfrppxxx.js
packages/sync-server/src/app-gocardless/banks/tests/boursobank_bousfrppxxx.spec.js
upcoming-release-notes/5344.md

I wrongly thought that all the card transactions will always have their first line with the `CARTE` identifier. But as I have seen recently, it's not the case, and we shouldn't rely on the ordering of the array returned by the Boursorama GoCardless integration.
Thus, check for transaction patterns in all of the lines of the unstructured array.
This addresses a true case (added in test) where the payee name was wrongly extracted as being `110,04 Gbp / 1 Euro = 0,860763454`.

Fix Boursorama GoCardless transaction ordering

---

packages/desktop-client/src/components/CommandBar.tsx
upcoming-release-notes/5348.md

Adds the following items to the Command Bar:
- Navigation
- All Accounts (redirects to `/accounts`)
- Accounts
- On Budget (redirects to `/accounts/onbudget`)
- Off Budget (redirects to `/accounts/offbudget`)
The library icon is used instead of the piggy bank, to indicate a multi/aggregated acct view vs a single acct view.
Resolves #5339

feat(CommandBar): add aggregated acct views

---

packages/desktop-client/src/components/modals/KeyboardShortcutModal.tsx
upcoming-release-notes/5340.md

Improve the keyboard shortcuts modal by making it searchable and more extendable. This should make it easier in future to allow the user to rebind their shortcuts.
Have gotten some community feedback here: https://discord.com/channels/937901803608096828/1389677350215618623/1396402979350908958
**Demo:** 
**The new modal would replace this:** 
- It's unsearchable
- It's large and will only going to get larger as new shortcuts are added
- It would be difficult to extend it to allow users to rebind their shortcuts

:keyboard: Enhanced keyboard shortcuts modal

---

packages/loot-core/src/server/budget/cleanup-template.ts
upcoming-release-notes/5377.md

When using local group cleanup, currently all funds available in To Budget are distributed into the sinks. This behaviour seems somwhat odd and also results in all later groups or the "global" cleanup run to possibly have no funds as they've been distributed before.
This patch now changes the group usage of cleanup, to only distribute funds made available by the group itself. If one also wants to sink money from To Budget into the category, a simple addtional `#cleanup sink`, will achieve this.
Fixes #5374

Only use fund from local group during cleanup.

---

packages/desktop-client/src/components/payees/PayeeTableRow.tsx
packages/desktop-client/src/components/tags/ManageTags.tsx
packages/desktop-client/src/components/tags/TagRow.tsx
packages/desktop-client/src/queries/queriesSlice.ts
packages/desktop-client/src/style/tags.ts
packages/loot-core/src/server/db/index.ts
packages/loot-core/src/server/tags/app.ts
upcoming-release-notes/5368.md

I guess everything is in the title :D
Adds a button in the "tags" page to import/extract existing tags from notes.

Add button to import existing tag from transactions notes

---

packages/desktop-client/src/components/sidebar/Account.tsx
upcoming-release-notes/5362.md

This is an addition to my previous PR #5352 that only checks the hover media query:
```ts
window.matchMedia('(hover: none)').matches
```
but this does not work for some touchscreen devices (i.e. newer Samsung phones/tablets)
however this does work
```ts
window.matchMedia('(pointer: coarse)').matches
```
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer#coarse

[Enhancement] Disable Sidebar Tooltip on Touchscreen Device

---

packages/desktop-client/src/components/accounts/Reconcile.tsx
upcoming-release-notes/5373.md

When just loading a page the reconcile button doesn't select the amount. The second time you click it does. This makes it work for the first click

fix: reconcile select number on click

---

packages/desktop-client/src/components/select/DateSelect.tsx
upcoming-release-notes/5423.md

This change is related to #5095.
Fixes #5304

fix crash when enter is used to submit empty date in date picker

---

.github/actions/ai-generated-release-notes/comment-on-pr.js

This has caused some confusion, as the bot isn't able to push to the branch yet. I've left the other comment in there so that we can change it back once we get a solution sorted but this should clarify the message for now.
Despite the change, I don't think we need a release note for this one 😅

clarify ai generated release note comment

---

.github/scripts/count-points.mjs

1) Reviewers of release PRs created by the bot were being credited for the review.
https://github.com/actualbudget/actual/actions/runs/16696074125/job/47260378227
> matt-fidd: 24 (PRs: ... #5272 (2pts) ...)
2) Release regex too strict to consider below PR title as release
https://github.com/actualbudget/docs/pull/740

improvements to release PR points counting logic

---

packages/desktop-client/src/style/tags.ts
upcoming-release-notes/5457.md

Fixes https://github.com/actualbudget/actual/issues/5463
First reported in Discord
https://discord.com/channels/937901803608096828/1273368072555729098/1401321211291631728
Reproduction instructions:
1) Set system to light theme
2) Set theme in actual to "system default"
3) Observe that tags use the dark mode colourings instead of light

fix tag colors when using the light theme as system default

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/5460.md

Fixes https://github.com/actualbudget/actual/issues/5367

make payeeName fall back to default if the custom mapped bank sync field is missing

---

.github/workflows/docker-edge.yml
upcoming-release-notes/5404.md

I can understand not wanting to auto-trigger Docker builds on forks on schedule or whenever a push to master or a pull request is made *but* I think there's no reason to limit the ability for the fork owner to trigger a build manually through a workflow dispatch. As long as we exclude the push to DockerHub (which, unlike GitHub Packages, requires credentials not auto-generated by GH Actions), it can work just fine.

Allow Docker image build by workflow dispatch on forks

---

packages/desktop-client/e2e/help-menu.test.ts
packages/desktop-client/src/components/rules/RuleRow.tsx
packages/loot-core/src/shared/rules.ts
upcoming-release-notes/5421.md

This PR adds internationalization support for rule stage labels in the rules interface
Fixes #5338 
problematic test log : 
```
[chromium] › e2e/help-menu.test.ts:33:7 › Help menu › Check the keyboard shortcuts modal visuals 
Test timeout of 60000ms exceeded.
Error: locator.click: Target page, context or browser has been closed
Call log:
- waiting for getByRole('button', { name: 'Help' })
32 |
33 |   test('Check the keyboard shortcuts modal visuals', async () => {
> 34 |     await page.getByRole('button', { name: 'Help' }).click();
|                                                      ^
35 |     await page.getByText('Keyboard shortcuts').click();
36 |
37 |     const keyboardShortcutsModal = page.getByRole('dialog', {
```

Fix translate rule stages

---

packages/desktop-client/src/components/budget/SidebarGroup.tsx
packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
packages/desktop-client/src/components/reports/SaveReport.tsx
upcoming-release-notes/5396.md

This PR updates the UI to add missing translations for several user-facing texts, including :
"Show" / "Hide" in category group menus
"Delete" in modals
"Unsaved report" in the reports section

Fix missing translations

---

packages/component-library/src/SpaceBetween.tsx
packages/desktop-client/src/components/sidebar/Account.tsx
packages/loot-core/src/types/prefs.ts
upcoming-release-notes/5452.md

Improving the balance graph in side nav by making it less intrusive - ability to toggle it on/off per account. By default it is off.
Let me know if you have any feedback and/or thoughts.

feat: show/hide balance graph in side nav

---

packages/desktop-client/src/components/reports/Header.tsx
packages/desktop-client/src/components/reports/reportRanges.ts
upcoming-release-notes/5495.md

Fixes https://github.com/actualbudget/actual/issues/3988
I'm not sure what this if statement was originally in there to catch, but I'd imagine it was because the one month window was using a positive offset instead of 0.

fix live report date mode not supporting a 2 month window

---

packages/desktop-client/src/components/modals/EditRuleModal.jsx
packages/desktop-client/src/components/reports/DateRange.tsx
packages/desktop-client/src/components/reports/ReportSidebar.tsx
packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
packages/desktop-client/src/components/rules/ActionExpression.tsx
packages/desktop-client/src/components/rules/RuleRow.tsx
packages/desktop-client/src/components/rules/Value.tsx
packages/loot-core/src/shared/rules.ts
upcoming-release-notes/5486.md

The UI elements for custom reports and rule configurations were not displaying correctly due to missing or improperly applied translations.
- Replaced static `ALLOCATION_METHODS` with a dynamic `getAllocationMethods` function and translated its values.  
- Updated `actionFields` and `splitActionFields` to use dynamic functions (`getActionFields` and `getSplitActionFields`). ( Fixes #5466 )  
- Added translations for "Apply to all" / "Split xx" on the Rules page.  
- Added translations for date input fields in the Custom Report edit view.  
- Added translations for "this month" / "all time" on the Reports page.  
- Added translations for "budgeted" and "average" on the monthly spending card.

Fix translate custom report and rule

---

packages/desktop-client/src/components/accounts/Reconcile.test.tsx
packages/desktop-client/src/components/accounts/Reconcile.tsx
upcoming-release-notes/5528.md

Purpose: Fix incorrect mathematical equation calculations in the
reconcile window (Bug #5527)
Key Changes:
1. Fixed arithmetic evaluation in Reconcile.tsx:155-163:
- Replaced currencyToInteger() with proper arithmetic evaluation using
evalArithmetic()
- Added amountToInteger() for correct amount conversion
- Now properly evaluates mathematical expressions (e.g.,
"100+25.50-10") instead of treating them as literal strings
2. Added comprehensive test coverage in Reconcile.test.tsx:
- 231 lines of new tests covering reconciliation math scenarios
- Tests for positive/negative differences, arithmetic expressions, edge
cases
- Validates that reconciliation amounts are correctly calculated and
passed
Impact: Users can now enter mathematical expressions in reconcile inputs
and have them properly …

[BUG] Fix incorrect mathematic calculation in reconcile window

---

packages/component-library/src/View.tsx
packages/desktop-client/src/components/rules/RuleEditor.tsx
upcoming-release-notes/5529.md

Split off from: https://github.com/actualbudget/actual/pull/5516
Originally broken due to: https://github.com/actualbudget/actual/pull/5489
Before:
After:

Fix display of link schedules condition

---

packages/desktop-client/src/components/budget/goals/BudgetAutomation.tsx
packages/desktop-client/src/components/budget/goals/actions.ts
packages/desktop-client/src/components/budget/goals/editor/HistoricalAutomation.tsx
packages/desktop-client/src/components/budget/goals/reducer.ts
packages/desktop-client/src/components/modals/BudgetAutomationsModal.tsx
packages/loot-core/migrations/1754611200000_add_category_template_settings.sql
packages/loot-core/migrations/1754611200000_add_category_template_source.sql
packages/loot-core/src/server/aql/schema/index.ts
packages/loot-core/src/server/budget/app.ts
packages/loot-core/src/server/budget/category-template-context.test.ts
packages/loot-core/src/server/budget/category-template-context.ts
packages/loot-core/src/server/budget/goal-template.ts
packages/loot-core/src/server/budget/schedule-template.test.ts
packages/loot-core/src/server/budget/statements.ts
packages/loot-core/src/server/budget/template-notes.test.ts
packages/loot-core/src/server/budget/template-notes.ts
packages/loot-core/src/server/db/types/index.ts
packages/loot-core/src/types/models/category.ts
packages/loot-core/src/types/models/templates.ts
upcoming-release-notes/5532.md

My current migration plan is:
1. Roll out automations UI and let users opt in on a per-category basis. In a future PR I'll add a "migration" modal for both directions; for now notes-based templates will get displayed in the UI, and if you hit 'Save' they are converted to UI automations.
2. At some point in a future release once we have full support in the UI and expect most users have migrated to the UI, remove the ability to populate notes-based templates during application. This means effectively you can't create notes-based templates and can only migrate them to the UI. We could potentially release both experimental features at this point.
3. At some point far in the future, remove the ability to migrate. At this point anyone with unmigrated notes-based templates will need to upgrade …

Add backend logic to support automations UI

---

packages/desktop-client/src/components/mobile/accounts/AccountTransactions.tsx
packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.tsx
packages/desktop-client/src/hooks/useAccountPreviewTransactions.ts
packages/desktop-client/src/hooks/useCategoryPreviewTransactions.ts
packages/desktop-client/src/hooks/usePreviewTransactions.ts
packages/desktop-client/src/hooks/useTransactions.ts
upcoming-release-notes/5415.md

Fix reverted changes on some hooks (could be due to incorrect rebase/merge), this PR aims to fix that + a change on the loading experience on mobile to display transactions as they load.
Meaning, normal transactions would be displayed even when the preview transactions are not yet loaded, and display the preview transactions as they load (a loading indicator would be displayed to indicate the preview transactions are still being loaded). This should improve the user experience because the preview transactions are slower to load than the normal transactions.

Fix transaction hooks and improve transactions loading experience in mobile

---

eslint.config.mjs
packages/desktop-client/src/components/FixedSizeList.tsx
packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
packages/desktop-client/src/components/filters/FiltersMenu.jsx
packages/desktop-client/src/components/filters/PayeeFilter.tsx
upcoming-release-notes/5438.md

The `GenericInput` component automatically filters transfer payees from closed accounts.
This behavior is desirable  when payees to be selected must exist (e.g. set the payee of a transaction) but less so when you want to filter on a transfer payee from a closed account.
I decided not to "hack" this into the existing `GenericInput` component but create a `PayeeFilter` component. Hacking it into the `GenericInput` component would've required prop drilling from `FiltersMenu` into the `GenericInput` to the `PayeeAutocomplete` component. Adding yet another property to the `GenericInput` which is only meant for **one** type, as already done with the `multi` property which is only relevant for autocomplete.
This PR also contains the slight refactoring of `filterActivePayees` to extract logic …

fix filter transactions by closed account transfer payee

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/codeql.yml
.github/workflows/update-vrt.yml
upcoming-release-notes/5586.md

Enhance CI workflows to support repository dispatch events and improve branch handling
- Added support for `repository_dispatch` events in build, check, and codeql workflows.
- Updated concurrency group to include `client_payload.pr_number` for better context.
- Modified checkout steps to reference the correct branch from `client_payload` if available.
**Important:** I have not actually fully tested this. In theory - I think it will work. But if it fails after merging (because we need to merge to test it.. and I'm a bit lazy in terms of creating a fork and all that stuff..) - I will simply roll back this PR.

Dispatch github ci jobs after running update-vrt workflow

---

packages/desktop-client/src/components/transactions/TransactionsTable.tsx
upcoming-release-notes/5634.md

The transactionError modal was displaying its content across two lines due to insufficient width constraints.
- Updated the `style` property of the modal to set `maxWidth` and `minWidth`.
- Added `whiteSpace: 'nowrap'` to the `Text` component inside the `TransactionError` to ensure the text remains on a single line.
- Create a split transaction.
- Modify the transaction value so that the amount is less than the total value.
- Confirm that the modal's width adjusts within the defined constraints.
|from|to|
|--|--|
| <img width="684" height="111" alt="Capture d’écran 2025-08-24 à 11 27 45" src="https://github.com/user-attachments/assets/cd2de29e-f5da-4727-a83f-785641b28305" /> | <img width="684" height="327" alt="Capture d’écran 2025-08-24 à 11 29 00" …

[fix] Adjust modal styles and text wrapping in TransactionError

---

packages/desktop-client/src/components/budget/MonthPicker.tsx
upcoming-release-notes/5622.md

Fixes #5621 
There's a weird behavior I can't seem to pinpoint with `monthUtils.subMonth` and float values, where sometimes the subtraction matches the result's ceiling, and other times it matches its floor, which I suspect is related to date-fns/date-fns#4061. In the meantime, I've simply made the operation always return the result's floor, in order to make the behavior predictable.
Example:
`monthUtils.subMonths('2023-01', 4)` = 2022-09
`monthUtils.subMonths('2023-01', 4.5)` = 2022-09
`monthUtils.subMonths('2024-11', 4)` = 2024-07
`monthUtils.subMonths('2024-11', 4.5)` = 2024-06

Fix range calculator on the MonthPicker component

---

packages/desktop-client/src/components/reports/Header.tsx
packages/desktop-client/src/components/reports/ReportSidebar.tsx
packages/desktop-client/src/components/reports/getLiveRange.ts
packages/desktop-client/src/components/reports/reportRanges.ts
packages/desktop-client/src/components/reports/reports/Calendar.tsx
packages/desktop-client/src/components/reports/reports/CashFlow.tsx
packages/desktop-client/src/components/reports/reports/CustomReport.tsx
packages/desktop-client/src/components/reports/reports/CustomReportListCards.tsx
packages/desktop-client/src/components/reports/reports/GetCardData.tsx
packages/desktop-client/src/components/reports/reports/NetWorth.tsx
packages/desktop-client/src/components/reports/reports/Spending.tsx
packages/desktop-client/src/components/reports/reports/Summary.tsx
packages/loot-core/src/server/transactions/app.ts
packages/loot-core/src/shared/months.ts
upcoming-release-notes/5753.md

Fixes https://github.com/actualbudget/actual/issues/5310
Adding a `get-latest-transaction` function to extend end dates in reports beyond today.

feat(reports): extend report end date to the latest transaction date

---

packages/api/methods.ts
upcoming-release-notes/5758.md

This allows previewing imported transactions ahead of importing. This is useful for import scripts like https://github.com/lunchflow/actual-flow, where the users will preview the transactions ahead of the import then confirm.
The name `isPreview` wasn't very self explanatory, so I'm proposing `dryRun`, similar to what's used in AWS CLI ([example](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html#options)), but open to feedback on this 😄 I also didn't rename across the board to keep the PR focused, but happy to do so as well.

add a 'dryRun' option to transactions import API

---

packages/desktop-client/src/components/transactions/TransactionsTable.tsx
upcoming-release-notes/5777.md

Translated  ‘(No payee)’ for a scheduled transaction

[WIP] [FIX] Translate Schedule '(No payee)'

---

packages/desktop-client/src/components/reports/reportRanges.ts
packages/desktop-client/src/components/reports/reports/Calendar.tsx
packages/desktop-client/src/components/reports/reports/CalendarCard.tsx
packages/desktop-client/src/components/reports/reports/CashFlow.tsx
packages/desktop-client/src/components/reports/reports/CashFlowCard.tsx
packages/desktop-client/src/components/reports/reports/NetWorth.tsx
packages/desktop-client/src/components/reports/reports/NetWorthCard.tsx
packages/desktop-client/src/components/reports/reports/SpendingCard.tsx
packages/desktop-client/src/components/reports/reports/Summary.tsx
packages/desktop-client/src/components/reports/reports/SummaryCard.tsx
upcoming-release-notes/5790.md

Fixes https://discord.com/channels/937901803608096828/1389677350215618623/1420520966295126036
This was a balance between retaining the existing behaviour and keeping the changes from https://github.com/actualbudget/actual/pull/5753. I settled on this way because I imagine most people will not add transactions in future months, so they wouldn't see a difference. If you do though, the ranges will push on to the month with the furthest ahead transaction in it, which I can only assume is what you wanted if you added transactions to them.
WDYT? We could also just revert the behaviour so the live ranges just push to the current month and ignore the future transactions but IMO that would go against https://github.com/actualbudget/actual/pull/5753.

fix live report time ranges

---

.github/scripts/count-points.mjs
upcoming-release-notes/5791.md

Fixes https://github.com/actualbudget/actual/actions/runs/17410800211/job/49427250454#step:4:8
Also ups concurrency limit, 50 should be safe and helps to speed it up.

replace deprecated function in count points script

---

packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
upcoming-release-notes/5817.md

The indexes assigned were not being generated in the same order as it is rendered, that was messing up the hover indexes when the list was filtered and changed order

fix payee autocomplete hovering randomly

---

packages/desktop-client/src/components/manager/ManagementApp.tsx
packages/desktop-client/src/components/modals/CreateAccountModal.tsx
packages/desktop-client/src/components/modals/LoadBackupModal.tsx
packages/desktop-client/src/components/payees/ManagePayees.tsx
packages/desktop-client/src/components/reports/reports/NetWorth.tsx
packages/eslint-plugin-actual/lib/rules/no-untranslated-strings.js
packages/eslint-plugin-actual/lib/rules/prefer-logger-over-console.js
packages/eslint-plugin-actual/lib/rules/prefer-trans-over-t.js
packages/eslint-plugin-actual/lib/utils/import-helpers.js
upcoming-release-notes/5827.md

Expands the rule to look at JSX attributes and adds fixers, also adds an abstraction for importing modules in fixers.
JSX attribute strings are pretty hard to properly identify, so to be safe and catch the low-hanging fruit I've added a whitelist so we don't start messing with function arguments or properties used for rendering instead of user-facing etc...

expand eslint untranslated string rule

---

packages/desktop-client/src/components/transactions/TransactionsTable.tsx
upcoming-release-notes/5807.md

Fixes https://github.com/actualbudget/actual/issues/3294
Transaction amount was being updated even when `debit` and `credit` are not specifically updated. This is not a problem in general but when decimals are hidden now the serialized transaction is missing decimals. So if we don't use original amount, it also removes the decimals on any update, such as changing notes, cleared, etc.

fix: losing transaction amount decimals on update

---

packages/api/utils.js
packages/api/utils.ts
packages/loot-core/src/server/importers/ynab4.ts
upcoming-release-notes/5747.md

Updates api amount conversion utilities to use the loot-core versions.
- Removed duplicate implementations: Deleted the local amountToInteger and integerToAmount function implementations
- Added re-exports: Used a single export statement to re-export both functions from the loot-core module
- Maintained API compatibility: The public API remains exactly the same - consumers of this module won't need to change anything

Align amount conversion utilities between api and loot-core

---

packages/desktop-client/src/components/mobile/payees/MobilePayeesPage.tsx
packages/desktop-client/src/components/mobile/payees/PayeesList.tsx
packages/desktop-client/src/components/mobile/payees/PayeesListItem.tsx
packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
packages/desktop-client/src/components/payees/PayeeRuleCountLabel.tsx
packages/desktop-client/src/hooks/usePayeeRuleCounts.ts
upcoming-release-notes/5842.md

Added a loading indicator to the rules count label.
Also extracted the rules-count fetching logic into a reusable hook and implemented it in all the necessary places.

Mobile payees - add loading indicator to rules count label

---

packages/loot-core/src/server/transactions/transaction-rules.ts
upcoming-release-notes/5870.md

Fixes https://github.com/actualbudget/actual/issues/5868
Test budget:
[post-early.zip](https://github.com/user-attachments/files/22725227/post-early.zip)
1. Go to Bank of America
2. Post the Dominion Power split schedule today
On edge, it does not split. On this deploy, it does.

run schedule rules regardless of posted date

---

packages/plugins-service/bin/build-service-worker
upcoming-release-notes/5878.md

Fix for plugin service worker not being found

🐛 Fix for worker in dev mode
