actualbudget/actual

package.json

Noticed some fields were added to package.json in #1 and added a missing comma that was causing `yarn install` to fail. 
Cool that this project is open source :)

Add missing comma in package.json

---

packages/desktop-client/src/components/Settings.js
packages/desktop-client/src/components/manager/Modals.js
packages/loot-core/src/platform/client/fetch/index.web.js
packages/loot-core/src/platform/server/connection/index.electron.js
packages/loot-core/src/platform/server/fs/index.web.js
packages/loot-core/src/server/cloud-storage.js
packages/loot-core/src/server/main.js
packages/loot-design/src/components/manager/Import.js
packages/loot-design/src/components/manager/ImportActual.js

This PR does a few things, but the two main things it enables are:
* Exporting data as a compressed zip file on the desktop app. This was already available on the web app, but due to limitations of the IPC used by the desktop app it hadn't been enabled yet.
* Allows importing of these compressed zip files that Actual exports. Clicking "import file" will show a list of file types to import that now includes Actual.
These compressed files are just zip files containing two files: a `db.sqlite` and `metadata.json`. If you are using the desktop app, you can see these two files locally by opening up a budget file in your local Actual directory. All it does it zip them up.
As you can see in the PR, there were several annoying bugfixes required for this which is why it took a while to get this …

Add ability to import Actual files; enable export on desktop

---

packages/import-ynab4/package.json
packages/import-ynab5/package.json

The `package.json` files for the importer packages haven't been updated and so are pointing at the old repositories. If we're moving to a monorepo model, the packages should point towards this repository (and probably archive the old repositories).

Update importer packages `package.json` to point to monorepo

---

packages/desktop-client/jest.config.js

We're missing a comma in this file which makes the `module.exports` invalid.

Add missing comma to jest.config.js

---

.circleci/config.yml

There's a few formatting errors in the circleCI config which vscode automatically fixes on save. This PR performs these changes to avoid noise in diffs which make meaningful changes to this file.

Fix yaml formatting in CI config

---

bin/package-browser
packages/loot-core/bin/build-browser
packages/loot-core/bin/build-mobile

Running `package-browser` on Linux gets me the error:
```
bin/package-browser: 9: Syntax error: "(" unexpected
```
This appears to be due to the fact that [the shebang specifies `sh`](https://unix.stackexchange.com/a/253900) whereas the other scripts use bash. Switching the shebang to match the other files fixes this issue.

Fix some errors caused by using `bash` syntax with `sh` shebang

---

.github/actions/setup/action.yml
.github/workflows/build.yml
.github/workflows/lint.yml
bin/package
bin/package-browser
packages/desktop-electron/afterSignHook.js
packages/desktop-electron/package.json

Builds on top of #53, #55 and #72 as they all fix issues which causes the CI build to blow up.
This PR adds a github workflow which checks that running the steps in [releasing.md](https://github.com/actualbudget/actual/blob/master/docs/releasing.md) succeeds and that we can build the electron app on linux/mac/windows platforms.
This also includes some small changes to `bin/package` and `bin/package-browser` to avoid performing linting in CI but it shouldn't affect usage from the CLI.

Add a CI workflow to perform builds of api, web and electron packages

---

packages/loot-design/package.json
packages/loot-design/patches/downshift+1.31.16.patch
yarn.lock

There seems to be patched dependency which was missed out from #55 and is currently causing #50 to fail in CI.
I've updated the patch for this package to match the version which is referenced in the lock file.

Update downshift patch to match installed version

---

packages/loot-design/src/components/modals/ImportTransactions.js
packages/loot-design/src/components/modals/ImportTransactions.test.js

Addresses issue #116 by adding new regexes to meet the currently available formats. If anyone has additional test cases to suggest that would be swell.

Fix: parse dates without a delimiter in CSV import

---

package.json
packages/loot-core/package.json
packages/loot-core/src/shared/util.js
packages/loot-core/src/shared/util.test.js
packages/loot-design/src/components/modals/SelectLinkedAccounts.js
packages/mobile/package.json
yarn.lock

Closes #90 
1. The babel transform to CommonJS for Jest (as I understand it) was failing. Seemed to be due to shifting deps versions, and bumping `@babel/plugin-transform-modules-commonjs` addressed it.
2. And of course, removed `currency-formatter`
Switch to `en-ZA` as our example locale for `space-comma`.
(`za-ZA` does not exist. Might have been a typo for `zu-ZA`, but that is a `comma-dot` locale, to use Actual notation.)
Is [this the best way](https://github.com/actualbudget/actual/pull/94/files#diff-6f58f196a7aadd917737fb14e3a029efc67613f24c081bfed8d4c6433c6b308fR288-R289) to fix to 2 decimal places? 
* Usually, the `currency` param to `NumberFormat` would dictate the `minimumFractionDigits`/`maximumFractionDigits` values, but we're avoiding setting a specific currency (along with …

currency-formatter -> Intl.NumberFormat

---

docs/Building-for-Windows.md
packages/loot-core/package.json

This pull updates patches for the latest version of dependencies, fixes npm scripts to run on windows, fixes a logic error when running `loot-core/bin/build-browser` for the first time in development mode, and creates a doc page for how to get the build to work on Windows with Git Bash.

Building for Windows

---

package.json
yarn.lock

This PR https://github.com/actualbudget/actual/pull/132 replaced `jwl-dev-utils` with `react-dev-utils` and used a much greater major version. This broke the react error overlay feature; when developing and something goes wrong, instead of seeing the error overlay you don't see anything, and the app feels "locked up" but there's really a transparent div covering the whole screen.
There's an error in the console: `process in not defined`. After some research, looks like we need to lock `react-error-overlay` to a specific version. This fixed it for me. I don't love it, but maybe we can move off this whole build stack at some point.
r? @TomAFrench

Force react-error-overlay to 6.0.9 to fix error

---

packages/desktop-client/config/webpack.config.js

This removes the bogus warning for us not having moment.js installed which pikaday throws if it can't find it.
https://github.com/Pikaday/Pikaday/issues/815

Silence warning for missing moment.js install

---

packages/desktop-client/src/components/manager/subscribe/ConfirmPasswordForm.js

Closes #29 
- At the bootstrap page, when the user sets the password and press enter or even when the password field is empty, he is redirected to the demo page.
- I used the "onEnter" prop from the Input component to trigger the "onSubmit" function whenever the user presses enter within both password input fields.
- The user is redirected to the demo page after pressing enter.
[old-screen-record](https://user-images.githubusercontent.com/71379045/177626271-5ba29253-4c4b-477c-ba1f-c51b7fc265ca.webm)
- In this screen record i fill the password fields and then i press enter. The page demo is launched.
- The user is redirected to the files page after pressing enter.
[new-screen-record](https://user-images.githubusercontent.com/71379045/177625445-fda04a4f-271f-4c1c-bf5d-63d203bfacf5.webm)
- …

fix: hitting enter after setting password redirects to demo page

---

.github/workflows/opened-issues-triage.yml

This adds an action to mark new issues with a `needs triage` label on creation (We'd need to create this label as well).
Motivation for this being that we'd remove this label once the issue has been assessed so new issues won't fall through the cracks.

Add action to mark new issues for triage

---

packages/loot-core/package.json
yarn.lock

Using yarn 3.2.0 and node 16.15.0, I'm getting failures on `yarn install` related to the fix commit we depend on for `adm-zip`:
Could be something specific to me, but I figure let's bump this package to match [the version used in actual-server](https://github.com/actualbudget/actual-server/blob/master/package.json#L17), which resolves the error for me locally.

Fix adm-zip install failure

---

packages/loot-design/package.json
yarn.lock

We no longer have any patches in loot-design so we don't need to call it in the package's context

Remove patch-package dependency from loot-design

---

packages/loot-design/src/components/budget/rollover/BudgetSummary.js

Fix handling of -0 in budget summary

---

packages/desktop-electron/package.json
packages/import-ynab4/package.json
packages/import-ynab5/package.json
packages/loot-core/package.json
yarn.lock

#204 causes `bin/package-browser` to take 30mins or so to complete which is unacceptably long. It's most likely due to the weird circular dependencies we have.
I'm reverting this change while we fix this.

Revert change to use the importers from inside the monorepo

---

packages/desktop-client/src/components/accounts/TransactionsTable.js

This addresses #226
Currently only the `credit`/`debit` columns can be focused to press enter and add a transaction, but if you tab past them to the `cleared` column it stands to reason you'd want to add it at that point too.

Allow `enter` to create new transaction when focused on `cleared` column

---

packages/loot-design/src/components/modals/CloseAccount.js

Actual generally omits currency symbols so that it's currency agnostic, however we display a $ when closing an account.
This PR removes this $ symbol for consistency.

Remove dollar sign from close account modal

---

packages/desktop-client/src/components/modals/ManageRules.js

This bug has been around for a while and I finally tracked it down. The fix is small, but requires understanding several important things:
* When an item is deleted, several other items may be pointing to it. In several cases, we allow changing this pointer. One case is when you merge payees; we delete all but 1 payee, and change the pointers of all of the deleted ones to the final one. Everything else in the system that uses payees will automatically be linked to the final payee (if any of the merged payees was used)
* To do this, we have "mappings" tables with two columns: one id of the real item, and a second id of the item it "points" to. When querying for items, we _always_ need to join through this table. This is only needed for categories and payees (I think?), and it's …

Render a schedule rule with the mapped payee id; fixes crash

---

packages/loot-design/src/components/sidebar.js

This PR adds a help button to the menu and directs the user to the community documentation at https://actualbudget.github.io/docs
The URL is opened in a new tab in the browser.

Add a help button to the menu

---

packages/loot-design/src/components/common.js
packages/loot-design/src/components/modals/CreateLocalAccount.js

This is a small fix.
Right now, it seems like an attempt was made to insert a hidden button. This **does not work** on my computer (Safari 16.1).
The correct fix as I understand it is to mark non-submit buttons as `type="button"`.
I've searched the codebase and only found one form button that needs to be modified.

Fix enter to create accounts

---

packages/import-ynab4/package.json
packages/import-ynab5/package.json
packages/loot-core/src/platform/server/connection/index.electron.js
yarn.lock

This should fix the importers.
The issue is something that @TomAFrench pointed out in https://github.com/actualbudget/actual/pull/204. The API package should definitely never be pulled from npm. It should always be required from the workspace, and the way it works is the backend "injects" the ability for the API to send messages directly to the backend. It does this by importing the module and mutating internal state.
If something like the importer ends up pulling the API package from npm instead of the workspace, it won't know how to talk to the backend. When running outside the app, it works differently and knows how to communicate across a socket.
The issue is currently the importers depend on `@actual-app/api` version `^1.0.0`. At some point, the api package got bump to a major …

Always pull in API package from workspace (fixes #378)

---

packages/desktop-client/src/components/accounts/Account.js
packages/loot-design/src/components/spreadsheet/useSheetValue.js

Fixes #393
---
**Problem:** clicking on "reconcile" causes a fatal page crash.
**Issue:**
by default `useSheetValue` returns `undefined` value.
In the calculations we use `cleared` balance minus `targetBalance` (customer input) to calculate `targetDiff`. If `cleared` is `undefined`, we end up with `targetBalance === NaN`.
`targetBalance` later is used in the `format()` util function. This function expects number values and not a `NaN`.
https://github.com/MatissJanis/actual/blob/4904da500672f11d28bc47ddedfbaaae94b96aeb/packages/desktop-client/src/components/accounts/Account.js#L107-L111
**Fix:**
The simple fix is to return `null` by default in `useSheetValue`. `null` is already used as a default value for `string`-type bindings [here](https://github.com/MatissJanis/actual/blob/master/packag …

fix(useSheetValue): default value should be null not undefined

---

packages/api/index.js
packages/import-ynab4/importer.js
packages/import-ynab5/importer.js

The backend imports the `import-ynab4` and `import-ynab5` packages, which we pulling in `@actual-app/api` directly. When we switched to the API using a full bundled version of the app, this is a problem. The importer packages are special because they are inlined directly into Actual, so although they invoke the API they are actually just running directly against Actual when in the app.
We can import just the methods from the API instead, which avoids pulling in the whole bundle. This fixes building the backend, and unblocks us to cut a release. Building the backend previously took many minutes (and resulted in a huge bundle) because it was embedding the API build; now it takes ~30 seconds.

Avoid pulling in the bundled app from API in backend

---

packages/desktop-client/src/components/accounts/Account.js

As per issue #371, after selecting one or more of the children of a split transaction and performing a change, any 'EDIT FIELD' operation would also be erroneously applied to the unselected siblings & parent as well. 
This was caused by `options({ splits: 'grouped' })` retrieving *all* the children of any selected split transaction. This appears to be the intended behaviour for this option (as far as I can tell), however it is now accounted for in the calling code.
I'm up for more performant suggestions - although I reckon this here is pretty alright, with a set used to minimise performance degredation with larger selections. Perhaps a new splits option for SQL queries might make sense? The only trouble with that is that the parents will still need to be retrieved for some other logic to …

Fix child transaction selection edits also applying to their unselected siblings.

---

packages/desktop-client/src/components/accounts/Account.js

Added a button to the reconciliation menu that will automatically create reconciliation balance adjustment transaction according to the target diff calculated.
Demo:

feat(account): button to create reconciliation balance updates

---

.gitattributes

Proposing this change to support windows development better, i ran into an issue with `yarn start:browser` where lint would throw not allowing local start. 
https://cdn.discordapp.com/attachments/1027831756545609789/1051764870065967164/image.png

Update git attributes for better End of Line handling

---

packages/loot-core/package.json
packages/loot-core/src/mocks/setup.js
packages/loot-core/src/server/accounts/__snapshots__/sync.test.js.snap
packages/loot-core/src/server/accounts/__snapshots__/transfer.test.js.snap
packages/loot-core/src/server/accounts/sync.test.js
packages/loot-core/src/server/accounts/transfer.test.js
packages/loot-core/src/server/main.test.js
packages/loot-core/src/server/spreadsheet/spreadsheet.test.js
packages/loot-core/src/server/sync/sync.test.js
yarn.lock

Re-enabling and fixing skipped unit tests.
Before:
```
➤ YN0000: [loot-core]: Test Suites: 4 skipped, 32 passed, 32 of 36 total
➤ YN0000: [loot-core]: Tests:       33 skipped, 210 passed, 243 total
➤ YN0000: [loot-core]: Snapshots:   40 passed, 40 total
➤ YN0000: [loot-core]: Time:        131.646 s
```
After:
```
➤ YN0000: [loot-core]: Test Suites: 1 skipped, 35 passed, 35 of 36 total
➤ YN0000: [loot-core]: Tests:       2 skipped, 241 passed, 243 total
➤ YN0000: [loot-core]: Snapshots:   69 passed, 69 total
➤ YN0000: [loot-core]: Time:        145.029 s
```

test: re-enable skipped unit tests

---

packages/desktop-client/src/components/manager/ConfigServer.js

Adding a test-budget creation button on the very first screen to simplify things in the preview and dev environment.
The button is not visible for prod builds.

feat: creating test budget on the config page

---

packages/desktop-client/src/components/LoggedInUser.js
packages/desktop-client/src/components/Titlebar.js

- hide the “🔁 Offline” button
- when clicking on “No server,” close the current budget before attempting to navigate to `/config-server`

Improve handling of “no server” state

---

README.md

Adding Netlify badge to our README.
Netlify have provided us with an open-source license for preview deployments. They have been instrumental so far to get through the backlog of PRs.

docs: add netlify as sponsors to README

---

packages/desktop-client/src/components/manager/ConfigServer.js
packages/desktop-client/src/components/manager/ManagementApp.js
packages/loot-design/src/components/common.js
packages/loot-design/src/components/manager/BudgetList.js

Fixes the overlap @MikeBishop [noted here](https://github.com/actualbudget/actual/discussions/433#discussioncomment-4605317): 
Move the version info from bottom right to top left at narrow widths.
Here we're widening from a tiny phone (iPhone SE) and landing back at today's desktop layout:
Stack the server URL and version info in the center bottom. But feels a little crowded down there to me.
Also seen in the problem demo, the account boxes were growing a little too wide at intermediate widths. Now they won't grow awkwardly wide for no reason. (As seen in the solution demo.)

Fix overlap of version info and server URL

---

packages/desktop-client/src/components/SidebarWithData.js
packages/loot-design/src/components/sidebar.js

<details><summary>Outdated screenshots</summary>
&larr; The tools are back inline. The section defaults to closed unless you load the page into one of the tools, then it will open itself.
…and the parent item highlights itself when collapsed if any of its children are selected &rarr;
.
.
<br>New look for the Accounts section: &rarr;
- The “Accounts” header now toggles the visibility of the entire section, just like the Tools section (although the Accounts section is always open by default)
- There’s now a new header called “All accounts” (or “All open accounts” if you have closed accounts, would appreciate feedback on this distinction) that shows your net worth, and lets you see transaction history for on and off budget accounts combined (i.e. what “Accounts” used to do)
- The button to …

Further iteration on the sidebar design

---

packages/desktop-client/src/components/ManageRules.js

Fixes https://github.com/actualbudget/actual/issues/450
Rules page fails to load when link-schedule rules > 0 and payees not already in state
Not sure if this is the best way to achieve this, but it fixes the issue

Fix bug where rules page may not load due to link-schedule payee dependency

---

packages/loot-core/src/client/shared-listeners.js

We are not actively reporting bugs anywhere anymore. So this text was misleading.
Fixing it to be more appropriate.

:speech_balloon:  change misleading automatic bug-report text

---

packages/desktop-client/bin/build-browser
packages/desktop-client/bin/watch-browser

Making the `build-browser` and `watch-browser` commands use the `desktop-client` version.
We are currently not cutting new releases for electron app. How we do releases for that is yet to be figured out. Until then - we'll be bumping up only the web version numbers.

:bug:  make build-browser, watch-browser commands use desktop-client vers

---

packages/desktop-client/config/paths.js
packages/desktop-client/src/browser-preload.js
packages/desktop-electron/package.json

Reverting some unintentional removals after the mobile app cleanup in https://github.com/actualbudget/actual/pull/443
This will make electron-app dev-server work again.

:rewind:  reverting some changes to fix electron-app

---

packages/desktop-client/src/components/budget/MobileBudgetTable.js

Fixes #470 
See ☝🏻 this issue for details of the bug.
In short: an `onEdit` click handler was bringing up the keyboard for mobile users
Let's get rid of this block entirely.

mobile: disable edit on tap of category balance

---

.github/workflows/e2e-test.yml

- install only chromium for playwright; this should make it quicker and solve problems such as [this one](https://github.com/actualbudget/actual/actions/runs/3909627256/jobs/6680910274)
- swapped around `yarn install` and playwright install tasks to make things slightly faster

:construction_worker:  improving playwright install speed

---

.github/workflows/opened-pr-triage.yml
.github/workflows/stale-pr.yml
.github/workflows/stale.yml

Added the ability to mark PR as stale after 30 days for PR's that are waiting review and added the label when new PR's are created

Update stale workflow

---

.github/workflows/build.yml

Electron builds are consistently failing on master branch. We need to fix them and then we can un-comment the CI job. Until that is done - disabling them.
See: https://github.com/actualbudget/actual/issues/468

:construction_worker:  disable failing electron builds

---

tsconfig.json

> To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.
Per https://github.com/Microsoft/vscode/issues/31188, just excluding `node_modules` isn’t enough, we also have to ignore the relevant directories anywhere in the directory hierarchy.

Fix TypeScript warning about too many files

---

packages/desktop-client/src/components/settings/FixSplits.js

I’m not sure when this happened but it’s probably my fault. Would be nice to have type checking to warn about this in the future :)

Fix “Repair split transactions” button being missing

---

packages/import-ynab4/importer.js

Fix YNAB4 importer: the `cleared` state was not being read from the import file.
Closes #399

:bug: (ynab4) transaction cleared state in imports

---

packages/loot-design/src/components/budget/rollover/TransferTooltip.js

Fixes #566
This change allows the category list to pop up upon clicking into the text box without waiting for text input first. As issue #566 stated, this is consistent with the accounts transaction page where you simply click on the category box and the list of categories appears without any keyboard input.

[Feature] List of categories in transfer money dialog

---

packages/desktop-client/src/components/util/GenericInput.js

This change affects both the Rules modal and filters tooltip.  It will drop down a list of available options for the selected field without the need of keyboard input.

opens the category/payee/account lists on focus

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Let me know if you have any feedback on the language in the template. The fields are based on (i.e. shamelessly copied and pasted from) the [Babel](https://github.com/babel/babel/issues/new?assignees=&labels=i%3A+needs+triage%2Ci%3A+enhancement&template=feature_request.yml), [GitHub Desktop](https://github.com/desktop/desktop/issues/new?assignees=&labels=&template=feature_request.yaml), and [Mastodon](https://github.com/mastodon/mastodon/issues/new?assignees=&labels=suggestion&template=2.feature_request.yml) feature request forms.

Add an issue template for feature requests

---

packages/desktop-client/src/components/accounts/TransactionsTable.js

Resolves #567 by removing the title attribute on PayeeCell and add `text-overflow` styling for Transfer Accounts in that cell too.

Remove GUID on hover from PayeeCell

---

packages/loot-design/src/components/NotesButton.js

Closes #563
This PR adds a hover to the NotesButton that displays NotesTooltip!

Add 'View on Hover' to Category Notes for #563

---

packages/loot-design/src/components/budget/rollover/rollover-components.js

This automatically opens the category drop down menu when the field is selected to cover over spending from another category.  This will match the behavior of the earlier PRs.

Cover Overspending dropdown menu, open on click

---

packages/desktop-client/src/components/accounts/Account.js

@shall0pass reported a bug where the accounts page would crash if you selected a scheduled transaction, this is because getTransaction will return `undefined` for a preview ID. We'll check that all transactions is defined before attempting to access `is_child` on the transaction now. 
This was bug was introduced with #582!

Add truthy condition to ambiguousDuplication check

---

yarn.lock

A small upgrade to fix
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

:arrow_up:  upgrade caniuse-lite

---

packages/loot-design/src/components/PayeeAutocomplete.js

Fixes #280. That said, I’m not sure if this is a good feature — might it be confusing to have e.g. both a payee and an account named HSBC?

Allow creating a payee with a name matching an existing account

---

packages/desktop-client/src/components/manager/ManagementApp.js

Currently, the “Server URL: X [change]” text is only shown on the files list. With this change, it is also visible on the login, bootstrap, and server error pages. This way, even if you don’t have the password to the server stored in your local config, you can still change to a new server or stop using a server.
Testing steps:
1. Connect to a running Actual Server.
2. Log out.
3. Try to change to a different server, or stop using a server.

Allow configuring the server from any page on the management app

---

packages/loot-core/src/shared/arithmetic.js

This does allow e.g. `$50+£20 → 70` which is not semantically valid, but hopefully people will notice that 🤞

Support arbitrary currency symbols in expressions

---

packages/desktop-client/src/components/FinancesApp.js
packages/desktop-client/src/util.js

This is an alternate method to determine the isMobile status for using the responsive mobile view.  This should respect the "Desktop site" option if used in a mobile browser.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent
Reference: https://www.tutorialspoint.com/javascript-how-to-detect-if-a-website-is-open-on-a-mobile-or-a-desktop

Use navigitor.userAgent to determine isMobile

---

packages/api/package.json
packages/desktop-electron/package.json
packages/loot-core/package.json
yarn.lock

Upgrading node-fetch to fix security issues. Especially important in `actual-server` (which imports `@actual-app/api`)
- https://cwe.mitre.org/data/definitions/173.html
- https://cwe.mitre.org/data/definitions/200.html
- https://cwe.mitre.org/data/definitions/601.html

:arrow_up:  upgrade node-fetch to ^2.6.9

---

packages/desktop-client/src/components/schedules/EditSchedule.js
packages/loot-design/src/components/PayeeAutocomplete.js

This makes the schedule editor match the behavior of the PayeeAutocomplete in TransactionsTable
Fixes #300 
**BEFORE**
**AFTER**

Schedule Editor: Keep payee list open while toggling transfer payees focus

---

packages/desktop-client/src/components/schedules/LinkSchedule.js
packages/desktop-client/src/components/schedules/SchedulesTable.js
packages/desktop-client/src/components/schedules/index.js
packages/loot-design/src/components/common.js

You can currently search by payee name, account name, next date, amount, and status (e.g. upcoming/missed).

Add support for filtering the schedules table

---

packages/desktop-client/src/components/ManageRules.js

Fixes #614. Now you’ll see this:
Searching for `(deleted)` will also work as expected.

Improve behavior of deleted payees/categories/accounts in rules

---

packages/desktop-client/src/browser-server.js
packages/desktop-client/src/components/FatalError.js
packages/desktop-client/src/index.js

This message could definitely use some improvement (maybe by linking to a doc with instructions to fix?). I considered hooking it up as an in-app notification, but I wasn’t sure if that would show up at the right time, and this feels severe enough to demand immediate action before continuing to use the app.

Add a warning when SharedArrayBuffer is not available

---

packages/desktop-client/src/components/accounts/Account.js

This fix removes the mutation of the closed account name string and conditionally prefixes "Closed: " to closed account name title
fixes #616, fixes #622
https://user-images.githubusercontent.com/2892349/216729993-519bdde3-3e08-4a25-b58b-a4b1e7bc2050.mov

Fixes editing closed account names issue #616

---

packages/loot-design/src/components/budget/rollover/TransferTooltip.js

Resolves #284! It looks like this behavior was intended previously but didn't work because the Input component catches the Enter key and calls onEnter instead.

Fix form submission on TransferTooltip when pressing enter

---

packages/loot-core/src/server/main.js

When creating an account, the “starting balance” transaction will be added only if the balance is nonzero

Skip the “Starting Balance” transaction if the balance is 0

---

packages/loot-design/src/components/budget/rollover/BudgetSummary.js

Previously, this seems to have always been 0.

Fix default value of “Move to a category”

---

packages/desktop-client/src/components/UpdateNotification.js
packages/desktop-client/src/components/manager/ManagementApp.js

The Actualbudget blog no longer exists, replaced the links with the OSS release notes, this resolves #626

Removed reference to blog

---

packages/desktop-client/package.json

Currently `actual-server` has to pull in these packages when installing for production, which is unnecessary since they’re already bundled into the published package. This also triggers peer dependency warnings

Move desktop-client deps to devDeps

---

packages/loot-design/src/components/CategorySelect.js
packages/loot-design/src/svg/v0/Delete.js
packages/loot-design/src/svg/v0/Delete.svg
packages/loot-design/src/svg/v0/Merge.js
packages/loot-design/src/svg/v0/Split.js
packages/loot-design/src/svg/v0/merge.svg
packages/loot-design/src/svg/v0/split.svg

I think I regressed this in #485. Checked all of the other v0 icons and confirmed that they are not affected.

Fix coloring of the “Split Transaction” button in the category picker

---

packages/desktop-client/src/browser-preload.browser.js
packages/desktop-client/src/browser-server.js
packages/desktop-client/src/components/FatalError.js
packages/loot-core/src/client/actions/budgets.js

Clicking through sets a value in `localStorage` that bypasses the error.

Allow bypassing SharedArrayBuffer override

---

packages/desktop-client/src/components/ManageRules.js
packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/components/accounts/Filters.js

Fixes #643. The left side of the filter is now a button.
Clicking on it opens the same editor you get when creating a new filter. This required some code changes to allow pre-filling an existing filter (rather than starting a new one).

Allow editing filters

---

packages/desktop-client/src/components/settings/Encryption.js

This is blocked on https://github.com/actualbudget/docs/pull/104 getting merged. To test this out, you’ll have to run locally and then visit your computer’s IP address.
For future reference, unlike disabling the app when SharedArrayBuffer is unavailable, end to end encryption actually will to work at all when the crypto API is unavailable.

Block enabling e2e encryption when the crypto API is unavailable

---

packages/loot-core/src/server/main.js

In the closed-source version of actual this was used to promp the user to subscribe. This is no longer the case, but it was never cleaned up.

:fire:  remove closed-source subscription notification code

---

packages/desktop-client/src/components/manager/subscribe/ChangePassword.js

Now, when you enter the new password, we will log in with the new password and then send you to the file list.

Don’t force user to re-enter password after changing it

---

packages/desktop-client/src/components/ManageRules.js
packages/desktop-client/src/components/accounts/Filters.js
packages/loot-core/src/shared/rules.js

This PR fixes a few existing edge cases, along with a few I probably introduced in #646. I’ve now tested all of the different filter types both in rules and in the account view, and things seem to work OK.

Fix error cases in displaying filters/rules

---

packages/desktop-client/src/components/accounts/Account.js

Closes https://github.com/actualbudget/actual/issues/664!
Adding a little button to clear the search term, as well as listening for the 'Esc' key to clear that way too.
https://user-images.githubusercontent.com/3413011/221344831-bee98cbd-b27b-4c16-843c-bdfd6232f6f6.mp4

Add button and 'esc' shortcut to clear transaction filter

---

packages/loot-design/src/components/budget/index.js

Part of https://github.com/actualbudget/actual/issues/126
Removing lively usage in `MonthPicker`

:fire:  removing lively from MonthPicker

---

packages/desktop-client/src/components/settings/Encryption.js

It turns out `hasOwnProperty(crypto, 'subtle')` always returns false.

Fix check for crypto.subtle

---

packages/loot-design/src/components/modals/EditField.js

Fixes #673. `onSelect(null)` is called when you blur the autocomplete field, so I ignore that call for the purposes of updating the value. This does mean it’s no longer possible to bulk remove a payee/category but I doubt people want to do that.

Don’t allow bulk editing to set a field to null

---

packages/desktop-client/e2e/schedules.test.js

Some people are saying that it will not always be February 28, 2023. Updated the e2e test to be a bit more lenient just in case the current date changes at some point in the future. ;)

Fix e2e test to not assume it’s been run on Feb 28, 2023

---

.github/actions/setup/action.yml
.github/workflows/build.yml
.github/workflows/e2e-test.yml
.github/workflows/lint.yml
.github/workflows/opened-issues-triage.yml
.github/workflows/test.yml

Nothing major to see here.. just upgrading github actions so they would stop telling us about deprecations

:construction_worker:  upgrade github actions

---

package.json

Yarn v2 does not put a `node_modules` folder inside of `packages/loot-design` so this cannot possibly do anything. Additionally, `rm` is not available in `cmd.exe` for Windows. Ref: #730.

Remove outdated part of the postinstall script

---

packages/api/package.json
packages/loot-core/package.json
yarn.lock

A new release for `api` too so we could start using `better-sqlite3` v8 in `actual-server`.

:bookmark: (5.1.0) upgrade better-sqlite3 to v8.2

---

packages/loot-design/src/components/modals/ImportTransactions.js

Fixes #19 by setting the file type before attempting the parse. You’ll now be able to change the import options even if the first import attempt failed.

Set the filename/filetype before attempting to parse

---

packages/loot-core/src/server/accounts/sync.js

Check if the transaction amount is a positive 0 rather than -0.
I went for casting the string with `Number` but I could instead replace the whole condition with `!trans.amount.startsWith('-')` or with `trans.amount > 0 || trans.amount == '0.00'` if either of these variants are preferred.
Fix for https://github.com/actualbudget/actual/issues/724#issuecomment-1464907064

:bug: (nordigen) fix detection of -0.00 "debited" transactions

---

packages/loot-core/src/server/accounts/sync.js

Try falling back to `remittanceInformationUnstructuredArray.join(', ')` when neither `debtor/creditorName` nor `remittanceInformationUnstructured` fields are present.
Addresses a suggestion from https://github.com/actualbudget/actual/issues/724#issuecomment-1464907064

🐛 (nordigen) fallback to array version of remittanceInformationUnstructured if necessary

---

packages/loot-core/src/server/aql/compiler.js
packages/loot-core/src/server/aql/schema/executors.js
packages/loot-core/src/server/aql/schema/executors.test.js

**Don't merge yet**: these changes are ready, but I want to add tests before merging
I recently migrated my personal usage of Actual over to the open-source version and imported a bunch of transactions. I have a _lot_ of history in Actual, including a lot of weird edge cases like deleted split transactions. While reconciling I noticed that my account balance shown at the top was incorrect, even though the running balance was current.
Digging into this, I discovered that we aren't correctly handling aggregate queries when querying transactions in the "grouped" mode. Aggregate queries don't make sense in the "grouped" mode. Grouped means that you want a list of transactions that include both the parent and child transactions (when they are split). If you are summing up all the amount, you …

Route aggregate queries in transaction grouped mode through the correct layer to remove deleted transactions

---

LICENSE.txt

Inspired by react: https://github.com/facebook/react/blob/main/LICENSE
I'm no lawyer, but IMO it's safe to remove the year from the license.

Remove year from the LICENSE

---

packages/loot-core/src/server/accounts/sync.js

Fallback to `bookingDate` if `valueDate` is empty.
Fix for: https://github.com/actualbudget/actual/issues/724#issuecomment-1464914546

:bug: (nordigen) fallback to bookingDate if valueDate is not set

---

packages/desktop-client/src/components/Modals.js
packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/components/modals/CreateAccount.js
packages/desktop-client/src/hooks/useSyncServerStatus.js
packages/loot-core/src/server/main.js
packages/loot-design/src/components/modals/NordigenExternalMsg.js

Related to: https://github.com/actualbudget/actual/issues/724#issuecomment-1455160250
Depends on https://github.com/actualbudget/docs/pull/126 to be merged first.
Two changes here:
1. show "link account" only if actual-server is used (user is "online");
2. allow linking accounts only if Nordigen is configured (using new API to get the status for it);
Also ported the `CreateAccount` modal to a functional component.

:bug: (nordigen) check server status before linking accs

---

packages/desktop-client/package.json

Why not `23.3.1`? Because we already released that version for `actual-server`

:bookmark: (23.3.2) nordigen fixes

---

packages/loot-core/src/server/accounts/sync.js

Fixes https://github.com/actualbudget/actual/issues/724#issuecomment-1468453526
And add the missing fallback condition that wasn't catered in https://github.com/actualbudget/actual/pull/745

fix(nordigen/sync): Use bookingDate as fallback during sync

---

package.json
packages/desktop-client/package.json
packages/loot-design/package.json

before:
```
kcab.worker.4bdc73a8d45eb2115156.js (2.1 MiB)
xfo.kcab.worker.4bdc73a8d45eb2115156.js (1010 KiB)
```
after:
```
kcab.worker.39f5fba82d7bc7477962.js (1.41 MiB)
xfo.kcab.worker.39f5fba82d7bc7477962.js (1000 KiB)
```
What’s changed:
- `loot-core` did not have a `browserslist` config, so `@babel/preset-env` assumes we want to [transpile all the way back to ES5](https://babeljs.io/docs/options#no-targets). I’ve removed the `browserslist` config from each of the `package.json` files and moved it to the root so this doesn’t happen again.
- I updated the target from `electron 3.0` to `electron 12.0` to match our Electron dependency
- I’ve added `defaults` (currently equivalent to `> 0.5%, last 2 versions, Firefox ESR, not dead`) which is [recommended by …

Reduce client build size by 1MB

---

packages/desktop-client/config-overrides.js
upcoming-release-notes/763.md

This way formatting issues won’t prevent the preview from building (and it should build a bit faster due to not having to run ESLint).

Disable ESLint when building in CI

---

packages/node-libofx/emscripten.cpp
packages/node-libofx/ffi.js
upcoming-release-notes/670.md

I am currently not working on adding support for importing to multiple accounts, but I wanted to give anyone who takes that on a starting point by updating the underlying C library to provide access to the account name field.

node-libofx: add transaction_acct_name function

---

packages/loot-core/src/mocks/index.js
upcoming-release-notes/771.md

This is not a full fix for the flakiness. One of the test cases will still be flaky. But at least this fixes the other test cases thus improving stability.

:white_check_mark: reducing flakiness of tests by removing randomization

---

packages/loot-core/package.json
packages/loot-core/src/mocks/arbitrary-schema.js
packages/loot-core/src/server/sync/migrate.test.js
packages/loot-core/src/server/sync/sync.property.test.js
upcoming-release-notes/772.md
yarn.lock

Upgraded `fast-check` to improve unit test performance.
(ignore `set up environment` step - that is slow only the first time it's ran because of no dependency cache; focus on the "test" step)
Before:
After:

:arrow_up:  upgrade fast-check to improve unit test perf

---

packages/desktop-client/src/index.js
upcoming-release-notes/776.md

Finishing off the React v18 upgrade by doing a change in `react-dom`. Effectively this upgrades from v17 to v18.
https://react.dev/blog/2022/03/08/react-18-upgrade-guide

:arrow_up:  finish react v18 upgrade: react-dom change

---

packages/loot-design/src/components/payees.js
packages/loot-design/src/components/table.js
upcoming-release-notes/781.md

Just cleaning up things: removing an unused code-path.

:fire:  remove unused `tableNavigatorOpts` code-path

---

packages/desktop-client/src/components/Modals.js
packages/desktop-client/src/components/SidebarWithData.js
packages/desktop-client/src/components/Titlebar.js
packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/components/settings/Experimental.js
packages/desktop-client/src/hooks/useFeatureFlag.js
packages/loot-design/src/components/budget/rollover/BudgetSummary.js
packages/loot-design/src/components/modals/EditField.js
upcoming-release-notes/786.md

Refactored all feature flags to use the new `useFeatureFlag` hook.
Also added a new functionality to this feature flag: ability to define custom "default" value for a feature flag. This will allow us to enable the new autocomplete component for everyone using Netlify builds eventually (need to address some issues before doing so).

:recycle:  move all feature flags to use useFeatureFlag hook

---

packages/desktop-client/src/components/schedules/EditSchedule.js
packages/desktop-client/src/hooks/useFeatureFlag.js
packages/loot-design/src/components/NewAutocomplete.js
packages/loot-design/src/components/NewPayeeAutocomplete.js
upcoming-release-notes/789.md

Enabling the new autocomplete for dev/preview deployments.
This will allow us to spot any more issues there might be before we release the new autocomplete.
https://github.com/actualbudget/actual/issues/773

:sparkles: (autocomplete) enable new version for dev/preview deploys

---

packages/loot-design/src/components/modals/CreateLocalAccount.js
upcoming-release-notes/774.md

This fixes #753, adding a clarification message under the Off-budget tick box to inform that the Account type is not changeable after the account has been created.
It also adds on a separate line a link to the Accounts documentation to find more information.

753 - Clarify Account type cannot be changed

---

packages/loot-design/src/components/autocomplete-styles.js
upcoming-release-notes/787.md

Making consistent height between multi/single input autocomplete.
Before:
After:

:bug: (autocomplete) consistent input height between multi/single input

---

packages/loot-design/src/components/autocomplete-styles.js
upcoming-release-notes/793.md

Now all of the gaps are 4px and (at least in my browser) the typed text lines up exactly with the placeholder.

Match spacing in autocomplete

---

packages/desktop-client/src/components/accounts/TransactionsTable.test.js
upcoming-release-notes/795.md

Disabling the flaky unit test step. We should re-enable it eventually, but right now it just creates unnecessary noise..

:green_heart:  disabling flaky unit test step

---

packages/desktop-client/src/components/SidebarWithData.js
packages/desktop-client/src/components/settings/Experimental.js
packages/desktop-client/src/components/settings/FixSplits.js
packages/desktop-client/src/components/settings/Global.js
packages/desktop-client/src/components/settings/UI.js
packages/desktop-client/src/components/settings/index.js
upcoming-release-notes/799.md

This PR improves the consistency of the settings UI by moving everything (except the budget name field on mobile) into `<Setting>` boxes. Additionally, it adds a “Settings” option to the file dropdown menu (I keep expecting it to be there, and I think it’s reasonable to expose it in both locations so it’s easier to access)

Improve visual consistency on the settings page

---

packages/desktop-client/src/components/budget/index.js
upcoming-release-notes/797.md

#786 changed the way feature flags are used in components. While refactoring, the `BudgetSummary` component was refactored to get the value of the `goalTemplatesEnabled` flag from props rather than Redux store, but the value of the flag was never passed down to it. Side effect of that was accidentally disabling goal templates, as the flag value was always `undefined`.
This PR fixes that — the flag value is now passed in so that the goal complete feature can now be correctly enabled. (And  the value of the `newAutocomplete` flag is passed down to the `ToBudget` component as well.)

Re-enable goal templates by passing flag values to the budget summary component

---

packages/loot-core/src/shared/util.js
packages/loot-core/src/shared/util.test.js
upcoming-release-notes/808.md

- When parsing an amount string, consider surrounding parentheses to mean the amount is negative.
- Ensures all input to `parseFloat()` is sanitized.
Closes: #807

transaction-import: treat (amount) as -amount

---

packages/desktop-client/src/components/autocomplete/autocomplete-styles.js
upcoming-release-notes/834.md

Implement min-width for the autocomplete to make it look better on small screens.
https://github.com/actualbudget/actual/issues/773#issuecomment-1482254636

:bug: (autocomplete) set min-width of the autocomplete

---

packages/desktop-client/src/components/autocomplete/NewPayeeAutocomplete.js
upcoming-release-notes/836.md

When you open the payee autocomplete and click on "make transfer" button in the footer: there is a noticable delay between the renders.
This is because the previous `CreatableSelect` component is unmounted and a new `Select` component gets mounted. The only difference between the two: ability to create new payees.
If we remove this logic and simply always keep the component in the `creatable` state - there are no long re-mounts and thus the flow is not so disruptive. But the downside is: you can create payees whilst in the "transfer" mode.
Not exactly the best solution.. but IMO it's better this way than with the massive delay.
https://github.com/actualbudget/actual/issues/773

:bug: (autocomplete) delay when switching from Select to CreatableSelect

---

packages/desktop-client/src/components/autocomplete/NewPayeeAutocomplete.js
upcoming-release-notes/837.md

Correctly flip top/bottom the payee autocomplete. Other autocompletes don't have this problem because they don't have a custom "footer". Whereas this one has it.. and it messes with `react-select` calculations.
Before:
After:

:bug: (autocomplete) set min-height used to calculate the flip (top-bottom)

---

packages/desktop-client/src/components/accounts/TransactionsTable.js
packages/desktop-client/src/components/autocomplete/autocomplete-styles.js
upcoming-release-notes/839.md

Removing portaliztion of the autocomplete from the table view in order to improve the scrolling experience.
Before:
https://user-images.githubusercontent.com/886567/229307705-b013bcde-aaf6-4eec-b269-9cae37370637.mov
After:
https://user-images.githubusercontent.com/886567/229307664-2de32356-f2c6-4e90-a0fa-aec88747756c.mov

:bug: (autocomplete) remove portal from table view for smoother experience

---

packages/desktop-client/e2e/page-models/budget-page.js
upcoming-release-notes/845.md

Sometimes the test failed because..
`parseFloat("1,234.55") === 1)`

:white_check_mark: (e2e) improve stability of budget e2e tests

---

packages/desktop-client/package.json
packages/import-ynab4/package.json
packages/import-ynab5/package.json
packages/loot-core/package.json
upcoming-release-notes/849.md
yarn.lock

Previously, we were using an alpha version of date-fns v2. Now we’re using the latest stable v2.

Update to latest stable date-fns version

---

packages/desktop-client/src/components/accounts/Filters.js
upcoming-release-notes/855.md

Closes #779
Normalize the input value when switching between single/multi select fields. Most visible when using the "notes" field filter.

:bug:  normalize value when switching between single/multi select

---

packages/loot-core/src/client/update-notification.js
upcoming-release-notes/854.md

Closes #764
Dismiss the update notification only after clicking "close" button

:bug:  dismiss update notification only after clicking close

---

packages/desktop-client/config-overrides.js
packages/desktop-client/src/util.js
upcoming-release-notes/869.md

This should speed up builds in CI, and must not have gotten caught when upgrading `react-scripts`.
ref: arackaf/customize-cra#278

Disable ESLint in CI again

---

packages/loot-core/src/platform/server/sqlite/index.electron.ts
packages/loot-core/src/platform/server/sqlite/index.web.ts
packages/loot-core/src/server/accounts/payees.js
packages/loot-core/src/server/aql/compiler.js
packages/loot-core/src/server/db/index.js
upcoming-release-notes/865.md

Fixes #840 by creating application-defined SQL functions (https://www.sqlite.org/appfunc.html) for Unicode-aware implementations of `LOWER()` and `UPPER()`. This uses `String.prototype.toLower/UpperCase()` JS method.
I initially wanted to just redefine `LOWER()` and `UPPER()` but due to [sql.js not supporting the definition of deterministic functions](https://github.com/sql-js/sql.js/issues/551), I had to just define them as separate functions and use that in the appropriate places. It's probably better like that anyway...

Use Unicode-aware implementations of LOWER() and UPPER() in SQL queries

---

packages/desktop-client/src/components/accounts/Account.js
upcoming-release-notes/882.md

Reproduction:
1. open netlify deployment
2. open account page
3. select 1x transaction
4. go to the hamburger menu and "create rule"
5. click "save" in the modal
6. before: it does not work - error in console; after: it works

:bug: (rules) creation from account page

---

packages/desktop-client/src/components/autocomplete/NewPayeeAutocomplete.js
upcoming-release-notes/881.md

https://github.com/actualbudget/actual/issues/773
---
Before:
"create payee" is visible for exact matches
After:
"create payee" is visible only if NOT exactly matched

:bug: (autocomplete) show 'create payee' only if no payee matched

---

upcoming-release-notes/884.md
yarn.lock

This fixes a warning about an unsupported TypeScript version when linting.

Upgrade @typescript-eslint packages

---

packages/loot-core/bin/copy-migrations
upcoming-release-notes/893.md

It turns out this command is not installed by default on macOS. Fortunately the code doesn’t really require it to be used.

Remove usage of `realpath`

---

packages/desktop-client/src/components/Page.js
packages/desktop-client/src/components/accounts/MobileAccounts.js
packages/desktop-client/src/components/settings/index.js
upcoming-release-notes/887.md

Improving the `Settings` page header on mobile devices. And unifying the implementation in mobile `Accounts` page to use the generic `Page` component.
Before:
After:

:art: (mobile) settings page header

---

packages/desktop-client/src/components/accounts/TransactionsTable.js
packages/desktop-client/src/components/autocomplete/NewPayeeAutocomplete.js
upcoming-release-notes/902.md

Fixes issue #495. Possibly found a bug as well... using the cached accounts and payees meant they weren't used from the calling function, which prevented the use of my filtered list of accounts.

Fixes Issue 495 Transfer allowed from same account

---

packages/desktop-client/src/browser-preload.browser.js
packages/desktop-client/src/components/table.js
upcoming-release-notes/926.md

It turns out that `event.key` for ctrl/cmd+Z is `z`, and it’s `Z` for ctrl/cmd+shift+Z.

Fix handling for shortcuts

---

packages/desktop-client/src/components/modals/ImportTransactions.js
packages/loot-core/package.json
packages/loot-core/src/server/accounts/parse-file.js
upcoming-release-notes/921.md
yarn.lock

Hi there, 
I try to tackle #798 here. It was suggested to throw this behind a feature flag, so here it is!
this does its best to import the problem file in #767. 
I am working on this because it would make my work on #918 easier :)
Feel free to set the feature flag to true and try the new importer. The date parser is not as sophisticated as the one in `node-libofx`, but I tried 3 different OFX files, one from my bank, one from the mocks, and one from #767. They all seem to work well enough on that front, but this is definitely the weak point of the new implementation.
Let me know what you think!

Add experimental new OFX importer

---

packages/desktop-client/src/components/autocomplete/Autocomplete.js
packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js
packages/desktop-client/src/components/util/GenericInput.js
upcoming-release-notes/931.md

Cleaning up the autocomplete state updates by removing the `updater` and moving to react state hooks.
This is mostly a copy&paste, but I also fixed a few small issues and improved things a bit.. apologies for the big PR, but making this smaller would be very tricky.

:recycle: (autocomplete) cleaning up state updates

---

packages/desktop-client/src/components/table.js
upcoming-release-notes/939.md

Fixes #937. I also checked through all other uses of `.key` and made sure I didn’t make any other mistakes.

Fix j/k shortcuts to move between transactions on account pages

---

packages/desktop-client/src/components/schedules/EditSchedule.js
upcoming-release-notes/946.md

Don’t reset checked transactions when creating a schedule

---

packages/desktop-client/src/components/modals/NordigenExternalMsg.js
upcoming-release-notes/950.md

For: https://github.com/actualbudget/actual/issues/724#issuecomment-1465501335

:bug: (nordigen) fallback button to re-init bank-sync for popover blockers

---

packages/desktop-client/src/components/FinancesApp.js
upcoming-release-notes/960.md

Closes #935
Before: we render all the pages (even the inactive ones in some cases)
After: we render only the visible pages. Thus the topbar color is set only 1x.. thus the settings page topbar has the correct color.

:bug: (mobile) correct topbar color on settings page

---

packages/desktop-client/src/components/common.js
packages/desktop-client/src/components/spreadsheet/CellValue.js
upcoming-release-notes/967.md

I removed the unused prop `numberOfLine` prop in this PR: https://github.com/actualbudget/actual/pull/962
Now I'm adding back some functionality that was missing. For who knows how long..

:bug: (Text) single-line text

---

.eslintrc.js
packages/desktop-client/src/components/accounts/MobileAccount.js
packages/desktop-client/src/components/budget/MobileBudgetTable.js
packages/desktop-client/src/components/debug/index.js
packages/desktop-client/src/components/sort.js
packages/desktop-electron/index.js
packages/loot-core/src/server/spreadsheet/new/parser.ts
packages/loot-core/typings/window.d.ts
upcoming-release-notes/974.md

Switch to TS version of `no-unused-vars` rule. 
(Trying to use enums on another branch and the JS version throws false warnings.)

@typescript-eslint/no-unused-vars

---

package.json
upcoming-release-notes/977.md

When people first start out with actual they usually run `yarn start`. And oftentimes it doesn't work.. because we haven't yet fixed the electron (desktop) version.
Swapping the default `start` command to use `start:browser`. This should help newcomers get started more easily.

:wrench:  make start:browser the default cmd instead of start:desktop

---

packages/desktop-client/src/components/modals/NordigenExternalMsg.js
upcoming-release-notes/969.md

Improving error handling for Nordigen.
Before: if loading banks failed - a loading indicator would be shown forever.
After: is loading banks fails - an error message is shown.

:bug: (nordigen) bank-list error handling

---

.github/workflows/issues-close-feature-requests.yml
upcoming-release-notes/954.md

We have too many open issues in `actual`. This makes maintaining the list very difficult. Especially because many of the issues are feature requests.
So to better manage the issue list: I'd propose we follow the strategy lodash uses. All feature requests are automatically closed with a new label added to them. These feature requests can then be voted on and/or commented in the closed state. If sufficiently many people vote on the issue (via emojis), then the dev team might consider implementing it. If nobody votes on it - nothing happens. But then these issues are not cluttering our list.
What this new github action does:
- if the issue is labeled with "feature"
- adds a comment explaining the situation
- adds label "needs votes"
- adds a "+1" reaction to the root message
- closes the …

:construction_worker:  auto-close feature requests

---

packages/desktop-client/src/components/accounts/TransactionsTable.js
packages/desktop-client/src/components/accounts/TransactionsTable.test.js
upcoming-release-notes/992.md

Closes #943
Creates the transaction when clicking "enter". Irrelevant of which field is currently active.

:bug: (transactions) create transaction when clicking enter

---

packages/desktop-client/src/components/reports/CashFlow.js
packages/desktop-client/src/components/reports/Header.js
packages/desktop-client/src/components/reports/NetWorth.js
packages/desktop-client/src/components/reports/graphs/cash-flow-spreadsheet.js
packages/desktop-client/src/components/reports/graphs/net-worth-spreadsheet.js
packages/desktop-client/src/hooks/useFilters.ts
upcoming-release-notes/994.md

Low hanging fruit for reports: ability to filter the existing reports.
https://user-images.githubusercontent.com/886567/236334378-6e42e563-f1ab-4c4b-a8b5-55f1a7deba63.mov
With this improvement I hope to inspire more people to take a look at reports and start adding improvements here too. There's lots of things we could do, but here's how I would imagine it:
Eventually there would be a new "reports" page. In this page you select a visualization you want to use (timeseries, table, barchart, sankey? maybe something else too?). You then proceed to set filters to fine-grain your query. As you are doing this - the vizualisation gets auto-updated with fresh data. 
Once you're happy with the results: you click "save". This adds the viz to the reports homepage. You can view it there or you can …

:sparkles: (reports) ability to fine-tune reports with filters

---

packages/loot-core/src/server/budget/goal-template.pegjs
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1004.md

By default when using the "up to" feature of a template, funds above the limit are removed to bring the category balance down to the limit.  This adds the ability to prevent funds removal.  The syntax is `#template up to 100+` where the `+` signals to not add negative budgeted amounts.  This will add funds up to 100 but not pull back to 100.
My use case:
I get a partial internet reimbursement through work once a year.  When the reimbursement comes in I categorize it directly as "internet" so I have extra funds sitting in that category to be used for the next few months.  I want to have a template add money only if its needed but not remove funds if there is extra.

Goal Templates: add option to prevent removing funds when using "up to" in goal

---

.eslintrc.js
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1015.md

Multi-line `if`/`for` statements in JS can be confusing since there aren’t braces to indicate which code is enclosed in the statement. I set the configuration to `multi-line` to enforce usage of braces for multi-line statement bodies, but still allow things like `if (foo) return;`. I additionally added the `consistent` option to require braces for all elements of an if/else chain if one element has it. As you can see, this set of options pretty closely matches the existing code style.
I was going to comment in #1008 about this stylistic change but realized that it’s (IMO) a little impolite to ask for code style changes unless they can be automatically enforced.
Note that `if (foo) { \n return; \n }` is still valid and won’t be collapsed. I tried to automatically collapse all such cases …

Enable 'curly' rule

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
CONTRIBUTING.md
docker-compose.yml
upcoming-release-notes/1032.md

Adds support for [devcontainers](https://containers.dev/), this should make onboarding easier and should allow (especially simpler) contributions entirely online via Github Codespaces 🚀

Add .devcontainer

---

packages/desktop-client/src/components/accounts/TransactionsTable.js
packages/desktop-client/src/components/autocomplete/AccountAutocomplete.js
upcoming-release-notes/1034.md

Changes in the pr:
- Removed closed accounts when adding a transaction 
- Updated ordering of the account autocomplete popup
Previous ordering seemed to put closed accounts at the top, then order accounts by name. This PR makes the accounts appear in the same order as they do on the left panel - on budget first, then off budget, then closed accounts.
(increased max height just for the screenshots)
Before:
After, without closed accounts (adding a transaction):
After, including closed accounts:
First PR to this project - let me know if i messed something up.

Updated account ordering in the account autocomplete popup

---

packages/desktop-client/e2e/page-models/account-page.js
packages/loot-core/src/mocks/number-formats.ts
packages/loot-core/src/shared/arithmetic.test.ts
packages/loot-core/src/shared/arithmetic.ts
upcoming-release-notes/1029.md

From the discussion in #894, I made decimal separators agnostic for all number formats and added tests. Please let me know if it makes sense once you try it.
> We could also check after imports to see if there was a mismatch in detected decimal separators and pop up a warning.
I haven't added any mismatch detection and warning in this PR, but if you'd like me to I can add a commit here or make a second PR for it.

Make number parsing agnostic to decimal and thousands separators (#894)

---

package.json
packages/desktop-client/src/components/budget/MonthCountSelector.js
packages/desktop-client/src/components/common/Button.tsx
packages/desktop-client/src/components/sidebar.js
upcoming-release-notes/1048.md

- Fix clicking buttons in the toolbar on macOS (previously they were not clickable)
- `yarn start:electron` now launches the Electron app
- The sidebar is now identical to the web version

A few fixes for Electron

---

packages/desktop-client/src/components/accounts/TransactionsTable.js
packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.js
upcoming-release-notes/1038.md

The payee autocomplete was always using cached accounts. Added a check to see if accounts was already passed in as a parameter - only using cached if it wasnt.

Fixed a bug where it was possible to make a transfer to the same account as the one making the transfer.

---

packages/api/index.js
upcoming-release-notes/1054.md

This allows using the API as documented. In #877, I think this was unintentionally converted to be a named export.

Export `api/methods.js` at the top level again

---

packages/loot-core/bin/copy-migrations
upcoming-release-notes/1056.md

yarn build failed on copy-migrations because /bin/sh is not bash on WSL and doesn't expect -e

change copy-migrations shebang to bash

---

packages/loot-core/src/server/budget/goal-template.pegjs
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1052.md

Add option to schedule templates to budget the full amount only in the needed month.  Default behavior stays the same of spreading the expense out over the available range.
To use the option, use a template like `#template schedule full SCHEDULE_NAME`
Also some minor cleanup.

Template: Apply schedule template only on needed month

---

packages/loot-core/src/server/budget/goal-template.pegjs
upcoming-release-notes/1059.md

Revert the parser cleanup that broke parsing for some goal templates.  Undoes some changes from #1052.
@shall0pass How is this.  It works for me on the previously broken templates.

Goals: fix broken parser

---

packages/desktop-client/src/components/NotesButton.tsx
packages/loot-core/src/client/data-hooks/accounts.tsx
packages/loot-core/src/client/data-hooks/payees.tsx
packages/loot-core/src/client/query-hooks.tsx
upcoming-release-notes/1061.md

As you can see, this removes a bit of boilerplate. I looked at the other places that call `liveQuery` now, and they don’t seem very easy to covert to the hook so I left them alone for now.

Use the useLiveQuery hook in a couple more places

---

.eslintrc.js
packages/desktop-client/src/components/NotesButton.tsx
packages/loot-core/src/client/data-hooks/accounts.tsx
packages/loot-core/src/client/data-hooks/payees.tsx
packages/loot-core/src/client/query-hooks.tsx
upcoming-release-notes/1064.md

Since each `q` call returns a brand new `Query` object, it will always be necessary to use `useMemo` to cache the value to avoid recreating the query. As a result, I’ve made `useLiveQuery` pass its arguments directly into `useMemo`, so you can’t forget to do so.
Fixes a performance regression from #1061.

Integrate useMemo into useLiveQuery

---

.eslintrc.js
packages/desktop-client/src/components/SidebarWithData.js
packages/desktop-client/src/components/accounts/MobileTransaction.js
packages/desktop-client/src/components/manager/ConfigServer.js
packages/loot-core/src/client/data-hooks/accounts.tsx
packages/loot-core/src/client/data-hooks/payees.tsx
packages/loot-core/src/client/data-hooks/schedules.tsx
packages/loot-core/src/client/query-hooks.tsx
upcoming-release-notes/1070.md

- Enforce that imports from the same package are merged into a single import
- In `loot-core`, require that imports of other `loot-core` files use a relative import (like the vast majority of such imports) rather than specifiers starting with `loot-core/` (probably a result of moving files out of other packages into `loot-core`)

More import-related ESLint rules

---

packages/desktop-client/src/components/budget/index.js
upcoming-release-notes/1067.md

Clicking the a category in the "spent" column for the budget table was not working because `this.props.history` is undefined.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'push')
```

:bug: (budget) link from budget to transactions not working

---

packages/loot-core/src/server/budget/goal-template.pegjs
upcoming-release-notes/1083.md

Fix bug brought up in discord where `#template $100 by 2023-06 repeat every 12 months` would fail.
The parser was looking for a single digit so would max out at 9.
I added a new value to the parser "positive" that allows any number larger than 0, and used that for the by goals.

fix parser bug where by goals couldn't repeat on months/years >9

---

packages/loot-core/src/server/budget/cleanup-template.ts
upcoming-release-notes/1084.md

The cleanup script could sometimes throw an error if 'sink' and 'source' were in the same category in the wrong order.  This PR filters out the 'source' line if it exists and only uses the first 'sink' template line if it exists.

Bug: Cleanup script

---

packages/api/index.js
packages/api/methods.js
packages/loot-core/src/server/api.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/types/main.handlers.d.ts
upcoming-release-notes/1075.md

- Sync before closing the budget
- Add an explicit `sync()` method to the API

Sync more often when using the API

---

packages/loot-core/src/server/budget/cleanup-template.ts
upcoming-release-notes/1095.md

There was one more location where the cleanup script could generate an error.  This should fully resolve the error, along with https://github.com/actualbudget/actual/pull/1084.

Goals: Cleanup script error

---

packages/loot-core/src/server/api.ts
upcoming-release-notes/1073.md

Previously, this would fail with a confusing “cannot read property of `undefined`” error.

Add clear error to API when no budget is open

---

package.json
packages/desktop-electron/package.json
upcoming-release-notes/1106.md
yarn.lock

1. Upgrade all `cross-env` versions to be the same
2. Added `cross-env` to `desktop-electron` - it was used there, but was missing as a dep

:wrench: (cross-env) add missing dep and upgrade all to same version

---

packages/desktop-client/src/components/payees/index.js
upcoming-release-notes/1107.md

Hi there,
The unused payees button broke in between the initial PR and now - and here's a fix!

BUGFIX Unused Payees: Corrected an issue where the filter control was not being referenced

---

packages/loot-core/src/server/budget/goal-template.pegjs
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1101.md

Added the option to add a remainder goal template.  This will use the remaining available funds and dump them into the respective category. There is optional weighting.  The remainder templates will be forced to the lowest priority as to run after all other templates.
Usage: `#template remainder <weight>`  Add the template line to any categories you want to catch any remaining funds such as savings.  The amount added to the category will equal `remaining_budget/total_of_weights*weight`. The default weight is 1.

Goals: Remainder option

---

.github/actions/setup/action.yml
upcoming-release-notes/1118.md

This should fix the test failures on `master` — currently tests are failing because the cache was created with an old version of Node.

Partition GitHub Actions cache based on Node version

---

packages/desktop-client/src/components/ServerContext.js
packages/desktop-client/src/components/manager/subscribe/common.tsx
packages/desktop-client/src/hooks/useFeatureFlag.ts
packages/loot-core/src/server/accounts/sync.ts
packages/loot-core/src/server/cloud-storage.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/types/main-handlers.d.ts
upcoming-release-notes/984.md

Previously, the frontend would attempt to make real requests to `https://not-configured/`, which of course failed. I’ve changed the internal structure to have the lack of a server expressed as a `null` server. A new `did-bootstrap` browser-level setting has been added to track if the user clicked “Don’t use a server.”
Finally, I updated the auth logic for methods that call out to the server to make them consistent and use the early return style which reduces indentation.

Fix sync-related errors that show up in the console when not using a server

---

packages/desktop-client/src/hooks/useNordigenStatus.ts
upcoming-release-notes/1127.md

Small bugfix for nordigen.
Do not perform the server status check if the user is actually offline.

:bug: (nordigen) perform status check only if server is online

---

packages/desktop-client/src/components/accounts/AccountSyncCheck.js
packages/desktop-client/src/hooks/useNordigenStatus.ts
upcoming-release-notes/1133.md

Further Nordigen fixes for expired bank-links. With the recent changes to the router, we had broken this functionality.

:bug: (nordigen) expired bank-links

---

packages/desktop-client/src/components/schedules/DiscoverSchedules.js
packages/desktop-client/src/hooks/useSendPlatformRequest.ts
upcoming-release-notes/1136.md

Closes #1125
Disables (hides) the "all payees" checkbox when schedules are loading.
Reproduction:
1. open `/schedule/discover`
2. while the data is still loading - click on the checkbox in the table header
3. after loading finishes - the page crashes with an error

:bug:  disable 'all payees' checkbox while schedules are loading

---

packages/loot-core/src/server/main.ts
upcoming-release-notes/1140.md

URLs with the trailing slash don’t work well — requests end up being made to `https://example.com//sync/sync` and such which can 404

Strip a trailing slash off of server URLs

---

packages/desktop-client/src/components/budget/misc.js
upcoming-release-notes/1143.md

This PR is for the first item listed in #559: `Expand All / Collapse All Categories`
For the expand / collapse all categories functionality, I was choosing between having a single `Expand / collapse all categories` button or one for each: `Expand all categories` and `Collapse all categories` buttons. 
For the initial implementation, I have opted with the latter. Please let me know which one is the right way to go or if there are other suggestions and I'll just accordingly.

Expand / collapse all categories

---

packages/desktop-client/src/components/FinancesApp.js
packages/desktop-client/src/components/LoggedInUser.js
packages/desktop-client/src/components/manager/ConfigServer.js
packages/desktop-client/src/components/manager/ManagementApp.js
packages/desktop-client/src/global-events.js
packages/desktop-client/src/util/ExposeNavigate.js
packages/desktop-electron/menu.js
packages/loot-core/src/client/actions/budgets.ts
packages/loot-core/src/client/upgrade-notifications.ts
packages/loot-core/typings/window.d.ts

This introduces a new global `__navigate` function connected to the current router. This is useful when swapping between routers (such as when opening/closing a file) or when doing menu actions from within Electron.
There’s still an issue here around how modals work. Presently, modals are represented as a linked list, with the user-visible URL displaying the URL of the topmost modal, and a chain of `locationPtr` objects in state that go through the open modals in order, before eventually ending up on the page that forms the backdrop of all open modals. This approach has a couple of downsides:
- If you refresh the page while a modal is open, the modal will fill the screen
- This does not always happen; for example, the Create Account modal does not interact with the router at all, but the …

Clean up __history usage

---

packages/desktop-client/src/components/manager/Import.js
packages/desktop-client/src/components/manager/ImportActual.js
packages/desktop-client/src/components/manager/ImportYNAB4.js
packages/desktop-client/src/components/manager/ImportYNAB5.js
packages/loot-core/src/client/actions/notifications.ts
upcoming-release-notes/1155.md

Closes #1069
I've not actually tested this change. Which is why I'm not changing it to direct links (as they might not work).
Instead I'm just applying a very quick patch so the message would not be misleading anymore.

:bug:  remove 'we have been notified' copy

---

packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/components/accounts/MobileAccount.js
packages/desktop-client/src/components/budget/index.js
packages/desktop-client/src/components/payees/index.js
upcoming-release-notes/1178.md

* Provide `match` prop to class components that still rely on it.
* Fixes #1169
* Fixes an unrelated crash on Payees

React Router 6 fixes

---

packages/desktop-client/src/components/manager/DeleteFile.js
upcoming-release-notes/1066.md
upcoming-release-notes/1170.md

- on desktop, it was 500px instead of 512px wide which left it positioned left of center
- on mobile, it was also 500px wide which overflowed the screen

Fix “delete file” modal layout

---

.github/workflows/issues-feature-implemented.yml
upcoming-release-notes/1183.md

I noticed that this run failed: https://github.com/actualbudget/actual/actions/runs/5366199111/jobs/9735490726

Fix completed feature request handling

---

packages/desktop-client/.eslintignore
upcoming-release-notes/1199.md

This fixes an error that you’ll  see about an unused export if you build before linting.

Add public/data to .eslintignore in desktop-client

---

packages/desktop-client/package.json
packages/desktop-client/src/fonts.scss
packages/desktop-client/src/index.tsx
upcoming-release-notes/1213.md
yarn.lock

Poorly optimized browsers may have downloaded the non-variable-font versions of Inter since the `@font-face` declarations were present (but unused).
This will make the deployed images significantly smaller, and also makes the size comments more accurate/helpful.

Bundle only the variable font version of Inter

---

packages/desktop-client/config-overrides.js
packages/desktop-client/src/components/App.js
packages/desktop-client/src/components/DevelopmentTopBar.tsx
packages/desktop-client/src/components/FatalError.js
upcoming-release-notes/1229.md

Adding a Netlify deployment banner so it would be easy to jump back to the PR from a preview link.

:sparkles:  add netlify development banner

---

packages/desktop-client/config-overrides.js
packages/desktop-client/package.json
upcoming-release-notes/1230.md
yarn.lock

Bringing back asset caching. This means we won't need to do a full re-build for every change.
I had previously disabled caching because the backend changes (kcab) were not picked up properly. But now that should be fixed too.

:wrench:  improved dev-server - enable asset cache

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1193.md

Add recurring schedule support.
To test: use the schedule keyword with a daily or weekly recurring schedule.

Goals: Add recurring schedule support

---

packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/components/accounts/TransactionList.js
packages/desktop-client/src/components/accounts/TransactionsTable.js
upcoming-release-notes/1228.md

For #547 
In addition to the arrow icon, I have also updated the recurring/calendar icon to open the edit schedule page.

Add onClick handlers to the schedule and transaction icons in the transaction list (#547)

---

packages/import-ynab4/importer.js
packages/import-ynab5/importer.js
upcoming-release-notes/1224.md

Fixes #1220. Previously, the importer wasn’t correctly setting the ID of subtransactions on split transactions. This was mostly fine since the ID wasn’t used for much, but as shown in the referenced issue, if a subtransaction is a transfer, it won’t be correctly matched with its pair in the other account. Future imports will now handle this correctly. I’m not sure if there is a way we could detect and fix this in existing budgets.

Fix importing transfers from YNAB4/5

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/codeql.yml
.github/workflows/e2e-test.yml
.github/workflows/electron.yml
.github/workflows/release-notes.yml
.github/workflows/size-compare.yml
upcoming-release-notes/1251.md

Cancel previous CI runs if a new push is made. Thus saving a bit of CI resources.

:wrench:  cancel previous CI runs if a new push is made

---

packages/loot-core/src/platform/server/sqlite/index.d.ts
packages/loot-core/src/platform/server/sqlite/index.electron.ts
packages/loot-core/src/platform/server/sqlite/index.web.ts
packages/loot-core/src/server/cloud-storage.ts
upcoming-release-notes/1242.md

Solves #1238
If we are happy with this approach, which I don't _love_, I'll tidy it up a bit first, check the file doesn't exist, use a random(er) name, wrap it in a functon etc.
Basically the `better-sqlite` `serialize` function can't be used, as I guess under the surface its allocating a chunk of memory in C.
I tried to wrap all this logic inside the `exportDatabase` function in `/server/sqlite/index.electron.ts` but I had a lot of problems trying to import `fs` there if anyone can give advice.

Fix electron export issue

---

packages/desktop-client/src/components/accounts/MobileAccounts.js
upcoming-release-notes/1247.md

:bug: (mobile) reduce the size of account cards

---

packages/desktop-client/src/components/FixedSizeList.js
upcoming-release-notes/1262.md

Fixes #1241
This was probably not noticed because most of the time the screen is wider than it is tall, so it just results in showing more rows than necessary.

Fix calculation of how many table rows to render

---

packages/desktop-client/e2e/page-models/account-page.js
packages/desktop-client/e2e/page-models/close-account-modal.js
packages/desktop-client/src/components/modals/CloseAccount.js
packages/desktop-client/src/components/reports/Header.js
upcoming-release-notes/1259.md

We have `Select` and `CustomSelect`.
`Select` - native select component where controlling the style and UX is much more difficult. `CustomSelect` - as the name implies - a custom select implementation.
The goal of this PR is to remove a few usages of the `Select` component. Eventually I want to get rid of it entirely.
--
Testing:
1. reports page (month selectors)
2. "close account" modal

:recycle: (select) removing 2x usages of the Select component

---

packages/desktop-client/src/components/App.js
upcoming-release-notes/1267.md

The banner in #1229 pushes the bottom bar items (including version & “change server URL” button) out of view on Netlify builds.

Fix layout of the management app with the demo bar in place

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1254.md

When using the percent goal you can only use current month income.  When operating under a month ahead strategy you are saving this months moneys for next month, so the percentage goal loses most of its usefulness.  This PR adds the option to use the current available funds as the base for the percent calculation.  
This will use the funds that were available at the start of the template run regardless of priority level to match the income based option as much as possible.

Goals: Add option to percent goal to use available funds

---

packages/loot-core/src/server/sync/index.ts
upcoming-release-notes/1302.md

The logs for `invalid-schema` were not logging the used query or the metadata. So fixing this.
It would make debugging issues such as https://github.com/actualbudget/actual/issues/1296 easier.

:loud_sound:  improving 'invalid-schema' error logs

---

README.md
upcoming-release-notes/1297.md

The "community documentation" link below Code Structure headline in `README` will direct user to page not found error

Fix page not found error in README

---

packages/desktop-client/package.json
packages/desktop-client/src/components/FinancesApp.js
upcoming-release-notes/1306.md
yarn.lock

Reverts actualbudget/actual#1204
Closes https://github.com/actualbudget/actual/issues/1293
This is way more complicated than originally anticipated. Reverting the change to fix the prod build. Someone can work on re-introducing this in a later build, but we need to be sure it doesn't break once more.

Revert "Fix drag and drop on touch devices (#1194)"

---

packages/desktop-client/src/components/accounts/Account.js
upcoming-release-notes/1305.md

Reported on Discord:
```
Hello,
I found a bug when entering multiple transactions and  jumping from one account to another. Here are the repro steps
Step 1. Select Account 1 on the For budget list on the left pane.
Step 2. Click +Add new 
Step 3. Enter your transaction and click Add
Step 4. Change to Account 2
Step 5. Enter your second transaction and click Add
The second transaction is going to be registered under Account 1. 
Note that after adding the first transaction, the new transaction line remains, as shown on the screenshot.
Also, if you then add a third transaction on Account 3, it's going to be registered under Account 2, so it seems that internally, the value of which account to register the transaction under is updated only after the transaction is saved. 
This can …
```

:bug:  changing pages while adding a transaction

---

packages/desktop-client/src/components/common/CustomSelect.tsx
upcoming-release-notes/1314.md

Currently `CustomSelect` will always have scrollbar even the height is not higher than the max height. 
Change the style to make the scrollbar only show when the content overflow the max height.
Before:
After:
Reference discussion: #1294

Fix Custom Select unnecessary disabled scrollbar

---

packages/desktop-client/src/components/common/CustomSelect.tsx
packages/desktop-client/src/components/reports/Header.js
upcoming-release-notes/1325.md

Add a new parameter `defaultLabel` to `CustomSelect` component, to make it able to set a default label when the value is not included in options.
Also have added JSdoc to CustomSelect
Reference issue: https://github.com/actualbudget/actual/pull/1277#issuecomment-1628793696

Fix the CashFlow report crash because of the new CustomSelect

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1344.md

I have a budget with 57 templates, which causes a noticeable lag.  I've used performance.now() to show that my templates take 4-4.5 seconds to calculate and fill.  This PR uses the setZero function that already exists to reduce that time to 3-3.2 seconds, a substantial improvement.

Goals: Use setZero function within goal templates for speed improvement

---

packages/desktop-client/src/browser-preload.browser.js
packages/desktop-client/src/components/modals/ImportTransactions.js
upcoming-release-notes/1349.md

Closes https://github.com/actualbudget/actual/issues/1313.
See my comments on the issue for investigation into what was happening. It seems WebKit wants the file input in the DOM to reliably fire `change` events when the user makes a selection. I set the input to `display: none` to make sure that even if it sticks around in the DOM for some reason it's not interactive.

Fix importing transactions in Safari and clean up openFileDialog API

---

packages/desktop-client/src/components/modals/ConfirmCategoryDelete.js
upcoming-release-notes/1351.md

Found there is a bug should fix after refactoring to `CategoryAutoComplete`
Bug: User can transfer budget to the category (or group) which user want to delete

Fix a bug in confirm category delete

---

packages/desktop-client/src/components/DevelopmentTopBar.tsx
upcoming-release-notes/1353.md

Stop the demo build bar from shrinking on mobile/small sizes

---

packages/desktop-client/src/components/payees/index.js
upcoming-release-notes/1335.md

- The button will now be hidden by default so that users who don’t have any unused payees won’t have to think about it (since we merge by default, unused payees should be pretty rare)
- The number of unused payees will be shown on the button to help understand how much cleanup needs to be done

Update logic for showing and rendering the “Show unused payees” button

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1312.md

Using the 'up to' keywords can have unexpected results when there are two statements in the same category with different priority levels.
The current fill can be different than what is expected.
This PR would change this behavior to the following.

Goals: Fix calculated fill when using multiple 'up to' statements in different priority levels

---

packages/desktop-client/src/components/payees/index.js
upcoming-release-notes/1334.md

Since this table extends all the way to the bottom of the screen, the bottom corners should not be curved. (Alternatively, it should have some bottom padding, but I kinda like this look)

Remove bottom border radius from the payee table

---

packages/desktop-client/src/components/select/DateSelect.js
upcoming-release-notes/1316.md

fix #1301
After the change,  upper components will not detect the press enter event before the datepicker is closed.

Fix clicking enter will create empty transaction

---

packages/desktop-client/src/components/Modals.tsx
packages/desktop-client/src/hooks/useActions.ts
packages/loot-core/src/client/actions/budgets.ts
packages/loot-core/src/client/actions/modals.ts
packages/loot-core/src/client/reducers/modals.ts
packages/loot-core/src/client/state-types/modals.d.ts
upcoming-release-notes/1359.md

This makes sure the right parameters are passed when pushing a modal, and is the first use of the `useActions` hook.

Add clear typings to the modals

---

packages/desktop-client/src/components/settings/FixSplits.js
upcoming-release-notes/1363.md

There was a spelling error on the settings page that was bothering me. Fixed a run-on sentence and a fragment.

spelling error in FixSplit.js

---

packages/desktop-client/src/icons/v2/MoonStars.js
packages/desktop-client/src/icons/v2/Sun.js
upcoming-release-notes/1378.md

I changed the default icon color in #1368, but didn't apply that change to the icons added in #1367. This does that.

Update coloring of newly added icons

---

packages/desktop-client/src/components/table.tsx
upcoming-release-notes/1366.md

FYI @carkom.
This was triggering the following error since the `saveScrollWidth` call was made from `renderRow` which is called inside the `render` method of the table component:
<details><summary>Long error stack:</summary>
```
Warning: Cannot update a component (`TransactionTableInner`) while rendering a different component (`FixedSizeList`). To locate the bad setState() call inside `FixedSizeList`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
at FixedSizeList (packages/desktop-client/src/components/FixedSizeList.js:32:5)
at AvoidRefocusScrollProvider (packages/desktop-client/src/hooks/useProperFocus.js:39:46)
at packages/desktop-client/src/setupTests.js:13:8
at div
at View (packages/desktop-client/src/components/common/View.tsx:19:11)
at div
at …
```

Move saveScrollWidth call to layout effect

---

packages/desktop-client/src/components/transactions/TransactionsTable.js
upcoming-release-notes/1380.md

Correct the width of StatusCell

---

packages/desktop-client/src/components/FixedSizeList.js
packages/desktop-client/src/style/styles.ts
upcoming-release-notes/1385.md

Resolves #1358 
This change will make users can scroll the whole page while the viewport height is lower than `550px`, but cannot when higher.
I don't really sure which is the "good" height number to determine should users have ability to scroll the whole page or not.
The double scrollbar is helpful to the budget page because the upper component always stand `250px` height. The outer scrollbar make users have ability to scroll down to focus on another part. Otherwise, their screen will always be occupied by the upper component.
However, to the transaction table page. This outer scrollbar is meaningless from my perspective, because the upper component is very small, even right now I've limited the height to ensure the outer scrollbar only appear when the viewport height is lower than …

Remove double scrollbar as the screen is big enough

---

packages/desktop-client/src/components/ManageRules.js
upcoming-release-notes/1342.md

Try to delete table navigator in rules page and didn't see any breaking changes from my perspective.
However, I'm a new user to this application. This PR only aimed at helping to preview the rules page if there're any breaking changes after deleting table navigator.
Related issues: https://github.com/actualbudget/actual/issues/1341

Delete table navigator from rules page

---

packages/desktop-client/src/components/filters/FiltersMenu.js
upcoming-release-notes/1389.md

This has never worked, and can be represented more clearly using the greater than and less than operators as two separate filters. Brought up in Discord: https://discord.com/channels/937901803608096828/1132639847778107422

Exclude “isbetween” op from the filter UI

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1400.md

Depending on the remainder scaling and weights there is sometimes 1 cent leftover after the remainder pass in the goals.  I allowed the scale factor to include sub cents, which sometimes fixes the issue, and an explicit check.  This way high weight templates will pull in the extra most of the time as expected, but if the weights are about even then the last one run will get the floating 1 cent.  I think there could still be an edge case when the total weights is very high with respect to funds available, but its likely not a big deal.

Goals: fix leftover 1 cent in remainder goal

---

packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/components/transactions/TransactionsTable.js
upcoming-release-notes/1406.md

There were lines from #1232 that were left out of #1354. They are still missing from the current master file. This adds them back in to restore the functionality of 1232.

Fix Sorting/Balance interactions

---

packages/desktop-client/src/components/FatalError.js
packages/desktop-client/src/components/Titlebar.js
packages/desktop-client/src/components/common.tsx
packages/desktop-client/src/components/common/AnchorLink.tsx
packages/desktop-client/src/components/common/Paragraph.tsx
packages/desktop-client/src/components/gocardless/GoCardlessLink.js
packages/desktop-client/src/components/manager/ImportActual.js
packages/desktop-client/src/components/manager/ImportYNAB4.js
packages/desktop-client/src/components/manager/ImportYNAB5.js
packages/desktop-client/src/components/manager/WelcomeScreen.js
packages/desktop-client/src/components/manager/subscribe/Bootstrap.tsx
packages/desktop-client/src/components/modals/CloseAccount.js
packages/desktop-client/src/components/modals/CreateAccount.js
packages/desktop-client/src/components/modals/CreateEncryptionKey.js
packages/desktop-client/src/components/modals/FixEncryptionKey.js
packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
packages/desktop-client/src/components/modals/MergeUnusedPayees.js
packages/desktop-client/src/components/modals/PlaidExternalMsg.js
packages/desktop-client/src/components/payees/index.js
packages/desktop-client/src/components/reports/CashFlow.js
packages/desktop-client/src/components/reports/NetWorth.js
packages/desktop-client/src/components/schedules/DiscoverSchedules.js
packages/desktop-client/src/components/schedules/PostsOfflineNotification.js
packages/desktop-client/src/components/settings/FixSplits.js
packages/desktop-client/src/hooks/useStableCallback.ts
upcoming-release-notes/1413.md

Moving the code to separate files. Functionally should be no differences.

:recycle:  moving P, useStableCallback, AnchorLink common components

---

packages/desktop-electron/index.js
upcoming-release-notes/1417.md

https://github.com/actualbudget/actual/issues/1047
Before:
After:

:bug: (electron) always show titlebar

---

packages/desktop-client/package.json
packages/desktop-client/src/components/spreadsheet/CellValue.tsx
packages/desktop-client/src/components/spreadsheet/format.ts
packages/loot-core/package.json
packages/loot-core/src/client/selectors.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/1423.md
yarn.lock

Closes #1415
Fix number formatter not listening to state changes. This is not a fully comprehensive solution. We will need to run a migration campaign to port over from direct usage of `format` util to `useFormat`, but this is a first step that solves the most glaring issue.

:bug:  fix number formatter not listening to state changes

---

packages/desktop-client/src/components/payees/index.js
upcoming-release-notes/1430.md

`applyFilter` exits early if the filter is unchanged, so this call doesn’t do anything.

Remove no-op applyFilter call

---

packages/crdt/package.json
packages/crdt/src/crdt/index.ts
packages/crdt/src/main.ts
upcoming-release-notes/1434.md

Fixes:
```
WARNING in ./packages/crdt/src/crdt/index.ts 3:0-126
export 'Clock' (reexported as 'Clock') was not found in './timestamp' (possible exports: Timestamp, deserializeClock, getClock, makeClientId, makeClock, serializeClock, setClock)
@ ./packages/crdt/src/main.ts 2:0-129 2:0-129 2:0-129 2:0-129 2:0-129 2:0-129 2:0-129 2:0-129 2:0-129 2:0-129
@ ./packages/crdt/index.ts 1:0-27 1:0-27
@ ./packages/loot-core/src/server/main.ts 3:0-41 1996:4-17 1996:38-55 1997:90-109 1997:110-1[23](https://github.com/actualbudget/actual/actions/runs/5711879798/job/15474279705?pr=1432#step:4:24)
```
https://github.com/actualbudget/actual/actions/runs/5711879798/job/15474279705?pr=1432

:bug: (crdt) export Clock as a type to fix warning

---

packages/desktop-client/src/icons/v2/Eye.js
upcoming-release-notes/1450.md

Eye.js is currently set to a static color (black). This PR allows you to change the color of the icon with the style element - mimicing all other icons in Actual.

fix eye coloring

---

upcoming-release-notes/1449.md
upcoming-release-notes/README.md

The current link in the README directs to a github page that has a link to the documentation page on how to write release notes.  I've updated the link here to just go straight to the documenation page on how to write good release notes.

Release note README link update

---

packages/crdt/package.json
upcoming-release-notes/1438.md
yarn.lock

Upgrading murmurhash. The new version has TS types.
Apart from that, it looks pretty much the same.
Diff: https://www.diffchecker.com/CEpBedX1

:arrow_up: (crdt) upgrade murmurhash

---

packages/desktop-client/src/components/common/Select.tsx
upcoming-release-notes/1458.md

In some situations the text in the Select component will be too big, which will make the inner vertical scrollbar appear. This PR is to hide the vertical scrollbar.

Bugfix: remove select component inner scrollbar

---

.github/workflows/check.yml
.github/workflows/issues-feature-implemented.yml
packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/components/accounts/Balance.js
upcoming-release-notes/1473.md

:bug: (schedules) fix showing balance of approximate transactions

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1478.md

The 'interval' value from the schedules is not set if the schedule is monthly.  This change will check for a valid number for the interval value and if it does not exist will default to 1 (monthly).

[Bug] Goals: Monthly schedule can cause error

---

packages/desktop-client/src/components/table.tsx
upcoming-release-notes/1494.md

It seems #1436 caused a regression in the background color of the transactions button.
`demo.actualbudget.org` right now looks like:
With the fix in this PR:
It looks like the transparent background was added explicitly in #1436: https://github.com/actualbudget/actual/pull/1436/files#diff-816cd66052d6811e3d3cac9f19920d8b57c09d3c3b0c882c4fc768d314776d45R905
It's not entirely clear to me why that was done, @carkom was there a specific reason for that change?

Fix transactions button background color

---

packages/desktop-client/src/components/transactions/TransactionsTable.js
upcoming-release-notes/1379.md

Previously the "budgeted accounts" page would show the account in the payee column for scheduled transactions.  I'm not sure if this is the correct fix since I'm a bit confused by the exact intent with the various variables that appear to be used for multiple things, but this appears to at least fix the issue.
One weird thing I noticed is that scheduled transactions also show up on the "off budget accounts" page but they _don't_ show up on the "all accounts" page.
Resolves #1333.  Resolves #1026.

Show correct payee for scheduled transactions on budgeted accounts page

---

packages/desktop-client/src/components/reports/CategorySelector.tsx
packages/desktop-client/src/components/reports/Overview.js
packages/desktop-client/src/components/reports/graphs/category-spending-spreadsheet.tsx
packages/desktop-client/src/components/reports/graphs/common.tsx
upcoming-release-notes/1491.md

Added loading indicators to the cards in reports page. Previously the blocks were "flashing" as data was loading. Now the blocks are stable and showing loading indicators.
This is a very obvious issue for bigger budgets. Not so much for smaller budgets.

:sparkles: (reports) add loading indicators

---

packages/desktop-client/src/components/reports/util.js
upcoming-release-notes/1518.md

Fixing a small typo here where multiple transfers across different payees on the same day fail to be summed up resulting in significant balance errors.

:bug: (reports) fix incorrect cashflow balance

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/1499.md

Because different banks use the date fields in vastly different ways we now let the server's bank integrations decide which date we should use.
Depends on actualbudget/actual-server#243.

Rely on date determined by server for GoCardless transactions

---

packages/desktop-client/src/components/mobile/MobileAmountInput.js
upcoming-release-notes/1551.md

1. On mobile, on the new transaction screen, enter an Amount, but don't tap away from the Amount field
2. Tap `Add Transaction`
3. The amount entered is positive.
* The amount here is negative if you first blur Amount, e.g. by editing another field like Payee before adding the transaction.
Our FocusableAmountInput (used for mobile transaction entry) applies negation logic `onBlur`. We have some "queued changes" logic for catching values a person has changed but not "locked in" via blur -- this exact scenario. It catches the new value of Amount on every change. However, that `onChange` handler did not apply the negation logic that `onBlur` uses.
Ensure `FocusableAmountInput` used in `MobileTransaction` conditionally applies negation logic the same way `onChange` as it does `onBlur`. 
The …

:bug: Mobile entry will enter positive value instead of negative 

---

packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/budget/MobileBudgetTable.js
upcoming-release-notes/1546.md

Two fixes for mobile:
1. hide sync button if sync is not active
2. after clicking the sync button - do not change the color to black
After:
Before:

:bug: (mobile) hide sync button if sync is not active

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/1484.md

This lets us fetch and process as few transactions as possible, while still allowing for fetching data back to 90 days ago if we haven't imported transactions for a while.

Make GoCardless fetch transactions from 7 days before the last imported transaction

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/1559.md

We should not override the date in case the user has manually corrected it.

Don't update transaction date when syncing from GoCardless.

---

packages/desktop-client/src/components/accounts/Account.js
upcoming-release-notes/1547.md

Closes #1327
Reproduction:
1. open transaction table
2. perform reconciliation to open the reconciliation top-message
3. switch account
4. before: the reconciliation bar is still active; after: the reconciliation bar resets

:bug:  reset reconciliation status when switching accounts

---

packages/desktop-client/src/components/App.tsx
upcoming-release-notes/1549.md

This is a nice, straightforward improvement we can make to syncing before going all the way and refreshing all clients when the server receives new data (#1496).
See the [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) for the event:
> The `visibilitychange` event is fired at the document when the contents of its tab have become visible or have been hidden.
> 
> ...
> 
> This event fires with a `visibilityState` of `hidden` when a user navigates to a new page, switches tabs, closes the tab, minimizes or closes the browser, or, on mobile, switches from the browser to a different app. Transitioning to `hidden` is the last event that's reliably observable by the page, so developers should treat it as the likely end of the user's session (for …

Sync on visibility change

---

packages/desktop-client/src/components/schedules/EditSchedule.js
packages/desktop-client/src/components/table.tsx
upcoming-release-notes/1571.md

h/t @Kidglove57 for [noticing this](https://github.com/actualbudget/actual/pull/1501#issuecomment-1686770556). 
The Schedules table in the Link Schedules modal gets squished to 0px height by the AutoSizer in `<Table>`, even if it has rows in it. In fact, the empty state "No transactions found" is the only situation where this table renders with a proper height.
1. Fix the empty state to be able to render whether we're looking at Linked or Matched transactions.
2. Give `<Table>` a flex-basis equal to the row height multiplied by the number of rows, but let it flex grow AND shrink.
I don't like messing with `<Table>`, since it's used for Accounts transactions lists and several other places. But I verified the height comes out as expected in every spot where it's used. Large transaction …

:bug: Schedule editor: Linked transactions table collapses

---

packages/desktop-client/src/components/budget/MobileTable.tsx
upcoming-release-notes/1602.md

Refactor MobileTable to tsx related to issue #1483

Refactor budget/MobileTable to tsx

---

packages/desktop-client/src/components/forms.tsx
packages/desktop-client/src/components/reports/CategorySelector.tsx
packages/desktop-client/src/components/reports/CategorySpending.js
packages/desktop-client/src/components/reports/NetWorth.js
packages/desktop-client/src/components/reports/graphs/CategorySpendingGraph.tsx
packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
upcoming-release-notes/1592.md

This is work-in-progress. Creating PR so there will be public preview link
This PR makes reports (net worth and category spending) more responsive and makes them utilize all vertical space.
In plans: make all reports remember last used parameters (filters and date range)

Make reports more responsive

---

packages/desktop-client/package.json
packages/desktop-client/src/components/modals/ImportTransactions.js
packages/desktop-client/src/components/settings/Experimental.tsx
packages/desktop-client/src/hooks/useFeatureFlag.ts
packages/loot-core/src/mocks/files/8859-1.qfx
packages/loot-core/src/server/accounts/ofx2json.ts
packages/loot-core/src/server/accounts/parse-file.test.ts
packages/loot-core/src/server/accounts/parse-file.ts
packages/loot-core/src/types/prefs.d.ts
packages/loot-core/webpack/webpack.browser.config.js
upcoming-release-notes/1600.md
yarn.lock

Closes https://github.com/actualbudget/actual/issues/798. When this parser is stable enough, we can remove the node-libofx project/dependency.
Current parsing implementation supports CREDITCARDMSGSRSV1 and BANKMSGSRSV1 for credit card and bank statements respectively.
To test the new OFX parser, it needs to be enabled via the `Experimental features` setting:

Experimental OFX parser

---

packages/desktop-client/src/components/common/Search.tsx
packages/desktop-client/src/components/schedules/index.tsx
packages/desktop-client/src/components/settings/Encryption.tsx
packages/loot-core/src/client/actions/budgets.ts
packages/loot-core/src/client/actions/modals.ts
packages/loot-core/src/client/data-hooks/schedules.tsx
upcoming-release-notes/1644.md

- Relates to https://github.com/actualbudget/actual/issues/1483
- Rewrite `Schedules` component in tsx
- Will make a follow up PR for `SchedulesTable` as made in `TODO:`. Didn't want to include that here and make a long PR

[refactor] Schedules component in tsx

---

packages/desktop-client/src/components/common/Button.tsx
packages/desktop-client/src/components/modals/FixEncryptionKey.js
upcoming-release-notes/1634.md

Fix #1582 
**Root Cause**
Adding prop `type="button"` on `<Button>` doesn't work because it doesn't proparagated to HTML `<button>`.
**Changes**
- On Back button: add `isSubmit=false`.
- On Button component: Any `<Button>` with prop `type="primary"` should have be propagated as `<button type="submit">`, except if it's explicitly has prop `isSubmit=false`.

Fix submit form on enter key pressed

---

packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/budget/MobileBudgetTable.js
upcoming-release-notes/1665.md

:bug: (mobile) fix sync button design

---

packages/desktop-client/package.json
packages/desktop-client/src/components/accounts/MobileAccount.js
packages/desktop-client/src/components/accounts/MobileAccountDetails.js
packages/desktop-client/src/components/accounts/MobileAccounts.js
packages/desktop-client/src/components/transactions/MobileTransaction.js
upcoming-release-notes/1663.md
yarn.lock

Feature: pull down on the accounts (plural) or transaction list to trigger a sync (simple actual-server sync + bank-sync (if set-up)) while using the mobile app.

:sparkles: (mobile) pull down to trigger bank-sync

---

packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/loot-core/src/server/main.ts
packages/loot-core/src/server/server-config.ts
upcoming-release-notes/1657.md

Reproduction:
1. open demo
2. when prompted for server: enter `xxxxxxxx.fly.dev` (important: WITHOUT http/https protocol)
3. click "login"
4. branch demo link will work; master demo link will blow up

:bug: (signup) fix setting up for the first time with missing protocol

---

packages/desktop-client/src/components/transactions/MobileTransaction.js
upcoming-release-notes/1669.md

:bug: (mobile) fix schedule status positioning

---

packages/desktop-client/src/components/budget/MobileBudgetTable.js
upcoming-release-notes/1679.md

The name of the income group on mobile was hard coded to "Income".  This uses the name set by the user, including emojis.

Mobile: Show proper name of income group

---

packages/desktop-client/src/components/PrivacyFilter.tsx
packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/settings/Experimental.tsx
packages/desktop-client/src/hooks/useFeatureFlag.ts
packages/loot-core/src/types/prefs.d.ts
upcoming-release-notes/1688.md

🔥 removing privacyMode feature flag

---

packages/desktop-client/src/components/schedules/EditSchedule.js
upcoming-release-notes/1687.md

:art:  fix multiline label in schedules modal

---

packages/desktop-client/src/components/transactions/MobileTransaction.js
upcoming-release-notes/1698.md

When pull-to-refresh wrapped the transaction list, sticky date headers stopped being sticky.
Let's restore the stickiness.

:bug: Mobile account transaction list: Fix sticky date section headers

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/codeql.yml
.github/workflows/electron.yml
upcoming-release-notes/1692.md

Do not cancel github CI jobs running on master branch. But do this for PRs to save resources

:construction_worker:  do not cancel github ci jobs on master branch

---

packages/desktop-client/src/components/common/Menu.tsx
packages/desktop-client/src/components/schedules/SchedulesTable.tsx
packages/desktop-client/src/components/schedules/StatusBadge.tsx
packages/desktop-client/src/components/schedules/index.tsx
packages/desktop-client/src/components/table.tsx
packages/loot-core/src/client/data-hooks/accounts.tsx
packages/loot-core/src/client/data-hooks/payees.tsx
packages/loot-core/src/client/data-hooks/schedules.tsx
packages/loot-core/src/shared/util.ts
packages/loot-core/src/types/models/schedule.d.ts
tsconfig.json
upcoming-release-notes/1691.md

Relates to  https://github.com/actualbudget/actual/issues/1483

[refactor] Migrate Schedules Table to typescript

---

package.json
upcoming-release-notes/1707.md
yarn.lock

First introduced in https://github.com/actualbudget/actual/pull/163, but now this is no longer necessary

:wrench:  removing unnecessary manual module resolution

---

packages/desktop-client/src/components/accounts/MobileAccountDetails.js
packages/desktop-client/src/components/accounts/MobileAccounts.js
packages/desktop-client/src/components/responsive/PullToRefresh.tsx
upcoming-release-notes/1706.md

:bug: (mobile) scrolling in lists with pull-to-refresh

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1718.md

Fixed a bug where report budget income templates would compound instead of replacing previous values.
Fixed an issue where the list of budgeted values to apply to the db would persist between priority runs.  This caused every processed template to be applied again in all future priority runs.  That wasn't very noticeable when accessing locally, but on slower networks it would bog down the process a lot as each db change would be sent to the server.

Goals: speed up and a bugfix

---

packages/desktop-client/src/components/FinancesApp.tsx
upcoming-release-notes/1721.md

If no route matched - redirect to the budget page.
I suspect this is why in some cases people report seeing a blank page with no content.
Reproduction:
1. open and login to a server
2. open budget page
3. manually edit the url to point to "/login"
4. before: a blank page opens; after: you are redirected back to "/budget"

:bug: (mobile) redirect to budget page for all 404

---

packages/desktop-client/src/components/reports/CashFlow.js
upcoming-release-notes/1723.md

This is a very minor change. It bothered me that the after opening the Cash Flow report, the default number of months is so large (30 months shown). I've changed this to 5 months which is what the Net Worth graph does.
I also thought about changing it to all months until the date of the first transaction but decided against this.

changed default months to 5 in cash flow report

---

packages/desktop-client/src/components/common/Button.tsx
packages/desktop-client/src/components/settings/UI.tsx
upcoming-release-notes/1725.md

Add link type to Button Component

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1738.md

If a category had two templates, it was possible to overbudget in a category if the priority level was lower.  I've attached a test budget.
To replicate, set the Food budget to zero and then apply the templates.  demo.actualbudget.org and this PR will provide different calculated fills.
[PR_test-budget.zip](https://github.com/actualbudget/actual/files/12728677/PR_test-budget.zip)

[Bugfix]: Goals - Fixed an overbudgeting condition

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1753.md

The templates conditions were not finding a value when 'in between' was chosen from schedules.  This adds a check on the schedule amount type, and if 'in between' is found will return the median value.  I believe this matches the behavior of the scheduled transaction in the ledger.  It may make more sense to fill the maximum amount here for a budgeted value.  I'm interested in any comments on what the expected behavior should be.
 
Fixes: https://github.com/actualbudget/actual/issues/1747

[Bug] Goals: Fix schedules 'in between' calculation

---

packages/loot-core/src/server/budget/cleanup-template.ts
upcoming-release-notes/1750.md

This feels like a hack. There's probably a more elegant way to handle this condition.  The report is correct in that the carryover isn't created initially.  To replicate the error:
1. Start a fresh budget
2. Add an account with a starting balance
3. Add a single transaction and assign a category
4. DO NOT FILL ANY BUDGET CELLS
5. Enable goal templates
6. Run the end of the month cleanup script.
The master branch will show the error that is reported.  What I have done here is check for the null value.  If a null value is found, set the budget cell to it's current value.  By doing this, the database tables get updated and carryover will no longer be reported as null.
https://github.com/actualbudget/actual/issues/1748

[Bug] End of month cleanup error

---

packages/desktop-client/src/components/Titlebar.tsx
upcoming-release-notes/1770.md

Addresses [Bug]: ctrl+s should sync #1685
Adds a `KeyHandlers` to `SyncButton` to capture ctrl+s

Sync on ctrl+s

---

packages/desktop-client/globals.d.ts
packages/desktop-client/src/components/common/Input.tsx
packages/desktop-client/src/components/common/View.tsx
packages/desktop-client/src/components/select/DateSelect.tsx
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/1776.md

Convert DateSelect component to TypeScript and update category query type.
#1483

Maintenance: DateSelect component to tsx & server-handlers get-categories type

---

packages/desktop-client/src/components/budget/MobileBudgetTable.js
upcoming-release-notes/1783.md

The sync button in the mobile budget header is overlapping with the new (triple verical dots) menu.

Fix mobile budget header sync button

---

packages/desktop-client/src/components/budget/BudgetCategories.js
packages/desktop-client/src/components/budget/BudgetTable.js
packages/desktop-client/src/components/budget/BudgetTotals.js
packages/desktop-client/src/components/budget/ExpenseCategory.js
packages/desktop-client/src/style/themes/dark.ts
upcoming-release-notes/1795.md

Much of the budget table wasn't themed, but had hard coded colors.  This moves over to the theme values.  Dark theme I think needs edited to fix the group colors.
Existing
New:

Darkmode: fix theming on budget table

---

packages/desktop-client/src/components/common/Modal.tsx
packages/desktop-client/src/components/modals/FixEncryptionKey.tsx
packages/desktop-client/src/icons/AnimatedLoading.tsx
packages/desktop-client/src/icons/Loading.tsx
packages/loot-core/src/client/state-types/queries.d.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/1784.md

Convert FixEncryptionKey, Loading, AnimatedLoading components to TypeScript and update get-payee query type.

Maintenance: Convert FixEncryptionKey, Loading, AnimatedLoading components to TypeScript

---

packages/desktop-client/src/components/ManageRules.tsx
packages/desktop-client/src/components/budget/util.ts
packages/desktop-client/src/components/modals/PlaidExternalMsg.tsx
packages/desktop-client/src/components/sort.tsx
packages/desktop-client/src/components/util/DisplayId.tsx
packages/loot-core/src/server/rules/types/handlers.ts
packages/loot-core/src/shared/rules.ts
packages/loot-core/src/types/models/rule.d.ts
upcoming-release-notes/1823.md

Convert Sort Utils, DisplayId, PlaidExternalMsg components to Typescript

Maintenance: Converting Utils and Sort to typescript

---

packages/desktop-client/src/components/FinancesApp.tsx
packages/desktop-client/src/components/GlobalKeys.tsx
packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/accounts/MobileAccount.js
packages/desktop-client/src/components/accounts/MobileAccounts.js
packages/desktop-client/src/components/budget/index.js
packages/desktop-client/src/components/common/ButtonLink.tsx
packages/desktop-client/src/components/common/Link.tsx
packages/desktop-client/src/components/manager/ConfigServer.tsx
packages/desktop-client/src/components/manager/subscribe/ChangePassword.tsx
packages/desktop-client/src/components/manager/subscribe/Error.tsx
packages/desktop-client/src/components/manager/subscribe/common.tsx
packages/desktop-client/src/components/modals/CreateLocalAccount.tsx
packages/desktop-client/src/components/payees/ManagePayeesPage.js
packages/desktop-client/src/components/settings/UI.tsx
packages/desktop-client/src/components/sidebar/SidebarWithData.tsx
packages/desktop-client/src/components/sidebar/Tools.tsx
packages/desktop-client/src/components/transactions/MobileTransaction.js
packages/desktop-client/src/hooks/useNavigate.ts
packages/desktop-client/src/util/router-tools.tsx
upcoming-release-notes/1808.md

Fixes https://github.com/actualbudget/actual/issues/1735

Custom useNavigate which tracks previous location

---

packages/desktop-client/src/components/transactions/MobileTransaction.js
upcoming-release-notes/1824.md

This PR allows categorising transactions to off budget accounts (as payee) when using mobile, in order to align with the behavior when using desktop.
Closes #1822

Allow categorise transfer to off budget accounts on mobile

---

packages/desktop-client/src/components/budget/MobileBudgetTable.js
packages/desktop-client/src/components/spreadsheet/CellValue.tsx
upcoming-release-notes/1844.md

Fix issue where mobile edit fields are shown when scrolling through budget in mobile

Fix mobile budget click handlers

---

packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
upcoming-release-notes/1855.md

Fixes https://github.com/actualbudget/actual/issues/1846

:bug:  fix: add missing top border for budget menu icon

---

packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
packages/desktop-client/src/components/budget/report/components.tsx
packages/desktop-client/src/components/budget/rollover/rollover-components.tsx
upcoming-release-notes/1856.md

:bug:  fix: bring back rollover arrow in budget page

---

packages/desktop-client/src/components/accounts/Account.js
packages/desktop-client/src/hooks/useSelected.tsx
upcoming-release-notes/1864.md

This PR improves the situation described in issue #283. Here's a demo:

Make Select All respect filters and splits

---

packages/desktop-client/src/components/modals/ImportTransactions.js
packages/desktop-client/src/components/modals/ImportTransactions.test.js
upcoming-release-notes/1862.md

Support dates like "Dec 24, 2020" and "december 24, 2020".
My new 401k provider gives CSVs that look like this:
```csv
Requested date,Fulfilled date,Transaction type,Pre-tax,Roth,Employer,Total,Transaction Id
"Dec 24, 2020","Dec 24, 2020",Payroll,1.00,2.00,3.00,4.00,TXN-REDACTED
```
This patch allows me to import their CSVs without having to adjust the file before importing it.

Support month names when importing transactions

---

packages/desktop-client/src/components/budget/BudgetSummaries.tsx
packages/desktop-client/src/components/budget/ExpenseGroup.js
packages/desktop-client/src/components/budget/MonthPicker.tsx
packages/desktop-client/src/components/budget/MonthsContext.tsx
packages/desktop-client/src/components/budget/SidebarCategory.tsx
packages/desktop-client/src/components/budget/SidebarGroup.tsx
packages/desktop-client/src/components/budget/rollover/BudgetSummary.tsx
packages/desktop-client/src/hooks/useResizeObserver.ts
upcoming-release-notes/1879.md

Convert BudgetSummaries, MonthPicker, SidebarCategory components to Typescript.

Maintenance: BudgetSummaries, MonthPicker, SidebarCategory components to tsx.

---

packages/loot-core/src/server/budget/goals/goalsBy.ts
packages/loot-core/src/server/budget/goals/goalsPercentage.ts
packages/loot-core/src/server/budget/goals/goalsRemainder.ts
packages/loot-core/src/server/budget/goals/goalsSchedule.ts
packages/loot-core/src/server/budget/goals/goalsSimple.ts
packages/loot-core/src/server/budget/goals/goalsSpend.ts
packages/loot-core/src/server/budget/goals/goalsWeek.ts
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1888.md

This is mostly a reorganization attempt to reduce the line count of goaltemplates.ts and move the logic for calculating each type of template into it's own file.  I think this could be useful when trying different logic, especially relating to schedules.
Test budget attached. It was exported in September, so the Income templates work best when applying the templates in that month.
[2023-09-22-_goal template tests.zip](https://github.com/actualbudget/actual/files/13310573/2023-09-22-_goal.template.tests.zip)

[Maintenance] Goals break out goal target calculations to individual files

---

packages/desktop-client/src/components/budget/ExpenseCategory.tsx
packages/desktop-client/src/components/budget/ExpenseGroup.tsx
packages/desktop-client/src/components/budget/IncomeCategory.tsx
packages/desktop-client/src/components/budget/RenderMonths.tsx
packages/desktop-client/src/components/budget/SidebarCategory.tsx
packages/desktop-client/src/components/budget/SidebarGroup.tsx
packages/desktop-client/src/components/sidebar/Account.tsx
packages/desktop-client/src/components/sort.tsx
upcoming-release-notes/1897.md

Convert ExpenseGroup, ExpenseCategory, IncomeCategory components to Typescript.

[Maintenance] Convert ExpenseGroup, ExpenseCategory, IncomeCategory components to Typescript.

---

packages/desktop-client/src/style/themes/dark.ts
packages/desktop-client/src/style/themes/light.ts
upcoming-release-notes/1911.md

Fixing previous merge due to duplicate colors in theme files.

Duplicate color removal

---

packages/loot-core/src/server/budget/goals/goalsSchedule.ts
packages/loot-core/src/shared/months.ts
upcoming-release-notes/1917.md

Resolves #1913 
When the next_date loop is executed, it is iterated in 1 day increments looking for a 'next schedule'.  What was happening was the loop had a current date that occurred on a weekend and when we went to get the next occurrence (which should land on the weekend) it was returning that occurrence 1 day before.  So each time the loop was set back 1 day before adding the 1 day and we had an infinite loop condition.  I've added a check to look for how many days difference the current date and the next date are, and if that value is 0, it will add 3 days instead of 1.  I used 3 to resolve the same situation had the schedule landed on a Sunday.

[Bugfix] Goals: Fix Schedule Infinite loop

---

packages/desktop-client/src/components/autocomplete/AccountAutocomplete.tsx
packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
packages/desktop-client/src/components/autocomplete/PayeeAutocomplete.tsx
packages/desktop-client/src/components/autocomplete/SavedFilterAutocomplete.tsx
packages/desktop-client/src/components/common/Button.tsx
packages/desktop-client/src/components/modals/CloseAccount.tsx
packages/loot-core/src/client/actions/queries.ts
upcoming-release-notes/1923.md

Convert CloseAccount, AccountAutocomplete, SavedFilterAutocomplete, PayeeAutocomplete components to Typescript.

[Maintenance] Update CloseAccount, AccountAutocomplete, SavedFilterAutocomplete, PayeeAutocomplete components to Typescript.

---

packages/desktop-client/src/components/common/InputWithContent.tsx
packages/desktop-client/src/components/util/AmountInput.tsx
upcoming-release-notes/1936.md

- Small refactor to start exploring the codebase. Maintains parity with the previous JS component.
- Tweaked the props of the `InputWithContent` component to reflect how it is used and quell the typescript errors.
- Most uses  appear to omit `leftContent` or `rightContent` so this allows for that instead of explicitly passing undefined values.
- It probably never makes sense to use this component with neither prop, but adding a union with an intersection representing the exclusive optional cases is pretty ugly.
I was going to do `GenericInput` too, but that's some form of factory pattern that requires a bit more thought so keeping this PR tight and simple.
Part of #1483

[Maintenance] Refactor amount input to typescript

---

packages/api/package.json
upcoming-release-notes/1934.md

so that a warning comes up if you try to install the package with lower version of node then what is required
Should hopefully fix #1903

Specify minimum node version for @actual-app/api nom package

---

packages/loot-core/src/shared/util.ts
upcoming-release-notes/1938.md

- Fixes space-comma format for newer NodeJS versions (18.18, and 21.x)
en_ZA no longer follows space-comma format in ICU 73 data, so switching to en_SE to restore functionality.
The locale details for en_SE can be found here: https://github.com/unicode-org/icu/blob/main/icu4c/source/data/locales/en_SE.txt
Fix for https://github.com/actualbudget/actual/issues/1937

Switch from en-ZA to en-SE for space-comma NumberFormat

---

packages/loot-core/src/server/accounts/ofx2json.ts
upcoming-release-notes/1921.md

Support multiple months in experimental ofx parser

---

packages/desktop-client/src/components/mobile/MobileAmountInput.js
upcoming-release-notes/1929.md

Hello there,
This pull request is in response to positive feedback on my suggestion noted on #1782.
It's been a while since I originally added those observations. After a quick test on my end, I can confirm the minor change is still applicable.
**EDIT:** Noticed a bunch of E2E and VRT failures. If they are legitimate (I'm unsure), perhaps this change needs to be rethought.
---
Closes #1782

Fix flickering scroll bar on mobile transaction input (#1782)

---

packages/desktop-client/src/components/payees/ManagePayees.js
packages/desktop-client/src/components/payees/PayeeMenu.tsx
packages/desktop-client/src/components/payees/PayeeTable.tsx
packages/desktop-client/src/components/payees/PayeeTableRow.tsx
packages/desktop-client/src/components/table.tsx
upcoming-release-notes/1948.md

The diff might be hard to compare on this one as I'm factoring components out of the large `index.js` file (unclear why that's an index file to begin with). The main changes are:
- Components are the same, but with typing for the props.
- Hardening of parameters and props for the `Table` component and associated `useTableNavigator` hook. This was needed to correctly propagate types through to the table item rendering function and elsewhere that fields and IDs are exposed.
The main oddities in here:
- The `PayeeEntity` type defined in `loot-core`'s models has an optional `id`. That is incompatible with the `TableItem` type expected by the `Table` component. Potentially that optionality is incorrect, but rather than scour the codebase to confirm if that's the case I've just added a …

[Maintenance] Refactor payee table to typescript

---

packages/api/methods.js
packages/loot-core/src/server/accounts/sync.ts
packages/loot-core/src/server/accounts/transactions.ts
packages/loot-core/src/server/api.ts
packages/loot-core/src/server/importers/ynab4.ts
packages/loot-core/src/server/importers/ynab5.ts
upcoming-release-notes/1944.md

- Enable learnCategories support in ynab transaction importing
- Exposes learnCategories up through the api
- Adds runTransfer conditions to batchUpdateTransactions so importer can still skip transfer processing
Part of https://github.com/actualbudget/actual/issues/1943

Create category rules for ynab imports

---

packages/desktop-client/src/components/transactions/MobileTransaction.js
upcoming-release-notes/1955.md

The category field in mobile transaction is disable and empty when the transaction is a transfer or account is off budget. This PR adds a `Transfer` and `Off Budget` text to the field similar to how it is done in the desktop transactions table.

Transfer and Off Budget category in mobile

---

packages/desktop-client/src/components/modals/GoCardlessExternalMsg.js
packages/desktop-client/src/components/modals/PlaidExternalMsg.tsx
upcoming-release-notes/1970.md

Why do this change? The button had green default color and then on hover it turned purple. Which is pretty weird.. Instead we can just use the default colors for it. Makes things easier
| Before | After |
|--------|--------|
|<img width="573" alt="Screenshot 2023-11-25 at 17 59 23" src="https://github.com/actualbudget/actual/assets/886567/d5cfadb1-561f-4156-bdba-129c1363c997">| <img width="577" alt="Screenshot 2023-11-25 at 17 58 53" src="https://github.com/actualbudget/actual/assets/886567/4f8ec876-18f4-4f07-9378-a7b33a514623"> |

:art: (fix) gocardless success button color

---

packages/desktop-client/src/components/budget/SidebarGroup.tsx
upcoming-release-notes/1975.md

There's a bug when user cancel add group (leave the input blank and click outside input). I've manage it with delete `value: undefined` in inputProps following SidebarCategory.tsx code.

Fix cancel add category group

---

packages/desktop-client/src/components/modals/ConfirmCategoryDelete.tsx
packages/desktop-client/src/components/modals/GoCardlessExternalMsg.tsx
packages/desktop-client/src/components/modals/ManageRulesModal.tsx
packages/loot-core/src/types/models/gocardless.d.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/1972.md

Update ConfirmCategoryDelete, GoCardlessExternalMsg, ManageRulesModal to tsx

[Maintenance] Update ConfirmCategoryDelete, GoCardlessExternalMsg, ManageRulesModal to tsx

---

packages/loot-core/src/server/budget/goals/goalsSchedule.ts
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/1984.md

There was an omission from the recent refactor.  This will pass the scheduleFlag argument back to the main function so that the loop is not run multiple times.
Fixes https://github.com/actualbudget/actual/issues/1983

[Bugfix] Goals: Schedule overbudget condition

---

packages/api/index.js
packages/api/package.json
packages/api/validateNodeVersion.js
upcoming-release-notes/1980.md
yarn.lock

Validates minimum node version to 18.12.0 for @actual-app/api npm package

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/2000.md

Priority sorting was using alphabetical sorting instead of numeric sorting.  This fixes it to sort as expected.
Fixes #1999

[Goals]: Sort the priorities properly

---

packages/desktop-client/src/components/NotesButton.tsx
packages/desktop-client/src/components/Notifications.tsx
packages/desktop-client/src/components/ThemeSelector.tsx
packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/UpdateNotification.tsx
packages/desktop-client/src/components/accounts/Header.js
packages/desktop-client/src/components/budget/BudgetTotals.tsx
packages/desktop-client/src/components/budget/MobileBudgetTable.js
packages/desktop-client/src/components/budget/report/budgetsummary/BudgetSummary.tsx
packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
packages/desktop-client/src/components/manager/BudgetList.js
packages/desktop-client/src/components/schedules/SchedulesTable.tsx
packages/desktop-client/src/components/select/RecurringSchedulePicker.js
packages/desktop-client/src/components/sidebar/ToggleButton.tsx
packages/desktop-client/src/components/transactions/TransactionsTable.js
packages/desktop-client/src/components/util/AmountInput.tsx
upcoming-release-notes/2025.md

Adding aria-labels to some buttons to improve accessibility score. 
Notes: 
- There's still loads of issues left - I've only tackled a few here
- Color contrast is a common issue across pages
- Might want to start adding data-test-id to elements to make the Puppeteer tests more resilient

[Maintenance] Adding Aria labels for accessibility

---

packages/loot-core/src/server/db/index.test.ts
packages/loot-core/src/server/db/index.ts
upcoming-release-notes/2002.md

I'm not 100% familiar with the design of the data model so may have misinterpreted what's going on here, but how I read this:
- The tombstone flag is used to soft delete categories.
- When creating a new category, duplicate names within a group are prevented.
- When checking for duplicate names, the tombstone flag was unchecked which meant deleted categories were falsely blocking creation.
I had a look at category deleteion logic to verify that simply including the tombstone flag in this check is sane and see that there's a category mapping being maintained to redirect one category to another on deletion. So from what I can tell the correct behaviour here is to allow a new category with the previously deleted name, rather than to revive the old category (to preserve that old mapping …

Fix failure to create category with deleted name

---

.eslintrc.js
packages/desktop-client/src/components/NotesButton.tsx
packages/desktop-client/src/components/ScrollProvider.tsx
packages/desktop-client/src/components/Titlebar.tsx
packages/desktop-client/src/components/budget/report/ReportContext.tsx
packages/desktop-client/src/components/budget/rollover/RolloverContext.tsx
packages/desktop-client/src/hooks/useSelected.tsx
packages/loot-core/src/client/data-hooks/accounts.tsx
packages/loot-core/src/client/data-hooks/payees.tsx
packages/loot-core/src/client/data-hooks/schedules.tsx
packages/loot-core/src/client/query-hooks.tsx
upcoming-release-notes/2029.md

Enabling `react/no-children-prop` rule and fixing the issues.

:recycle: (eslint) enable 'react/no-children-prop' rule and fix issues

---

packages/api/methods.test.ts
upcoming-release-notes/2036.md

Part of https://github.com/actualbudget/actual/issues/1074
Adds tests for the category APIs

Add API category tests

---

packages/desktop-client/src/components/common/Modal.tsx
upcoming-release-notes/2082.md

Added a bit of margin on the sides of modals:

Add left and right margins to modals

---

packages/desktop-client/src/components/budget/rollover/RolloverComponents.tsx
upcoming-release-notes/2093.md

Fix issue 1878

---

packages/loot-core/src/server/budget/types/handlers.d.ts
packages/loot-core/src/server/mutators.ts
packages/loot-core/src/server/undo.ts
packages/loot-core/src/shared/async.ts
packages/loot-core/src/types/api-handlers.d.ts
packages/loot-core/src/types/handlers.d.ts
packages/loot-core/src/types/server-handlers.d.ts
tsconfig.json
upcoming-release-notes/2065.md

Fixing first batch of issues that become visible when enabling `strictFunctionTypes`.

:recycle: (TypeScript) fix strictFunctionTypes violations (pt 1)

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/2099.md

If someone had pre-budgeted a category and only applied the templates instead of overwrote with templates, the over budget checks wouldn't consider the amounts budgeted in those already budgeted categories, causing over budget.
This changes the process of leaving existing budgets by removing those categories from the list of templated categories, instead of saving and reapplying the previous amount.
Ive attatched a test budget that shows what was happing.
There are two templates that together budget the available funds.  They both have priorities set so they shouldn't be allowed to over budget.  The one category has a budgeted value.  
Select "Apply Budget Templates" and see the over budget even though that shouldn't be allowed.
[2023-12-17-_test-budget.zip](https://github.com/actualbudget …

[Goals]: fully skip budgeted categories when only applying

---

packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/2100.md

Fixes an issue where non-hidden categories in hidden groups would get run during template processing

[Goals]: don't run templates in hidden groups

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/2140.md

reconciled (locked) transactions should not get updated upon importing
Closes #2103

:bug: (import) fix reconciled transactions getting overriden on import

---

packages/desktop-client/src/components/ManageRules.tsx
packages/desktop-client/src/components/rules/SimpleTable.tsx

Builds on https://github.com/actualbudget/actual/pull/2141 to fix the load more rules functionality mentioned in #1502.
I've tested on my display with chrome and firefox, and this seems to do the trick and simplifies some extraneous useEffect.  More testers would be welcome!
Note this PR is branched off matiss/fix-1502, so the request is to get merged into that branch and not master... If you want to handle it some other way, let me know and i can update.

Fix load more when scrolling to end of rules table

---

packages/desktop-client/src/components/ManageRules.tsx
packages/desktop-client/src/components/rules/SimpleTable.tsx
upcoming-release-notes/2141.md

Previously the filtering was applied only to the loaded data. Meaning if there are >1 pages of data - it would initially apply only to the first page. After this fix - the filters are applied to all the pages.

:bug: (rules) fix filtering in the rules page

---

packages/desktop-client/src/components/filters/FiltersMenu.jsx
packages/loot-core/src/shared/rules.ts
upcoming-release-notes/2108.md

PR #1789 added a flag for reconciled transactions. This PR adds a new filter that lets you filter reconciled transactions.
https://github.com/actualbudget/actual/assets/5488094/dcf29674-7954-4a7b-ad36-ad1d8e096e3c

Adding filter for reconciled transactions

---

packages/desktop-client/src/components/accounts/Account.jsx
packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/2134.md

Simple change adding `date` to the fields that should trigger a confirmation prompt when editing a locked transaction. Aside from the amount, it seems like preventing accidental changes in transaction date is the most important reason that something would not be considered consistent with the bank statement - the order of transactions.
This addition only affects places that already had such a check in the first place - i.e. the mobile UI is unaffected since it triggers the confirmation prompt regardless of the field that is edited.

Ask for confirmation when editing date of a locked transaction

---

packages/desktop-client/src/components/transactions/TransactionsTable.jsx
upcoming-release-notes/2144.md

Fixes #2041 
A race condition existed where the parent transaction in `transactionMap` was not yet updated to reflect the recently added child transaction when `onCheckEnter()` is called.
This PR gets the parent transaction from the same transactions array that the child transaction is retrieved from, which reflects the latest split calculation / error state.

Fix when pressing Enter adds an extra split transaction when no split remains

---

packages/desktop-client/src/components/accounts/MobileAccount.jsx
upcoming-release-notes/2114.md

Hello,
if you access the mobile view from a "special" account url the website crashes:
/accounts/budgeted
/accounts/offbudget
/accounts/uncategorized
To recreate resize your browser while accessing one of the mentioned urls.
The Problem in my opinion is that these accounts not really exist and so account is later undefined and not able to be queried for the balance etc.
My simple fix is a little "error" page with a button back to the Accounts Overview:
Thank you

Add "error" Page for special accounts in Mobile

---

packages/desktop-client/src/components/budget/report/budgetsummary/ExpenseProgress.tsx
packages/desktop-client/src/components/budget/report/budgetsummary/IncomeProgress.tsx
upcoming-release-notes/2196.md

I was thinking that the color of the report budget pie chart background looked a bit off, especially in dark mode.  This would change the color to match the table background instead of the page background.
Existing:
New:

change the pie chart background color in the report status

---

packages/desktop-client/src/components/budget/report/ReportComponents.tsx
upcoming-release-notes/2195.md

Fix the missing border on the category budget dropdown in report budget.
New:
Existing:

fix missing borders in single category drop down in report budget

---

.github/workflows/e2e-test.yml

Reverts actualbudget/actual#2074
Sadly this won't work for forks. They do not have our github token (security) and hence the fork PRs won't have the comment added to them.

Revert ":construction_worker: (ci) adding helper comments for failed CI jobs"

---

.github/workflows/electron-master.yml
.github/workflows/electron-pr.yml
upcoming-release-notes/2209.md

Electron builds in PRs are now failing. Apparently even if an empty `CSC_LINK` env variable is set - it kicks off code signing. Which will obviously not work.. and should not work in PRs coming from forks.
So I'm splitting the electron build job in 2x: one that runs on master (and code signs & notarizes the build) and one that runs on PRs (no code signing).
https://github.com/electron-userland/electron-builder/issues/6921

:wrench: (ci) fork the electron build job - master and PR

---

packages/loot-core/src/mocks/budget.ts
packages/loot-core/src/platform/server/connection/index.web.ts
packages/loot-core/src/server/main.ts
packages/loot-core/src/server/mutators.ts
packages/loot-core/src/server/schedules/types/handlers.ts
packages/loot-core/src/types/api-handlers.d.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/2136.md

- Args and return values from runHandler should now work within loot core
- Updated some of the handler types to be more accurate
Split from https://github.com/actualbudget/actual/pull/2053 to start preparing to bring types to the API.
Can be verified by going to one of the places that runHandlers is called, like the main.test.ts or the mocks/budget.ts and trying to put in some incorrect args to a handler that is strongly typed.
Like the following where a `test: "this will error"` was added:
```
await runHandler(handlers['schedule/create'], {
schedule: {
name: 'Phone bills',
posts_transaction: false,
test: "this will error",
},
conditions: [
{
op: 'is',
field: 'payee',
value: payees.find(item => item.name === 'Dominion Power').id,
},
{
op: 'is',
field: 'account',
value: account.id,
},
{ …
```

Add proper types to runHandler

---

.github/workflows/size-compare.yml
packages/desktop-client/vite.config.mts
upcoming-release-notes/2224.md

- Change to more closely match the `.chunk` syntax we use with webpack
- This should improve an issue with our size compare as well
The improvement for size compare is that our github action is stripping out the hashes before passing the size compare, but was based on the period.
We have the additional difficulty here of rollup using base64 hashes, which can include `_-` which complicates our ability to just strip out what we want.
This should improve the output, but there likely is a few more tweaks to be made, as our current vite stats seem to be missing the css and font sizes, which were previously present in this action.
Because this action uses `pull_request_target` only the action from master is run. In order to test the changes here I opened a sibling PR using just `pull_reqest`. …

Change the vite chunk filename hash usage

---

packages/desktop-client/package.json
packages/desktop-client/vite.config.mts
upcoming-release-notes/2233.md
yarn.lock

- Swap our swc plugin to remove-react-properties
- Configure remove-react-properties to preserve our testids
We need to pass a swc-plugin in order for swc to be used during build (using it at build matches what we did for webpack prior to vite), otherwise it only gets used for the dev server. The remove console plugin was doing what it promised! (I had misread it's config when I added it, and thought I had effectively disabled it by passing an empty config).
The plugins we have to choose from are here: https://github.com/swc-project/plugins/tree/main/packages
I don't think any of them are necessary for actual at this time, so I choose the remove react properties plugin. I had to configure it a bit with some property, otherwise it will strip out all our data-testids by default. So now it …

Restore ability to use console.log in vite

---

packages/loot-core/src/shared/async.ts
packages/loot-core/src/shared/months.ts
packages/loot-core/src/shared/query.ts
packages/loot-core/src/shared/schedules.ts
packages/loot-core/src/shared/test-helpers.ts
upcoming-release-notes/2228.md

Part 2 of: https://github.com/actualbudget/actual/pull/2212

♻️ (typescript) fixing strictNullChecks=true issues

---

packages/desktop-client/src/components/reports/ChooseGraph.tsx
packages/desktop-client/src/components/reports/ReportSummary.tsx
packages/desktop-client/src/components/reports/graphs/AreaGraph.tsx
packages/desktop-client/src/components/reports/graphs/BarGraph.tsx
packages/desktop-client/src/components/reports/graphs/DonutGraph.tsx
packages/desktop-client/src/components/reports/graphs/StackedBarGraph.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
packages/desktop-client/src/components/reports/spreadsheets/calculateLegend.ts
packages/loot-core/src/types/models/index.d.ts
packages/loot-core/src/types/models/reports.d.ts
upcoming-release-notes/2244.md

Moving entities and updating existing. Also creating a new entity for the custom report data.

Custom Reports update entites

---

packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
upcoming-release-notes/2249.md

I had a comparison typescript matching issue that causes the table graph in custom reports to crash.

Custom Reports: fix broken table

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
upcoming-release-notes/2250.md

Lately we have been getting a lot of GoCardless "bug reports" due to either mismatching bank data (due to a missing bank-mapper) or user server misconfigurations. It's very rare that the bank-sync reported issues are actual bug reports.
Hence adding a bit more friction here.
1. a support link will be available directing folks to Discord for support
2. additional block for gocardless bug reports - a bit of friction so we don't need to continue asking for additional information

:wrench: add link to community discord for support

---

packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTable.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableHeader.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableList.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableRow.tsx
packages/desktop-client/src/components/reports/graphs/tableGraph/ReportTableTotals.tsx
packages/desktop-client/src/components/reports/reports/CustomReport.jsx
upcoming-release-notes/2258.md

I left out the final useage for compact elements in last compact PR. Adding now.

add compact to custom reports

---

packages/desktop-client/src/components/Titlebar.tsx
upcoming-release-notes/2273.md

The "uncategorized transactions" banner is flashing on page load. This is because `count` variable can also be `null`. 
And while I was working in the file: made it strict TS compliant.

:bug: fix uncategorized transaction banner flashing on load

---

packages/desktop-client/src/components/table.tsx
upcoming-release-notes/2277.md

- Drop unused usage of forwardRef on TableWithNavigator
Fixes a warning being throw in the console and during web tests regarding a missing ref parameter to forwardRef.
Example of the warning can be seen in the current master tests here: https://github.com/actualbudget/actual/actions/runs/7622910204/job/20761871770#step:4:29

:bug: Fix a missing ref param warning for forwardRef

---

packages/desktop-client/src/components/modals/ImportTransactions.jsx
upcoming-release-notes/2278.md

- Fixes an error regarding passing `false` to title when category is not available

:bug: Avoid passing a boolean to the import trans category title

---

packages/loot-core/src/server/budget/actions.ts
upcoming-release-notes/2281.md

There is an error in the database insertion if the entry doesn't initially exist when applying goal templates.
Previously an entry like this: 
would be created.  With this change, an entry like this: 
will be created.  The issue I was seeing was that the color coded goal templates were not always rendering color, and in the process of tracking the issue down discovered this as the root issue.

[Bugfix] Goals: Database entry

---

packages/desktop-client/src/components/budget/MobileBudget.tsx
packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
upcoming-release-notes/2263.md

No functional changes. This is just to re-use the same `useSingleActiveEditForm` hook that is currently being used in mobile transaction page. The hook prevents editing any other field when another one is currently being edited/active.

[Cleanup] useSingleActiveEditForm hook on mobile budget table

---

packages/loot-core/src/server/budget/cleanup-template.ts
upcoming-release-notes/2282.md

This change will update the monthly target to match the spent value for the month after applying the 'End of month cleanup' tool.  The end result is that after reallocating funds from source categories to sink categories, the balance will remain green instead of turning yellow for source categories.

[Enhancement] Goal Target with cleanup template

---

packages/desktop-client/src/components/accounts/Header.jsx
packages/loot-core/migrations/1704572023730_add_account_sync_source.sql
packages/loot-core/migrations/1704572023731_add_missing_goCardless_sync_source.sql
upcoming-release-notes/2308.md

Patching a migration that for whatever reason did not update the `account_sync_source` field. Thus `goCardless` broke for some random accounts.
Also patching the `sync` button in the UI:
- the sync button should not be visible if the server is not connected (thus bank-sync will be unavailable)
- the sync button should be disabled if the customer if offline (thus also the bank-sync will not be available until reconnection)

:bug: (goCardless) patch incomplete migration

---

packages/desktop-client/src/components/budget/rollover/budgetsummary/BudgetSummary.tsx
upcoming-release-notes/2313.md

Fixes the issue brought up [on discord here](https://discord.com/channels/937901803608096828/1027831756545609789/1202623348669161482).  Light theme still works as expected.
Before:
After:

fix budget header collapsed colors

---

.github/actions/setup/action.yml
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/codeql.yml
.github/workflows/e2e-test.yml
.github/workflows/electron-master.yml
.github/workflows/electron-pr.yml
.github/workflows/issues-feature-implemented.yml
.github/workflows/release-notes.yml
.github/workflows/size-compare.yml
upcoming-release-notes/2319.md

Same as https://github.com/actualbudget/actual-server/pull/307

:wrench: upgrade deprecated github actions

---

docker-compose.yml
packages/desktop-client/README.md
upcoming-release-notes/2316.md

Quality of Life enhancement. Stumbled upon this when running the Visual Regression Tests. Update the VRT docs to reflect dev container usage together with the HTTPS flag as well.

[Maintenance] Pass HTTPS flag to dev container to enable HTTPS

---

bin/docker-start
upcoming-release-notes/2304.md

Don't launch browser when in docker
Fixes https://github.com/actualbudget/actual/issues/2301

Fix docker start browser error

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/2309.md

Match split transaction entries when importing transactions

Consider child transactions when fuzzy matching imported transactions

---

packages/loot-core/src/server/accounts/sync.ts
upcoming-release-notes/2300.md

Currently, when a new transaction is imported, if the transaction doesn't match an existing transaction with the same imported ID, Actual tries to fuzzy match the transaction with an existing transaction. To do this, Actual selects all existing transactions 4 days prior and 1 day after the imported transaction date. It then runs some logic to try to find a matching existing transaction from the ones selected.
The problem is 4 days prior and 1 day after is too restricting. The few issues are:
There's no reason why the match logic shouldn't be symmetrical (so 4 days prior and 4 days after)
Quite frequently, this logic fails to find the right transaction because the imported transaction might be 2 days after or 5 days prior. This is extremely noticeable with transfers between accounts. …

Change lookback and look forward time range when fuzzy matching

---

packages/desktop-client/src/components/autocomplete/Autocomplete.tsx
upcoming-release-notes/2325.md

This fixes an annoying bug I noticed: if you have a dropdown open, and select an item, you can't then go and modify what you typed and select a new item without refocusing the field (it just clears a state). Illustration:
1. Find an item
2. Select it
3. Try to edit your selection; no dropdown appears again
With this PR, step 3 now looks like this:
This is useful for certain keyboard-based workflows, as you can `CTRL-A, Backspace` to search for a new category (or`Backspace` a single letter to search common prefixes) instead of `Blur field, refocus field`.

Re-open autocomplete dropdown on change

---

packages/desktop-client/src/components/accounts/Header.jsx
packages/desktop-client/src/components/common/Input.tsx
packages/desktop-client/src/components/sidebar/SidebarWithData.tsx
upcoming-release-notes/2327.md

Resolves a confusing behaviour where clicking outside the field erased changes instead of saving them (this didn't match how transactions behave). This PR makes the title field consistent with how transactions behave.
In detail:
1. Budget and account name fields will save their values on blur.
2. Budget and account name fields can still be cleared by pressing "Escape".

Save name fields on unfocus

---

packages/loot-core/src/types/api-handlers.d.ts
upcoming-release-notes/2334.md

A simple second pass at api-handlers type
Just updating the ones that have matching return types in the server handlers.
Further passes will need to also get the server handlers into better shape.

Typescript: pass 2 at updating api-handlers to match server handlers

---

packages/loot-core/src/platform/client/fetch/index.d.ts
packages/loot-core/src/platform/client/fetch/index.web.ts
upcoming-release-notes/2343.md

Patching a incorrect return type for `sendCatch` method.

:bug: (typescript) patching sendCatch type

---

packages/loot-core/src/server/accounts/ofx2json.ts
upcoming-release-notes/2342.md

- Return an empty array instead of an array of undefined
Related to parse error seen in https://github.com/actualbudget/actual/issues/2331

Fix parse errors with OFX data with no transactions

---

packages/desktop-client/src/components/accounts/MobileAccounts.jsx
packages/desktop-client/src/components/budget/MobileBudgetTable.jsx
packages/desktop-client/src/components/mobile/MobileNavTabs.tsx
packages/desktop-client/src/components/responsive/PullToRefresh.tsx
upcoming-release-notes/2352.md

Suggested quick fix for https://github.com/actualbudget/actual/issues/2040. 
Adds padding to the bottom of pages where the mobile navigation bar is displayed, to avoid the fixed position of the bar overlapping page content.
Bug was especially visible on Safari iOS.

fix: Mobile menu blocks items #2040

---

tsconfig.json
upcoming-release-notes/2380.md

Add folders to tsconfig excludes to fix vscode "Configure Excludes" warning and make ts server work.

[Maintenance] Add tsconfig excludes

---

package.json
packages/desktop-client/package.json
packages/desktop-client/vite.config.mts
packages/loot-core/src/platform/server/fs/index.web.ts
upcoming-release-notes/2369.md
yarn.lock

This PR adds a vite plugin for offline PWA support, so that you can install the app as a PWA and then use it offline.
It worked well in my brief testing (both in dev and after installing), but would love other folks to try it out and let me know their thoughts.

Add plugin for offline PWA support

---

packages/desktop-client/src/components/modals/EditRule.jsx
packages/desktop-client/src/components/rules/ActionExpression.tsx
packages/desktop-client/src/components/rules/RuleRow.tsx
packages/loot-core/src/server/accounts/transaction-rules.ts
packages/loot-core/src/server/rules/app.ts
packages/loot-core/src/shared/rules.ts
packages/loot-core/src/types/models/rule.d.ts
upcoming-release-notes/2368.md

This PR adds additional UI for the rules-with-splits experimental feature. This should make it easier to tell what a rule is doing when it has splits.

Display rules with splits on rules page

---

packages/loot-core/src/shared/util.test.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/2399.md

Attempt to fix #2374.  
This puts a strict limit to 1 or 2 decimal places.  The test is complaining because there is one that passes in three decimal places.  Are there regions where decimal amounts have more than 2 digits? If so then this bug is unfixable without a major overhaul of the parsing to have a known data format, where currently the parsing is format agnostic.
Looks like there are a few places that have 3 decimal places for financial data, mostly in the middle east.  Im not sure there is a way to fix the issue without blocking potential users from those countries.  Does anyone else have ideas on how to parse the csv in the issue without limiting to 2 decimal places?

Update csv amount parser.  Fix #2374

---

packages/desktop-client/e2e/accounts.test.js
packages/desktop-client/e2e/page-models/account-page.js
packages/desktop-client/src/components/accounts/Account.jsx
packages/desktop-client/src/components/accounts/Header.jsx
packages/desktop-client/src/components/table.tsx
packages/desktop-client/src/components/transactions/SelectedTransactions.jsx
packages/loot-core/src/client/transfer.test.ts
packages/loot-core/src/client/transfer.ts
upcoming-release-notes/2398.md

Add an option in the selected transactions menu in mutli-account budget pages (all accounts, for budget/etc), that allows you to relate two transactions across accounts as a transfer. 
Feature: https://github.com/actualbudget/actual/issues/1891
- Transactions amount must match
- Transactions must be from different acounts
- Split transactions not eligible
Single account pages don't show the option at all in the selection menu:
Multi account pages always show the option in the selection menu, but disabled when the selections are not valid for the transfer action:
For valid selections the action is enabled in the selection tooltip:

Add option to make a transfer from two selected transactions

---

packages/loot-core/src/server/budget/cleanup-template.ts
upcoming-release-notes/2409.md

#2295 introduced the logic to automatically fund rollover categories after non-rollover categories and before utilizing the sink categories.  This PR reverts that logic.  The documentation will be amended to recommend using the 'sink' term on rollover balance categories if the desire is to fund those categories.  This approach allows both workflows.

[End of Month Cleanup] Remove automatic funding of rollover categories

---

packages/loot-core/src/server/budget/goals/goalsSchedule.ts
upcoming-release-notes/2404.md

A simple schedule, one that is recurring monthly and is budgeted fully every month, would not consider an existing balance.  This PR adds 2 things.
1.  If a simple schedule, not combined with schedule it is greater than 1 month (sinking fund), has a category balance and that balance is less than needed to complete the schedule... the budgeted amount will only add the difference needed to complete the schedule.
Example:   75 is needed for this month, 50 is in the category from last month.  The budgeted amount will be 25.   (Previously, it would be 75.)
2.  The filter for finding schedules is simplified and less error prone.  The only filter specified is one for monthly recurring or 'full' schedules.  This PR implements a negate filter for all other schedules so it's more guaranteed not to …

[Goals] Schedule top off amount

---

packages/desktop-client/e2e/accounts.test.js
upcoming-release-notes/2434.md

- If tests ran too fast, the transactions wouldn't finish rendering before the select of the transactions was attempted.

Fix flaky transfer e2e test

---

packages/desktop-client/src/components/accounts/Account.jsx
upcoming-release-notes/2447.md

This fixes #2397 by having scheduled transactions also show when on the "All accounts" page.
A side effect is it also fixed the issue of past transactions that are linked to schedules not showing the schedule icon.

Show scheduled transactions when viewing "All accounts"

---

packages/desktop-client/src/components/Modals.tsx
packages/desktop-client/src/components/accounts/Account.jsx
packages/desktop-client/src/components/modals/ConfirmUnlinkAccount.tsx
upcoming-release-notes/2441.md

This PR fixes #2440 by adding a modal that shows whenever someone clicks "Unlink account" from the account menu.  The modal will confirm if they want to unlink and provide and option to cancel.

Show a modal to confirm unlinking accounts

---

packages/desktop-client/src/components/budget/BudgetTable.jsx
upcoming-release-notes/2452.md

- restore the collapsed property
Fixes: https://github.com/actualbudget/actual/issues/2430
Followup to: https://github.com/actualbudget/actual/pull/2293

Fix budget key tab navigation

---

packages/desktop-client/src/components/autocomplete/CategoryAutocomplete.tsx
packages/desktop-client/src/components/autocomplete/ItemHeader.tsx
packages/desktop-client/src/style/themes/midnight.ts
upcoming-release-notes/2461.md

Also thrown in a change to make ItemHeader component not depend on category groups as it's also used by other types of autocomplete components
Before:
After:

Fix midnight theme autocomplete hover

---

packages/desktop-client/src/components/accounts/Account.jsx
upcoming-release-notes/2475.md

This fixes #2454 so that when viewing uncategorized transactions, it does not attempt to show any upcoming scheduled transactions.  The error message goes away, and no upcoming transactions are shown.

Fix error when viewing uncategorized transactions when there are upcoming scheduled transactions.

---

packages/desktop-client/src/components/reports/spreadsheets/cash-flow-spreadsheet.tsx
upcoming-release-notes/2485.md

Closes #2237
Do not include off-budget transfers in the "expenses" in the cash flow card
Demo budget file: 
[2024-03-21-_test-budget.zip](https://github.com/actualbudget/actual/files/14705805/2024-03-21-_test-budget.zip)

:bug: (report) do not include offbudget transfers in cash-flow card expenses

---

packages/desktop-client/src/components/modals/ImportTransactions.jsx
packages/loot-core/src/shared/util.ts
upcoming-release-notes/2494.md

Closes #1811
Disallow importing transactions with too large or too small amounts. These transactions are poison pills. We allow to import them, but afterwards they crash the app with no way to recover. So now it will no longer be possible to import with poison pill amounts.

:bug: (import) disallow importing transactions with too large or small amounts

---

packages/desktop-client/src/components/mobile/accounts/Account.jsx
packages/desktop-client/src/components/mobile/accounts/AccountDetails.jsx
packages/desktop-client/src/components/mobile/accounts/Accounts.jsx
upcoming-release-notes/2476.md

This is a first attempt at fixing #2473.  It adds account sync indicators to the account details page when on mobile:
It also does a few tweaks to how the sync indicators are handled on mobile:
- It left-aligns the indicators, so they are in a column. This mimics the non-mobile behavior.
- It updates them to show failed/pending status (currently it always shows green).
- It updates to use the same theme colors as the non-mobile indicators.

feature: Show account sync indicators when viewing accounts on mobile

---

packages/loot-core/src/server/accounts/sync.ts
packages/loot-core/src/server/main.ts
upcoming-release-notes/2529.md

We keep getting many bug reports about gocardless/simplefin. And in most cases (or ALL cases?) they are not legitimate issues in Actual, but it's hard to troubleshoot and help without some more debug information.
So this PR adds a few more console.log lines to ease the troubleshooting process.

:chart_with_upwards_trend: adding extra console.log lines for bank-sync to help with troubleshooting

---

packages/loot-core/src/server/budget/goals/goalsSimple.ts
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/2535.md

If using a template such as #template up to 1000, the budgeted amount would not reach 1000 if a negative balance was rolled over from the previous month. This change allows for rolling over a negative balance from a previous month.
I've tested 3 scenarios:
Category balance of -500. Budgeted amount is 1500.
Category balance of 0. Budgeted amount is 1000.
Category balance of 500. Budgeted amount is 500.
All scenarios result in a final category balance of 1000, which I believe is the expected behavior of 'up to'.
Discord report: https://discord.com/channels/937901803608096828/1223925566583865354/1223925566583865354

Goals: Up To Template calculation with negative category balance

---

packages/desktop-client/src/gocardless.ts
upcoming-release-notes/2518.md

All banks are supposed to provide at least 90 days of access.
As of July 2023 EEA banks are required to allow access for up to 180 days[0], but this does not apply to UK banks, and apparently there might still be EEA banks which don't comply with the new regulations.
We should consider eventually defaulting to 180 days and allowing per-bank and maybe per-country overrides, but bumping it to 90 days immediately provides a better user experience.
[0]: https://nordigen.zendesk.com/hc/en-gb/articles/13239212055581-EEA-180-day-access

Bump GoCardless access validity from 30 to 90 days

---

packages/desktop-client/package.json
packages/desktop-client/src/components/common/Input.tsx
packages/desktop-client/src/hooks/useMergedRefs.ts
upcoming-release-notes/2509.md
yarn.lock

Replace `mergeRefs` with `useMergedRefs`. Updated the `useMergedRefs` hook to support `Ref` because we use `Ref` in component props.

[Maintenance] Replace react-merge-refs with useMergedRefs

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
upcoming-release-notes/2548.md

Updated the Github issues template to (hopefully) reduce the amount of customer support tickets we receive.

:wrench: updated github issue template to hopefully reduce the amount of support

---

packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
upcoming-release-notes/2555.md

Removed need to serialize transaction and remove the old comment saying we don't have access to serialized transactions. Also renamed some `transaction` variables to `unserializedTransaction` to avoid confusion with the other serialized `transaction` variables

[Maintenance] Update TransactionEdit conponent onEdit function to use serialized transactions

---

packages/desktop-client/src/components/modals/CategoryGroupMenuModal.tsx
upcoming-release-notes/2570.md

Fixes https://github.com/actualbudget/actual/issues/2565
After looking at the menu options on the desktop view and comparing them to the mobile view, there is not currently a need to show a menu option in the mobile view.  Selecting the option resulted in a crash.  The desktop view has options to rename and create categories; however, the mobile view already uses a different method to accomplish those tasks.  The remaining option of Show/Hide the Income group category has no effect on the desktop view and thus doesn't really need to be displayed in Mobile view to replicate the functionality.  This PR simply hides the menu option if, and only if, the Income Group is selected. All other groups and categories are unaffected.

[Bugfix] Remove menu from income group on mobile view

---

packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
upcoming-release-notes/2572.md

Close modal after transferring / covering balance in mobile budget page

[Mobile] Close modal after transferring / covering balance in mobile budget page

---

packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
upcoming-release-notes/2573.md

Fix mobile report budget bug where you can't click on an income category's budgeted input

[Mobile] Fix report budget income budgeted input

---

packages/desktop-client/src/components/table.tsx
upcoming-release-notes/2523.md

Implements #2315
Happy for any feedback on this PR, or warnings of any issues I might have overlooked. Would add a test but not quite sure if this is worth an end to end add.
Release note upcoming.

When starting input with operator, append to existing value instead of replacing

---

packages/desktop-client/src/components/accounts/Account.jsx
upcoming-release-notes/2569.md

Feedback: support creating rules from split transactions on the accounts page.

Support splits in create-rule option on account page

---

packages/desktop-client/src/components/modals/ImportTransactions.jsx
upcoming-release-notes/2585.md

This PR adds the Checkbox for reconciliation also to CSV imports.
Issue mentioned in:  #2564 #2420 #608 #2561
Screenshot:

Add option to disable reconciliation when importing CSV and  files.

---

packages/desktop-client/src/components/Modals.tsx
packages/desktop-client/src/components/budget/BudgetCategories.jsx
packages/desktop-client/src/components/budget/ExpenseCategory.tsx
packages/desktop-client/src/components/budget/SidebarCategory.tsx
packages/desktop-client/src/components/mobile/budget/BudgetTable.jsx
packages/desktop-client/src/components/mobile/budget/index.tsx
packages/desktop-client/src/components/modals/CategoryMenuModal.tsx
packages/loot-core/src/client/state-types/modals.d.ts
upcoming-release-notes/2582.md

Closes #2578.
This dims the categories if the parent group is hidden.  It also does not show the 'hide'/'show' menu items if the category is hidden (as that would not actually change their hidden status anyway).

Dim categories hidden by their groups

---

packages/loot-core/src/shared/util.test.ts
packages/loot-core/src/shared/util.ts
upcoming-release-notes/2588.md

I updated the file import amount parser a bit ago to only allow 2 decimal places. The point of that was to not accidentally set something as decimal when a number didn't include any decimal amount. 
This PR adjusts the parser to allow 5 or 1-2 digits after the decimal marker. This way files that use the finance-y format of 5 decimal places work.

Allow 5 decimal places in file import parser

---

packages/desktop-client/src/components/App.tsx
packages/desktop-electron/index.js
packages/desktop-electron/menu.js
packages/desktop-electron/preload.js
upcoming-release-notes/2580.md

The "load backup" feature isn't working in Electron - it throws a fatal error.
This is because the menu item isn't passing in the budget ID related to the backup (required parameter).
The fix is to pass the budget ID into the menu item and push the load-backup modal with it.
**Error:** 
````
TypeError: Cannot read properties of undefined (reading 'budgetId') at app://actual/static/js/index.h17Pcr58.js:202:122692 at Array.map (<anonymous>) at mxe (app://actual/static/js/index.h17Pcr58.js:202:121619) at Gx
````
This is it working:

Electron: Fix load backup functionality

---

packages/desktop-client/src/components/accounts/Account.jsx
upcoming-release-notes/2589.md

This PR fixes #1013 
This is my first change in Actual and I've only got limited React experience so if there is a better way to do this, or to recall previous state values, please shout and I'll amend.

Force transaction cleared checkboxes to show on reconcile view

---

packages/desktop-client/src/browser-server.js
packages/desktop-client/src/components/FatalError.tsx
upcoming-release-notes/2601.md

Adding a bit of extra error handling in case the backend has failed loading (fatal error).
It seems at some point we have lost the fatal error handling logic. Meaning that in case of fatal errors (backend totally failed loading) - we would show an endless spinning bar instead of an error message.
So this _slightly_ improves the situation.. the user will now see an error message.
---
Also renamed `e` vars to something else. This _might_ fix https://github.com/actualbudget/actual/issues/1766 , but since I've not been able to reproduce the issue locally - it's mostly a shot in the dark.

:zap: extra error handling in case backend failed loading

---

packages/desktop-client/src/components/Modals.tsx
upcoming-release-notes/2609.md

[Maintenance] Add missing key prop to all modals

---

packages/desktop-client/src/style/styles.ts
upcoming-release-notes/2614.md

:bug: (tooltip) add scrollbars to tooltips that go out of bounds

---

packages/desktop-client/src/components/budget/index.tsx
packages/desktop-client/src/components/mobile/budget/index.tsx
upcoming-release-notes/2613.md

Honor the `budget.startMonth` pref to open the last month the user was working on before closing the app (similar to how it is on desktop)

[Mobile] Use budget start month pref on mobile to match desktop behavior

---

.github/workflows/electron-master.yml
upcoming-release-notes/2620.md

Rename the Electron Master workflow so that it shows up different in the actions page.
I guess Im mostly assuming that this will cause the actions page to rename the side bar name.  I just want then to not both be "Electron".

rename electron master workflow

---

packages/desktop-client/src/components/manager/DeleteFile.tsx
packages/loot-core/src/server/main.ts
upcoming-release-notes/2649.md

Patching how we build the file objects. `cloudFileId` should not be set for local-only files.
This leads to the "delete file" modal always showing the "delete remote file" button. Even when the button should not be there.

:bug: fix budget-type identification when deleting files

---

packages/loot-core/src/server/main.ts
upcoming-release-notes/2641.md

Make /login show descriptive error when an incorrect password is submitted

---

.github/workflows/electron-master.yml
.github/workflows/electron-pr.yml
upcoming-release-notes/2658.md

Fixes the currently failing osx electron builds like: https://github.com/actualbudget/actual/actions/runs/8802913164/job/24159785683#step:4:40

Fix for electron builds

---

packages/loot-core/src/server/accounts/parse-file.ts
upcoming-release-notes/2653.md

fixes: #2647
My bank always generates an empty record for qif. This shows up as an empty line when importing. This prevents it from being imported successfully. Right now, I am manually editing the qif file before importing each time.
With this change, transactions with empty date and amount are ignored.
```
!Type:CCard
D04/10/2024
N1111111
PABC
A
T123
^
^
```

Ignore transactions with empty date & amount

---

packages/loot-core/src/server/budget/goal-template.pegjs
packages/loot-core/src/server/budget/goals/goalsAverage.ts
packages/loot-core/src/server/budget/goaltemplates.ts
upcoming-release-notes/2688.md

Adds a new template to automatically run a "Set X month average" like is possible in the budget page.  This way if a user likes those they can run them with other templates.  This matches the function of the existing button by reading the spent amount of the previous months and averages it.
Fixes #2587
docs: actualbudget/docs#351

[Goals]add template to set x month average

---

packages/desktop-client/src/components/ThemeSelector.tsx
packages/desktop-client/src/style/theme.tsx
packages/loot-core/src/types/models/index.d.ts
packages/loot-core/src/types/models/transaction.d.ts
packages/loot-core/src/types/prefs.d.ts
packages/loot-core/src/types/server-handlers.d.ts
upcoming-release-notes/2676.md

- This is part of working towards having enough correct types to be able to run tsc on our packed api without error.
- Working towards being able to ship types for the api in the package
Related to https://github.com/actualbudget/actual/pull/2559

Fix some additional incorrect types

---

packages/desktop-client/src/components/settings/Export.tsx
upcoming-release-notes/2713.md

Right now, export uses the budget ID as the name of the export zip file which is always `My-Finances-xxxxxx`. This makes it hard to know which budget export is for which budget when you have multiple budget files.

Use budget name as export file name

---

packages/loot-core/src/server/api-models.ts
packages/loot-core/src/types/api-handlers.d.ts
upcoming-release-notes/2716.md

- Otherwise the types used in the API were actually wrong vs the data we were sending
Related to fixing the api types issues blocking https://github.com/actualbudget/actual/pull/2559

Create types for the external versions of entities meant for the API

---

packages/desktop-client/src/components/NotesButton.tsx
packages/desktop-client/src/components/common/Modal.tsx
packages/desktop-client/src/components/common/Tooltip.tsx
packages/desktop-client/src/components/modals/ScheduledTransactionMenuModal.tsx
upcoming-release-notes/2664.md

[Mobile] Schedule name and date in mobile scheduled transaction modal

---

packages/loot-core/src/shared/schedules.ts
upcoming-release-notes/2712.md

Steps to reproduce:
1. Create a schedule that is upcoming (appears as preview transactions)
2. Create a split transaction
3. Link a child transaction to the schedule
4. Preview transaction doesn't disappear
If you do the same with non-split transactions, the preview transaction will disappear as expected

Fix preview transactions not detecting schedule as paid when a child transaction is linked.

---

packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx
packages/desktop-client/src/components/mobile/transactions/TransactionEdit.jsx
packages/desktop-client/src/components/util/AmountInput.tsx
packages/loot-core/src/shared/util.ts
upcoming-release-notes/2746.md

Auto insert decimals to mobile split transaction amounts
